### ISSUE TITLE
Skills that have been selected is not visible on the bets tab but instead displays skills that have been obtained via aghanim's scepter/shard

### ISSUE THREAD

**Issue by Roshrach** [arcadia-redux/custom_hero_clash_issues#1000]
![image](https://user-images.githubusercontent.com/78736351/113353484-4fd65980-9370-11eb-87c9-9bc8219efa22.png)

**Comment by fcalife** [comment]
what's the bug

**Comment by Draze22** [comment]
Skills that are selected after the round starts don't show in the duel UI I think.

**Comment by Roshrach** [comment]
probably a visual bug. notice the artic burn skill not visible on the bets tab. this is probably because of alchemist's agha ultimate being on the second slot.
