### ISSUE TITLE
Rapiers can't be picked up

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1004]
This is probably due to us stopping players from sharing items.

**Comment by Draze22** [comment]
Was unable to reproduce this in demo mode.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/118126869-4266c180-b43c-11eb-971a-665979f48fb2.png)

**Comment by dym-sh** [comment]
same with gems

**Comment by lovro-m** [comment]
do you get a message "cannot pickup enemy items" when you try to pick up?

**Comment by dym-sh** [comment]
yep, same as with all other items

**Comment by Osamabinfrank** [comment]
Literally unplayable, Devine rapier new meta

**Comment by dym-sh** [comment]
rapier is a giant oof atm:
- no longer has True Strike
- still drops on death (and stays in duel area)
- cant be sold/replaced w/o dying

so, "meta"? no.
just non-trasferable to the enemy

**Comment by Osamabinfrank** [comment]
> rapier is a giant oof atm:
> 
> * no longer has True Strike
> * still drops on death (and stays in duel area)
> * cant be sold/replaced w/o dying
> 
> so, "meta"? no.
> just non-trasferable to the enemy

You don't say

**Comment by dym-sh** [comment]
please mark sarcasm with `/s`, otherwise its invisible in plain text
