### ISSUE TITLE
You can Hookshot Bulwark Aghs soldiers

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1007]
![image](https://user-images.githubusercontent.com/63279022/113565234-03c83500-964e-11eb-9975-c0dd1d41b138.png)

**Comment by Snoresville** [comment]
i dont see a problem

**Comment by SanctusAnimus** [comment]
both of them are dota spells, which means that's a dota interaction

**Comment by Draze22** [comment]
I can confirm this interaction happens in Vanilla dota.
