### ISSUE TITLE
Sharpshooter should be updated to work on creeps

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#1009]
Currently travels through creeps without affecting them and affects only the first enemy hero hit.

Should be changed to apply damage/slow/break to all creeps it passes through without changing how it interacts with heroes.

**Comment by Draze22** [comment]
Bushwack does work on creeps.

**Comment by Draze22** [comment]
If we make Sharpshooter work on creeps it changes how effective it is in duels. When using it against a summoner build it will hit one of the summons instead of the enemy hero.

**Comment by darklordabc** [comment]
> Bushwack does work on creeps.
How come it doesnt have a not saying so?

**Comment by Draze22** [comment]
What we could do is make it pass through and damage/slow/break all units.

**Comment by Draze22** [comment]
> 
> 
> > Bushwack does work on creeps.
> > How come it doesnt have a not saying so?

Because it works on creeps in Vanilla Dota.

**Comment by Draze22** [comment]
Closing this until someone comes up with a reasonable way for Sharpshooter to affect creeps (without ruining it against heroes).

**Comment by Draze22** [comment]
This can now be implemented.
