### ISSUE TITLE
Liquid Frost doesn't deal percent damage

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1010]
![image](https://user-images.githubusercontent.com/63279022/113690915-456ce480-970f-11eb-8ac9-19482e8fbc93.png)
![image](https://user-images.githubusercontent.com/63279022/113690979-574e8780-970f-11eb-8a66-cd58ab5845c2.png)
![image](https://user-images.githubusercontent.com/63279022/113691084-6d5c4800-970f-11eb-91eb-3b4ed51de333.png)

**Comment by SanctusAnimus** [comment]
Doesn't work for me even on jakiro with all his abilities
