### ISSUE TITLE
Skills refresh in fountain at 300% speed instead of 200%

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#1013]
Arcane Acceleration is something like 700%
also items don't do the smooth cooldowning and are unaffected by the bugged refresh speeds

**Comment by Snoresville** [comment]
Arcane acceleration will no longer exist next update, but the base problem still exists

**Comment by AustraliaIsMyCity** [comment]
Fixed https://github.com/arcadia-redux/custom_hero_clash/commit/6f649c2068cfae0fb7567be74671eae149ddcc06
