### ISSUE TITLE
Revenge bug

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1018]
![image](https://user-images.githubusercontent.com/63279022/114255663-00d79680-99f8-11eb-8fcc-00a7e7cfafbd.png)
![image](https://user-images.githubusercontent.com/63279022/114255702-3d0af700-99f8-11eb-98b2-9eafbf22687d.png)
![image](https://user-images.githubusercontent.com/63279022/114255736-793e5780-99f8-11eb-8c36-179655bd4f25.png)

**Comment by fcalife** [comment]
Revenge innate was removed
