### ISSUE TITLE
Reworked shackles & summon wolves have some issues

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#1020]
Shackles:

 - Serpent wards created from shackles are currently not affected by summon power
 - If you have Mass Serpent Wards and shackles, the serpent wards created by shackles are max level, instead of using Mass Serpent Wards' level
 - Shackles shard cast range bonus is applied on server, but not visible on the client
 - Some shackles particles are bugging out like below:
 
![dota2_GGS86azSjQ](https://user-images.githubusercontent.com/7921728/114255894-c2f15880-998c-11eb-8481-387f629d883f.png)

![dota2_brWd0oJCev](https://user-images.githubusercontent.com/7921728/114255896-c5ec4900-998c-11eb-80b0-4c2875772db8.png)

Summon Wolves:

 - Summon Wolves' wolves are also not affected by summon power
 - Summon Wolves is missing shard description (fixed)
 - Summon Wolves is missing all wolf stats information on tooltip (health, damage, etc.)

**Comment by ZLOY5** [comment]
I cant only reproduce this particle bug

**Comment by fcalife** [comment]
Trying again, I had to use "magus" innate in order to reproduce it

Problem is probably on magus itself (shouldn't trigger channeling abilities)
