### ISSUE TITLE
Create a standard layout for patch notes

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#1021]
Currently our patch notes look like an unformatted brick wall of text on the dota client (I mean on the arcade page, not in our game). We really should put in some effort on making their presentation at least a bit better.

### ADD CATEGORIES. USE FORMATTING FOR HEADERS. EITHER UNDERLINE OR BOLD WITH A LARGER FONT

Each category can have a brief explanation of what was changed related to it, possibly with the reasoning behind the changes, if there's any.

 - Use actual bullet points in patch notes instead of hyphens "-" <-- this is a hyphen
   - Use list indentation if necessary, to further talk about topics which need longer explanations or secondary comments
   - Indentation is awesome
 - Syntax for that on arcade page, if I remember correctly, is

```
 [list]
 [*] item
 [*] item
 [*] item
 [/list]
```
 
 - General change, not related to an ability, hero or item. General text description of what was changed.
 - Ability/item/hero name: change. Stats before -> stats after.
 - Example ability: damage increased from 100/200/300/400 to 200/300/400/500
 - Another possible format: 100/200/300/400 -> 200/300/400/500 damage
 - I don't mind which one but pick a format and stick to it.
 - Either finish sentences with a period or don't. But be consistent about it.
 
 increased vs reduced vs rescaled:
 
 1/2/3/4 to 2/3/4/5: INCREASED (all values increased)
 
 1/2/3/4 to 1/2/3/5: INCREASED (at least one value increased, others did not decrease)
 
 1/2/3/4 to 1/2/2/3: REDUCED (at least one value decreased)
 
 1/2/3/4 to 1/1/4/4: RESCALED (at least one value increased , at least one value reduced)

**Comment by Draze22** [comment]
> Either finish sentences with a period or don't. But be consistent about it.

Hard isn't it:

> General change, not related to an ability, hero or item. General text description of what was changed.
> Ability/item/hero name: change. Stats before -> stats after.
> Example ability: damage increased from 100/200/300/400 to 200/300/400/500
> Another possible format: 100/200/300/400 -> 200/300/400/500 damage
> I don't mind which one but pick a format and stick to it.
> Either finish sentences with a period or don't. But be consistent about it.

On a more serious note I don't finish sentences with periods unless I do multiple sentances in one hyphen/bullet point, is that good enough?

**Comment by Draze22** [comment]
> Syntax for that on arcade page, if I remember correctly, is

Is this something I need to do or Darklord needs to do?

**Comment by Draze22** [comment]
> Use list indentation if necessary, to further talk about topics which need longer explanations or secondary comments

Indentation looks shit here since the patch notes are so thin:
![image](https://user-images.githubusercontent.com/63279022/122046069-ccca8880-ce21-11eb-9311-764ff8c7fc43.png)

TAB doesn't indent in discord so I'd have to press space multiple times each time I want to make an indent.

In summary I'm only going to use indents if absolutely necessary.

**Comment by Draze22** [comment]
Pretty sure I do most of the rest quite well and constistently at this point but I'll make an effort to do a better job, particularly utilizing underlines, bold and italics.

**Comment by SanctusAnimus** [comment]
Pretty sure we now have a decent format of patch notes
