### ISSUE TITLE
Improve charge-based behavior of Duel and Track

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#1023]
Using Duel as an example, after being used, it goes on cooldown normally. If the cooldown elapses during the round, and the player tries to use the ability again, the game says it is out of charges.

Instead of going on cooldown, the ability should be disabled entirely (grayed out), and enabled again when its round-based charges reset.

**Comment by SanctusAnimus** [comment]
Implemented
