### ISSUE TITLE
Chaos Meteor with Aghs Shard has a -2 second cooldown

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1024]
In vanilla Dota Aghs Shard reduces the cd from 55s to 40s.

![image](https://user-images.githubusercontent.com/63279022/114264997-a0fde180-9a31-11eb-8366-43bdd6ae27a2.png)

**Comment by ZLOY5** [comment]
Since seems it hardcoded we can only rewrite or set original CD>15

**Comment by fcalife** [comment]
Fixed by @AustraliaIsMyCity in https://github.com/arcadia-redux/custom_hero_clash/commit/e86b42765754a4d92fff149937eceeb3a8ea2ebb
