### ISSUE TITLE
Duel doesn't give bonus damage

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1027]
![image](https://user-images.githubusercontent.com/63279022/114292416-d0fcc180-9ad1-11eb-8710-326566133e01.png)

**Comment by Snoresville** [comment]
VALVE!!!!!!!!!!!!!!!!!

**Comment by Snoresville** [comment]
https://dev.dota2.com/forum/dota-2-custom-games-tools/scripting-bugs-suggestions/2258672-legion-commander-s-duel-no-longer-gets-duel-damage-from-winning-duels-vs-creeps
lets see if valve sees this

**Comment by SanctusAnimus** [comment]
Duel got disabled. If so desired, rewrite should go as a separate issue
