### ISSUE TITLE
Marksmanship doesn't give bonus agi to heroes using switcheroo to be ranged

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1029]
![image](https://user-images.githubusercontent.com/63279022/114296940-44fa9200-9af1-11eb-821a-7d02f1912a91.png)

**Comment by Snoresville** [comment]
With switcheroo innate:
Tested with Phantom Lancer: He gains marksmanship bonus
Tested with Monkey King (reported not working): He gains marksmanship bonus
Tested with Drow Ranger: She does not get marksmanship bonus

Conclusion: we should ask if they saw this in fountain
