### ISSUE TITLE
Magus can cause abilities to peirce magic immunity

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1030]
![image](https://user-images.githubusercontent.com/63279022/114309625-23b69780-9b2b-11eb-9ba3-981a1c96190c.png)

**Comment by ZLOY5** [comment]
Pretty sure this fixed in https://github.com/arcadia-redux/custom_hero_clash/commit/0ce579407b17b07dd2c9ad253f4f3c2354429d22

**Comment by Snoresville** [comment]
close it if it's already in the game @ZLOY5
