### ISSUE TITLE
Daily quests in duos should account for partner, at least in neutral rounds

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1031]
i.e. kill creeps, or kill ancients – you either forced to make solo runs, or ask partner to not lasthit, both of which are suboptimal

**Comment by SanctusAnimus** [comment]
@arcadia-redux/balance-team so what do we decide on that one? Should quests account for teammates or nah?

**Comment by Draze22** [comment]
I say don't bother.

**Comment by SanctusAnimus** [comment]
Then i'm closing, reopen if rest of balance team thinks otherwise
