### ISSUE TITLE
FFA Hero Soul bug

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1033]
![image](https://user-images.githubusercontent.com/63279022/114341577-7466d880-9b9d-11eb-9e52-d4fd389817e2.png)
![image](https://user-images.githubusercontent.com/63279022/114341599-7fba0400-9b9d-11eb-8281-4ba76f71222e.png)

**Comment by ZLOY5** [comment]
Should be fixed long time ago
