### ISSUE TITLE
If a hero soul dies in a duos duel and that player reconnects during the duel they'll get revived

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1036]
Pretty sure this can only happen in duos since in ffa the hero soul would get removed from the game.

![image](https://user-images.githubusercontent.com/63279022/114342043-6ebdc280-9b9e-11eb-898f-ce444bdf70f5.png)

**Comment by Draze22** [comment]
1. Disconnect before picking a hero.
2. Reconnect once you die in a duel (but before your Duos partner dies in the duel).
3. You will be invulnerable for the duration of that duel.

**Comment by Draze22** [comment]
This bug now causes the player who reconnects to lose an aegis if the die in the duel. 

![image](https://user-images.githubusercontent.com/63279022/124141174-871de900-dacc-11eb-9da2-c19b09c88c8d.png)

**Comment by ZLOY5** [comment]
Ah shit, here we go again

**Comment by ZLOY5** [comment]
What if picked hero spawns only after round ends?

**Comment by Draze22** [comment]
> What if picked hero spawns only after round ends?

Perfect.
