### ISSUE TITLE
A Suggestion. though this might be a dumb one

### ISSUE THREAD

**Issue by Jakarooo** [arcadia-redux/custom_hero_clash_issues#1041]
make the map bigger. This *might reduce lag when at round 40-50 onwards.

*this could be used as a beta(?) I don't know if you guys considered to have a bigger map but this might help since entities form faraway might not render at a %100. idk I'm just suggesting since the lag on round 40 onwards is unbearable

**Comment by Snoresville** [comment]
That is dumb because lag isnt based of the size of the arenas.
