### ISSUE TITLE
Late Bloomer inate is +0 per level and +0.35 stats per boss?

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1043]
![late bloomer +0 35](https://user-images.githubusercontent.com/59403389/114532265-f530dd80-9c4c-11eb-9a66-c494e6eee8dc.jpg)

**Comment by Snoresville** [comment]
Yes?

**Comment by dym-sh** [comment]
so, +3.5 to all stats every 10 levels?

**Comment by Snoresville** [comment]
Not necessarily
It's (bosses killed) * 0.35 * hero level

**Comment by dym-sh** [comment]
this wording is hella confusing and needs a spreadshit graph to prove its exponential

**Comment by Snoresville** [comment]
This innate give an all attribute stat gain per level of 0.
This number increases by 0.35 for each boss killed.

**Comment by Snoresville** [comment]
we cool?
