### ISSUE TITLE
CHC Spectator mode lags incredibly hard based on the number of players in the fountain

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#1046]
No FPS lag is observed, no packet loss or ping spikes.

https://youtu.be/O-7xIEEwkjM

**Comment by ZLOY5** [comment]
Seems for spectators lower net limits. I will try increase think duration for better cooldowns and we see if this help

**Comment by ZLOY5** [comment]
Seems fixed
