### ISSUE TITLE
Sinister Gaze Aghs preview icon is broken

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1048]
![image](https://user-images.githubusercontent.com/63279022/114819038-21d92680-9e00-11eb-8b7b-7d38643bf500.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/114819121-4b924d80-9e00-11eb-85b7-3d3e6ec50012.png)

**Comment by SanctusAnimus** [comment]
Effect is working, but icon is indeed broken. I don't think we can do anything with it though?

**Comment by Draze22** [comment]
The Aghs preview is kind of a mess in CHC, we can make a big issue at some point to fix it once it becomes a higher priority.
