### ISSUE TITLE
Swapping Spirit Bear in DUOS allows getting multiple bears

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1049]
![image](https://user-images.githubusercontent.com/63279022/114819293-96ac6080-9e00-11eb-9b1f-3320461ed41f.png)
![image](https://user-images.githubusercontent.com/63279022/114819477-df641980-9e00-11eb-921c-7d2c4cf9f53d.png)

**Comment by SanctusAnimus** [comment]
It was prohibited from swapping for some time, then i guess refactor ate it, so i'll disable it from swapping again i guess

**Comment by SanctusAnimus** [comment]
Done
