### ISSUE TITLE
Tinkerer doubles the negative effects of neutral items

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1055]
Doubles the following negative effects/aspects of abilities:
1. Witless Shako mana decrease.
2. Eye of Midas 10 round cooldown.

**Comment by Snoresville** [comment]
Is the goal of this issue to halve negative effects?

**Comment by SanctusAnimus** [comment]
I think it's quite fair though?

**Comment by Snoresville** [comment]
yeah, the innate is literally by the book and is right now fair enough

**Comment by ZLOY5** [comment]
Like what aasense in eye of midas upgrade if player still have 5k gold per 10 rounds

**Comment by Snoresville** [comment]
plus, eye of midas interaction only happens in duos, so ffa players would never experience it

**Comment by Draze22** [comment]
I think it should just not double the negative effects of these items instead of doubling them, since currently if you want Eye of Midas for it's ability to instantly kill a unit it's actually worse with tinkerer.
