### ISSUE TITLE
Double mastery UI is broken

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1060]
![image](https://user-images.githubusercontent.com/63279022/115106801-11fd4600-9faa-11eb-898e-20ef6204fad0.png)

**Comment by ZLOY5** [comment]
@fcalife or @darklordabc or another one who doing updates just should hover tooltips to compile

**Comment by Sheodar** [comment]
Works fine in master now. Maybe trouble with not compiled files.
![image](https://user-images.githubusercontent.com/23509297/115340931-50645200-a1b0-11eb-944e-c6f864f60a4b.png)

**Comment by darklordabc** [comment]
Should be fixed since recompiling
