### ISSUE TITLE
Auras still damage enemies even after tempest double dies

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1063]
Both AIMC and I saw this occur first hand with Luminance.

**Comment by darklordabc** [comment]
This should be an easy fix

**Comment by Draze22** [comment]
Looks like this also happens with rot and potentially other damaging aura effect or even all aura effects.
![image](https://user-images.githubusercontent.com/63279022/115985691-5adb7d00-a5f0-11eb-9fdc-37054eee7c42.png)

**Comment by ZLOY5** [comment]
Fixed
