### ISSUE TITLE
Only zeus can find static field

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1066]
![image](https://user-images.githubusercontent.com/63279022/115397115-13887180-a229-11eb-8af6-92130d68617f.png)

https://www.youtube.com/watch?v=BwlrnJkk4Lg

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/115538005-170d0e80-a2a4-11eb-9492-1f0461e3b044.png)

well, yes? it was done specifically so cause static field by default works only with zeus abilities iirc, at least used to work that way at the time we made it personal

**Comment by Draze22** [comment]
Other heroes can still find Zeus's other skills and make use of static field. I'll make a poll to see if people want to be able to find static field on all heroes.

**Comment by Draze22** [comment]
> Other heroes can still find Zeus's other skills and make use of static field. I'll make a poll to see if people want to be able to find static field on all heroes.

Only took me just under 2 months to make this poll.

**Comment by Draze22** [comment]
Poll Squad agrees to let all heroes find static field although they are mostly Veteran players which would bias them towards this decision.

![image](https://user-images.githubusercontent.com/63279022/122091812-8e968e80-ce4c-11eb-93c1-99127a36ecd3.png)

**Comment by Osamabinfrank** [comment]
> Poll Squad agrees to let all heroes find static field although they are mostly Veteran players which would bias them towards this decision.
> 
> ![image](https://user-images.githubusercontent.com/63279022/122091812-8e968e80-ce4c-11eb-93c1-99127a36ecd3.png)

i see 4 who is actually good at the game if i count myself

**Comment by Draze22** [comment]
Update on the vote ratio:
![image](https://user-images.githubusercontent.com/63279022/122207105-1af49000-cee5-11eb-9918-5ec152a13f10.png)

**Comment by Snoresville** [comment]
so... are we good to go on making static field available to all heroes?

**Comment by Draze22** [comment]
> so... are we good to go on making static field available to all heroes?

Yes.
