### ISSUE TITLE
Track is super broken atm

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1067]
You often cant use track even though you have full charges.

![image](https://user-images.githubusercontent.com/63279022/115406133-3d926180-a232-11eb-976b-2fc5e3caf4b7.png)

**Comment by Draze22** [comment]
Duel has the same issue.

**Comment by SanctusAnimus** [comment]
hmm is there any particular moment after which it doesn't reenable itself? maybe refresher / rearm etc?

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/115517643-b2b17580-a2ca-11eb-90af-ed9598dcb36e.png)

**Comment by SanctusAnimus** [comment]
Should be fixed
