### ISSUE TITLE
Move the fountain spawn location that's behind the shop keeper

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1069]
It's difficult to select the player who spawns in that location to see what items, skills, etc they have.

![image](https://user-images.githubusercontent.com/63279022/115663240-932a5380-a383-11eb-9522-9edfe3eb4157.png)

**Comment by darklordabc** [comment]
Is this still an issue?

**Comment by Draze22** [comment]
> 
> 
> Is this still an issue?

Yes.
