### ISSUE TITLE
Consider adding necronomicon back to the game

### ISSUE THREAD

**Issue by Jakarooo** [arcadia-redux/custom_hero_clash_issues#1070]
since the summoners are now adjusted(multicast no longer works on summon skills, innate is adjusted) and the only strong summoner skill now is warlock's golem.

**Comment by Osamabinfrank** [comment]
Em death ward is much better especially when you have the shard upgrade, venom with his wards too as well as np and his units..
Why is the poor golem better than a non targatble wd ward?

**Comment by Jakarooo** [comment]
True, I also believe death wards are the best summoner skill, but for the others, not so much since 1; venom's ward doesn't deal much damage, even with CoD. 2; nature prophet's units is a no go in pvp since you have to go to the corner of the arena to spawn them; giving the enemy the chance to hit first. 3.  Brood mother's spiderlings and enigma's demonic conversion is useless in pvp.

**Comment by Osamabinfrank** [comment]
Huh? 1. They are extremely op when you reach lvl 25 on venom, 2. You can just get his q? Which is an amazing skill for every build especially if you hace cdr
3. Yep but thats how balance works, some units are amazing, some good and some meh.

**Comment by fcalife** [comment]
bear can get you to round 80 solo

**Comment by Jakarooo** [comment]
> Huh? 1. They are extremely op when you reach lvl 25 on venom, 2. You can just get his q? Which is an amazing skill for every build especially if you hace cdr
> 3. Yep but thats how balance works, some units are amazing, some good and some meh.


It really depends on luck. 1. talent is only applicable if you're using venomancer. Any hero other than venomancer makes the skill underpowered. 2. as what I've said in the first sentence, it really depends on luck. chances are, if you're using a summoner innate/build, you're likely looking for a summoner related skill, rather than defensive/offensive skill. 




> bear can get you to round 80 solo

Depends if you get lucky on early game and won a lot of duels in early game so you can put items in the bear. You won't get a lot of money by just finishing the round first alone.

**Comment by Osamabinfrank** [comment]
You can say that about any build
This game is luck based

**Comment by SanctusAnimus** [comment]
I believe we decided to stay without necronomicon, reopen if i'm wrong
