### ISSUE TITLE
I cast homing missle as my first ability and game crashed

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#1072]
![image](https://user-images.githubusercontent.com/16277198/115805832-16ea4b80-a429-11eb-9bbb-d41dc7f95373.png)

**Comment by fcalife** [comment]
cursed

**Comment by efe-efe** [comment]
Can't reproduce, i even tried selecting the same innate but couldn't get the error

**Comment by SanctusAnimus** [comment]
Cannot reproduce
