### ISSUE TITLE
Text to rearrange abilities overlaps on actual abilities (maybe russian/chinese issue)

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#1075]
![image](https://user-images.githubusercontent.com/16277198/115814435-5f5d3580-a438-11eb-9531-441af450a0eb.png)

**Comment by Draze22** [comment]
I've never seen this in English.

**Comment by ZLOY5** [comment]
Cant reproduce this, maybe it happens only with a specific screen resolution or aspect ratio

**Comment by Draze22** [comment]
No more reports of this closing for now.
