### ISSUE TITLE
Big Game Hunter's particles are bug

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1077]
![image](https://user-images.githubusercontent.com/63279022/115875843-ff42af80-a488-11eb-9f09-1cf26f60b834.png)
![image](https://user-images.githubusercontent.com/63279022/115875885-09fd4480-a489-11eb-8b22-5b545c7e4e32.png)

**Comment by SanctusAnimus** [comment]
Looks like it was a compilation issue, works fine now

**Comment by SanctusAnimus** [comment]
Looks like it was a compilation issue, works fine now
