### ISSUE TITLE
Skywrath Mage's Aghanim's Shard gets procced by toggling Pulse Nova

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1079]
No other toggled abilities seem to proc Sky's Shard.

**Comment by lovro-m** [comment]
I'll put this in the shard megathread. I guess it has to be completely rewritten.

**Comment by lovro-m** [comment]
This shard looks hero specific and not spell specific. I suggest we make it a passive that gets called same as other shard spells with "AbilityDraftUltShardAbility" when you take mystic flare.

**Comment by Draze22** [comment]
Toggling Phantom Rush also procs Sky/Arcane bolt shard.

![image](https://user-images.githubusercontent.com/63279022/124865597-4ce9a580-dffe-11eb-930c-4c401a644663.png)
![image](https://user-images.githubusercontent.com/63279022/124865597-4ce9a580-dffe-11eb-930c-4c401a644663.png)

**Comment by lovro-m** [comment]
Both pulse nova and phantom rush fixed in PR
