### ISSUE TITLE
when you won the game and chose to continue playing it, make the pause button pause only the timer instead of the whole game

### ISSUE THREAD

**Issue by Roshrach** [arcadia-redux/custom_hero_clash_issues#1081]
Doesn't make any sense pausing the whole game when you're the only one playing. It should've been pausing the timer button since you're only one playing the game and you'll have more time getting ready for the next round especially on rounds 70 and up. This doesn't disrupt any gameplay whatsoever since there is only 1 player playing the game.

**Comment by Osamabinfrank** [comment]
It will make the game much easier, you have 15 seconds to react to new rounds that's more than enough

**Comment by Snoresville** [comment]
swift arcana exists. no abusing the pause timer
