### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1083]
![image](https://user-images.githubusercontent.com/63279022/115981275-dbd94b00-a5d5-11eb-9570-9cb9eff046f6.png)
![image](https://user-images.githubusercontent.com/63279022/115981292-f90e1980-a5d5-11eb-91ea-6f436d83742d.png)
![image](https://user-images.githubusercontent.com/63279022/115981324-2955b800-a5d6-11eb-9316-9b6e48ed0bfa.png)
![image](https://user-images.githubusercontent.com/63279022/115981339-5013ee80-a5d6-11eb-9b2a-abea31391daa.png)

**Comment by SanctusAnimus** [comment]
this is useless without reproduction
