### ISSUE TITLE
Disable using shadow blade and shadow amulet while in the fountain

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1085]
The issue with being able to use these items in the fountain is you can use them in the fountain and put the into your stash before the duel and essentially have 7 item slots.

**Comment by efe-efe** [comment]
I've two posible solutions for this which prevents us from coding the items from scracth:
* Constantly checking if the player is both, in fountain and invisible, and remove the invisibility modifiers when both are true
* As soon as the round starts, destroy the invisibility modifiers

**Comment by Draze22** [comment]
Yes, include glimmer cape and silver edge. We already have a list of abilities that cannot be used in the fountain, presumably we could add these 4 items to that list.

**Comment by Snoresville** [comment]
we could make an invisibility innate from this lol

**Comment by efe-efe** [comment]
> Yes, include glimmer cape and silver edge. We already have a list of abilities that cannot be used in the fountain, presumably we could add these 4 items to that list.

The list you mention only disable abilities, sadly items don't have the disabled state, but i think disabling them at the order filter will work fine
