### ISSUE TITLE
Invisible permanent Deathward in the duel arena

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1089]
Seems to be caused by Tempest Double casting Deathward. My guess is the Tempest double has to die while channeling it, or be still channeling it when the duel ends.

![image](https://user-images.githubusercontent.com/63279022/116194541-5344e100-a774-11eb-87dd-0b749be7b198.png)
![image](https://user-images.githubusercontent.com/63279022/116194647-75d6fa00-a774-11eb-8079-2e998dd1ed60.png)
![image](https://user-images.githubusercontent.com/63279022/116194673-7cfe0800-a774-11eb-8dd5-9c9d66a0af3e.png)
![image](https://user-images.githubusercontent.com/63279022/116194694-84bdac80-a774-11eb-8645-7dc35884f048.png)

**Comment by efe-efe** [comment]
Can't reproduce, i tried:

* Killing (with damage) the Tempest Double while channeling
* Killing (by expiration) the Tempest Double while channeling
* Winning the duel while Tempest Double is channeling

All of this points tried with Death Ward and with Voodo Switchero (except for the first one, is imposible to kill the clone while outsied the map with Voodo Switchero)

Any ideas on what else could we try?

**Comment by Draze22** [comment]
Closing this for now since we've been unable to reproduce it and no-one else has reported it.
