### ISSUE TITLE
Make icons for the new masteries

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#1093]
These are the ones being added:

- War Veteran: increases all damage output, but only against creeps
- Warrior: increases autoattack damage
- Goldfinger: increases all gold gain
- Crescendo: gain stacking bonus damage every time you attack (resets on round end)
- Numb: part of damage received is negated and dealt over time after a delay (this is most commonly known as 'staggered' damage)
- Quickdraw: increases the damage of the first few damage instances you deal in a round

**Comment by natoshi** [comment]
![image](https://user-images.githubusercontent.com/3074666/116360733-e2033d80-a808-11eb-882d-d027490ae755.png)

**Comment by Jakarooo** [comment]
instead of gold finger, how about rename it to Midas touch?  since you know, it gives you more gold gain

**Comment by fcalife** [comment]
thank you, those are great!
