### ISSUE TITLE
Attribute Bonus Bug (not auto leveling when high enough level)

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#1095]
I'm at lvl 200, and for some reason only a few of my attributes are upgraded, and I haven't unlocked my third mastery yet?
![image](https://user-images.githubusercontent.com/16277198/116223903-5ac7b280-a793-11eb-8cee-ae32f780cc7a.png)

**Comment by efe-efe** [comment]
In relation with https://github.com/arcadia-redux/custom_hero_clash_issues/issues/1110, the ability points won't be autoleveled anymore, since it doesn't makes sense in CHC

**Comment by SanctusAnimus** [comment]
So i guess it was fixed since #1110 is closed?
