### ISSUE TITLE
Remove these grey bars of disconnected players

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#1098]
![image](https://user-images.githubusercontent.com/16277198/116233372-8bf9b000-a79e-11eb-975e-d11aead2d40b.png)
Just show their icon, the big grey bars is just stealing screen real estate. Dont need to show their names either.

**Comment by Draze22** [comment]
Not showing dead player names at all makes tournaments really hard to run.

**Comment by darklordabc** [comment]
Show it in expanded view

**Comment by darklordabc** [comment]
But minimum and normal mode, hide it

**Comment by Sheodar** [comment]
Implemented
