### ISSUE TITLE
Add an option to hide the Duel UI (during duels)

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1100]
This is more important in DUOS since it has a much bigger Duel UI.

![image](https://user-images.githubusercontent.com/63279022/116255791-ece0b280-a7b5-11eb-8588-c845fcbae735.png)
![image](https://user-images.githubusercontent.com/63279022/116255815-f1a56680-a7b5-11eb-842a-e7e6316bdd69.png)

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/116393206-028fbf80-a82a-11eb-8b1e-bb7e7a22d55d.png)
why is it even showing cooldowns ALL the time now? i thought the idea was to show cooldowns in the betting menu only?

**Comment by ZLOY5** [comment]
Maybe it my bad, and I misunderstood the task.
But in any case i added option to hide abilities.
![image](https://user-images.githubusercontent.com/10956575/116394507-a9c12680-a82b-11eb-8eaf-abc1c39eb65f.png)
![image](https://user-images.githubusercontent.com/10956575/116394631-d83f0180-a82b-11eb-80c4-8d6b238e7ef7.png)
