### ISSUE TITLE
New innate idea: Trader

### ISSUE THREAD

**Issue by Roshrach** [arcadia-redux/custom_hero_clash_issues#1101]
an innate trader where you can sell your items for 70-80% instead of 50% of the price (?)

**Comment by darklordabc** [comment]
Sounds good to me

**Comment by Snoresville** [comment]
should explain why it is good/nuanced enough to be an innate. this sounds like a mastery

**Comment by Draze22** [comment]
Adding this to Issue #658 (new idea megathread).
