### ISSUE TITLE
Reasons why people play chaos over clash

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#1102]
![image](https://user-images.githubusercontent.com/16277198/116272783-8911b600-a7c4-11eb-98e2-434710d5461a.png)
https://docs.google.com/spreadsheets/d/1Qx2GnsRpeLYo4QrCZYVBwnuk-_2xrHSMTkqJoPmGnBA/edit#gid=0

**Comment by Draze22** [comment]
Pretty sure the main reason is way more people have tried Chaos than Clash.

**Comment by Draze22** [comment]
We've implemented or are working on all of these issues.
