### ISSUE TITLE
Import Torture Pipe from Chaos

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#1105]
May need to change it a little bit.

----------------------------------------------------------------------------

Draze22:

Torture Pipe (5740) = Spirit Vessel (2840) + Crown (450) + Crown (450) + Recipe (2000):

+ 300 Health
+ 3 Mana Regen
+ 12 All Attributes
+ 3 Armor

Active is identical to Spirit Vessel with the following changes:

- 7s Cooldown
- Doesn't require or gather charges
- Deals 50 damage per second to enemies
- Gives 75 hp regen to allies

Passive: increases the damage of all DOT abilities by 50% with the following exceptions:

- All % damage abilities
- Maledict
- TBD

----------------------------------------------------------------------------

Torture Pipe 2 (9740) = Torture Pipe (5740) + Vitality Booster (1000) + Vitality Booster (1000) + Recipe (2000):

+ 1000 Health
+ 4 Mana Regen
+ 15 All Attributes
+ 4 Armor

Active is identical to Spirit Vessel with the following changes:

- 7s Cooldown
- Doesn't require or gather charges
- 5% current health per second
- 50% hp regen, healing, lifesteal and spell lifesteal reduction
- Deals 80 damage per second to enemies
- Gives 125 hp regen to allies

Passive: increases the damage of all DOT abilities by 100% with the following exceptions:

- All % damage abilities
- Maledict
- TBD

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/116288603-5bb01280-a79a-11eb-94ae-8afcf40d1d10.png)
for reference

**Comment by Draze22** [comment]
Does this buff stack additively or multiplicatively with spell amp or does it replace spell amp entirely?

**Comment by Snoresville** [comment]
do you guys want to give noob humiliator another reason to say that we're copying them? bruh

**Comment by Draze22** [comment]
At this point we both copy each other.

**Comment by fcalife** [comment]
> Does this buff stack additively or multiplicatively with spell amp or does it replace spell amp entirely?

Multiplicatively

**Comment by AustraliaIsMyCity** [comment]
![image](https://user-images.githubusercontent.com/50186248/116986152-c7512d00-ad10-11eb-8b06-9ebc13f802d4.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/119304040-02a8a100-bcaa-11eb-97f5-914d405e0ef4.png)
![image](https://user-images.githubusercontent.com/63279022/119304010-f886a280-bca9-11eb-94ca-65bb393b538c.png)

**Comment by AustraliaIsMyCity** [comment]
this item gives too many stats, also the magic resistance needs to be removed entirely

**Comment by Snoresville** [comment]
remove magic resistance from a pipe upgrade? wtf
take a look at guardian's helmet if you want "too many stats"

**Comment by AustraliaIsMyCity** [comment]
we already have a hood upgrade upgrade we dont need another

just make it build from something else lol

**Comment by Snoresville** [comment]
Normally, urn/vessel has a cooldown of 7 seconds. Is this item that powerful enough to justify doubling its cooldown?

**Comment by Snoresville** [comment]
50/100% damage increase on dot sounds too weak to me imo, i would just buy starforce and have it do the same thing but better

**Comment by fcalife** [comment]
it does stack with starforce.

I kinda agree though, maybe add some stat-based scaling like the chaos version, since we're going the damage route.

@AustraliaIsMyCity @Draze22 could you make a power curve you think is reasonable for this item and show it in the discord channel?

**Comment by Draze22** [comment]
> it does stack with starforce.
> 
> I kinda agree though, maybe add some stat-based scaling like the chaos version, since we're going the damage route.
> 
> @AustraliaIsMyCity @Draze22 could you make a power curve you think is reasonable for this item and show it in the discord channel?

Pretty sure if we add a power curve it will either be too weak early game or too strong late game since DOT spells will then be affected by two items that each buff linearly, resulting in quadratic growth from buying stats.

**Comment by Draze22** [comment]
> Normally, urn/vessel has a cooldown of 7 seconds. Is this item that powerful enough to justify doubling its cooldown?

Our upgrade doesn't require charges which is why we increased the cooldown, I'll change it back to 7s cd but it may have to be nerfed.

**Comment by Draze22** [comment]
List of abilities Torture Vessel affects:
Acid Spray, Arcane Curse, Avalance, Battery Assault, Battle Hunger, Blade Fury, Bramble Maze, Burning Spear Frosthaven, Celestial Hammer, Cinder Brew, Cold Feet, Corrosive Skin, Dismember, Doom, Dual Breath, Elder Dragon Form, Epicentre, Fire Remant (Shard), Fire Spirits, Fiend's Grip, Fireball, Firefly, Flame Guard, Flamebreak, Flamethrower, Flaming Lasso, Flux, Freezing Field, Frostbite, Icarus Dive, Ice Wall, Ice Vortex (Shard), Ignite, Ion Shell, Leech Seed, Liquid Fire, Macropyre, Magnetize, Malefice, Mortimer Kisses, Nature's Grasp, Nethertoxin, Overgrowth, Poison Attack, Poison Nova, Poison Sting, Poison Touch, Psionic Trap, Rot, Sand Storm, Scorched Earth, Searing Chains, Shackles, Shadow Strike, Shadow Word, Shrapnel, Solar Guardian, Spear of Mars (Shard), Static Storm, Thunder Strike, Time Dilation, Torrent, Torrent Storm, Upheaval (Shard), Venemous Gale, Viper Strike, Wraithfire Blast.

Torture Vessel does not affect items.

**Comment by SanctusAnimus** [comment]
This should be reflected in ability notes, not in the item description (please, for the love of god)

**Comment by Snoresville** [comment]
is it okay if you also listed the abilities that torture pipe does not affect? it's not to put in the description, but for me to remember what abilities the passive effect does not affect

**Comment by SanctusAnimus** [comment]
> is it okay if you also listed the abilities that torture pipe does not affect? it's not to put in the description, but for me to remember what abilities the passive effect does not affect

rest of 600+ abilities that are not mentioned above i guess lmao

**Comment by Snoresville** [comment]
lmao my desk will be filled with my nose blood if i did a white-list instead of a black-list

**Comment by ZLOY5** [comment]
That should be whitelist of abilties with defined special values that should be affected. Otherwise we get tons of a bugs.

**Comment by Snoresville** [comment]
any more notes on the balance? maybe some abilities we're forgetting to include? (e.g. mystic flare)

**Comment by Draze22** [comment]
> 
> 
> any more notes on the balance? maybe some abilities we're forgetting to include? (e.g. mystic flare)

As discussed make sure the active can't be cast on ancient units. I decided not to add mystic flare and rocket barrage since they deal damage spread between any enemies in range but we could allow them to be affected.
