### ISSUE TITLE
Add a button to hide duel status UI

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#1106]
![2D8D0D42-BB85-4BEE-9431-5783222097C1](https://user-images.githubusercontent.com/50186248/116319471-ed02a180-a7f9-11eb-8051-8934aa165a62.png)
Button should save state between rounds but not between games

**Comment by efe-efe** [comment]
Isn't this the same as https://github.com/arcadia-redux/custom_hero_clash_issues/issues/1100 ?
