### ISSUE TITLE
Using the 9k gold re-choose mastery book reduces the maximum equiped masteries by 1

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1107]
![image](https://user-images.githubusercontent.com/63279022/116352354-5e614500-a838-11eb-8382-45e47f14d53f.png)

**Comment by Draze22** [comment]
This requires another unknown step.

**Comment by SanctusAnimus** [comment]
Probably a script error, couldn't reproduce
