### ISSUE TITLE
Cinder brew icon doesn't work in the ability picking UI

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1108]
![image](https://user-images.githubusercontent.com/63279022/116362083-0715a180-a845-11eb-821f-4987a98208e9.png)

**Comment by efe-efe** [comment]
Not sure how to reproduce this, i've tried forcing that spell and it shows the icon correctly 
![image](https://user-images.githubusercontent.com/20274256/116769514-c23b6780-aa0a-11eb-9ec6-60ece2ea85d1.png)

**Comment by SanctusAnimus** [comment]
Could be due to compilation error of sorts, can't reproduce
