### ISSUE TITLE
Attribute auto-leveling needs to be smarter

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1110]
Currently attribute auto-leveling happens at the same levels it does in vanilla Dota. The problem with this is in CHC players have 1-2 extra abilities.

Lazy but simple fix: delay the auto-leveling by 17 rounds, this will mean almost all players will have finished skilling their abilities and their talents. But it also means the more ultimate's a player has the less accurate this will be. Could be a decent hotfix but a bad long term fix.

Thorough but difficult fix: Start auto-leveling attributes based on how many ultimates and regular abilities the player has. 

Auto-leveling should start at level: 8 (talents) + 4 * number of regular abilities + 3 * number of ultimates + 1 (starting level). 

And to be extra thorough this should consider Necromastery and Requiem of Souls as two separate abilities despite the fact that taking Requiem gives Necromastery. For all other abilities with multiple parts it should consider them the same ability.

**Comment by SanctusAnimus** [comment]
Is that auto-leveling even introduced by us? i doubt we can influence it easily if it's not our mechanic

**Comment by Draze22** [comment]
Pretty sure we had the option of disabling it but I might be wrong. Maybe we can't alter it. If we can't alter it but can disable it that might be the better option.

**Comment by efe-efe** [comment]
For starters i will disable this mechanic (in a hacky way, because valve didn't provided API to disable it), since it doesn't makes much sense in CHC, mainly because you can swap abilities and refund the spent points. Is pretty hard to know when you actually wan't to keep those points for later usage
