### ISSUE TITLE
Add Shard and Scepter upgrade previews to the hero selection screen

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1116]
![image](https://user-images.githubusercontent.com/63279022/116520296-e406f280-a915-11eb-8ab7-945dd98c1b7e.png)

**Comment by SanctusAnimus** [comment]
But both shard and scepter are bound to abilities, not heroes? What's the point?

**Comment by Draze22** [comment]
Most players pick heroes to try and get their abilities.

**Comment by lovro-m** [comment]
Not all heroes have shard and scepter abilities. I don't know if this is a good or a bad thing.
