### ISSUE TITLE
Elder Dragon Form causes memory leaks

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1119]
![image](https://user-images.githubusercontent.com/63279022/116658335-24787600-a9d3-11eb-875c-316600b2e203.png)

**Comment by AustraliaIsMyCity** [comment]
o m e g a l u l we knew it did this before we added it back, the particles are never released and it makes a fuck ton of them

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/117243509-bc1a1080-ae7a-11eb-8ab7-aa682a57c173.png)

**Comment by SanctusAnimus** [comment]
Should be fixed by @ZLOY5 , reopen if still an issue (make sure it's uploaded tho)
