### ISSUE TITLE
Add an options to preview which innate choices you have

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1120]
Going to need Darklord to sign off on this.

![image](https://user-images.githubusercontent.com/63279022/116658902-11b27100-a9d4-11eb-9ec5-fb036ec4d863.png)

**Comment by Roshrach** [comment]
I agree on this  since usually, i base my innates on what skills i can pick first and vice versa

**Comment by SanctusAnimus** [comment]
Awaiting for @darklordabc input

**Comment by darklordabc** [comment]
No

**Comment by SanctusAnimus** [comment]
Aight
