### ISSUE TITLE
Add new ways to sort masteries

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1121]
1. Alphabetically. (This should be default and needs to be done separately for Chinese)
2. By most used for that player. (This would require tracking how often they used each ability and may not be worth implementing)
3. By what the mastery does, grouping masteries that do similar things. (This would need to be discussed and decided on)
4. A favorites category where the player can customize the order and save it for later. (Obviously requires some effort to implement)

For now option one should be implemented as the default sorting method and the other options can be discussed further and potentially implemented at a later date.

**Comment by Snoresville** [comment]
alphabetically would be poorly translated in russian/chinese unless we can handle it

**Comment by Draze22** [comment]
That's true, we would need to have it sorted alphabetically for each language separately.

**Comment by Snoresville** [comment]
names for innates in russian is the same as english, just need to deal with chinese

**Comment by Osamabinfrank** [comment]
I can help you correct the Russian name or description if you want.

**Comment by SanctusAnimus** [comment]
I'd stop on alphabetical and unlocked sorts (i.e. locked at the top, then unlocked, higher the level of unlocked - earlier it is)

**Comment by Jakarooo** [comment]
what about sorting masteries by color? i found it easier to find masteries that i wanted to use by color. This was, I guess, present before 7.29(not related at all) but probably removed by the devs

**Comment by ZLOY5** [comment]
![image](https://user-images.githubusercontent.com/10956575/117185060-1a46e500-ade2-11eb-9a54-ae9b5acbb824.png)
But not sure how it works for chinese localization
