### ISSUE TITLE
5v5 testing reminders

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#1131]
Just things that should be tested before 5v5 is released

- test what happens to a player who disconnects after loading but before pick phase
- test what happens to a player who disconnects during pick phase
- test what happens to a player who abandons the game
- test a full team abandon (should trigger victory for the other team)
- add more to this list as needed

**Comment by Snoresville** [comment]
we good with this? lol

**Comment by Snoresville** [comment]
enfos already out
