### ISSUE TITLE
hide MMR and parties until too late to escape

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1137]
players are leaving early when they see parties or people with high MMR, ruining the game for others, we should delay this information until they can't escape without getting penalized

Opened from Discord by **darklord#1296**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/838938516834222111)

**Comment by Osamabinfrank** [comment]
Just want to mention in advanced, its possible to see who is in a party at the dota 2 lobby filling screen so if you add that feature people won't be able to complain about parties as they had the opportunity to dodge the game before even connecting to the server.
