### ISSUE TITLE
Demo mode improvement suggestions

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1144]
- [x] Add a button to add/remove curses.
- [x] Allow retraining skills using retraining books.

**Comment by ZLOY5** [comment]
Curses button implemented.

Also you can remove any ability with retrain book and then pick other ability with demo UI. This is not enough?

**Comment by Draze22** [comment]
> Curses button implemented.

Ty ty.

> Also you can remove any ability with retrain book and then pick other ability with demo UI. This is not enough?

It would be nice to be able to test retraining mechanics in demo mode such as librarian (gives extra retrain choices). It's not too much more difficult to test these sorts of things with cheats in a solo lobby but it would be easier in demo mode.
