### ISSUE TITLE
Can't level attributes once you take every talent

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1147]
Don't know exactly what causes this yet.

**Comment by Jakarooo** [comment]
this is actually every time you complete the talents. well, at least in my experience

**Comment by SanctusAnimus** [comment]
Works for me just fine tho? And alt holding works too, so how is that a bug, it's how this window is working in dota

![NgpMBOGToW](https://user-images.githubusercontent.com/43399078/117951374-c7f35000-b31c-11eb-8d6e-b189278e8475.gif)

**Comment by Draze22** [comment]
Nevermind I just somehow never new clicking on the attribute tree did anything.

> Works for me just fine tho? And alt holding works too, so how is that a bug, it's how this window is working in dota
> 
> ![NgpMBOGToW](https://user-images.githubusercontent.com/43399078/117951374-c7f35000-b31c-11eb-8d6e-b189278e8475.gif)
