### ISSUE TITLE
Death Pact gives Burning Army even though Burning Army is linked to Strafe

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1148]
What's more, if a player has Aghanim's Scepter Death Pact and Strafe, retraining Strafe will remove Burning Army. This can be fixed by backpacking the Agh's Scepter and putting it back in your inventory. This more niche part of this bug won't be a problem once Death Pact with Agh's no longer gives Burning Army.

**Comment by SanctusAnimus** [comment]
In dota it's linked to death pact, why do we link it to strafe again? I'll remove link from death pact, but i'm just curious

**Comment by Draze22** [comment]
> In dota it's linked to death pact, why do we link it to strafe again? I'll remove link from death pact, but i'm just curious

It should actually be linked to Skeleton Walk since Clinkz' Aghs shard requires you to have both Burning Army and Skeleton Walk.

Fom memory someone decided it was better to link it to strafe despite my objections.
