### ISSUE TITLE
Tempest Double allows you to get a 4th Mastery

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1151]
I Haven't been able to reproduce this but it has been reported multiple times so it can be done. May need to set a fortune reward in the CHC discord for steps to reproduce this bug.

**Comment by Osamabinfrank** [comment]
Tempest for 4?

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/117527684-2d8bc780-b011-11eb-8ab9-43691730b2fc.png)

**Comment by Draze22** [comment]
Steps to reproduce:
1. Max out attributes on your hero to get a 3rd mastery.
2. Use Tempest Double (after round 4).
3. As the Tempest Double put a skill point into attributes.
4. You will be able to equip 4 masteries.
5. Reapeat setps 2 and 3 to get a 5th and 6th mastery.
