### ISSUE TITLE
Pirate Hat can spawn bounty rune on the invisible cliff surrounding fountain

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1153]
which makes it impossible to pickup unless some hero has flying movement

![bounty on the cliff](https://user-images.githubusercontent.com/59403389/117427266-2a1b1200-af25-11eb-9868-0536e70cc9c5.jpg)

**Comment by SanctusAnimus** [comment]
Eh what gives, it can be broken anyway
