### ISSUE TITLE
should ion shell be able to apply to creep-heroes?

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1154]
![cant put ion shell on bear](https://user-images.githubusercontent.com/59403389/117427985-e543ab00-af25-11eb-9cb3-c2ff1973b811.jpg)

**Comment by Draze22** [comment]
I don't see why it shouldn't.

**Comment by lovro-m** [comment]
It has been specifically overridden in the kv files so there must be a reason.

**Comment by Draze22** [comment]
Probably caused a bug with Spirit Bear.
