### ISSUE TITLE
Finger of Death counter resets to zero if killed by Finger of Death of another player

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1155]
not sure if same would happen with lotus/mirror involved,
another player must have skilled Finger of Death among their spells tho

![finger of death counter resets to 0](https://user-images.githubusercontent.com/59403389/117429349-43bd5900-af27-11eb-99d0-bc4f3cc9203b.jpg)

**Comment by Snoresville** [comment]
cant seem to replicate this with pvp, steps?

**Comment by Draze22** [comment]
This gets reported every so often but never with enough information to reproduce it.
