### ISSUE TITLE
Advertise in-game that we will reset mmr in 2 weeks

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1156]
Content: (see comment below for more details)
- [x] Title.
- [x] Description.
- [x] Rewards.

Design:
- [ ] Choose a position to place the pop-up.
- [ ] Choose the font style, size and colour for the title, description and rewards.
- [ ] Design the background and accompanying images/decoration.
- [ ] Incorporate the countdown clock which will be set for 2 weeks after we are ready to implement it.

Implementation:
- [ ] Code the countdown clock. (Needs to show weeks, days, hours, minutes).
- [ ] Code a close button.
- [ ] Implement everything that ends up being designed.

**Comment by Draze22** [comment]
Only some of the following will be implemented.
![image](https://user-images.githubusercontent.com/63279022/117450529-af81df00-af84-11eb-864c-960ce572342a.png)
![image](https://user-images.githubusercontent.com/63279022/117450552-b6a8ed00-af84-11eb-8108-1f07da84f9c3.png)

**Comment by SanctusAnimus** [comment]
Also note that there's no chests like those and i doubt we'll make them in time (or at all), so i guess don't mention them in advertisement at all

**Comment by Draze22** [comment]
Yeah, we'll only be doing the fortune and glory rewards for this reset.

**Comment by Osamabinfrank** [comment]
Don't you think the amounts of fortune is way too low? Imagine how people will feel to get rewarded with 15 fortune for 300 games+ with over 40 mins for each game wasted just to get so little that it won't be enough to even upgrades 1 mastery to lvl 3

**Comment by efe-efe** [comment]
I added some logic to manage the MMR reset countdown on the Dota Client, the idea is to retrieve the info from the server (in seconds) only once per match, and then update it on the Client by using a Timer. Here you can check the code to see if it serves the purpose: https://github.com/arcadia-redux/custom_hero_clash/pull/807

Any feedback is well received

**Comment by Draze22** [comment]
Done.
