### ISSUE TITLE
Add zoom controls

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1157]
Very subtle slider hidden on hud somewhere that can be permanently hidden, that allows players to control how zoomed in or out the camera is

Opened from Discord by **darklord#1296**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/840221379005513798)

**Comment by Draze22** [comment]
This has actually been decided to be put in settings (still with a slider).
