### ISSUE TITLE
Possible causes of the frequent crashes

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1159]
1. Luminance/Blademail causing what would previously have been ties.
2. False Promise ending and causing lethal damage after the duel has ended but before the player is teleported to the fountain.
3. Borrowed time activating automatically during a duel.

**Comment by fcalife** [comment]
GJ. what was happening?

**Comment by Draze22** [comment]
> GJ. what was happening?

https://github.com/arcadia-redux/custom_hero_clash_issues/issues/1164
