### ISSUE TITLE
Mastery tier 3 upgrade duration became undefined

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1161]
![image](https://user-images.githubusercontent.com/63279022/117607483-69ed2e00-b19f-11eb-83f1-f9eeb1d4ca3b.png)
![image](https://user-images.githubusercontent.com/63279022/117607489-6c4f8800-b19f-11eb-9bd0-b585939f3741.png)

**Comment by Draze22** [comment]
This indicates that this can happen the day before a tier 3 mastery upgrade runs out.
![image](https://user-images.githubusercontent.com/63279022/117607602-b0428d00-b19f-11eb-811c-f78b79b363f0.png)

**Comment by Sheodar** [comment]
Should be fixed after commit 29.05.21:2:48 (GMT+2)
