### ISSUE TITLE
Borrowed time + aeon disk is causing servers to crash during duels

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1164]
Steps to reproduce:
1. Have borrowed time and aeon disk.
2. Get into a duel.
3. Have your aeon disk procced.
4. Let Aeon disk effect end.
5. Take more damage so borrowed time procs automatically.
6. Server will crash every time.

**Comment by Draze22** [comment]
> Borrowed time activates during aeon disk active or after?

Aeon Disk activates first, then after the buff fades the player is damage further by their opponent, this is when borrowed time activates and crashes the server.

**Comment by ZLOY5** [comment]
I`m not sure it fixed, but i cant reproduce it now
