### ISSUE TITLE
Monkey Menace overtime bug

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1167]
Steps to reproduce:
1. Start Monkey Menace wave and don't kill the big monkey.
2. Survive until overtime ends (easier said than done without cheats).
3. Once the round forcibly ends you will lose an aegis, be respawned in the fountain and several smaller Monkeys will permanently be in your creep arena.

This is primary abusable in PVE games.

**Comment by Draze22** [comment]
I think the sort of solution we need to this is when overtime ends and we kill all creeps, we kill all creeps again 5 seconds later.

**Comment by SanctusAnimus** [comment]
Iirc @ZLOY5 tried to fix that and splitting stone dudes bug? Is there any confirmation on it still being an issue?

**Comment by Draze22** [comment]
> Iirc @ZLOY5 tried to fix that and splitting stone dudes bug? Is there any confirmation on it still being an issue?

Since it's so difficult to abuse and no-one has reported it since I'm going to close this.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/131435098-0726dec4-8e3f-4f32-a32f-9bfce2e8156f.png)
![image](https://user-images.githubusercontent.com/63279022/131435174-3abbb096-08f9-4845-acc0-fa95fab54738.png)
