### ISSUE TITLE
The server crashes every second game

### ISSUE THREAD

**Issue by izhastron** [arcadia-redux/custom_hero_clash_issues#1168]
1) Traceback:

[VScript] Script Runtime Error: ...ts/vscripts/heroes/hero_warlock/warlock_upheaval_lua.lua:163: attempt to call method 'SendBuffRefreshToClients' (a nil value)
stack traceback:
	...ts/vscripts/heroes/hero_warlock/warlock_upheaval_lua.lua:163: in function 'Data'
	...ts/vscripts/heroes/hero_warlock/warlock_upheaval_lua.lua:153: in function <...ts/vscripts/heroes/hero_warlock/warlock_upheaval_lua.lua:151>
[VScript] Script Runtime Error: ...ts/vscripts/heroes/hero_warlock/warlock_upheaval_lua.lua:163: attempt to call method 'SendBuffRefreshToClients' (a nil value)
stack traceback:
	...ts/vscripts/heroes/hero_warlock/warlock_upheaval_lua.lua:163: in function 'Data'
	...ts/vscripts/heroes/hero_warlock/warlock_upheaval_lua.lua:153: in function <...ts/vscripts/heroes/hero_warlock/warlock_upheaval_lua.lua:151>
	
[VScript] Script Runtime Error: ...ts/vscripts/heroes/hero_warlock/warlock_upheaval_lua.lua:163: attempt to call method 'SendBuffRefreshToClients' (a nil value)
stack traceback:
	...ts/vscripts/heroes/hero_warlock/warlock_upheaval_lua.lua:163: in function 'Data'
	...ts/vscripts/heroes/hero_warlock/warlock_upheaval_lua.lua:153: in function <...ts/vscripts/heroes/hero_warlock/warlock_upheaval_lua.lua:151>
[VScript] Message count limit of 10 hit. Subsequent duplicate messages will be squelch

2) Traceback:

[VScript] Script Runtime Error: .../2141071809.vpk:scripts/vscripts/items/ranged_cleave.lua:35: attempt to index local 'ability' (a nil value)
stack traceback:
	.../2141071809.vpk:scripts/vscripts/items/ranged_cleave.lua:35: in function <.../2141071809.vpk:scripts/vscripts/items/ranged_cleave.lua:32>
[Entity System] ExecuteQueuedCreation() took 1213us [ Spawned: 18, Activated 0, PostDataUpdate: 93, Destroyed: 0, Deallocated: 0, PvsUpdate: 0 ]
Set target panel parameter "title" to the value "Heavy Armory"
Set target panel parameter "ability_1" to the value "1334"
[SteamNetSockets] [#1448587917 SDR server steamid:90146462719227913 vport 0] 2 reply timeouts, last recv 5363.4ms ago.  Sending keepalive.

**Comment by izhastron** [comment]
After these traces, the server freezes and floods. [SteamNetSockets] [# 1448587917 SDR server steamid: 90146462719227913 vport 0] 2 reply timeouts, last recv 5363.4ms ago. Sending keepalive.

**Comment by SanctusAnimus** [comment]
Should have been fixed with borrowed time/aeon fixes
