### ISSUE TITLE
Players are somehow spawning as multiple heroes

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1169]
![image](https://user-images.githubusercontent.com/63279022/117760583-3b3b8a00-b269-11eb-8232-fa089f85f96f.png)
![image](https://user-images.githubusercontent.com/63279022/117760598-4098d480-b269-11eb-96f3-74faab91be01.png)

**Comment by Draze22** [comment]
The same player seems to be abusing this.

**Comment by Osamabinfrank** [comment]
His steam incase you need it.
https://steamcommunity.com/profiles/76561198894140858
