### ISSUE TITLE
Rend debuff stays on Spirit Bear after a duel

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1170]
![image](https://user-images.githubusercontent.com/63279022/117761023-febc5e00-b269-11eb-857c-a29562a2d0e0.png)

**Comment by lovro-m** [comment]
How did you reproduce this? I get into a duel with a bot spirit bear and after the duel the bear has rend debuff in base, but when the next round teleports the bear rend modifier is no longer there.

**Comment by Draze22** [comment]
> How did you reproduce this? I get into a duel with a bot lone druid with a spirit bear and after the duel the bear has rend debuff in base, but when the next round teleports the bear rend modifier is no longer there.

Sounds like it got fixed then.
