### ISSUE TITLE
Magician doesn't change the visual width of Macropyre

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1171]
![image](https://user-images.githubusercontent.com/63279022/117761139-30352980-b26a-11eb-82f0-33af23d5a693.png)

**Comment by SanctusAnimus** [comment]
Looks like a particle limitation. Should we disable magician from working on macropyre width at all?

**Comment by Draze22** [comment]
> Looks like a particle limitation. Should we disable magician from working on macropyre width at all?

Or we could add an ability note that explains that it does increase the width, just not visually.

**Comment by Draze22** [comment]
Tooltip Added: https://github.com/arcadia-redux/custom_hero_clash/commit/a941954857e41384b8d845087f99684b2bbe8669.
