### ISSUE TITLE
Nerf boots of travel

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1175]
Boots of travel feel a little overtuned at the moment since Valve has systematically made many fast abilities and heroes slower in recent patches.

**Comment by Snoresville** [comment]
What seems to be the problem? too cheap of an option, speed bonus too powerful, or something else?

**Comment by Draze22** [comment]
> What seems to be the problem? too cheap of an option, speed bonus too powerful, or something else?

The amount of movespeed they give is just a little too obnoxious at the moment.

**Comment by Snoresville** [comment]
suggestions for the new value?

**Comment by Osamabinfrank** [comment]
Why would you nerf something like this? It gives an opportunity to snowball and comeback, its been like this for months and no one had any issues, its very fun and nerfing such minor yet great thing doesn't seems reasonable.

**Comment by WDCGroup98** [comment]
blame draze for opening this lol

**Comment by Snoresville** [comment]
no more discussion about this for 3 weeks? sounds like boots of travel is not a problem

**Comment by Draze22** [comment]
> suggestions for the new value?

Nerf boots of travel 2 from 225 movespeed to 205 movespeed.
