### ISSUE TITLE
Add Commending

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1177]
Can be used in scoreboard during game, or in end game scoreboard, can only be used once per game, every player can use it

Opened from Discord by **darklord#1296**
Follow the conversation [here](https://discord.com/channels/501306949434867713/769109626020298784/841731991098884127)

**Comment by AustraliaIsMyCity** [comment]
add tipping at the same time

**Comment by AustraliaIsMyCity** [comment]
commends are dumb, making a new issue for tipping
