### ISSUE TITLE
Spirit Bear doesn't get automatically teleported to Duels

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1178]
![image](https://user-images.githubusercontent.com/63279022/118082418-83d97b80-b400-11eb-8d79-d6d31cfce355.png)

**Comment by ZLOY5** [comment]
I fixed that yesterday.
https://github.com/arcadia-redux/custom_hero_clash/commit/c599c1aaf39637c01d87edbfe10f36f0656b7b37
