### ISSUE TITLE
Flying movement can be used to prevent creeps from hitting you

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1181]
![image](https://user-images.githubusercontent.com/63279022/118368462-8517cd80-b5e5-11eb-9dd4-432c09096ce3.png)
![image](https://user-images.githubusercontent.com/63279022/118368476-8b0dae80-b5e5-11eb-920d-4b86b73a5973.png)

**Comment by lovro-m** [comment]
Should we make creeps be able to destroy trees with their movement if the clock runs out?

**Comment by Draze22** [comment]
> Should we make creeps be able to destroy trees with their movement if the clock runs out?

That should work.
