### ISSUE TITLE
Breaker innate can cause the focus innate to not trigger

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1184]
![image](https://user-images.githubusercontent.com/63279022/118389772-dae48800-b66e-11eb-892a-953891d8b79e.png)

**Comment by Snoresville** [comment]
it may be incorrectly reported, for all we know, it could be a coincidence where he picked focus in the middle of a duel and his opponent happens to have the breaker innate

**Comment by Draze22** [comment]
> it may be incorrectly reported, for all we know, it could be a coincidence where he picked focus in the middle of a duel and his opponent happens to have the breaker innate

Since it hasn't been reported again and I couldn't reproduce it I'm going to assume you're correct.
