### ISSUE TITLE
Late Bloomer doesn't work retroactively

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1185]
Late Bloomer doesn't count bosses a player kills before they take late bloomer.

**Comment by Draze22** [comment]
Waiting on approval from Firetoad or Darklord to decide if we consider this a feature and rewrite the description, or call it a bug and track how many bosses every player/team has killed every game (or some other better solution to fix this bug).

**Comment by Snoresville** [comment]
why should it be retroactive? by round 10, people should have an idea of what innate to take

**Comment by Draze22** [comment]
> why should it be retroactive? by round 10, people should have an idea of what innate to take

The description says it's retroactive.

**Comment by Snoresville** [comment]
what the fuck

**Comment by Draze22** [comment]
It also says it provides the bonus stats for every boss you defeat, not every boss you defeat after choosing late bloomer.
