### ISSUE TITLE
Camera zoom out feature makes the screen increasingly black as you zoom out in DUOS

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1188]
The black section of the screen starts at the top and gets larger as you zoom out further. Interestingly it also starts covering arenas before it starts covering the borders between arenas.

![image](https://user-images.githubusercontent.com/63279022/118767855-9f8dc780-b8c1-11eb-8532-786380869653.png)
![image](https://user-images.githubusercontent.com/63279022/118767881-a74d6c00-b8c1-11eb-9302-0d0ae2242de7.png)
![image](https://user-images.githubusercontent.com/63279022/118767906-ae747a00-b8c1-11eb-8668-a7cb5f121ac2.png)
![image](https://user-images.githubusercontent.com/63279022/118767928-b59b8800-b8c1-11eb-989a-762992a71f36.png)

**Comment by SanctusAnimus** [comment]
Far z clipping kicks in lol, this needs to be tweaked in the map, and increasing it might hurt performance
