### ISSUE TITLE
Rearm Lua isn't considered a channel by the "channeled abilities require hold/stop" setting

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1192]
In other words even if you activate the "channeled abilities require hold/stop" setting in chc, rearm will cancel if you issue any action.

**Comment by SanctusAnimus** [comment]
doesn't seem like we can fix this, `IsChannelling` is not declared for lua abilities. reopen if someone dealt with this and knows how to fix it, i've tried most of the channel-related functions and failed
