### ISSUE TITLE
Duos duel winnings aren't displaying correctly

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1195]
Seems like the barrage text and duel history are innacurate.
![image](https://user-images.githubusercontent.com/63279022/118987417-94bb5b80-b9c3-11eb-8730-8eb7be34c90e.png)

**Comment by Snoresville** [comment]
is there a picture that shows the two marked sections and the gold on the barrage text? (the text the floats on the screen)

**Comment by Draze22** [comment]
> is there a picture that shows the two marked sections and the gold on the barrage text? (the text the floats on the screen)

Not that I can find.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/119095951-4acf8580-ba56-11eb-9a44-ee1640383a0b.png)

**Comment by Sheodar** [comment]
History past total results. Your personal history profit only

**Comment by Draze22** [comment]
> History past total results. Your personal history profit only

We know, it's 4x in the past results than it is in personal history instead of 2x.

**Comment by Sheodar** [comment]
Will check it. Just all this places have one source (barrage, history, personal histoty).

**Comment by Draze22** [comment]
> is there a picture that shows the two marked sections and the gold on the barrage text? (the text the floats on the screen)
![image](https://user-images.githubusercontent.com/63279022/119250593-7e401a80-bbe4-11eb-95e9-0194e5f7ad79.png)

**Comment by Snoresville** [comment]
need to see history too

**Comment by Draze22** [comment]
> need to see history too

Overall history and barrage text are double the duel summary and actual gold given based on all of these reports combined.

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **44** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.
