### ISSUE TITLE
Fix bonus abilities showing up in the duel UI

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#1196]
It should ONLY show proper abilities (ones which can be found when retraining, not granted by another ability or aghanims shard/scepter)
As a result of the current implementation, items sometimes get squished or don't show up at all, plus some abilities get cut off and dont show up:
![image](https://user-images.githubusercontent.com/50186248/119072580-0d0b3680-ba2f-11eb-81fc-40f815a40b4c.png)

Additionally please add:
- icons for aghs shard and scepter (always there but greyed out if players dont have them)
- What masteries the player has (but not what level), can just copy the UI from the existing mastery display for this.

**Comment by Sheodar** [comment]
- [ ] Hide addition abilities from shard/scepter (players can have a lot of this, our UI in a lot of places support 6 abilities)
- [ ] Add masteries traciking
