### ISSUE TITLE
DUOS players who disconnect while picking a hero still aren't always given a hero when they reconnect to the game

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1197]
![image](https://user-images.githubusercontent.com/63279022/119095785-1065e880-ba56-11eb-960a-f549b5266ee7.png)
![image](https://user-images.githubusercontent.com/63279022/119095799-14920600-ba56-11eb-8fd7-53670e8bf382.png)

**Comment by ZLOY5** [comment]
https://github.com/arcadia-redux/custom_hero_clash_issues/issues/972
Isn't it duplicate?

**Comment by Draze22** [comment]
Yes.
