### ISSUE TITLE
Tempest Double is effected by enemy's cascading arcana even when resummoned

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1198]
![image](https://user-images.githubusercontent.com/63279022/119143494-027e8a80-ba8b-11eb-8ed9-f85ea4c12fdb.png)
![image](https://user-images.githubusercontent.com/63279022/119143583-19bd7800-ba8b-11eb-8b75-040c183f65a7.png)

**Comment by SanctusAnimus** [comment]
Duplicate of 1172
