### ISSUE TITLE
Winters Curse + Fan of Knives instantly kills bosses

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1199]
Probably also intantly kills regular creeps and anicent creeps.
https://www.youtube.com/watch?v=p5oSq3IvFVk&t=11s

**Comment by ZLOY5** [comment]
To fix this we need rewrite Winters Curse. Ability prevents all potentially deadly damage and reapply it with Winter Curse ability inflictor and DAMAGE_TYPE_NONE.

**Comment by fcalife** [comment]
check if adding winter's curse to the list of no-spell-amp abilities works to prevent this.

**Comment by ZLOY5** [comment]
It kinda works, but Winter Curse just apply damage that equal to target health, not original value
