### ISSUE TITLE
You can get mutliple Spirit Bears by retraining Spirit Bear and getting it back again

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1202]
https://www.youtube.com/watch?v=9yXpL1ApfHM&t=141s
![image](https://user-images.githubusercontent.com/63279022/119229708-953b2a00-bb5c-11eb-9616-5523b58dd34a.png)
![image](https://user-images.githubusercontent.com/63279022/119229717-9cface80-bb5c-11eb-8fa2-01536d3b0ee7.png)

**Comment by lovro-m** [comment]
I am following this video and I am having trouble consistantly replicating the bug. In about 20% of cases I get two bears. Am I supposed to cancel rearm or something? I make sure to level up the bear before the rearm like at 0:18 in the video.

**Comment by Draze22** [comment]
> I am following this video and I am having trouble consistantly replicating the bug. In about 20% of cases I get two bears. Am I supposed to cancel rearm or something? I make sure to level up the bear before the rearm like at 0:18 in the video.

I'll test this out when I get the chance.
