### ISSUE TITLE
Cooldown of eye of midas is not ticking down on tempest double clone

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1203]
Cooldown of eye of midas is always stuck at 10 rounds for tempest double and not ticking down, so tempest double can use eye of midas only once per game

Opened from Discord by **Chariot#5818**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/845746464687915061)

**Comment by AustraliaIsMyCity** [comment]
this doesnt matter as tempest double should not be able to use eye of midas
