### ISSUE TITLE
Centre the DUOS creep arena camera position on the centre of the creep arena

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1204]
![image](https://user-images.githubusercontent.com/63279022/119305736-7ba8f800-bcac-11eb-94d9-dc53f8883034.png)

**Comment by ZLOY5** [comment]
Slightly moved camera to center
![image](https://user-images.githubusercontent.com/10956575/120159528-fb2f4d80-c1fd-11eb-8224-da784c4844ba.png)
