### ISSUE TITLE
Mirror Shield may not interact correctly with Magus

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1205]
![image](https://user-images.githubusercontent.com/63279022/119305996-d9d5db00-bcac-11eb-8013-b255e1a63068.png)

**Comment by efe-efe** [comment]
It doesn't seems to be the case, at least i can't reproduce it. Video proof:


https://user-images.githubusercontent.com/20274256/119529825-71403a00-bd50-11eb-92b0-503ac251245d.mp4

**Comment by Draze22** [comment]
> It doesn't seems to be the case, at least i can't reproduce it. Video proof:

I agree, everything looks fine there.
