### ISSUE TITLE
Rework Tinkerer

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1208]
* [x] Prevent it from doubling any Neutral Item cooldowns.
* [x] Prevent it from doubling the cooldown reduction from spell prism and quickening charm.
* [x] Make it have 50% effect on tier 5 Neutral Items.

**Comment by Draze22** [comment]
Add these reworks to this pull request: https://github.com/arcadia-redux/custom_hero_clash/pull/813.

**Comment by Snoresville** [comment]
Closed because the tasks were done in a commit: https://github.com/arcadia-redux/custom_hero_clash/commit/59846495d831ea093dc610fd95937ed03e99b229
