### ISSUE TITLE
Focus starts at max stacks when chosen during a duel

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1212]

**Comment by Draze22** [comment]
@ZLOY5 are you sure this was fixed correctly because I'm not even sure how to reproduce this bug?

**Comment by ZLOY5** [comment]
I`ve got this bug few times during work on https://github.com/arcadia-redux/custom_hero_clash_issues/issues/1183, but I thought I fixed it

**Comment by Draze22** [comment]
> I`ve got this bug few times during work on #1183, but I thought I fixed it

Ok, I'll check it next update to make sure.

**Comment by Draze22** [comment]
Focus seems to start at 270 stacks when chosen during a duel now.

![image](https://user-images.githubusercontent.com/63279022/120742540-69477d80-c53a-11eb-9c3e-d32679b95dbf.png)
![image](https://user-images.githubusercontent.com/63279022/120742547-6cdb0480-c53a-11eb-9982-f8de1ec4e17d.png)
