### ISSUE TITLE
Metamorphosis appears to be able to cause large amounts of lag just by activating it

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1213]
https://www.youtube.com/watch?v=YmDkkkSEjGk
![image](https://user-images.githubusercontent.com/63279022/119496412-cf980780-bda6-11eb-9876-21b2ae86df4a.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/120649153-cc47fe80-c4bf-11eb-93ec-c057302ecba7.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/120649310-f39ecb80-c4bf-11eb-8b4f-8c431f297446.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.
