### ISSUE TITLE
Dispersion is affected by spell amp

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1216]
Dispersion should not be affected by spell amp but currently is.

**Comment by Osamabinfrank** [comment]
It was affected by it for at least 3 months

**Comment by Draze22** [comment]
> It was affected by it for at least 3 months

It was rewritten in lua 5 days ago which is probably why it is currently affected by spell amp, I doubt it has been affected by spell amp for 3 months without anyone noticing and reporting it.

**Comment by Osamabinfrank** [comment]
> > It was affected by it for at least 3 months
> 
> It was rewritten in lua 5 days ago which is probably why it is currently affected by spell amp, I doubt it has been affected by spell amp for 3 months without anyone noticing and reporting it.

You were asking questions about it in the past, at that point it was already affected by spell amp
