### ISSUE TITLE
Reconnecting to the game breaks getting a third mastery from maxing out attributes

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1224]
I don't have exact steps to reproduce this yet but this video shows what happens when you do it: https://youtu.be/cQ0t3uOKSsQ.

![image](https://user-images.githubusercontent.com/63279022/120130362-5a468f80-c209-11eb-824e-963418969ea2.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/123597206-60df1b80-d836-11eb-8d98-774ecf91cdb0.png)
![image](https://user-images.githubusercontent.com/63279022/123597230-69375680-d836-11eb-83f1-c6ff50f16d9f.png)

**Comment by chariot-afv** [comment]
Still happening
![unknown](https://user-images.githubusercontent.com/44137926/125187144-efe52e00-e24f-11eb-8c8a-d5924ae49896.png)

**Comment by Sheodar** [comment]
Previous commit didn't fix it. Fixed this now.
