### ISSUE TITLE
Regular abilities in slot 7+ (no hotkey) don't show up in the duel UI

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1226]
We may need to confirm is having bonus abilities in slots 1 through 5 does the same thing.

![image](https://user-images.githubusercontent.com/63279022/120130986-c37ad280-c20a-11eb-8afd-f1b7d22d8335.png)

**Comment by Osamabinfrank** [comment]
![image](https://user-images.githubusercontent.com/80932191/120132107-6bc07500-c1d2-11eb-9b24-1d09aa8a3768.png)
checked for you.
