### ISSUE TITLE
Come up with a way to help disconnected players not die without it being abuse-able

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1227]
If we go too far players will intentionally disconnect during difficult rounds to beat them. If we do nothing players will keep getting frustrated by dying every time they disconnect.

At the moment I'm thinking when a player disconnects, once they lose an aegis they win the round. This is abuseable by players that know they'll lose both of their aegises but it may be worth it on the whole.

**Comment by Osamabinfrank** [comment]
cant you make something like for the first 3-6 rounds when all online players done the wave dced players get aegis lost buff but only for the first rounds?

**Comment by SanctusAnimus** [comment]
Should be tackled in master
