### ISSUE TITLE
Blitz strike one-shotting people causes bugs

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1230]
Blitz Strike can one shot players even if they have the Berserker innate.

![image](https://user-images.githubusercontent.com/63279022/120133944-6da92900-c210-11eb-8ce2-ca4398e46311.png)
![image](https://user-images.githubusercontent.com/63279022/120133957-739f0a00-c210-11eb-8e28-ad49b9cbcd5b.png)

**Comment by Draze22** [comment]
It's looking like it might only be Laguna Blade that can ause this (might have to do with the Shard, Aghs or a combination of both).
![image](https://user-images.githubusercontent.com/63279022/121802672-eaacb780-cc80-11eb-8b22-a92d13362536.png)

**Comment by Snoresville** [comment]
weird, blitz strike is only a damage increase

**Comment by lovro-m** [comment]
Maybe we should make it non-lethal damage to avoid one shots?

**Comment by ZLOY5** [comment]
Core of the problem: Aeon Disk check hp threshold before Blitz Strike damage multiplier applied ( in damage filter, that really last thing before damage really applied).
So better rework Blitz Strike to use MODIFIER_PROPERTY_BONUSDAMAGEOUTGOING_PERCENTAGE or something similar

**Comment by Draze22** [comment]
Video of a player getting elimanted after losing a duel because of Blitz Strike: https://www.youtube.com/watch?v=TFk5DTztYKM.

![image](https://user-images.githubusercontent.com/63279022/123534775-cf52a980-d762-11eb-8441-22589e6ff578.png)
