### ISSUE TITLE
Rework book of summoner

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#1231]
Change it from removes a random ability, giving a random summon ability to removes a chosen ability, replacing it with a choice between 2 summon abilities (NO DISCARD MECHANIC, can reroll it). New cost of 5k gold.

**Comment by Draze22** [comment]
Consume: Conjuration
Choose an ability to unlearn and draw a new one. Gives a choice between 2 summon abilities.
Hold down SHIFT while purchasing this item to instantly use it.

**Comment by Osamabinfrank** [comment]
Increase the chances for techies mines plz.. Tnx
