### ISSUE TITLE
Frost Army Boss's stun doesn't have an animation

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1233]
![image](https://user-images.githubusercontent.com/63279022/120289874-18027880-c305-11eb-9a48-bab9186f1070.png)

**Comment by lovro-m** [comment]
This one?
![frostarmy](https://user-images.githubusercontent.com/63733825/122891690-00874000-d345-11eb-918c-6697376d4c2d.gif)

**Comment by ZLOY5** [comment]
It fixed after reupload with compiled particles
