### ISSUE TITLE
Update masteries again

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1234]
it's been two weeks, time to do it again

Opened from Discord by **darklord#1296**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/849239093090451458)

**Comment by Draze22** [comment]
Balanced the most extreme masteries here (except Sprinter): https://github.com/arcadia-redux/custom_hero_clash/pull/824.

Still need to discuss the best way to buff sprinter.

**Comment by Draze22** [comment]
Done: https://github.com/arcadia-redux/custom_hero_clash/compare/da73cc88d8a1...236947030df9.
