### ISSUE TITLE
Switcheroo (ranged to melee) can stop working randomly

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1237]
I doubt this is accurate but it's difficult to prove it can't happen.

![image](https://user-images.githubusercontent.com/63279022/120404871-a53be080-c38a-11eb-94d3-23fe62b97b7a.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/123746749-68b1c500-d8f5-11eb-946e-28ea641ea813.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.
