### ISSUE TITLE
Link Tree Volley (Aghanim's Scpeter) to Tree Grab

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1238]
Also remember to unlink it from the ability it's currently linked to (presumably Grow).

**Comment by lovro-m** [comment]
Currently Grow gives craggy exterior when you have a shard upgrade. Do you want me to keep it like that?

**Comment by lovro-m** [comment]
Also Tree Volley is already linked to tree grab. 
![image](https://user-images.githubusercontent.com/63733825/120920412-e996eb80-c6be-11eb-9b54-6ad38478fc6a.png)

**Comment by Draze22** [comment]
> Currently Grow gives craggy exterior when you have a shard upgrade. Do you want me to keep it like that?

Yes.

**Comment by Draze22** [comment]
> Also Tree Volley is already linked to tree grab.
> ![image](https://user-images.githubusercontent.com/63733825/120920412-e996eb80-c6be-11eb-9b54-6ad38478fc6a.png)

I wonder if someone changed that recently.

**Comment by lovro-m** [comment]
So can we close this then?
