### ISSUE TITLE
Grand Librarian needs visual/practical improvement (discard button gets cut off)

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1239]
The Discard button gets cut off when a player has Grand Librarian and still has rerolls left.

Duos:
![image](https://user-images.githubusercontent.com/63279022/120642497-4ffded00-c4b8-11eb-9316-fe6c13803580.png)

FFA:
![image](https://user-images.githubusercontent.com/63279022/120643687-cfd88700-c4b9-11eb-9018-d31cb59f7d5f.png)

**Comment by SanctusAnimus** [comment]
It wasn't designed to fit so many abilities, and moving it up will conflict with quests window

**Comment by SanctusAnimus** [comment]
I'd honestly would give librarian +N rerolls or something like that, rather then making significant UI changes for the sake of single innate

**Comment by Draze22** [comment]
> I'd honestly would give librarian +N rerolls or something like that, rather then making significant UI changes for the sake of single innate

That does sound better.

**Comment by ZLOY5** [comment]
So what with this?
I added later button and it get worse, now u can see only Later, reroll and discard now hidden

**Comment by Draze22** [comment]
> So what with this?
> I added later button and it get worse, now u can see only Later, reroll and discard now hidden

yeah we need to rework librarian
