### ISSUE TITLE
Quality of Life improvements

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#1242]
All of these are suggestions from the community and can be found [here](https://discord.com/channels/694060511209324585/829873120638009354/829873214096277545)

- [x] Add a button to lock abilities, preventing them from being retrained (can be shown as greyed out, maybe with a padlock icon over the ability in the retraining menu)
- [x] Show previous matchup results in dueling UI
- [x] Add icons to the duel screen for Agh's shard, blessing, consumed moon shard
- [x] Add an indicator in the collection showing if you've earned your daily fortune
- [ ] Add a button to have the camera follow a chosen player when you are spectating or eliminated
- [x] Make ready-up accelerate all cooldowns to the point they would be at if the time wasn't skipped
- [x] Add a visual indicator to luminance when its bonus damage buff is active/inactive (just change the icon to be more/less epic)
- [x] #1697

**Comment by SanctusAnimus** [comment]
> Add a way to see what your teammate is planning to bet in real time

Should be first consulted with designers, we already have a ton of stuff in duel/betting window, same goes for this one
> Show previous matchup results in dueling UI

**Comment by AustraliaIsMyCity** [comment]
gonna split off the final issue and close this
