### ISSUE TITLE
Implement changes to Sprinter Mastery

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1243]
New (level 1/2/3): +50/100/150 move speed, and +0.5/1/2% outgoing damage for every 100 move speed.

**Comment by ZLOY5** [comment]
It going to be nerfed in my opinion

**Comment by Osamabinfrank** [comment]
> It going to be nerfed in my opinion

I doubt it necessarily, it doesn't seem to be op or worth a slot
