### ISSUE TITLE
Auto-attack set to always doesn't work

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1244]
Auto-attack set to always doesn't work unless you set it to never and back to always.

No clue if and how we can fix this.

**Comment by Osamabinfrank** [comment]
i doubt you can , over custom games also has it

**Comment by SanctusAnimus** [comment]
Valve being valve

**Comment by ZLOY5** [comment]
I`ve investigate this bug before. 
And find way to fix it, but can`t check if player really enabled always attack or not, so it force all players to use this option
`function modifier_auto_attack_fix:OnCreated()
	if GetLocalPlayerID() == self:GetParent():GetPlayerOwnerID() then
		SendToConsole("dota_player_units_auto_attack_mode 1")
		self:StartIntervalThink(1)
	end
end

function modifier_auto_attack_fix:OnIntervalThink()
	self:Destroy()
	SendToConsole("dota_player_units_auto_attack_mode 2")
end`

**Comment by SanctusAnimus** [comment]
well i don't thing we should force players to certain auto-attack mode

**Comment by ZLOY5** [comment]
Maybe anyone other know how to get it

**Comment by Osamabinfrank** [comment]
> well i don't thing we should force players to certain auto-attack mode, without knowing their options

Make a [v] opinion in the interface where the auto spectate, camera etc located
