### ISSUE TITLE
Attempt to have every player participate in the same number of duels by round 40

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1247]
A big problem is some players will go into sudden death having been in 1-2 less duels than most other players, causing them to then be in multiple in a row when duels start to be very detrimental to lose.

**Comment by fcalife** [comment]
Is resetting everyone's duel counter after round 40 an acceptable compromise?

**Comment by Draze22** [comment]
> Is resetting everyone's duel counter after round 40 an acceptable compromise?

Not ideal but better than the current system.

**Comment by ZLOY5** [comment]
So when sudden death activated clear duel counter for teams?

**Comment by AustraliaIsMyCity** [comment]
just clear all weights for matchmaker, that would be fine by me.

**Comment by fcalife** [comment]
I agree with just clearing it after r40
