### ISSUE TITLE
Make Grand Librarian give players a 100% chance to be offered one of their abilities

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1248]
Make Grand Librarian give players a 100% chance to be offered one of their abilities instead of the standard 65% (in the top left choice as normal of course).

**Comment by SanctusAnimus** [comment]
Does that replace current +N abilities in each selection? I hope it does

**Comment by Draze22** [comment]
> Does that replace current +N abilities in each selection? I hope it does

No, that would be in addition to the +N abilities in each selection.

**Comment by SanctusAnimus** [comment]
Well the count of bonus abilities should still be heavily reduced

**Comment by Draze22** [comment]
> Well the count of bonus abilities should still be heavily reduced

At 6 bonus choices it was an average innate and I've just reduced it to 4 bonus choices to stop it from breaking the UI. I'll be keeping a close eye on it to make sure it isn't OP if and when we make this new change.
