### ISSUE TITLE
Epicentre Agh's Shard doesn't work unless you're Sand King

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1249]

**Comment by lovro-m** [comment]
![epicenter3](https://user-images.githubusercontent.com/63733825/121805902-99cf9b80-cc4d-11eb-8ef6-879b347f7938.gif)
It doesn't work in the main area where it's not supposed to.

**Comment by Draze22** [comment]
> ![epicenter3](https://user-images.githubusercontent.com/63733825/121805902-99cf9b80-cc4d-11eb-8ef6-879b347f7938.gif)
> It doesn't work in the main area where it's not supposed to. Maybe with some items or other spells?

Ok, turns out it only works if you're Sand King.

**Comment by lovro-m** [comment]
Oh, I see.
