### ISSUE TITLE
Players can't upgrade masteries back to level 3 for a short period after their level 3 runs out

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1250]
![image](https://user-images.githubusercontent.com/63279022/121522262-43d5da80-ca38-11eb-9dc1-443ada019e29.png)

**Comment by ZLOY5** [comment]
Seems he still have lvl 3.
May be related to https://github.com/arcadia-redux/custom_hero_clash_issues/issues/1161
