### ISSUE TITLE
Bring back monkey king ultimate

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1253]
Opened from Discord by **darklord#1296**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/853029190458933258)

**Comment by ArcadiaReduxAutomation** [comment]
use creeps with caster model and have their attack (with 0 damage) proc main hero attacks without modifiers. Should also reduce amount of monkeys to something reasonable, like just a first circle of them

Comment from Discord by **Sanctus Animus#3413**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/853029987761651712)

**Comment by SanctusAnimus** [comment]
Ok opinion changed, make it as a scepter effect (spawning single static monkeys), and provide passive armor bonus

**Comment by Draze22** [comment]
Details:

- Attacks every 1.1 seconds.
- Passively provides 12/18/24 armor.
- Attacks are identical to the main hero's (same damage, same attack range, procs the same modifiers).
- Infinite duration but is removed when the hero enters the fountain and respawned (next to the hero) when the hero enters a creep or duel arena.
- Cannot be respawned while the main hero is invisible.

Active:

- 4s cooldown.
- 300 cast range (not affected by bonus cast range if possible).
- Moves the Soldier to the target location.
- 0 mana cost.
