### ISSUE TITLE
Rework Juxtapose to not cause massive lag, and re-add it to the game

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1254]
Can change the way it works. Here's a first draft:

```
Passively creates a 90/120/150% damage output, 200/150/100% incoming damage, illusion of your hero.

When killed, it returns after 4/3/2 seconds.

Juxtapose damage talent buffed from 5% to 40%.
```

Feel free to discuss

Opened from Discord by **Firetoad#5132**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/853030778941341736)

**Comment by Draze22** [comment]
Also the illusion should spawn at the start of a round (be it pvp or pve) and die when the round ends. - Firetoad
