### ISSUE TITLE
Check all issues, remove old ones and ones that we are never going to do. 

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#1255]
Check all issues, remove old ones and ones that we are never going to do.

**Comment by Draze22** [comment]
Checked Page 6 and the second half of Page 5 so far.

**Comment by Draze22** [comment]
Checked up to Issue 938.

**Comment by Draze22** [comment]
Checked up to (not including) Issue #1066.

**Comment by Draze22** [comment]
Checked up to (not including) Issue #1101.

**Comment by Draze22** [comment]
Checked every Issue, now all I need to do is test all the bugs that need multiple players to test.

**Comment by Draze22** [comment]
Done, except for a few issues that may or may not still be relevant. I can make a list of these issues if you want me to @darklordabc.
