### ISSUE TITLE
Dispersion sometimes stops working

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1261]
Several players have reported Dispersion not working part way through the game but there doesn't seem to be a clear reason why this is happening.

**Comment by lovro-m** [comment]
Which part of the dispersion because it has been rewritten. The passive damage reflect part or the shard part?

**Comment by Draze22** [comment]
> Which part of the dispersion because it has been rewritten. The passive damage reflect part or the shard part?

The reports don't specify but I'm pretty sure its the reflect part.

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **23** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.

**Comment by Draze22** [comment]
This could explain why it sometimes stops working.

![image](https://user-images.githubusercontent.com/63279022/125806862-65da19d8-ef99-4370-be5f-8c72a5e7e670.png)
