### ISSUE TITLE
Track charges can be refreshed by re-equipping Aghanim's Scepter

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1263]
1. Get Track and Aghanim's Scepter (not Blessing).
2. Use Track.
3. Move Aghs out of and back into your inventory.
4. You will have all of your Track charges restored.

![image](https://user-images.githubusercontent.com/63279022/121768841-c6c77400-cba3-11eb-897f-35bce5673bf3.png)

**Comment by SanctusAnimus** [comment]
Fixed
