### ISSUE TITLE
Magus doesn't proc things like Fiery Soul

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1269]
Not sure if we need to change this but it would be nice to decide if this is a bug or a feature.

**Comment by SanctusAnimus** [comment]
It shouldn't, imo. And i don't think we can change that easily

**Comment by Draze22** [comment]
> It shouldn't, imo. And i don't think we can change that easily

I'm inclined to agree.

**Comment by Snoresville** [comment]
skywrath can do two mystic flares at once with aghs, should he get two stacks for casting?

**Comment by Draze22** [comment]
> skywrath can do two mystic flares at once with aghs, should he get two stacks for casting?

Excellent comparison and in vanilla Dota he does not which gives us our answer (magus should not proc fiery soul).
