### ISSUE TITLE
Aghanim's prevention help incorrectly thinks Anchor Smash doesn't have a Shard upgrade

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1271]
![image](https://user-images.githubusercontent.com/63279022/122052149-b673fb00-ce28-11eb-8c94-d0e80295eaa7.png)

**Comment by lovro-m** [comment]
I'll check all the shard spells when I get home. Probably just missing "HasShardUpgrad" in the KV files.

**Comment by SanctusAnimus** [comment]
Well it's kinda right since we have custom anchor smash and it doesn't have scepter upgrade (despite description that was plainly copy-pasted)

**Comment by SanctusAnimus** [comment]
So i guess it's a bit more then just kv parameter
