### ISSUE TITLE
Change Side Gunner to be tied to Flak Cannon instead of Gyrocopter

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1272]
Not sure if it helps but Valve already did this in ability draft.

**Comment by lovro-m** [comment]
I finished the side gunner being hero specific and put it on flak cannon. Do we want to do the same with skywrath mage shard?

**Comment by Roshrach** [comment]
also, side gunner activates(or shoots) even if the hero is inside the chronosphere, please consider nerfing this

**Comment by asset-afv** [comment]
> also, side gunner activates(or shoots) even if the hero is inside the chronosphere, please consider nerfing this

Em, no? It is default dota interaction, and one of very few chrono "counters" (not even a counter really).
