### ISSUE TITLE
Add a more thorough description to the feedback form.

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1273]
We need the feedback form to explain 4 main things to players:
1. We can't respond to their feedback.
2. We can't see their game's replay.
3. It's usually too time consuming for us to find the end game stats for any match they refer to in their feedback.
4. If they want to have an actual conversion, send images and get responses with regards to their feedback they need to join the CHC discord.

This will also obviously need to be translated into Russian and Chinese.

**Comment by SanctusAnimus** [comment]
> We can't respond to their feedback.  
We do have plans on making responds, design job for respective panels is pending for more then a month already, can't do much without it

**Comment by SanctusAnimus** [comment]
> It's usually too time consuming for us to find the end game stats for any match they refer to in their feedback  

I can insert links to gathered match data in feedback embeds, but match data will only appear when at least one team was eliminated, and will get updated as more teams get eliminated (progressively) so idk how useful is that

**Comment by SanctusAnimus** [comment]
Where should that be? Fully visible text somewhere near the main text field? or as a tooltip from ( i ) hint?

**Comment by AustraliaIsMyCity** [comment]
this aged well

**Comment by AustraliaIsMyCity** [comment]
> Where should that be? Fully visible text somewhere near the main text field? or as a tooltip from ( i ) hint?

( i ) hint
