### ISSUE TITLE
Magician increases Blur's vanish radius

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1274]
This probably applies to 12v12 (and any other mode than uses magician).

![image](https://user-images.githubusercontent.com/63279022/122204023-fba83380-cee1-11eb-83ef-db250e6d4308.png)

**Comment by fcalife** [comment]
Fixed in https://github.com/arcadia-redux/custom_hero_clash/commit/f7120f3908d46b9a01a75b3f38fecc025a2c43ae
