### ISSUE TITLE
Creeps kept spawning in an eliminated player's arena

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1276]
Not only did creeps keep spawning in the dead players arena, everyone had to wait for overtime to finish every round because of it.

![image](https://user-images.githubusercontent.com/63279022/122356797-7c286c00-cf96-11eb-8b76-7cb3867a345c.png)

**Comment by SanctusAnimus** [comment]
Haven't seen any more reports of this, and no replication provided

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/123799450-96b1fc00-d92b-11eb-8099-9cde66ca6294.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.
