### ISSUE TITLE
suggestion: add a shiva's guard upgrade

### ISSUE THREAD

**Issue by Roshrach** [arcadia-redux/custom_hero_clash_issues#1279]
disable the movement speed slow amp(if there's any) and also the aura's amp and then add an upgrade. I think it would make sense since we have the luminance, a radiance upgrade. and shiva's guard the least used item in chc, i have seen atlease 3 players using shiva's guard (based on experience of course, i may be wrong)

**Comment by Draze22** [comment]
Shiva's Guard is a strong item, it doesn't need an upgrade.
