### ISSUE TITLE
Tempest Double Bulwark soldiers don't disappear when the Tempest Double dies

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1286]
![image](https://user-images.githubusercontent.com/63279022/122867730-4e17a300-d36d-11eb-857a-7d5dc9654687.png)

**Comment by lovro-m** [comment]
![bulwark_td](https://user-images.githubusercontent.com/63733825/122888165-df712000-d341-11eb-905b-d77689495c06.gif)
Am I missing something?

**Comment by SanctusAnimus** [comment]
Couldn't replicate
