### ISSUE TITLE
Big Game Hunter makes you deal double damage to Fortunius

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1287]
![image](https://user-images.githubusercontent.com/63279022/122875598-d1d68d00-d377-11eb-864f-75445f2306f3.png)

**Comment by Snoresville** [comment]
how did you even test this? it doesn't deal any more damage

**Comment by Snoresville** [comment]
probably need reproduction steps, in case i'm jumping the gun here

**Comment by Draze22** [comment]
> probably need reproduction steps, in case i'm jumping the gun here

Steps:
1. Take big game hunter.
2. Attack Fortunius.
3. You will kill him in 5 attacks.

**Comment by Snoresville** [comment]
https://cdn.discordapp.com/attachments/682631693172998165/856805366850519050/2021-06-22_17-27-34.mp4

**Comment by Snoresville** [comment]
production steps did not recreate the bug in ffa or duos

**Comment by Snoresville** [comment]
it has come to my attention that it has been fixed somehow 🥴
