### ISSUE TITLE
Guardian Helmet's description needs a full Chinese translation

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1288]
This is the current translation:

"DOTA_Tooltip_ability_item_guardian_helmet_Description"					"<h1>主动技能：大型修补</h1>恢复附近盟友%replenish_health_pct%%%的最大生命值与%replenish_mana_pct%%%的最大法力值，施放%status_resistance_buff%%%状态抗性增益，持续%buff_duration%秒。同时从施放者身上移除大部分负面效果。<br><br>被击晕时也可使用。<br><br>作用范围：%replenish_radius%<br>驱散类型：<span class=\"GameplayValues GameplayVariable\">Strong Dispel</span>\n<h1>Passive: Auto-Mend</h1>If your health is reduced below %aura_bonus_threshold%%% and <span class=\"GameplayValues GameplayVariable\">Greater Mend</span> is off cooldown, it is triggered automatically.\n<h1>Passive: Greater Guardian Aura</h1>Grants %aura_health_regen% health regeneration, %aura_armor% armor, and %aura_status_resistance%%% status resistance to nearby allies.<br><br>If an affected hero's health falls below %aura_bonus_threshold%%%, they receive an additional %aura_health_regen_bonus% health regeneration, %aura_armor_bonus% armor, and %aura_status_resistance_bonus%%% status resistance.<br><br>Radius: %aura_radius%"

**Comment by SanctusAnimus** [comment]
Fixed
