### ISSUE TITLE
Add a preview for the treasures

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1289]
![image](https://user-images.githubusercontent.com/63279022/123083252-3c182c00-d463-11eb-8fa9-7ea45f112334.png)

**Comment by SanctusAnimus** [comment]
We already have preview, magnifier icon

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/123084491-da879b80-d429-11eb-8640-26e2f38ba981.png)
![image](https://user-images.githubusercontent.com/43399078/123084519-e2dfd680-d429-11eb-9c5d-723cef164af9.png)
