### ISSUE TITLE
neutral-T5 mega-blink is multicasting (again?)

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1293]
(at least it was a day before THE event started)

resulting in multiples of animations, and only triggering all the effects at the end of the last one (~3 seconds for 4x  multicast),
such so duel-enemies can just casually walk out of the stun-AOE

![mega-blink multicasting](https://user-images.githubusercontent.com/59403389/123262856-a038ff80-d4f8-11eb-8bc9-f3544f4eef29.jpg)

**Comment by Draze22** [comment]
Fixed: https://github.com/arcadia-redux/custom_hero_clash/commit/8bbd4a3525dea378db66047268932abea6920460.
