### ISSUE TITLE
Torture pipe might reduce the duration of Dismember and Fiend's Grip on heroes

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1294]
![image](https://user-images.githubusercontent.com/63279022/123374637-c3cc7a80-d5ca-11eb-9ae9-b8678a42efb9.png)

**Comment by Osamabinfrank** [comment]
I think he was playing against people with high status resistance, i tried the bane ulti today and it worked like a charm.

**Comment by Snoresville** [comment]
The tooltip is kinda bugged (duration reads zero after equipping pipe for the first time), but the duration remains the same
