### ISSUE TITLE
Ice Blast can cause creeps to be at 0 health and not die

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1296]
![image](https://user-images.githubusercontent.com/63279022/123502644-4b7cbc80-d691-11eb-8ece-0ca5a6deef40.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/123506393-41fe4f00-d6a7-11eb-95d8-f87afe0cf350.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/123506668-cdc4ab00-d6a8-11eb-9325-b5b2510eb3cf.png)

**Comment by Draze22** [comment]
I've tested Ice Blast:

- killing a creep with just the initial damage.
- killing a creep with the tick damage triggering the shatter threshold.
- killing a creep with the initial damage triggering the shatter threshold.

None of these replacated this bug.

**Comment by asset-afv** [comment]
Can it be specific creep wave?

**Comment by Draze22** [comment]
> Can it be specific creep wave?

Might just be the spiderites I guess.

**Comment by Draze22** [comment]
> I've tested Ice Blast:
> 
> * killing a creep with just the initial damage.
> * the tick damage triggering the shatter threshold.
> * the initial damage triggering the shatter threshold.
> 
> None of these replacated this bug.

Tested these with spiderites and got the same results (normal deaths).

**Comment by Osamabinfrank** [comment]
> > I've tested Ice Blast:
> > 
> > * killing a creep with just the initial damage.
> > * the tick damage triggering the shatter threshold.
> > * the initial damage triggering the shatter threshold.
> > 
> > None of these replacated this bug.
> 
> Tested these with spiderites and got the same results (normal deaths).

Try testing them in duos, since creeps get a random buff each round

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/123746517-183a6780-d8f5-11eb-94f5-7e5213cf128a.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for 7 days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.

**Comment by Draze22** [comment]
This is definitely caused by Ice Blast. @Osamabinfrank may be right, it seems to be related to the upgrader totem.

![image](https://user-images.githubusercontent.com/63279022/129990675-6b0dfb23-69e6-4ed3-b24a-83f1ed3591f7.png)
![image](https://user-images.githubusercontent.com/63279022/129990689-a572730c-dd09-4fc8-a56d-29ed4cb8184f.png)

![image](https://user-images.githubusercontent.com/63279022/129991128-2ffd2d72-f7d7-4d8f-9e28-a0e803d4d3b3.png)
