### ISSUE TITLE
Players are sometimes able to kill each other before changing from an IO to the hero they picked

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1297]
Conversation in Discord starts here: https://discordapp.com/channels/694060511209324585/694440472273354762/858480619545821204

To summarise the conversation:

- One player experienced this two games in a row.
- Players would get very strange amounts of kill gold (anywhere from 1 gold to over 100).
- Another player commented that they also had this happen in a game they played.

**Comment by ZLOY5** [comment]
Seems introduced by me in https://github.com/arcadia-redux/custom_hero_clash/commit/8b8578b44911130e533509646bd48f9f22d146fb
Maybe fixed after https://github.com/arcadia-redux/custom_hero_clash/commit/d5d22c568b1685da9613586aed5cb7ce6d480735

**Comment by Osamabinfrank** [comment]
I played 4 games today
4 out of 4 had this early massacre
Gained extra 450 gold once

**Comment by lovro-m** [comment]
Can't we just give the starter heroes attack capability none?

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **8** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.

**Comment by Draze22** [comment]
This was fixed.
