### ISSUE TITLE
New way to cause the Tempest Double + Geminate Attack bug

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1298]
![image](https://user-images.githubusercontent.com/63279022/123541173-6f6dfa00-d786-11eb-8b25-2f65739f16b2.png)

**Comment by ZLOY5** [comment]
https://github.com/arcadia-redux/custom_hero_clash/commit/3e61691e61f6a6c742a7105d8ba9f9603f827468

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for 9 days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.

**Comment by SanctusAnimus** [comment]
I assume @ZLOY5 fixed that with commit above, reopen if reoccurs (**after update**)
