### ISSUE TITLE
suggestion: make change slarks lvl 25 talent tree to make it more useful

### ISSUE THREAD

**Issue by Roshrach** [arcadia-redux/custom_hero_clash_issues#1300]
I'm talking about the +65 essence shift duration. This probably needs to be changed since this talent tree is useless knowing the counter resets at the end of the round.

**Comment by Draze22** [comment]
> I'm talking about the +65 essence shift duration. This probably needs to be changed since this talent tree is useless knowing the counter resets at the end of the round.

It still affects how long you keep the essence shift stacks from duels for.
