### ISSUE TITLE
implement proper leaderboard (website)

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1301]
Opened from Discord by **non toxic egirl#1202**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/858794237655253002)

**Comment by ArcadiaReduxAutomation** [comment]
Assign <@231999894024486912>

Comment from Discord by **non toxic egirl#1202**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/858794280256798720)

**Comment by SanctusAnimus** [comment]
Implemented
