### ISSUE TITLE
Grand Librarian doesn't work on existing ability selections

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1305]

**Comment by Snoresville** [comment]
what?

**Comment by Snoresville** [comment]
are we really marking player negligence as bugs?

**Comment by Draze22** [comment]
> are we really marking player negligence as bugs?

You're forced to pick your innate (grand librarian) after you see your first ability selection. Makes no sense to have an innate that give you extra ability choices except you can't get the extra choices for at least one of your ability selections.

**Comment by Osamabinfrank** [comment]
Please don't, grand lib is already kinda broken, with the 100% chance to get 1 of ur default abilities and extra 4 spells, even though you don't get to use it on the first 2, those 2 should show if you need that innate or not and there are plenty of extremely broken and over power combos and the innate helps you get it, it more of a mid/end game innate

**Comment by Draze22** [comment]
> Please don't, grand lib is already kinda broken, with the 100% chance to get 1 of ur default abilities and extra 4 spells, even though you don't get to use it on the first 2, those 2 should show if you need that innate or not and there are plenty of extremely broken and over power combos and the innate helps you get it, it more of a mid/end game innate

According to the stats it's average round is a little below average compared to other innates, if this buff makes it too strong we can always reduce the number of extra choices.

**Comment by Osamabinfrank** [comment]
> > Please don't, grand lib is already kinda broken, with the 100% chance to get 1 of ur default abilities and extra 4 spells, even though you don't get to use it on the first 2, those 2 should show if you need that innate or not and there are plenty of extremely broken and over power combos and the innate helps you get it, it more of a mid/end game innate
> 
> According to the stats it's average round is a little below average compared to other innates, if this buff/fix makes it too strong we can always reduce the number of extra choices.

I mean it will almost always be like this its a last resort spell when u got nothing good or if you go for specific combo from the start. there are much better innates so it will be always a little below average or average statistically unless you make a buff too strong

**Comment by SanctusAnimus** [comment]
Way too problematic to implement
