### ISSUE TITLE
Heartstopper Aura doesn't trigger Big Game Hunter

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1306]
Not sure if we consider this a bug and fix it or a feature and leave it as is.

![image](https://user-images.githubusercontent.com/63279022/123747076-c7773e80-d8f5-11eb-916b-fdb670bc3053.png)

**Comment by SanctusAnimus** [comment]
Wasn't heartstopper a health reduction damage type? That one i believe is not influenced by any kind of increases and amplifiers

**Comment by SanctusAnimus** [comment]
Yeap, while tooltip says it's damage type is magical, in reality it's a hp removal and it doesn't invoke anything related to damage and amplification.
