### ISSUE TITLE
Serpent Wards aren't wards (can get bashed and affected by spells, etc)

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1307]
![image](https://user-images.githubusercontent.com/63279022/123799261-610d1300-d92b-11eb-8392-a7903732f0cc.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/123800646-daf1cc00-d92c-11eb-8de5-f593265a76ac.png)

**Comment by ZLOY5** [comment]
fixed
