### ISSUE TITLE
A player's daily quests got to 6/3 completed

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1308]
![image](https://user-images.githubusercontent.com/63279022/123799540-ad585300-d92b-11eb-9fa5-e548526f66e2.png)
![image](https://user-images.githubusercontent.com/63279022/123799555-b1847080-d92b-11eb-9bfc-67e7adfadaff.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.

**Comment by SanctusAnimus** [comment]
First and last time i've seen that, closing for now
