### ISSUE TITLE
Consider removing Craggy Exterior (Grow Aghs Shard)

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1310]
It's no longer in vanilla Dota but is quite a usefull affect that many players like.

**Comment by chariot-afv** [comment]
Did you mean "Consider keeping Craggy Exterior"? IMO it would be nice to keep it, one of few abilities that helps against chrono, and also helps against permabash in some cases.

**Comment by Draze22** [comment]
> Did you mean "Consider keeping Craggy Exterior"? IMO it would be nice to keep it, one of few abilities that helps against chrono, and also helps against permabash in some cases.

Actually the very fact that it counters perma-bash is enough for me to be strongly in favour of keeping it.
