### ISSUE TITLE
season end countdown is based on local time not UTC https://discord.com/channels/501306949434867713/682631693172998165/859800011993776138 https://cdn.discordapp.com/attachments/682631693172998165/859803904064618516/unknown.png

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1311]
Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/859804227915743242)

**Comment by AustraliaIsMyCity** [comment]
![image](https://user-images.githubusercontent.com/50186248/123980264-bd903100-da04-11eb-8587-713522c8b393.png)
![image](https://user-images.githubusercontent.com/50186248/123980286-c3861200-da04-11eb-9aa5-0bd9d054a075.png)

It's based on the time for your pc, not the server

**Comment by Draze22** [comment]
This was fixed here: https://github.com/arcadia-redux/custom_hero_clash/commit/1d33dc1db8491a4d416553ccd7e0d380670a5e40.
