### ISSUE TITLE
Dropping items in creep rounds reduces your networth for the compensation item calculations

### ISSUE THREAD

**Issue by izhastron** [arcadia-redux/custom_hero_clash_issues#1312]
You can get a gift for poverty if you place items in the battle arena, reducing your value. If the archive of the custom game does not match the version of the lobby leader and you enter the last one, then you get a ban, since the game starts and you are thrown out.

**Comment by Draze22** [comment]
> You can get a gift for poverty if you place items in the battle arena, reducing your value. If the archive of the custom game does not match the version of the lobby leader and you enter the last one, then you get a ban, since the game starts and you are thrown out.

I'll check out the first bug but the second one with getting banned is 100% in Valve's control.

**Comment by izhastron** [comment]
I meant getting things out not in duels, but when fighting monsters. The player lays out things during the battle with monsters, for example, at 8 or 9 rounds, after defeating the boss, he receives a gift. Then, in the 11th round, he picks up things

**Comment by Draze22** [comment]
> I meant getting things out not in duels, but when fighting monsters. The player lays out things during the battle with monsters, for example, at 8 or 9 rounds, after defeating the boss, he receives a gift. Then, in the 11th round, he picks up things

Pretty sure we fixed that.

**Comment by izhastron** [comment]
Sorry, maybe my information is out of date
