### ISSUE TITLE
Magus has no cooldown against creeps

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1313]
- I haven't yet tested this against heroes.
- The only thing that was changed about Magus last update (1st of July) was the proc chance from 20% to 25%.

**Comment by Snoresville** [comment]
lmao, this is proof that it seems like it's more than just the proc chance has been changed
the creep cooldown has been touched
![image](https://user-images.githubusercontent.com/19840964/124106260-334ada00-daa3-11eb-8dc9-b68c18e0a248.png)

**Comment by Snoresville** [comment]
Fixed in
https://github.com/arcadia-redux/custom_hero_clash/commit/0e9fef44c6b8ec594a2b693c54fef43c2e4de03f#diff-d00c64f01c905b21fab134340c9652767f5b56a7e70cfbcb23e14733800b6475
