### ISSUE TITLE
This match wasn't recorded properly

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1314]
Match: https://discordapp.com/channels/501306949434867713/682631693172998165/860023668306346014.

Match in Dota client:

https://cdn.discordapp.com/attachments/682631693172998165/860023764297318440/unknown.png

![image](https://user-images.githubusercontent.com/63279022/124069344-60859100-da7f-11eb-961c-cac862de1655.png)

![image](https://user-images.githubusercontent.com/63279022/124069412-772be800-da7f-11eb-9002-58bd17a9fc29.png)

**Comment by SanctusAnimus** [comment]
I'm aware of all these issues, don't make new ones for before/after match data submission

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.
