### ISSUE TITLE
Add the ability to choose spawn location in creep rounds

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1317]
Could make it available to everyone, cost fortune or glory to unlock or only be available to players with a Clash/Golden boost.

![image](https://user-images.githubusercontent.com/63279022/124259193-986d0100-db71-11eb-8bf7-a96112fdbf60.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/124259945-76c04980-db72-11eb-8662-d4448eb6a0f3.png)

**Comment by AustraliaIsMyCity** [comment]
i dont feel this is worth implementing
