### ISSUE TITLE
Bkb + False Promise during a duel makes the server crash

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1319]
![image](https://user-images.githubusercontent.com/63279022/124292712-3b854100-db99-11eb-8d42-bec165af01a0.png)
![image](https://user-images.githubusercontent.com/63279022/124292756-463fd600-db99-11eb-8d11-08fd85de17c5.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/124344838-39ae9280-dc18-11eb-8495-8a148091f163.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.

**Comment by Draze22** [comment]
Moved to issue #1334.
