### ISSUE TITLE
Rebalance Shackles' Aghs Shard

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1321]
Currently the Aghs Shard spawns a Serpent ward that does the equivalent damage of a level 3 Massive Serpent Ward, even when Shackles is at level 1. This is mainly an issue when players buy an Aghs Shard first item or pick the Aghanim's Blessing innate.

We have two main options for how to scale the damage:

1. Make the Serpent Ward damage scale based on the level of Shackles: 60/200/340/480 damage for level 1/2/3/4 Shackles instead of 480 at all levels.
2. Make the Serpent Ward damage scale based on the maximum level Serpent Ward would be if the player had it: 60/200/340/480 damage for a level 1-5/6-11/12-17/18+ hero.

**Comment by chariot-afv** [comment]
Second option. I was going to support first option initially, as it seemed less complicated and more native to dota (no hero level scalings), but then I realized that 480 damage wards at level 7 is just too strong. 
In regular dota shackles wards match power of ulti wards, meaning that you can achieve maximum damage at level 18 with level 3 ulti, which is reasonable, and option 2 emulates that.

**Comment by ZLOY5** [comment]
Can we just spawn level 1 by default, and everything else leave as it is now

**Comment by Draze22** [comment]
> Can we just spawn level 1 by default, and everything else leave as it is now

No, but I may not fully understand what you mean.

**Comment by SanctusAnimus** [comment]
Can @arcadia-redux/balance-team make a final decision of what to do here?

**Comment by ZLOY5** [comment]
> > Can we just spawn level 1 by default, and everything else leave as it is now
> 
> No, but I may not fully understand what you mean.

I mean if MSW not trained we spawn 1 level wards, otherwise by level of MSW

**Comment by Draze22** [comment]
Sure, that sounds reasonable and simpler than the solution I had.
