### ISSUE TITLE
Tempest Double was still getting attacked after dying AND being retrained

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1324]
https://youtu.be/SUH07cc8aOA?list=TLPQMDQwNzIwMjHe1kcLNMc4qw&t=5698.
![image](https://user-images.githubusercontent.com/63279022/124372663-4f32c380-dccf-11eb-8bdf-e909f8014dbf.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.
