### ISSUE TITLE
Duel breath 2x damage and range talent doesn't stack with Torture Tipe

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1325]
![image](https://user-images.githubusercontent.com/63279022/124383929-6515a800-dd12-11eb-81df-a41b9b8a6b57.png)

Also need to check if Torture Pipe affects Fire Spirits since someone reported it not working.

**Comment by Draze22** [comment]
This might just be because the talent incorrectly updates the tooltip.

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.
