### ISSUE TITLE
Liquid Frost stops working sometimes

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1327]
![image](https://user-images.githubusercontent.com/63279022/124565436-61eef900-de85-11eb-8bd4-1d0fae9f7387.png)

**Comment by Osamabinfrank** [comment]
Might have something to do with gaining a lot of spells, had it the over day and it worked perfectly fine till i got too many shard spells to the point where i had over 10 abilities, idk if what caused it to stop or the fact that it didn't have a pressable key as it was way in the end, i didn't bother checking it out at the time so you might want to look at it when you test it.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/125294958-15fdf180-e368-11eb-846a-7e80bbc964c1.png)

**Comment by Draze22** [comment]
> Might have something to do with gaining a lot of spells, had it the over day and it worked perfectly fine till i got too many shard spells to the point where i had over 10 abilities, idk if what caused it to stop or the fact that it didn't have a pressable key as it was way in the end, i didn't bother checking it out at the time so you might want to look at it when you test it.

Couldn't replicate this in demo mode.

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.
