### ISSUE TITLE
Spirit Bear bug

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1329]
Video proof of this bug: https://drive.google.com/file/d/1ljRXCgMdmz4nIPY1yUws7nMCBPxW4hC_/view?usp=sharing.

![image](https://user-images.githubusercontent.com/63279022/124634719-0004b280-deca-11eb-9a4b-11c8d937a776.png)

**Comment by Draze22** [comment]
Might be time to disable Spirit Bear from using Eye of Midas.

**Comment by lovro-m** [comment]
if darklord wants it to be fun we can disable it on spirit bear and leave it on tempest double

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.

**Comment by Draze22** [comment]
In my opinion we should just disable Spirit Bear from using Eye of Midas at all.

**Comment by AustraliaIsMyCity** [comment]
d i s a b l e    i t

**Comment by darklordabc** [comment]
I think a better fix would be to ensure the bears inherit and shares the cooldown of Midas, so the bear(s) can't do this bug.
