### ISSUE TITLE
Players managed to get two copies of the same ability on a hero in Duos

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1330]
![image](https://user-images.githubusercontent.com/63279022/124719534-98427c00-df4a-11eb-93c4-98db2083724e.png)
![image](https://user-images.githubusercontent.com/63279022/124719676-bd36ef00-df4a-11eb-94ae-548b5c562018.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.
