### ISSUE TITLE
Torture Pipe (1 and 2) may ignore spell block/reflect mechanics and spell immunity

### ISSUE THREAD

**Issue by Snoresville** [arcadia-redux/custom_hero_clash_issues#1331]

**Comment by Draze22** [comment]
Probably due to them being made the same way as Spirit Vessel which peirces linkens/lotus.

**Comment by Draze22** [comment]
Need to discuss if they should:
1. Ignore Linkens/Lotus (spell block/reflect).
2. Get dispelled by magic immunity being activated.
3. Be castable on magic immune targets.

**Comment by Draze22** [comment]
> 1. Ignore Linkens/Lotus (spell block/reflect).

Imo no.

> 2. Get dispelled by magic immunity being activated.

Imo yes.

> 3. Be castable on magic immune targets.

Definitely no.

**Comment by Snoresville** [comment]
> Probably due to them being made the same way as Spirit Vessel which peirces linkens/lotus.

it actually does, wow

**Comment by SanctusAnimus** [comment]
Made it to trigger lotus/linken, prevented from casting on magic-immune **enemies**. Was dispellable by pressing bkb already, so that's unchanged
