### ISSUE TITLE
Several abilities have the wrong icon in the ability selection UI

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1332]
This doesn't seem to be unique to any specific localization (language). Every ability has the correct icon once picked.

![image](https://user-images.githubusercontent.com/63279022/124864338-16ab2680-dffc-11eb-8256-8ab61fa99cbf.png)
![image](https://user-images.githubusercontent.com/63279022/124864355-1e6acb00-dffc-11eb-9820-f870c46129a7.png)
![image](https://user-images.githubusercontent.com/63279022/124864384-27f43300-dffc-11eb-9c09-df87460e51f5.png)

![image](https://user-images.githubusercontent.com/63279022/124864459-43f7d480-dffc-11eb-8c45-b5f1aa0980ef.png)

![image](https://user-images.githubusercontent.com/63279022/124864481-4fe39680-dffc-11eb-9a33-d6d2b0b4813a.png)

![image](https://user-images.githubusercontent.com/63279022/124864532-6c7fce80-dffc-11eb-9663-49912d421720.png)

![image](https://user-images.githubusercontent.com/63279022/124864620-9507c880-dffc-11eb-8b4b-32adc9a2eef1.png)

**Comment by chariot-afv** [comment]
1. Name is correct, icon is wrong
2. Misplaced icons seem to be consistent, Warlock's golems are always named "counterspell", in any localization.
3. Reports of this bug first appeared only recently (~12 hours ago), while last CHC patch was pushed around a week ago.

**Comment by chariot-afv** [comment]
- [ ] Counterspell
- [ ] Divine Sanction
- [ ] Bad Juju
- [ ] Arcane Supremacy (Rubick's passive)
- [ ] Ransack (Meepo's passive)
- [ ] Lucky Shot (Pango's passive)
- [ ] Divina favor (Chen's skill)
- [ ] Spirit link

**Comment by SanctusAnimus** [comment]
Fixed

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/125100579-9b8d6180-e11c-11eb-896c-39743156146e.png)
![image](https://user-images.githubusercontent.com/63279022/125100613-a6e08d00-e11c-11eb-82b2-b7c359125dd1.png)

**Comment by SanctusAnimus** [comment]
Fixed
