### ISSUE TITLE
Hero souls are too weak round 1 for players that are waiting to be given their hero

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1333]
![image](https://user-images.githubusercontent.com/63279022/125072601-2317a800-e0fe-11eb-9cd0-5f32b71c5e70.png)
![image](https://user-images.githubusercontent.com/63279022/125072661-30cd2d80-e0fe-11eb-8d45-9fce9abe2570.png)
![image](https://user-images.githubusercontent.com/63279022/125072743-4e9a9280-e0fe-11eb-84d5-3b90b790122a.png)

**Comment by Draze22** [comment]
If we can't improve the amount of time it takes to give every player their hero to under 15 seconds, I propose we give hero souls an active that gives them some more damage and health regen so that they can survive the first round without dying.

**Comment by ZLOY5** [comment]
Maybe give it back normal hero stats?
