### ISSUE TITLE
Potential server crash causes

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1334]
I'll be putting every potential crash cause here and testing them when I get the chance.

Things that actually can crash the server will have an individual issue opened and any issue conclusively tested will be hidden in this thread to reduce clutter.

- [ ] Chaotic Offering Golems being alive when a duel ends.
![image](https://user-images.githubusercontent.com/63279022/125118902-b3bcab00-e133-11eb-81e6-5731163cd109.png)
![image](https://user-images.githubusercontent.com/63279022/125235712-3d33cf00-e326-11eb-8af3-6b56d204b2cd.png)
![image](https://user-images.githubusercontent.com/63279022/126271610-41ef65de-6a26-49a2-92f1-733037eba134.png)

**Comment by chariot-afv** [comment]
- [ ] Metamorphosis + DK form + broodmother's insatiable hunger 
It either all of them combined, or some combination of two. Opponent had it last game in duos, server was severely lagging for everyone in match.

**Comment by Draze22** [comment]
- [ ] Bkb + False Promise during a duel.
![image](https://user-images.githubusercontent.com/63279022/125155513-cc64a980-e1a3-11eb-970c-654943b19fbd.png)
![image](https://user-images.githubusercontent.com/63279022/125155518-d2f32100-e1a3-11eb-9b8e-71b7f1bd4623.png)
![image](https://user-images.githubusercontent.com/63279022/125155520-d8506b80-e1a3-11eb-93f4-36e8320de1fa.png)

**Comment by dym-sh** [comment]
about 50+ of sharded Split Earth in the fountain (multicast+unstable+rearm) will overflow particle count for the entire server

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/125297081-447ccc00-e36a-11eb-9c5e-2a393d4dede4.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/125313381-84e34680-e378-11eb-8dd1-beac8232ae30.png)
"after applying walrus punch, the game crashed and the lobby floor crashed (+ several visual bugs)"
![image](https://user-images.githubusercontent.com/63279022/125313538-acd2aa00-e378-11eb-9752-d25a4e0a3082.png)
![image](https://user-images.githubusercontent.com/63279022/125313571-b2c88b00-e378-11eb-9c62-1abe8be563ba.png)
![image](https://user-images.githubusercontent.com/63279022/125313511-a5130580-e378-11eb-93f7-9662b7efd800.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/125384927-f6ed7700-e3dc-11eb-87c0-011c7a40eb97.png)
![image](https://user-images.githubusercontent.com/63279022/125384942-fce35800-e3dc-11eb-9d90-379c39624fd5.png)

**Comment by Draze22** [comment]
- [ ] Sunstrike/Cataclysm with Big Game Hunter.
![image](https://user-images.githubusercontent.com/63279022/126306088-753126b7-a9c9-414f-a4d7-9820eaa5952e.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/126383798-36d58240-2cce-48cb-89d2-95c54608efad.png)
![image](https://user-images.githubusercontent.com/63279022/126383897-e1895739-2cf8-4da5-9231-d9a455e97dfa.png)
![image](https://user-images.githubusercontent.com/63279022/126384211-fac875e5-a367-46c2-8f7c-9d2417ab1bcf.png)
![image](https://user-images.githubusercontent.com/63279022/126384159-a7040353-37c6-4826-8bd4-35846a19e451.png)

**Comment by Draze22** [comment]
- [ ] Wrath of Nature + Multicast.

![image](https://user-images.githubusercontent.com/63279022/127031385-0d86d811-6edf-48f2-a6f3-3bf1e3d9f8a5.png)
![image](https://user-images.githubusercontent.com/63279022/127031466-8458e4fd-0698-46b4-8f1f-d6955ffc2586.png)

**Comment by Draze22** [comment]
- [ ] Rocket Flare.

![image](https://user-images.githubusercontent.com/63279022/127133147-b367821d-4276-4a54-a8a8-67b2e225edff.png)
![image](https://user-images.githubusercontent.com/63279022/127133179-90d073bf-9bc8-4282-b5d7-ce7a003bab86.png)

**Comment by Draze22** [comment]
- [ ] Io (with tether attack talent) tethered to a hero that has Wukong's Command aghs.

![image](https://user-images.githubusercontent.com/63279022/127637996-209abe9c-af38-4d92-b204-bb18ab390432.png)
