### ISSUE TITLE
Switcheroo doesn't work on Juxtapose

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1335]
![image](https://user-images.githubusercontent.com/63279022/125161866-29725680-e1c8-11eb-8ac1-c44ef8210947.png)

**Comment by Draze22** [comment]
Still not fixed.

![image](https://user-images.githubusercontent.com/63279022/125916441-0e199e36-5135-47ab-9d6a-f17196900e87.png)

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/125924183-d9f1a158-7076-4bd8-bb1b-21dbd5587949.png)
???
