### ISSUE TITLE
Stength stolen decay, does not return after a duel

### ISSUE THREAD

**Issue by izhastron** [arcadia-redux/custom_hero_clash_issues#1336]
If the zombie steals a lot of stength and loses the duel, the player may lose aegis when defending against creeps

**Comment by SanctusAnimus** [comment]
So what do we do? Return stolen strength? @arcadia-redux/balance-team

**Comment by Draze22** [comment]
Since we didn't manage to make essence shift get removed after duels, we'll leave it as is for now.
