### ISSUE TITLE
Bear summoned by Tempest Double disappears

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1337]
started in the middle of the game (after losing a duel)

bear was still appearing during summon animation, but then just gone – during both creep and duel rounds

(iirc this is not a new bug, had same thing happen last year)

pictured: only one bear, Double's spell is still on cooldown after summoning in the previous round
![tempest bear gone](https://user-images.githubusercontent.com/59403389/125181221-031ddc80-e203-11eb-90ed-83db4f07c156.jpg)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.
