### ISSUE TITLE
bash-stacking should be ~~illegal~~ better balanced

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1338]
currently stacking Basher (the item) with any spell-based bash is against game-wide rules, but getting 3 different bash-spells is totally ok

**Comment by Snoresville** [comment]
build status resistance

**Comment by dym-sh** [comment]
solid advice haha do you have one agains double/tripple chrono?

**Comment by Snoresville** [comment]
yeah
blademail
