### ISSUE TITLE
Rework Static Field and Big Game Hunter

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1342]
- [x] Rework Static Field:
- Make every ability (not attacks) proc Static Field.
- Make Static Field proc a maximum of once per second on each unit. Also make Zeus's abilities ingore this rule completely (they aren't restricted by other abilities having procced Static field and don't restrict other abilities from proccing Static Field).

- [ ] Rework Big Game Hunter (needs discussion):
- Change it from 5% **current** health as damage to 2% **max** health as damage.
- Change it from affecting any unit damaged to only affecting the highest max health enemy. Visually indicate this with a target over that unit's head. (Selects a random enemy if all enemies have the same max health).

**Comment by fcalife** [comment]
what happens to big game hunter when all units have the same max health? does it work on all of them, or pick a random one?

**Comment by Draze22** [comment]
> what happens to big game hunter when all units have the same max health? does it work on all of them, or pick a random one?

Pick a random one or none of them makes the most sense to me.

**Comment by SanctusAnimus** [comment]
Static field is final and i can implement it already, right?

**Comment by Snoresville** [comment]
big game hunter without the cooldown? 5% to 2% is a massive nerf unless its cooldown can be thrown out

**Comment by Draze22** [comment]
> big game hunter without the cooldown? 5% to 2% is a massive nerf unless its cooldown can be thrown out

The cooldown will be kept, 2% max health is at least almost as strong as 5% current health in most situations and in other it's much stronger.

**Comment by fcalife** [comment]
removing its cooldown would make ion shell S tier and shackles SSSSSSS tier... which might be a good thing, not really sure.

I'd keep a very small cooldown at least (0.2s at least)

**Comment by SanctusAnimus** [comment]
How do you even plan on selecting highest max health enemies for spells like chain lightning, that don't deal damage instantly? Moreover, for any kind of event each damage instance is separate, there's simply no reliable way to get a group of damaged enemies and work with it without delays and other kinds of hacky workarounds

**Comment by fcalife** [comment]
you don't select on cast, the debuff is placed on the highest max health enemy when the round starts, and that enemyt is the only one affected by BGH

**Comment by fcalife** [comment]
also BGH works with any damage source (except itself), unlike static field

**Comment by Draze22** [comment]
> Static field is final and i can implement it already, right?

Yes, although I would like to intoduce both of these reworks to master at the same time.
