### ISSUE TITLE
Duel and Track charges can be refreshed by Refresher Orb and Overclocking

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1346]
This can lead to players stalling in rounds to wait for Refresher Orb or Overclocking to come off cooldown.

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/125195754-bfa58b80-e25f-11eb-9fee-f399e3809c82.png)

bruh

**Comment by Draze22** [comment]
Mistakes were made.
