### ISSUE TITLE
Duel (ability) doesn't give damage to your opponent if you lose the duel

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1347]
![image](https://user-images.githubusercontent.com/63279022/125202916-43d82d00-e2b9-11eb-9fe1-09e3daf2a1cc.png)

**Comment by SanctusAnimus** [comment]
Very strange, according to order filter, it doesn't even tries, maybe after-duel invulnerability interferes, hard to tell exactly

**Comment by AustraliaIsMyCity** [comment]
works when tested against heroes, doesnt work against creeps.

**Comment by Draze22** [comment]
Was fixed ages ago @AustraliaIsMyCity should probably claim this.
