### ISSUE TITLE
Wukong's Command crashes the game when levelled up

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1348]
![570_20210712011020_1_1080p](https://user-images.githubusercontent.com/59403389/125217137-438f6000-e2c0-11eb-8561-858bf0a12a7f.jpg)

![570_20210712011444_1_1080p](https://user-images.githubusercontent.com/59403389/125217143-45f1ba00-e2c0-11eb-9809-94f8e3d4e091.jpg)

**Comment by SanctusAnimus** [comment]
So what exactly you do, just pick it up?

**Comment by Draze22** [comment]
> So what exactly you do, just pick it up?

Crashes the game when cast.

**Comment by SanctusAnimus** [comment]
nope, crashes when leveled up, even to level 1, tested myself, and only happens on dedicated servers
