### ISSUE TITLE
Duel and Track don't work as intended with Magus

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1349]
Currently what happens is:

- If Track and Duel have at least 1 charge left they can be procced by Magus without a charge being used.
- If Track and Duel have 0 charges left they cannot be procced by Magus.

First alternative:

- If they have at least 1 charge left they can be procced by Magus but it uses a charge.
- If they have 0 charges they cannot be procced by Magus.

Second alternative:

- Magus cannot proc Duel or Track.

The current interaction between Duel/Track and Magus allows dueling/tracking most creeps in every round which is very strong. The first alternative is the most intuitive interaction between Magus and Duel/Track but can cause the player to Track the same creep multiple times accidentally or waste their only Duel charge on a full health creep that won't die in the duration of a duel. The second alternative is a little less intuitive than the first but without the downsides.

**Comment by Osamabinfrank** [comment]
Are you sure it need to be fixed? Swift arcane + refresher allows you to track 9 creeps, unstable too iirc
Magus makes you unable to chose different unit target spells when you have track

**Comment by SanctusAnimus** [comment]
Refresher doesn't work on track or duel, so does swift arcana since last patch
