### ISSUE TITLE
Fix a few issues with Mail/Announcements

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1353]
- [x] The Announcements are always unread at the start of each game.
![image](https://user-images.githubusercontent.com/63279022/125385402-c4904980-e3dd-11eb-8e95-ce77b7384f7a.png)

- [x] The Mail tab is always unread (if the user has no mail).
![image](https://user-images.githubusercontent.com/63279022/125385451-db36a080-e3dd-11eb-8772-35eefc7a2294.png)

**Comment by Sheodar** [comment]
Fixed
