### ISSUE TITLE
Reimplement gravekeeper cloak

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1354]
If we do introduce it we could also make it work against creeps by allowing damage from creeps to be reduced by it and also remove a stack the same way as heroes.

**Comment by SanctusAnimus** [comment]
It was removed cause it crashed upon retraining

**Comment by Draze22** [comment]
Should we add it to #391?

**Comment by SanctusAnimus** [comment]
I guess
