### ISSUE TITLE
Return Chakram procs Arcane Bolt's Shard 

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1355]
It can easily be spammed to gain hundreds of stacks between rounds so this should obviously be changed in some way.

![image](https://user-images.githubusercontent.com/63279022/125570266-70796856-d642-4c72-a83a-c3b565dfa04c.png)

**Comment by Draze22** [comment]
The main issue is being able to spam it while Chakram is traveling back to the player after a round. If we want to nerf the combo rather than completely remove it we could simply disable Chakram and Return Chakram from being used in the fountain.

**Comment by lovro-m** [comment]
Maybe add arcane bolt shard exceptions instead, this is why we rewrote the spell.

**Comment by Draze22** [comment]
> Maybe add arcane bolt shard exceptions instead, this is why we rewrote the modifier.

Yes, thats the obvious solution to disable the combo completely.
