### ISSUE TITLE
Aghanim's prevention assistance doesn't think Shackles has an Aghs Scepter upgrade

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1357]
![image](https://user-images.githubusercontent.com/63279022/125614830-41a01bf1-d42e-49b8-a184-aba03c8559f6.png)

**Comment by ZLOY5** [comment]
Weird, today i have no messages in tools mode when bought shard with Shackles only, maybe prevention feature just disabled in tools for me

**Comment by Draze22** [comment]
> Weird, today i have no messages in tools mode when bought shard with Shackles only, maybe prevention feature just disabled in tools for me

Scpeter not Shard.

**Comment by lovro-m** [comment]
Prevention is disabled in tools mode. The spell doesn't have a scepter upgrade, but the modifier for the serpent wards does so that's why.
