### ISSUE TITLE
Second Chakram doesn't auto-level to level 2

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1359]
It auto-levels to level 1 when aghs is bought (as it should). It auto-levels to level 3 when Chakram is leveled to level 3. But it does not auto-level to level 2 when Chakram is leveled to level 2.

**Comment by SanctusAnimus** [comment]
Currently it uses "LinkedAbility" kv property, which worked fine before. 
I'll fix it, but i blame gaben
