### ISSUE TITLE
late-game creeps were aggroed by an undefined entity

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1361]
possibly swapped and/or retrained Wukong's Command aghs' soldier?

![570_20210715080045_1_1080p](https://user-images.githubusercontent.com/59403389/125843412-ef198d06-505b-4490-b032-ebd645ec6dea.jpg)

**Comment by SanctusAnimus** [comment]
Definitely not an mk clone

**Comment by SanctusAnimus** [comment]
Maybe tempest double

**Comment by dym-sh** [comment]
our team had no tempest double through out the game tho?

**Comment by Draze22** [comment]
Seems similar to issue #1324.
