### ISSUE TITLE
Lobby Bots

### ISSUE THREAD

**Issue by fekalegi** [arcadia-redux/custom_hero_clash_issues#1362]
cant get in a "Normal" Lobby, it always has those bots with the lobby not limited to 10 in FFA , its limited to 600+

**Comment by Draze22** [comment]
Join a lobby that has the correct number of max players using the lobby list TAB.

**Comment by fekalegi** [comment]
well its just took so much time to get full 10 players in the lobby from that

**Comment by SanctusAnimus** [comment]
So? We can't do anything outside of game itself, lobby system belongs to Valve:tm: and they don't give a damn about bots and other issues of custom games
