### ISSUE TITLE
Fix selling allies retraining books by discarding them

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#1366]
1. Check item owner on cast
2. On discard, create item with `CreateItem()` and set owner to be the same as saved before
3. Put item in hero inventory using `CDOTA_BaseNPC:AddItem()`

**Comment by Draze22** [comment]
We could also take this opportunity to fix discarding allowing players to sell retraining books for full cost.
