### ISSUE TITLE
Allow Legion Commander's Duel to be refreshed only during Duels

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1368]
The reason we disabled Duel (LC) being un-refreshable was to prevent stalling and all skills and items get refreshed at the end of a Duel anyway.

**Comment by SanctusAnimus** [comment]
So is it for LC Duel exclusively, or for all round-based charge abilities (i.e. should Track also able to refresh on duels)?

**Comment by Draze22** [comment]
> So is it for LC Duel exclusively, or for all round-based charge abilities (i.e. should Track also able to refresh on duels)?

All round based charge abilities.
