### ISSUE TITLE
Static Field doesn't work properly 

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1373]
The Aghs Shard effect is affected by spell amp.

Every other ability doesn't proc Static Field.

**Comment by SanctusAnimus** [comment]
Is rewrite even uploaded?

**Comment by Draze22** [comment]
> Is rewrite even uploaded?

Yes, otherwise Static Field would at least affect Zeus's abilities which it currently doesn't.

**Comment by SanctusAnimus** [comment]
it should be fixed now, waiting for upload
