### ISSUE TITLE
Rating of unbalanced duos and underperforming rates

### ISSUE THREAD

**Issue by izhastron** [arcadia-redux/custom_hero_clash_issues#1375]
1) If a player plays with a teammate short left the game and won in duos mode, the player who left the game is given + pts. I think that this is not fair and it is necessary to deduct the amount he won.
2) In duos mode, when 3 teams remain, it is necessary to remove bets, since they cannot be lost. One player on the team bets on the right, the other on the left. Or you can only allow one bet per team.
3) It is necessary to prohibit taking two gamblers in the same team, because they can play against each other with an increased coefficient

**Comment by Draze22** [comment]
> 1. If a player plays with a teammate short left the game and won in duos mode, the player who left the game is given + pts. I think that this is not fair and it is necessary to deduct the amount he won.

Agreed.

> 2. In duos mode, when 3 teams remain, it is necessary to remove bets, since they cannot be lost. One player on the team bets on the right, the other on the left. Or you can only allow one bet per team.

Only allowing 1 bet per team seems better than removing bets completely but I'm not convinced we need to change it.

> 3. It is necessary to prohibit taking two gamblers in the same team, because they can play against each other with an increased coefficient

I haven't seen this in action yet but it sounds more like a cool strategy than something that needs removing.

**Comment by izhastron** [comment]
2) In the current situation, there is no excitement. And it turns out that the team that makes bets by betting, for example, 200, gets the same amount as the winner of the duel. It turns out there is no way to change the game with the help of bets, only skills are decisive

**Comment by Draze22** [comment]
Move to Issue #1430.
