### ISSUE TITLE
Show Fortune on Hud, like Gold

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1377]
Put more emphasis on it as a currency, it doesnt have to be as prominent as gold, but should always be visible and clicking it you can buy more

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/867920201230987284)

**Comment by darklordabc** [comment]
https://discord.com/channels/501306949434867713/684952282076282882/870092098001575956

**Comment by Sheodar** [comment]
Added (PR 884)
