### ISSUE TITLE
Static Field is affected by spell amp

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1378]
At least all spells proc it now though.

**Comment by SanctusAnimus** [comment]
Already fixed

**Comment by SanctusAnimus** [comment]
Well, should have been in latest patch

**Comment by Draze22** [comment]
> Well, should have been in latest patch

Well it wasn't, I just tested it.

**Comment by SanctusAnimus** [comment]
how foolish of me to expect gaben stuff to work out huh
