### ISSUE TITLE
Mirror Shield and potentially Linken's Sphere don't interact correctly with Blitz Strike

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1381]
![image](https://user-images.githubusercontent.com/63279022/126773285-e7623bf2-bb1e-49d1-9bfc-4cb2bb9dd90a.png)

**Comment by SanctusAnimus** [comment]
blitz strike doesn't deal damage on it's own, just increases outgoing damage of hero owning it, it can't do anything to how linken/mirror interact
