### ISSUE TITLE
Auto-confirmation for duel-bets randomly resets to off in the middle of the game

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1383]
happened in 3 games yesterday

no idea what caused it, screenshots would not really help here either

**Comment by Draze22** [comment]
So you're saying the setting automatically turns it self off at random points in the game and you have to turn it back on?

**Comment by dym-sh** [comment]
yes, no idea why i can happen either, since i dont even open the settings panel until i notice there is no icon of my hero on the bets panel

**Comment by dym-sh** [comment]
this kept ever since happening including today, one time i checked right at the start and it was off (was absolutely on during the prev game)

solo only, from my observations

also it feels like everyone within the server has auto-bet reset at the same, since when it happens – suspiciously little bets are placed at the following duel, however big the "sure win" would it be to bet on

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.

**Comment by dym-sh** [comment]
here's a screenshot, i guess, happened today in duos, after winning the duel

![auto-bet unchecked itself](https://user-images.githubusercontent.com/59403389/129107922-827cf68c-e313-44e1-9981-7d7e15521ccd.jpg)

no other setting changed itself, _ever_

**Comment by ZLOY5** [comment]
Sure you clicking button on duel panel itself
There is no other possibilities to do this

**Comment by dym-sh** [comment]
why is it there in the first place?

**Comment by ZLOY5** [comment]
To see and control auto confirmation option

**Comment by dym-sh** [comment]
like it does not look like a toggle, and it does not opens the settings dialog to confirm???

**Comment by ZLOY5** [comment]
If you have proposal how to do it better UX-wise please discribe

**Comment by dym-sh** [comment]
simply changing label to `Bet Auto-Confirmation: On (Off)`, and opening the settings window on click would probably solve the problem of accidents

coz like, 1px glow-shadow on a label is not enough of an indication for a toggle state even on 1080p screens, let alone 4K and up
