### ISSUE TITLE
Dangerous combination

### ISSUE THREAD

**Issue by Uberosh325** [arcadia-redux/custom_hero_clash_issues#1384]
I can't understand what gone wrong but, if i use:
Paid Perk on bonus damage 100/150/200% damage for spell or attack with 25% chance or so, Static Field (Zeus), Sticky Napalm (Batrider), Bloodrage (Bloodseeker), Firestorm (Pitlord). This eventually led to server crash. Probably only first there responsible for this.

**Comment by Draze22** [comment]
This was caused by Sticky Napalm + Static Field and has now been fixed.
