### ISSUE TITLE
Nerf Static Field

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1387]
Too early to tell for sure but so far it's the best ability in both FFA and DUOS.

There's two main ways we can nerf it:

1. Make it less effective when procced by non-Zeus abilities (50%).
2. Increase the time between procs from non-Zeus abilities (2-5s).
3. Or we could even do both.

**Comment by SanctusAnimus** [comment]
So which of it? or do you still need input from other members of @arcadia-redux/balance-team ?

**Comment by chariot-afv** [comment]
First option, to keep advantage of low cd skills. Let's nerf further only if it overperforms with -50% dmg.

**Comment by Draze22** [comment]
> So which of it? or do you still need input from other members of @arcadia-redux/balance-team ?

Waiting for AIMC.

**Comment by AustraliaIsMyCity** [comment]
ive seen reports of it having no cooldown between procs

**Comment by AustraliaIsMyCity** [comment]
as for nerfs, id say dropping it to 25% on non zeus abilities and giving it a cooldown of 1 second should be fine enough

**Comment by SanctusAnimus** [comment]
It does have a cooldown

**Comment by AustraliaIsMyCity** [comment]
Oh yeah also have we fixed the infinite damage loop between it and sticky napalm?

**Comment by SanctusAnimus** [comment]
Fixed 2 days ago

**Comment by AustraliaIsMyCity** [comment]
Ok cool, 25% damage for non zeus spells and thatll be that
