### ISSUE TITLE
Magus can proc Death Pact

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1392]

**Comment by SanctusAnimus** [comment]
It declines procing Devour cause it's a Toggle ability, should Death Pact be disabled manually from procing too?

**Comment by Draze22** [comment]
> It declines procing Devour cause it's a Toggle ability, should Death Pact be disabled manually from procing too?

I don't think it's necessary but it does get reported as a bug or unbalanced every so often. @AustraliaIsMyCity what do you think?

**Comment by ZLOY5** [comment]
Why autocasts disabled for magus?

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/126976017-684e7f4d-8cd3-432e-a84f-b512fddb6abf.png)
idk lol

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/126976066-7b2cdf1c-721c-495b-8253-9c7c5c60a3fc.png)
and the funnies thing is that it was disabled by you @ZLOY5

**Comment by ZLOY5** [comment]
Ah yes xD, they do nothing for most abilities iirc
