### ISSUE TITLE
Selecting Doom as your first ability will disconnect you and not give you Doom

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1396]
Not reproducable in demo mode.

![image](https://user-images.githubusercontent.com/63279022/127267312-da8c1722-132d-4074-9336-0b953a2a923c.png)

**Comment by ZLOY5** [comment]
I did not quite understand. He chose ability and it appeared in the hero only after reconnect?

**Comment by SanctusAnimus** [comment]
Feels like a client bug, he should check ingame files integrity. Couldn't reproduce both in demo and in live game
