### ISSUE TITLE
Duel can't be used some rounds

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1398]
![image](https://user-images.githubusercontent.com/63279022/127318187-ccc3dd9f-6f41-4220-a53f-aad28f903465.png)

**Comment by Draze22** [comment]
Not sure if this is the same bug or a different one.

![image](https://user-images.githubusercontent.com/63279022/127453993-bae5ce49-92e1-4299-96e1-724772a221bd.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.

**Comment by SanctusAnimus** [comment]
Haven't seen reports of that anymore, and no details about it, thus closing. 
Also @Draze22 why are you removing bot labels? He orients using them, if you don't have new details about bug, don't remove them or just close yourself
