### ISSUE TITLE
How to get 2 Spirit Bears

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1400]
![image](https://user-images.githubusercontent.com/63279022/127454740-6d55de47-a6aa-474c-ad37-25d1bb6a09d5.png)

**Comment by ZLOY5** [comment]
Already fixed in https://github.com/arcadia-redux/custom_hero_clash/commit/e3952fcb7bb3f5f7e00ea6a651a83612debedb91
