### ISSUE TITLE
Ice Blast can kill players in the fountain

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1401]
![image](https://user-images.githubusercontent.com/63279022/127474535-f95341aa-ef52-449e-867c-82be0aa7767a.png)

**Comment by Snoresville** [comment]
so what happened with the status resistance? why was it removed?

**Comment by Draze22** [comment]
> so what happened with the status resistance? why was it removed?

So people can easily check how much status resistance they have while in the fountain.

**Comment by Snoresville** [comment]
wow.

**Comment by fcalife** [comment]
maybe don't remove important things just for the sake of less important things

**Comment by ZLOY5** [comment]
We can add IsServer check so status resistance persists and player can see real value in UI
