### ISSUE TITLE
Culling Blade doesn't pierce Shallow Grave

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1402]

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.
