### ISSUE TITLE
Blitz Strike is very broken

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1406]
- [ ] The damage dealt is higher than a 350% crit (seems closer to 450%).
- [ ] Once the unit is below 90% hp damage dealt is doubled instead of normal.

**Comment by Snoresville** [comment]
First check box is wrong. It is indeed doing a 350% crit

**Comment by SanctusAnimus** [comment]
> First check box is wrong. It is indeed doing a 350% crit  
no it wasn't lmao

**Comment by SanctusAnimus** [comment]
until fix crit popup was showing right amount of damage, but damage multiplier was higher by 100% and those 100% worked even on <90% health because yes

**Comment by Snoresville** [comment]
![image](https://user-images.githubusercontent.com/19840964/127642383-0c7487db-a8b7-495a-928d-30afed0869e7.png)
175 is about 350% of 50

**Comment by SanctusAnimus** [comment]
are you even reading what i'm writing?
> crit popup was showing right amount of damage, but damage multiplier was higher

**Comment by Snoresville** [comment]
no because i was on my own fix and actually trying to fix it

**Comment by SanctusAnimus** [comment]
Crit popup in case of blitz strike is just call to `SendOverheadEventMessage`, not crit property. Turns out 3.5 multiplier and 350% total damage increase aren't same thing lmao
