### ISSUE TITLE
add double click protection for rerolling

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1409]
after clicking the reroll button, make it greyed out for 1 second and make clicking it do nothing + show a notification saying its prevented an accidental double click

Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/802155090608783371/870904400841940993)

**Comment by Draze22** [comment]
Which reroll button did we do this for, rerolling heroes or abilities/innates?

**Comment by SanctusAnimus** [comment]
abilities/innates, heroes iirc already had that?

**Comment by Osamabinfrank** [comment]
Please if you add such feature make the ability to turn it off like the shard tool tip
Adding this without the feature to turn it off will decrease the amount of books you can use in the pre duel time of 15 sec

**Comment by SanctusAnimus** [comment]
wdym how does it reduces anything? you only have 2 rerolls

**Comment by Osamabinfrank** [comment]
> wdym how does it reduces anything? you only have 2 rerolls

I thought she meant the use of the book to reroll an ability not the reroll button itself
Sorry
