### ISSUE TITLE
delete tiny bot

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1410]
pls ive lost so many hours to that boi taking 6 million years to attack

Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/870911079163777054)

**Comment by SanctusAnimus** [comment]
since bots now has ai, this is pretty much irrelevant
