### ISSUE TITLE
blitz strike works on yourself

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1411]
should be disabled for allied heroes

Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/802155090608783371/870915784078143528)

**Comment by SanctusAnimus** [comment]
eh but it's so funny, especially with life break

**Comment by ArcadiaReduxAutomation** [comment]
*with the exception of heroes affected by winter wyvern ultimate

Comment from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/802155090608783371/870915897005588550)
