### ISSUE TITLE
Player couldn't equip a second Mastery

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1413]
![image](https://user-images.githubusercontent.com/63279022/127780369-0c55d60f-f4d2-49a6-a373-d45fd91c9bca.png)
![image](https://user-images.githubusercontent.com/63279022/127780372-4cdf335e-d41f-405e-96a8-7bdfa37aba12.png)

**Comment by ZLOY5** [comment]
Looks like player picked mastery, but somehow UI don't show it

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.
