### ISSUE TITLE
Duel Aghs should keep its cooldown at 0s instead of lowering it to -20s

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1416]
Mostly an issue of players being confused by it having a negative cooldown rather than having an impact on gameplay.

**Comment by SanctusAnimus** [comment]
Duel already has 0s cooldown though?

**Comment by Draze22** [comment]
> Duel already has 0s cooldown though?

As in currently aghs lowers the cooldown to -20s.

**Comment by SanctusAnimus** [comment]
Lmao guess what, cd reduction with scepter is not in kv. It's literally hardcoded, in localization too
`Increases Duel duration, and makes Legion Commander and her opponent only take 50% damage from other sources. Reduces cooldown by 20 seconds.`

**Comment by Draze22** [comment]
We could instead increase the cooldown of Duel to 20s, that way Aghs reduces it to 0s.

**Comment by SanctusAnimus** [comment]
i guess
