### ISSUE TITLE
Implement new daily fortune logic

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1417]
Players will now be able to collect 1x free fortune per day by simply opening the store and clicking a button (see UI-related issue).

This should happen INSTEAD of the current bonus, which is granted after finishing a game in the top 50% placements.

To reiterate: we *remove* the current bonus, and *add* the new one. This should not increase the amount of free daily fortune given, and has nothing to do with Fortunius.

Opened from Discord by **Firetoad#5132**
Follow the conversation [here](https://discord.com/channels/501306949434867713/684952282076282882/872437428168818688)

**Comment by SanctusAnimus** [comment]
Implemented
