### ISSUE TITLE
Proximity Mines placed after round ends are stackable

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1422]
![image](https://user-images.githubusercontent.com/63279022/128588860-c20aa549-ec28-486c-a13c-a9b868cbe753.png)

https://youtu.be/JTnfwn3TJck.

**Comment by Draze22** [comment]
We could even make this a feature all the time to buff mines.

**Comment by lovro-m** [comment]
if we want to, can't we just fix this by teleporting the tempest double to base, instead of it staying in the arena?

**Comment by Draze22** [comment]
> if we want to, can't we just fix this by teleporting the tempest double to base, instead of it staying in the arena?

Yes.

**Comment by Draze22** [comment]
But that may introduce new bugs so be careful.

**Comment by ZLOY5** [comment]
Maybe just kill it after wave cleared?

**Comment by Draze22** [comment]
It can live for up to 38s so that would potentially kill it too quickly.

**Comment by Draze22** [comment]
I'm going to leave this as a feature for now.
