### ISSUE TITLE
Player ended up underneath the map

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1425]
Note the minimap.

![image](https://user-images.githubusercontent.com/63279022/128629948-bbf5420e-32d0-409e-a5ac-0ea2edc1516f.png)
![image](https://user-images.githubusercontent.com/63279022/128629967-e2dcee2e-11e7-4191-8875-0509dfacd861.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.
