### ISSUE TITLE
Soul Link full heals Mass Serpent Ward

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1426]
![image](https://user-images.githubusercontent.com/63279022/128630114-dffdf12b-7f55-4d0b-b8f6-6dc4ba6929ba.png)

**Comment by Draze22** [comment]
I can't think of a good solution to this other than completely disabling Soul Link healing MSW.

**Comment by ZLOY5** [comment]
We can fully disable MSW healing

**Comment by lovro-m** [comment]
Can we make each hit heal the wards by 2 or 3 hp?

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/132021615-8f62e4d7-45da-4d9f-bba1-3cecafad12c5.png)
![image](https://user-images.githubusercontent.com/43399078/132021965-0f07a5a8-c21f-4a18-a1b1-acfac95e2c79.png)

so how's that supposed to work?

**Comment by Snoresville** [comment]
i think this is about the soul link innate

**Comment by SanctusAnimus** [comment]
oh kek
