### ISSUE TITLE
Make Abandoned Duos players lose rating based on when they leave the game

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1430]
In other words if a player Abandons before any team gets eliminated they should be considered as coming 6th no matter what place their team ends up finishing in. This shouldn't affect the amount of mmr any other player in the game gets compared to the current system.

**Comment by SanctusAnimus** [comment]
We are sending after-match for a team when it gets eliminated, exactly at that moment

**Comment by SanctusAnimus** [comment]
Or what's this issue is about?

**Comment by SanctusAnimus** [comment]
If i understood you properly, you propose to record their place at the moment they were when abandoned? So i can just reach top 1 on round 5 and insta-leave to get rewards as a top 1 player? that doesn't sound sane

**Comment by ZLOY5** [comment]
> If i understood you properly, you propose to record their place at the moment they were when abandoned? So i can just reach top 1 on round 5 and insta-leave to get rewards as a top 1 player? that doesn't sound sane
No, in that case abandoned player loses mmr like he's in sixth place, but his teammate stay in game and can get 1st place.

**Comment by Draze22** [comment]
> If i understood you properly, you propose to record their place at the moment they were when abandoned? So i can just reach top 1 on round 5 and insta-leave to get rewards as a top 1 player? that doesn't sound sane

More like count them as having been eliminated when they abandoned.

**Comment by SanctusAnimus** [comment]
Currently entire game and backend are counting everything for teams. I don't see this worthy to rewrite and alter existing codebase this much. Mmr doesn't mean much here anyway, there's no weak buff like in 12v12 or whatever
