### ISSUE TITLE
change log has dashes and bullets

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1434]
![image](https://cdn.discordapp.com/attachments/684952282076282882/874598924453838848/unknown.png)

Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/684952282076282882/874598924688687174)

**Comment by Draze22** [comment]
Simplest solution is to remove the dashes.
