### ISSUE TITLE
Add sounds to enfos

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1436]
Need a lot of global sounds to indicate events:
- round start countdown
- pvp start countdown (different for 1v1 and 5v5)
- team lost a life (different when lives are very low)
- enemy lost a life
- tense stinger when team creep count is too high (needs cooldown)
- team purchased demon upgrade
- enemy purchased demon upgrade
- team wizard cast a spell (if the spell has no global sound)
- enemy wizard cast a spell (if the spell has no global sound)

Opened from Discord by **Firetoad#5132**
Follow the conversation [here](https://discord.com/channels/501306949434867713/870345695331221574/874900180057620520)

**Comment by ArcadiaReduxAutomation** [comment]
$assign Firetoad

Comment from Discord by **Firetoad#5132**
Follow the conversation [here](https://discord.com/channels/501306949434867713/870345695331221574/874900296168534047)

**Comment by Draze22** [comment]
Pretty sure this was finished but never closed
