### ISSUE TITLE
Can we fix buffs being displayed backwards for the flipped UI?

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1438]
![image](https://user-images.githubusercontent.com/63279022/129108783-fc70be33-d282-403b-87c9-07bb421cf8bc.png)

**Comment by SanctusAnimus** [comment]
Since it's a valve hud, most likely it won't be changable easily, it would mean we'll need to set scale for each modifier panel every frame
