### ISSUE TITLE
Creep Ai stopped working

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1442]
![image](https://user-images.githubusercontent.com/63279022/129443985-8be749f3-7014-40bb-880e-82beb42358d2.png)

**Comment by Osamabinfrank** [comment]
That can happen if dazzle went into ghost scepter and ran away from the agro range and his teammate attacked them while dazzle stayed away without dealing any dmg. , happened to me a couple of times. Might be wrong as i never tried to reproduce it. But i saw the pattern. My teammates rarely ever die and i rarely ever play duo.

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.
