### ISSUE TITLE
Add 3 new creep rounds

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1444]
Just to freshen things up

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/876114581410435114)

**Comment by fcalife** [comment]
Any ideas?

**Comment by Osamabinfrank** [comment]
> Any ideas?

How about bringing back attack of the ancients? It was removed over a year ago and i doubt anyone even remember it. It was a challenging mini boss fitting well after 30/40 rounds

**Comment by fcalife** [comment]
> > Any ideas?
> 
> How about bringing back attack of the ancients? It was removed over a year ago and i doubt anyone even remember it. It was a challenging mini boss fitting well after 30/40 rounds

The reasons they were removed still stand, though, it was a very chaotic fight where it felt like they were just throwing everything and the kitchen sink at you with no rhyme or reason.

**Comment by fcalife** [comment]
Idea 1: attack of the 50ft tall jellyfish

2-3 large enemies with this model:
![4dWKX0y3Q4](https://user-images.githubusercontent.com/7921728/130307599-d67d436c-dd85-4c35-99e1-b18ec19d0eb9.gif)

~150-200 health, 6-8 damage

They have long range, and attack with rays of electricity (similar to thunderbirds).

Normally they do nothing special, but if you lure them close to each other (~200-250 radius - their initial positions are farther away than this) to aoe them down, they link up with a very visible electric tether, and gain a large, ever-increasing attack speed bonus. This lasts for 5-6 seconds, after which the connection overloads and the jellyfish are blasted away from each other (not a super large distance, but enough to stop them from tethering again immediately).

**Comment by fcalife** [comment]
Idea 2: the three-body problem

One of each of these guys:
![image](https://user-images.githubusercontent.com/7921728/130307862-3ef0d008-4df2-4698-9d5a-c7934bc3665a.png)
![image](https://user-images.githubusercontent.com/7921728/130307877-08e88f1d-ac00-4847-8a72-fbb51ea691ef.png)
![image](https://user-images.githubusercontent.com/7921728/130307907-f533cbe3-e258-4ad7-8310-2af95ff02427.png)

They do not move from their initial positions (but can be moved, knocked back, etc. normally).

The wizards each attack with a differently colored beam. Their "attack animation" consists of playing their spawn animation for a split second, which looks shitty indeed (shitty wizards...).

Each wizard has 110 health and 2-4 damage to start with.

Each wizard's attack inflicts a different debuff: silence (1s), break (3s), or disarm (2s). Those effects have a 4s cooldown.

Whenever one of the wizards dies, the remaining wizards' health and damage are tripled. This works for current *and* maximum health.

Example: silence wizard is killed when break and disarm wizards had 30 health left. The break and disarm wizards now have 90 health left.

If the break wizard is then killed without any extra damage being dealt to the disarm wizard, it will now have 270 health left.

Healing prevention abilities completely prevent the health increasing effect.

**Comment by fcalife** [comment]
Just briefly describing the other rounds we brainstormed so its easier to find their information:

3: necronomicon round

1x necrowarrior + 1x necroarcher

tier 2, warrior burns mana (not a lot), archer buffs warrior a bit, warrior has ~2x the archer's health

4: mecha donkeytron 9000

1x mecha donkey

tier 4, ancient creep, knocks you back making you bounce on walls, then charges towards you

5: derpy drakes

generic drakes (red quadruped drake model), add this if one of the 4 other rounds ends up being too annoying/too hard. simple round with a weaksauce crit on a cooldown.

6: f r i d g e

????????????

**Comment by fcalife** [comment]
Added in https://github.com/arcadia-redux/custom_hero_clash/commit/63f145fa87bcf58031f6278df382cff3289d1fd2
