### ISSUE TITLE
If you use Telekenesis on your hero (not enemy) you can't move to a new position

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1446]
Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/873123795530043402/876149069469331456)

**Comment by Snoresville** [comment]
Telekinesis stuns yourself, so this is intended behaviour.

**Comment by Snoresville** [comment]
no it's not
