### ISSUE TITLE
Give players 1 second of complete invulnerbility after respawning with an aegis

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1447]
This is to prevent players dying again before they have time to react.

**Comment by fcalife** [comment]
I'm fairly sure this is already the case; IIRC, instant death happens because sometimes enemies manage to kill the player before the modifier is even applied (you cannot apply modifiers to dead units).

**Comment by ZLOY5** [comment]
Heroes already fully immune to damage first second after respawn and now modifier applied right after respawn, so instant death should be fixed also
