### ISSUE TITLE
When you revive, push back enemies so the player has a chance not to be surrounded and killed again

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1448]
Should have some kind of graphical effect and maybe slow the enemies down, like a blinding like from that wizhard hero, maybe give them miss chance

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/802155090608783371/876350061779484712)

**Comment by Snoresville** [comment]
something like blinding light from kotl?

**Comment by Draze22** [comment]
If you want to go with pushing them back we'd have to also disarm and silence the creeps for a few seconds and make sure those debuffs aren't reduced by the creeps ever increasing resistance to disables.
