### ISSUE TITLE
developer chat button may be interfering with bet window on some resolutions

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1449]
![image](https://cdn.discordapp.com/attachments/873123795530043402/876819821189283840/Screenshot_20210816-232755_Discord.jpg)

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/873123795530043402/876819821378011177)

**Comment by ZLOY5** [comment]
![image](https://user-images.githubusercontent.com/10956575/129697279-e4d268b2-6096-4ce1-a245-cec32a062645.png)
