### ISSUE TITLE
creeps sometimes become invulnerable

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1451]
Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/876849963823419412)

**Comment by AustraliaIsMyCity** [comment]
sometimes one players creep wave will stay stunned and invulnerable causing the round to become unfinishable.

**Comment by AustraliaIsMyCity** [comment]
Occurs in both FFA and Duos

**Comment by AustraliaIsMyCity** [comment]
pretty sure it affects the player who comes last in the previous round

**Comment by SanctusAnimus** [comment]
Band-aid fixed
