### ISSUE TITLE
Aether Remnant + Multicast can cause visual bugs in Duels 

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1454]
Not 100% sure why but there are leftover visual Remnants only when Aether Remnant is multicast in Duels.

![image](https://user-images.githubusercontent.com/63279022/129658026-cb4e2852-233f-4770-b82f-31548f0f8c57.png)

**Comment by SanctusAnimus** [comment]
couldn't reproduce no matter how hard i tried
![image](https://user-images.githubusercontent.com/43399078/130353901-76286e84-5433-4204-abb3-9c4cab8d86de.png)
tried also with overclock and such, no difference, all particles are removed correctly
