### ISSUE TITLE
Several reports of the results screen never showing

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1457]
![image](https://user-images.githubusercontent.com/63279022/129821284-a56df63b-ce94-4346-a8e8-eabc3e465656.png)
![image](https://user-images.githubusercontent.com/63279022/129821302-b9334a10-27f7-4a81-8732-8de5024bcbd6.png)
![image](https://user-images.githubusercontent.com/63279022/129821322-9bc6d640-ccbb-41f1-a7f2-d6509dd35c94.png)

**Comment by ZLOY5** [comment]
Will be fixed after darklord's upload
