### ISSUE TITLE
Theory on how to break discarding 

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1462]
1. Choose an ability to retrain but don't choose a new ability.
2. Start a Duel.
3. Finish the Duel without dying.
4. Press Discard.

**Comment by ZLOY5** [comment]
What u mean break? Just does nothing?

**Comment by Draze22** [comment]
> What u mean break? Just does nothing?

It should give you no ability at all.

**Comment by Draze22** [comment]
And it should prevent further retraining. Also there's other stuff that happens after disconnecting and reconnecting because of the new bots.

**Comment by Draze22** [comment]
I can confirm these exact steps don't break Discarding.
