### ISSUE TITLE
Pudge's Dismember talent might reduce it's duration against heroes

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1466]
![image](https://user-images.githubusercontent.com/63279022/129993292-8ff8f9e7-7ed9-4230-b88f-01ffc8ef1387.png)

**Comment by ZLOY5** [comment]
![image](https://user-images.githubusercontent.com/10956575/130037056-791d6546-75a4-45c1-8dc1-8318e607f932.png)
