### ISSUE TITLE
Implement new Anchor Smash shard

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1469]
to prevent crashes it should have a 1 second cooldown between activation, please put this information on the tooltip in green text.

Opened from Discord by **non toxic egirl#1202**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/878122297116999750)

**Comment by fcalife** [comment]
> to prevent crashes it should have a 1 second cooldown between activation

kinda bootleg but I'm OK with this
