### ISSUE TITLE
When a player abandons the creeps they were against aren't killed

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1470]
The other possibility is that the creeps weren't killed when the player abandoned (they were supposed to spawn but weren't killed when the player was).

![image](https://user-images.githubusercontent.com/63279022/130177048-ecc357ba-a51a-4003-bedd-afa8e3b48851.png)
![image](https://user-images.githubusercontent.com/63279022/130177064-511c527f-1101-46aa-af38-cdeddc001017.png)
![image](https://user-images.githubusercontent.com/63279022/130177071-4eaa265f-9243-42e3-b408-17fc4daa15da.png)

**Comment by Draze22** [comment]
This confirms that the issue is creeps not getting killed when a player abandons.

![image](https://user-images.githubusercontent.com/63279022/130177586-24b195fb-981d-417b-8a32-7e1e47ad2402.png)
![image](https://user-images.githubusercontent.com/63279022/130177594-426ac3b2-e336-4abd-ac50-47bbd6964e0c.png)

**Comment by SanctusAnimus** [comment]
Fixed
