### ISSUE TITLE
Dead/disconnected player was put into a Duel (while dead)

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1471]
![image](https://user-images.githubusercontent.com/63279022/130177449-f35b7e4e-650d-4ff2-9cad-32afa54992c1.png)
![image](https://user-images.githubusercontent.com/63279022/130177535-337fc434-204b-4e0f-b756-aa6d19f48a9d.png)

**Comment by SanctusAnimus** [comment]
Fixed
