### ISSUE TITLE
The new daily Fortune notification looks like a warning

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1473]
Needs to be more inticing and less concerning.

**Comment by Draze22** [comment]
Should at least start by changing it to a colour other than red.

**Comment by AustraliaIsMyCity** [comment]
maybe change it to a red circle with a 1 inside it similar to a mobile notification?

**Comment by SanctusAnimus** [comment]
So what are we doing with it?

**Comment by ZLOY5** [comment]
Is it supposed be like warning so people dont forget to open shop. No?

**Comment by Osamabinfrank** [comment]
While you guys talking about this subject, is it possible to hide the notification? Like an opinion to turn off or a console command?

**Comment by SanctusAnimus** [comment]
At this point changing it doesn't make much sense and reason to it. Closing for now
