### ISSUE TITLE
Abilities that should be affected by Torture Pipe but aren't

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1474]
Approved:
- [x] Ancient Apparition's Ice Vortex Aghs Shard DPS.
- [x] Bane's Nightmare.
- [x] Doom's Infernal Blade Base Burn Damage.
- [x] Leshrac's Diabolical Edict. Very Similar to Rocket Barrage which already gets affected.
- [x] Luna's Eclipse. Very Similar to Rocket Barrage which already gets affected.
- [ ] Mars's Spear of Mars Aghs Shard Fire Trail DPS.
- [x] Razor's Eye of the Storm. Very Similar to Rocket Barrage which already gets affected, when combined with Static Link is a regular DOT ability and usually hits the same target even without Static Link.
- [ ] Tusk's Ice Shards Aghs Shard DPS.
- [x] Underlord's Firestorm Wave Damage.

**Comment by Snoresville** [comment]
I'll do the approved ones and wait for confirmation on the rest

**Comment by Snoresville** [comment]
Abilities I couldn't do:
diabolic edict - damage kv is not exposed in special values
luna eclipse - damage is tied to lucent beam's damage; but we can modify the number of beams
mars fire trail - damage value seems to be hard-coded into the ability
tusk ice shards - damage value seems to be hard-coded into the ability

**Comment by fcalife** [comment]
can we double diabolic edict's explosion count too?

**Comment by Snoresville** [comment]
oh yeah we can

**Comment by fcalife** [comment]
@Draze22 does anything still need validation here?

**Comment by Draze22** [comment]
> @Draze22 does anything still need validation here?

Would be nice to have a discussion about making items affected by torture pipe.

**Comment by Snoresville** [comment]
leshrac's diabolical edict and luna's eclipse: would it be fine to increase the number of edicts/beams so that they technically have the same damage increase because their damage values cannot be interacted with in code?

**Comment by Draze22** [comment]
> leshrac's diabolical edict and luna's eclipse: would it be fine to increase the number of edicts/beams so that they technically have the same damage increase because their damage values cannot be interacted with in code?

That's fine with me (they'll need an ability note explaining that).

**Comment by Snoresville** [comment]
for items, as long as their damage isn't scaling outside of spell amp (e.g. luminance and its strength-based burn) and that it's not percent damage (e.g. spirit vessel), then i believe it's safe to buff those too

**Comment by Snoresville** [comment]
although for those items, i believe there's a flat damage component? i guess we can buff just these kinds of aspects

**Comment by Snoresville** [comment]
wrath of nature is definitely not a dot imo, its like a global arc lightning

**Comment by Snoresville** [comment]
ink swell technically gives heroes a mini ion-shell
swashbuckle does feel like an aoe dot
rupture is really stretching it

**Comment by Draze22** [comment]
So Spear's fire trail and Ice Shard's explosions can't be buffed?

**Comment by Snoresville** [comment]
nope
