### ISSUE TITLE
Rebelance cooldown reduction items, abilities and talents according to the new cooldown reduction rules 

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#1475]
[OPEN TO DISCUSSION BEFORE IMPLEMENTATION]

### Neutral items

Make them equal to octarine core to allow some builds to save an item slot?

- option a) make quickening charm 25% CDR like octarine, and spell prism a slightly better value (30-35%)
- option b) make spell prism equal to octarine (25% CDR), and quickening charm a bit weaker (probably 20% CDR)
- option c) same as (b), but add a tier 5 version of spell prism that is better than octarine (30-35%, maybe even 40% CDR)

### Abilities

Pretty much only Bad Juju and Morph fit in here, and we're not opening the can of worms that is Morph. So, should we revert Bad Juju to its original value? Probably yes.

### Consequences

There's plenty of abilities whose cooldown we increased, compared to vanilla dota, due to being broken with enough CDR. We should re-evaluate each one of those and check if they can have their changes reverted partially or fully.

Charge-based abilities (I'm in favour of keeping those as they are):
- Duel
- Devour
- Track

Immortality/Invulnerability (maybe un-nerf them a bit?)
 - Borrowed Time
 - Shallow Grave
 - Reincarnation
 - False Promise
 - Shadow Realm
 - Book of Shadows (neutral item)
 - Phase Shift

Instakills
 - Hunter in the Night (with shard)
 - Hand of Midas

Others
 - Overclocking
 - Open Wounds (why?)

**Comment by Draze22** [comment]
> Talents
> All hero talents related to cooldown reduction have been removed. Do we follow suit, or re-add some to some heroes (ones with useless talents)?

Already removed.

**Comment by fcalife** [comment]
> Do we follow suit, or re-add some to some heroes (ones with useless talents)?

**Comment by Draze22** [comment]
I'm against adding cdr talents.

**Comment by AustraliaIsMyCity** [comment]
> Neutral items
Make them equal to octarine core to allow some builds to save an item slot?

option a) make quickening charm 25% CDR like octarine, and spell prism a slightly better value (30-35%)
option b) make spell prism equal to octarine (25% CDR), and quickening charm a bit weaker (probably 20% CDR)
option c) same as (b), but add a tier 5 version of spell prism that is better than octarine (30-35%, maybe even 40% CDR)
i like option C

**Comment by AustraliaIsMyCity** [comment]
> Abilities
Pretty much only Bad Juju and Morph fit in here, and we're not opening the can of worms that is Morph. So, should we revert Bad Juju to its original value? Probably yes.

yup

**Comment by AustraliaIsMyCity** [comment]
> Charge-based abilities (I'm in favour of keeping those as they are):
Duel
Devour
Track

agreed, leave as is; even without CDR they would still have the issues of stalling

**Comment by AustraliaIsMyCity** [comment]
> Immortality/Invulnerability (maybe un-nerf them a bit?)
Borrowed Time
Shallow Grave
Reincarnation
False Promise
Shadow Realm

IMO since all of these are still strong we should leave them nerfed

> Book of Shadows (neutral item)
Phase Shift

These two are pretty useless right now so I'm fine with reverting them to vanilla (as long as they cant be used to hit 100% uptime)

**Comment by AustraliaIsMyCity** [comment]
> Instakills
Hunter in the Night (with shard)
Hand of Midas
Hook
Arrow
Demonic Conversion

IMO these (any other instant kills im forgetting) should all be reverted to vanilla cooldowns, but made unrearmable.

**Comment by AustraliaIsMyCity** [comment]
> Others
Overclocking 

Same as BT/SG etc., still useful so leave as is imo

> Open Wounds (why?)

revert to vanilla CD, rearmable if not already

**Comment by Draze22** [comment]
> Neutral items
> Make them equal to octarine core to allow some builds to save an item slot?

> option a) make quickening charm 25% CDR like octarine, and spell prism a slightly better value (30-35%)
> option b) make spell prism equal to octarine (25% CDR), and quickening charm a bit weaker (probably 20% CDR)
> option c) same as (b), but add a tier 5 version of spell prism that is better than octarine (30-35%, maybe even 40% CDR)

I agree with option C with 30% cdr for tier 5.

> Immortality/Invulnerability (maybe un-nerf them a bit?)

> Borrowed Time
> Shallow Grave
> Reincarnation
> False Promise
> Shadow Realm

Shallow Grave and Reincarnation (only base ability, not Aghs) can be reverted to Vanilla. Everything else needs to stay the same.

> Others

> Overclocking
> Open Wounds (why?)

Agreed on leaving Overclocking as is, Open Wounds is being overriden with the same value as vanilla for some reason.

**Comment by Draze22** [comment]
Only thing left to do is add a 30% cooldown reduction neutral item to tier 5.

**Comment by Draze22** [comment]
Final part of this issue moved to #1525.
