### ISSUE TITLE
Figure out 7.30 neutral items updates

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#1479]
Discuss which items we want to remove, and which ones from the new batch will replace them. After the debate is done, a new issue will be created with the result.

### removed neutral items:

![image](https://user-images.githubusercontent.com/7921728/130192212-47cfdba2-cf17-46c9-a217-dd641c4d6c85.png)

### new neutral items:

![image](https://user-images.githubusercontent.com/7921728/130192274-a3c97089-d2e7-4a82-847e-9b8715b4af6f.png)

![image](https://user-images.githubusercontent.com/7921728/130192283-cf716ab1-4351-45d8-add1-e32209cd1ec0.png)

![image](https://user-images.githubusercontent.com/7921728/130192299-8374777b-17a3-4aa3-a578-e544db512c23.png)

![image](https://user-images.githubusercontent.com/7921728/130192327-f0b19683-2f4c-48d8-8fc2-f0720cd6539a.png)

![image](https://user-images.githubusercontent.com/7921728/130192345-3ee455ed-996b-4601-b3bf-598a8ab62c53.png)

![image](https://user-images.githubusercontent.com/7921728/130192361-299bc87d-d261-4a1c-a564-dc1b45f50d3a.png)

![image](https://user-images.githubusercontent.com/7921728/130192373-8749c957-ba99-4b91-a809-7e6ccd03786d.png)

![image](https://user-images.githubusercontent.com/7921728/130192394-8c2fa9f0-2291-4412-a9e2-2db3516ecd22.png)

### reworked neutral items

(ignoring minor stat changes since we use our own stats)

![image](https://user-images.githubusercontent.com/7921728/130192629-d7efda64-7f36-4168-85ae-2f35dc13f816.png)

![image](https://user-images.githubusercontent.com/7921728/130192663-93e1563b-5095-4e26-911d-e4c672dbef6c.png)

![image](https://user-images.githubusercontent.com/7921728/130192688-ae79cc61-2fb5-42c5-84e2-18415f0ae3a9.png)

![image](https://user-images.githubusercontent.com/7921728/130192699-fbda41ea-54cd-43a4-a865-aa4cfbb06c19.png)

**Comment by Snoresville** [comment]
ironwood tree and pig pole seems to be duplicates of each other in stats; in the context of this mode, mobility is not much of a problem so pig pole has a worse active than ironwood tree

**Comment by fcalife** [comment]
IMO:

- I won't miss any of the removed items. Maybe minotaur horn.
- Possessed mask is garbage now
- Stormcrafter is a bit weaker but whatever
- Pointless or meh: pig pole, witchbane (its a weak dispel), tumbler's toy (works somewhat for early duels I guess)
- Brigand's blade, fae grenade, arcanist's armor all seem fine additions
- Blast Rig and Ascetic's Cap are great
- New tier 5 item candidates: brigand's blade, ascetic's cap, arcanist's armor

**Comment by Draze22** [comment]
- I don't mind if Pig Pole or Ironwood Tree stays, both actives are basically useless in CHC.
- I don't see any reason not to update Possessed Mask, it won't be that much worse.
- Witchbane should definitely be added.
- I agree that the rest are good or great additions.
- We already have 2 items that grant status resistance at Tier 5, we should replace one of them if we add a version of Ascetic's Cap.
- I agree that Arcanist's Armor seems like a great potential Tier 5 item. Brigand's Blade sounds decent but nothing special as a tier 5.

**Comment by Draze22** [comment]
I'd also like to take this as an opportunity to rebalance the existing neutral items if @darklordabc agrees.

**Comment by fcalife** [comment]
CLosed by https://github.com/arcadia-redux/custom_hero_clash/pull/898 (@Draze22 don't forget to claim)
