### ISSUE TITLE
Swapping abilities while one player is choosing an innate doesn't give an error message

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1480]
Should give the same (or similar) error message to the one given when one player is choosing an ability.

**Comment by SanctusAnimus** [comment]
Why though? You can't swap innates? What's the issue?

**Comment by Draze22** [comment]
> Why though? You can't swap innates. What's the issue?

When one player is choosing an innate the other player can't propose to swap an ability until the other player chooses an innate. When they try to it just doesn't work instead of telling the player why.
