### ISSUE TITLE
Update talent overrides to 7.30

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#1481]
Some heroes have completely useless talents in the context of CHC, or talents for abilities not in the game. We usually override those with generic talents, so the hero doesn't have a completely useless skill point to spend.

This needs to be checked and updated to match the 7.30 changes to hero talents.

Heroes which should be checked (all heroes with overridden talents in CHC):
- [ ] Slardar
- [ ] Zeus
- [ ] Void Spirit
- [ ] Meepo
- [ ] Naga Siren
- [ ] Phantom Assassin
- [ ] Elder Titan
- [ ] Clinkz
- [ ] Brewmaster
- [ ] Morphling
- [ ] Tiny
- [ ] Ember Spirit
- [ ] Shadow Demon
- [ ] Gyrocopter
- [ ] Storm Spirit
- [ ] Dawnbreaker
- [ ] Wisp
- [ ] Nature's Prophet
- [ ] Enchantress
- [ ] Chen
- [ ] Phoenix
- [ ] Rubick
- [ ] Disruptor
- [ ] Skywrath Mage
- [ ] Doom
- [ ] Undying
- [ ] Spectre
- [ ] Nyx Assassin
- [ ] Dark Willow
- [ ] Winter Wyvern
- [ ] Lone Druid
- [ ] Monkey Kind
- [ ] Shadow Fiend
- [ ] Riki
- [ ] Luna
- [ ] Invoker
- [ ] Dragon Knight
- [ ] Windranger

**Comment by Draze22** [comment]
I already did this although is someone wants to double check they're more than welcome.
