### ISSUE TITLE
Lua-fy counter helix to make its shard effect cap at 4 charges

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#1483]
[OPEN TO DISCUSSION]

![image](https://user-images.githubusercontent.com/7921728/130197423-51be1f72-cb75-480e-95bc-76cd1570fc20.png)

Normally this effect caps at 5 charges. Make it cap at 4 charges instead.

This requires a lua rework, or modifier filter workaround, due to the shard's values not being exposed to KV (thanks, valve).

**Comment by Draze22** [comment]
Counter Helix is barely in the top 100 abilities since 7.30, I would like to wait and see how good it is.

**Comment by fcalife** [comment]
Sure, I'm OK with that

**Comment by AustraliaIsMyCity** [comment]
Imo this isnt needed given that creeps gain bonus damage during overtime

**Comment by AustraliaIsMyCity** [comment]
closed for now, can reopen if CH is too good after a few weeks, but i doubt it will be tbh
