### ISSUE TITLE
Add Broodmother's new scepter ability to her ultimate

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#1484]
![image](https://user-images.githubusercontent.com/7921728/130197748-f94aca5f-746e-4859-b497-c9a67e77aefe.png)

Add *Spinner's Snare* to Spawn Spiderlings (brood's ultimate).

**Comment by Draze22** [comment]
Pretty Sure @SanctusAnimus already did this.

**Comment by SanctusAnimus** [comment]
it's tied to Spin Web right now

**Comment by fcalife** [comment]
just change to spawn spiderlings and this is gucci then

**Comment by lovro-m** [comment]
Spinner's snare has 2 charges and doesn't cd properly in base, but I doubt we care.
