### ISSUE TITLE
Add a Strong Dispel to our custom Hand of God

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#1485]
![image](https://user-images.githubusercontent.com/7921728/130198349-f4293d88-8fbb-45da-9c90-6ac6007fdfff.png)

**Comment by Snoresville** [comment]
our custom hand of god already applies a strong dispel. do you want to make the strong dispel locked behind a scepter upgrade?

**Comment by Snoresville** [comment]
![image](https://user-images.githubusercontent.com/19840964/130319177-60c33c2b-289c-4048-a377-cba0b87b5920.png)
