### ISSUE TITLE
Update Clinkz's abilities

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#1486]
![image](https://user-images.githubusercontent.com/7921728/130198513-914b883d-af15-4b5f-8206-a45914621301.png)

If Strafe is still functional, keep it on the ability pool and add Clinkz's new skill to it.

If not, just add the new ability to the ability pool.

**Comment by lovro-m** [comment]
Clinkz strafe has now become burning barage ability. There is no previous strafe.
