### ISSUE TITLE
Update Black Hole interaction with midnight pulse and spell amp

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#1489]
![image](https://user-images.githubusercontent.com/7921728/130199446-33aaf23d-bf4c-42a7-aa72-e35cc65f5d39.png)

Previously, scepter Black Hole's percentage-based damage was dealt as a separate damage instance, attributed to midnight pulse (and only worked if you also had midnight pulse).

These patch notes imply something changed in the ability's mechanics. Verify if midnight pulse is no longer needed for the percentage-based damage to kick in, and update tooltips accordingly.

Verify if our special exception for black hole in `modifier_spell_amplify_controller` is still relevant, and update it accordingly.

**Comment by Draze22** [comment]
I can confirm that Midnight Pulse is not needed to Deal the 5% damage per second and have updated it accordingly. I can also verify that with Aghs Black Hole is not affected by spell amp but have not checked it without Aghs.

**Comment by Draze22** [comment]
Can now confirm that Black Hole is affected by Spell Amp without Aghs. The Conclusion is that nothing needs to be changed.
