### ISSUE TITLE
Update our custom stifling dagger

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#1494]
![image](https://user-images.githubusercontent.com/7921728/130201937-283eade2-e809-4a6d-8b08-487bf39e3b3e.png)

Just update the values.

**Comment by Draze22** [comment]
We aren't using a custom Stifling Dagger anymore.

**Comment by fcalife** [comment]
huh. was this recent? I vaguely remember someone using the flurry of daggers ability with giant strikes semi-recently

**Comment by Draze22** [comment]
Pretty sure a while back (maybe 3-6 months ago) we went through most of the ability that had a frosthaven version and picked one (either regular or frosthaven) based on which was the most useful, least buggy, worked with talents easily, etc and we decided to keep regular Stifling Dagger.

**Comment by fcalife** [comment]
oki doki!
