### ISSUE TITLE
Decide what the fuck we're doing with the new Anchor Smash talent

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#1499]
![image](https://user-images.githubusercontent.com/7921728/130203914-832e0f2f-254a-4583-8419-1c645a84d9f0.png)

...yeah.

After the debate is done, another issue should be created, to implement the solution and update Anchor Smash to its new values:

![image](https://user-images.githubusercontent.com/7921728/130204003-4c1c3558-ea69-45ec-b8f8-209071497a4d.png)

**Comment by Snoresville** [comment]
we're currently discussing this in https://github.com/arcadia-redux/custom_hero_clash_issues/issues/1469
pull request already submitted for review

**Comment by Snoresville** [comment]
and i do need to update those values on my branch

**Comment by SanctusAnimus** [comment]
merged with 1s cd, aimc will be angy probably but idc lmao
