### ISSUE TITLE
Can't exit spectator mode because this button covers the exit button

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1511]
![image](https://cdn.discordapp.com/attachments/682631693172998165/878270227845111858/unknown.png)

Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/878270227744456735)

**Comment by Draze22** [comment]
@AustraliaIsMyCity Is this fixed?

**Comment by AustraliaIsMyCity** [comment]
No

**Comment by Draze22** [comment]
Would be nice to finally fix this.

**Comment by AustraliaIsMyCity** [comment]
While we’re at it can we just like fix spectating entirely

**Comment by ZLOY5** [comment]
Ye, im trying, just for each iterate i must wait for update

**Comment by ZLOY5** [comment]
Fixed
