### ISSUE TITLE
Leaderboards don't properly order players by time

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#1512]
Notice in those two screenshots that the first two players' positions switch around:

![Discord_bxv5QnIzfT](https://user-images.githubusercontent.com/7921728/130266596-77da353e-8c5b-4d0f-9fc3-7e9092697c7b.png)

![Discord_LjmBaMd42R](https://user-images.githubusercontent.com/7921728/130266606-3437cad7-597d-4f86-9e17-91f4025a0cbf.png)

The leaderboards are being ordered by max round, but not by time. When 2 players are tied for the same maximum round, the one with the shortest recorded time should come first.

**Comment by SanctusAnimus** [comment]
Updated leaderboards sorting query, now should be correct
