### ISSUE TITLE
Magus puts Charge of Darkness on cd

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1516]
![image](https://user-images.githubusercontent.com/63279022/130336345-fefc21e3-8c07-47d7-9bc6-fb07a5018f88.png)

**Comment by Draze22** [comment]
Charge of Darkness can of course still get procced by magus while on cooldown and every time it does the cooldown gets reset (to full duration).

**Comment by SanctusAnimus** [comment]
so what should be do with it? disable from procing by magus?

**Comment by Draze22** [comment]
> so what should be do with it? disable from procing by magus?

I just realised that when Charge of Darkness hits an enemy it puts it on cooldown, I'll add an ability note to it explaining this interaction.

**Comment by Draze22** [comment]
Fixed: https://github.com/arcadia-redux/custom_hero_clash/commit/6866a984976ebf1ce2cc1ef19c1858ebd850def1.
