### ISSUE TITLE
Suggestion for "Soul link"

### ISSUE THREAD

**Issue by dayd21git** [arcadia-redux/custom_hero_clash_issues#1522]
By default, this talent gives 25% bonuses to creature attributes, as well as 10% regeneration.

In fact, at the initial stage of the game, this is a very strong gain both against creeps and in duels. It needs to be weakened. In addition, starting from about the sixtieth round, this gain becomes quite weak against creeps.

I suggest:
Default attributes are 5% + 0.4% per round.
Regeneration by default is 0% +0.2% per round.

**Comment by Draze22** [comment]
Both buffs are multiplicative meaning they're equally good the entire game.

**Comment by dayd21git** [comment]
> Both buffs are multiplicative meaning they're equally good the entire game.

You obviously spent very little time in games against the Summoners.
Any creeps at the start of the game under this talent are strong in both PVE and PVP.
Few people like to die in 2-3 shots, not having time to run half of the PVP arena.

**Comment by Draze22** [comment]
Summons are very strong early game even without Soul Link.
