### ISSUE TITLE
Add a cooldown reduction mastery

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1524]
10/20/30% CDR. Needs a new icon to go with it.

Opened from Discord by **Snoresville#2486**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/878880809111658537)

**Comment by ArcadiaReduxAutomation** [comment]
$i close

Comment from Discord by **Snoresville#2486**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/878880859032289310)

**Comment by darklordabc** [comment]
Why cloed?

**Comment by Draze22** [comment]
> Why cloed?

They opened 2 issues by accident and closed one.
