### ISSUE TITLE
Make a permanently implemented announcements board for tournaments and similar things

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1527]
- [ ] Should be toggle-able with a discord command, when off it disappears entirely, when on it shows the current announcement message when players load into the game.
- [ ] The message should be changeable from discord, and all links should be clickable.
Can probably just reuse the panel used for the previous tournament announcement.

Opened from Discord by **non toxic egirl#1202**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/879159672819552287)

**Comment by AustraliaIsMyCity** [comment]
Should be pretty quick to do, I’d prefer to have it implemented before the end of next week 😶

**Comment by SanctusAnimus** [comment]
We already have announcements panel, why do we need another one?

**Comment by AustraliaIsMyCity** [comment]
Oh neat i had no idea lol, how do i edit it?

**Comment by SanctusAnimus** [comment]
In game files lol, current one is intentionally not tied to backend. Ask sheodar, he made it, he knows more

**Comment by AustraliaIsMyCity** [comment]
@Sheodar

**Comment by Draze22** [comment]
@AustraliaIsMyCity do you still want this?

**Comment by AustraliaIsMyCity** [comment]
Not needed

**Comment by SanctusAnimus** [comment]
thus closing
