### ISSUE TITLE
Add Metamorphosis to the disabled abilities preview during hero picking

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1528]

**Comment by ZLOY5** [comment]
What this issue even means? If this ability not in the list it's not banned

**Comment by Draze22** [comment]
> What this issue even means? If this ability not in the list it's not banned

It was disabled by Sanctus using a differen't method.

**Comment by ZLOY5** [comment]
In tools all works fine even if I immitate abilities banned from server.

**Comment by Draze22** [comment]
No longer necessary.
