### ISSUE TITLE
Multicast isn't disabled by break

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1529]
additionally the effect it applies when cast should also be broken. Add a tooltip which specifies this.

Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/802155090608783371/879197383190265877)

**Comment by Draze22** [comment]
Wait are you saying Multicast should or shouldn't be affected by break?

**Comment by Draze22** [comment]
Ok if we're making it like vanilla multicast it should be affected by break.
