### ISSUE TITLE
Pausing in PVE at the last possible moment (at 5s till the next round) makes the unpause button never appear

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1530]
![image](https://user-images.githubusercontent.com/63279022/130388919-031d7f13-5cc2-4a64-b348-4b212d9dbfe9.png)
![image](https://user-images.githubusercontent.com/63279022/130388932-84f49cde-4e20-461d-be55-71d28ea081ab.png)

**Comment by Osamabinfrank** [comment]
Little extra info
You can continue the game by pressing the ready buttons
Sometimes pause bugs differenctly and starts saying unpausing automatically, and un pause even when you have 12 seconds left and you can immediately pause it again,

**Comment by Draze22** [comment]
Pretty sure the automatic unpause is because of Valve but I might be wrong. I guess we could try and detect automatic unpauses and auto pause after them.
