### ISSUE TITLE
Make the new lvl 20 Jingu Mastery talent work for our custom Jingu Mastery

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1532]
![image](https://user-images.githubusercontent.com/63279022/130541013-747ca907-ddcc-4ee2-95ef-cf5c0343b001.png)

**Comment by Snoresville** [comment]
that's strange, it doesn't do that? i'll have to check

**Comment by Snoresville** [comment]
seems to work as intended in master.
