### ISSUE TITLE
Two bots in a duel aainst each other both did nothing  for the entire duel

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1534]
![image](https://user-images.githubusercontent.com/63279022/130550812-f4201743-d7b0-4375-bab7-00bd017a8557.png)
![image](https://user-images.githubusercontent.com/63279022/130550722-3e69bebe-d9c3-4f58-8b71-df653c7533a5.png)

**Comment by SanctusAnimus** [comment]
Should already be fixed in master
