### ISSUE TITLE
Curse stacks stop Bad Juju's cooldown reduction from working

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1535]
Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/802155090608783371/879576534359347220)

**Comment by ArcadiaReduxAutomation** [comment]
also applies to octarine core and presumably all other sources of CDR

Comment from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/802155090608783371/879576677284466698)

**Comment by SanctusAnimus** [comment]
Fixed in feb2515
