### ISSUE TITLE
Add Ball Lightning back to CHC with a 1500 cast range

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1536]
My only concern is that people will be able to get enough mana to spam this and never take damage.

**Comment by Draze22** [comment]
I suppose we could increase the cast point if that happens.

**Comment by Snoresville** [comment]
mana regen? ball lightning is based on a percent of max mana

**Comment by chariot-afv** [comment]
Essence flux is a thing. If coupled with ball lightning and big enough mana pool (to make flat manacost  part of ball lighting), almost constant ball lightning is real.

**Comment by Snoresville** [comment]
true

**Comment by lovro-m** [comment]
add 1s cd between casts

**Comment by SanctusAnimus** [comment]
So what do we do with it? 1s cd and 1500 cast range?

**Comment by Draze22** [comment]
> So what do we do with it? 1s cd and 1500 cast range?

2s cd and 1500 cast range should be fine.
