### ISSUE TITLE
Make the Duos duel arena taller

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1539]
Doesn't make much sense for the FFA arena to be taller than the Duos arena.

**Comment by SanctusAnimus** [comment]
How's this high priority and what's the difference at all

**Comment by Draze22** [comment]
> How's this high priority and what's the difference at all

Basically Magician is currently exetremely strong in Duos because the Duos duel arena is shorter than the FFA Duel Arena.

**Comment by SanctusAnimus** [comment]
lol i thought "taller" meant arena height

**Comment by ZLOY5** [comment]
![image](https://user-images.githubusercontent.com/10956575/132104394-fdb7369e-21c1-46e3-be82-3eedb2b2bbda.png)
@Draze22  That what you need?

**Comment by ZLOY5** [comment]
Current arena for comparison
![image](https://user-images.githubusercontent.com/10956575/132104619-4267ec2b-eb06-41f9-aa94-dc7e91b1d6d4.png)

**Comment by Draze22** [comment]
> ![image](https://user-images.githubusercontent.com/10956575/132104394-fdb7369e-21c1-46e3-be82-3eedb2b2bbda.png)
> @Draze22 That what you need?

Yeah that's pretty good.
