### ISSUE TITLE
Increase hero damage to MSW from 2 per hit to 4 per hit

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1540]

**Comment by ZLOY5** [comment]
Idk, can we just half ward health?

**Comment by Draze22** [comment]
> Idk, can we just half ward health?

We don't want to make it weaker in creep rounds.

**Comment by SanctusAnimus** [comment]
but creeps pretty much ignore ward most of the time?

**Comment by Draze22** [comment]
We already made heroes deal 2 damage to MSW instead of 1, where's there so much push back to changing it to 4?

**Comment by SanctusAnimus** [comment]
It's just doesn't make much sense to me for ward to have a lot of health and damage multipliers when it can be just less hits

**Comment by fcalife** [comment]
Added in https://github.com/arcadia-redux/custom_hero_clash/commit/8c980954535ca38725c5320a4264c0392fbb166d
