### ISSUE TITLE
Using Summon Spirit Bear breaks Smoke of Deceit

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1543]
![image](https://user-images.githubusercontent.com/63279022/131255495-6c4c957a-ce76-46ae-8412-a6e4b7d02070.png)

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/132020257-cb0938ba-4ea3-4b8e-a4f4-afbebdb87bb2.png)
nope
