### ISSUE TITLE
Gem of Truesight on Spirit Bear doesn't give truesight

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1544]
![image](https://user-images.githubusercontent.com/63279022/131282883-f1304621-05e2-4787-bb32-588f514fdd22.png)

**Comment by ZLOY5** [comment]
![image](https://user-images.githubusercontent.com/10956575/131330552-9d7828f5-9aca-4f45-a98c-67fe65e1b93e.png)

**Comment by Draze22** [comment]
Wow, I didn't know that.
