### ISSUE TITLE
Rearm and Multicast exceptions 

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1550]
- Eye of the Storm: I would be open to allowing this to be Rearmed. It would be very strong but not op.
- Fatal Bonds: Requires multiple units and other things to deal damage for it to be effective. Imo it should be Rearmable.
- Spirit Bear: For some reason this can't be Multicast. Would there be an issue in setting it to multicast type summon?
- Blink (QOP): This should be Multicastable because of the Shard effect.
- Fan of Knives: Definitely shouldn't be Rearmable (too op). Imo Multicasting it is fine.
- Black Hole: Now that this does Aoe % damage with Aghs it's probably too op to Rearm.

**Comment by jakmarles** [comment]
how about making venomous gale not multicastable? 
currently only the last multicased gale will summon wards
enemies will just run away from the lane of gales when its multicasted
note that the sharded wards doesnt become any stronger

**Comment by Draze22** [comment]
Agreed.
