### ISSUE TITLE
User suggestion. 

### ISSUE THREAD

**Issue by Osamabinfrank** [arcadia-redux/custom_hero_clash_issues#1552]
I recall one of the devs saying that you guys planing on removing the cast time of rearm (its been done in regular dota on 7.29)but even without the change there are currently 2 highly overpowered combos which being around for ages and literally been used every tournament. I am talking about rearm + fan of knives and rearm + magnus ulti

My suggestion - make fan of knives non rearmable or change the dmg type from pure to magic.

And for rearm+rp -  make rp not pierce bkb

Yes both of the strategies has counter plays but the odds of getting them are way too slim.
Please consider nerfing it.
Beast

4 Sep 2121

**Comment by Draze22** [comment]
We're already planning on removing Rearm + Fan of Knives.

Rearm + Reverse Polarity isn't going to get nerfed because it can be dispelled. Just buy Aeon, Refresher and things to silence/stun your opponent.

**Comment by Osamabinfrank** [comment]
> We're already planning on removing Rearm + Fan of Knives.
> 
> Rearm + Reverse Polarity isn't going to get nerfed because it can be dispelled. Just buy Aeon, Refresher and things to silence/stun your opponent.

Aeon is useless since you can purge it, there plenty of spells and items to protect the caster from getting silenced. For example blur, shadow dance/realm, jugger q, chrono, bkb, satanic, lotus, demonic, doom etc
Rp + rearm would be useless if there wasn't a mana regen mastery which is a must have for rearm builds especially in tournaments.
But do as you think the best choice.

**Comment by Draze22** [comment]
There's this item called bkb to protect from nullifier so your aeon disk is useful. Or you could even use linken's + mirror shield.
