### ISSUE TITLE
Add warnings about % cdr not stacking from multiple sources

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1563]
do for all mods

Opened from Discord by **non toxic egirl#1202**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/885027988729651201)

**Comment by ArcadiaReduxAutomation** [comment]
as in like tooltips n shit

Comment from Discord by **non toxic egirl#1202**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/885028607142014988)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/132457910-527f10c6-a2b4-4999-931b-3c61c5514348.png)
