### ISSUE TITLE
Some players are reporting that the game lags after ~round 10

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1564]
![image](https://user-images.githubusercontent.com/63279022/132457374-83605b31-cfc5-47ce-8b91-65f5dc2d0383.png)

![image](https://user-images.githubusercontent.com/63279022/132457383-aba5f2fb-b6dc-4a9b-a29d-4ff811fec583.png)

![image](https://user-images.githubusercontent.com/63279022/132457529-bac411c7-928f-4bdb-8d7e-4b87be31bdd2.png)

![image](https://user-images.githubusercontent.com/63279022/132457628-0190816a-c0cf-4a55-b762-a854e4830329.png)

**Comment by Draze22** [comment]
Personally I haven't experienced this happening in any game I've played this update.

**Comment by Draze22** [comment]
As far as I can tell it started after the Septemeber 1st update and somehow only seems to effect some players (probably ones with shit pcs).

**Comment by Osamabinfrank** [comment]
I got GTX1080TI and i7 8700k 4.7ghz.fps drops from 240 to 60 on round 11
