### ISSUE TITLE
Capitalist text covers chat

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1568]
![image](https://user-images.githubusercontent.com/63279022/132944306-30325143-68f8-4a1f-ae7b-1e3bf197533d.png)

**Comment by SanctusAnimus** [comment]
Well, yes? it's supposed to be displayed like that? How else would it be

**Comment by Draze22** [comment]
> Well, yes? it's supposed to be displayed like that? How else would it be

Couldn't it be moved down slightly so it doesn't cover messages ( in this case Undying's message).

**Comment by AustraliaIsMyCity** [comment]
this issue is dumb
