### ISSUE TITLE
Batrider is called Nature's Prophet in the pick screen

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1571]
![image](https://user-images.githubusercontent.com/63279022/133108999-82213994-25e9-45bc-80a9-6e2f71f86489.png)

**Comment by SanctusAnimus** [comment]
lmfao

**Comment by Draze22** [comment]
Elder Titan is also called Doom.

![image](https://user-images.githubusercontent.com/63279022/133110245-887d859b-39a0-435a-a92e-9db7dd596827.png)

**Comment by Draze22** [comment]
Rerolling doesn't change the hero displayed.
