### ISSUE TITLE
If a player leaves without choosing an ability their partner cannot propose ability swaps

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1575]
![image](https://user-images.githubusercontent.com/63279022/133205873-1feeec57-89bc-4981-8905-af82c96ad192.png)

**Comment by SanctusAnimus** [comment]
This sounds like a source of bugs and abused with disconnection, considering that we can't test it in tools. Stays like that, intended mechanic
