### ISSUE TITLE
Add Masteries to the most expanded version of the side pannel 

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1576]
![image](https://user-images.githubusercontent.com/63279022/133209464-70c4fe08-6cab-422c-b9f6-c250ed9295c5.png)

**Comment by SanctusAnimus** [comment]
Iirx we already discussed that in the past? At best it won't show level of master like in duel panel

**Comment by Draze22** [comment]
> Iirx we already discussed that in the past? At best it won't show level of master like in duel panel

That's fine.

**Comment by Sheodar** [comment]
Implemented
