### ISSUE TITLE
Change how Venomous Gale's Shard is affected by Multicast

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1577]
Currently when Venomous Gale (with shard) is Multicast it spawns 1 Plague Ward for each unit (2 for heroes) hit by the final Venomous Gale. This means that if the first 3 casts of a 4x multicast hit a unit but the final cast misses no Plague Wards will be spawned.

We have 2 main options for changing this:

1. Make each unit hit by the inital Venemous Gale spawn a Plague Ward and any unit hit by an additional multicast Venemous Gale, buff the corresponding Plague Ward (double health and damage).
2. As a temporary lazy fix we could just make the initial Venemous Gale spawn Plague Wards instead of the final one.

**Comment by jakmarles** [comment]
summoners are currently pretty bad especially venom 
opinion 1 sounds more fair
