### ISSUE TITLE
Torture Pipe active pierces Borrowed Time

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1580]
Imo we should just revert back to Vanilla Borrowed time. It's a very strong spell, it doesn't need to also activate at 20% hp.

![image](https://user-images.githubusercontent.com/63279022/133595345-df771ea7-b315-4e89-a82f-ff39cff08edb.png)

https://discordapp.com/channels/694060511209324585/694440472273354762/887478827696140319

**Comment by Snoresville** [comment]
can't revert, we need its aghs passive mist coil effect to still work without mist coil

**Comment by Draze22** [comment]
> can't revert, we need its aghs passive mist coil effect to still work without mist coil

Need is a strong word.

**Comment by ZLOY5** [comment]
Would flat HP treshold too low starting from mid game? And often hero just die

**Comment by Draze22** [comment]
> Would flat HP treshold too low starting from mid game? And often hero just die

Yes, that is the problem a lot of people had with it that causes us to change it in the first place. However Borrowed Time is one of the best abilities in the game and doesn't really need to be noob proof.
