### ISSUE TITLE
Players don't lose mmr if they leave before round 2

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1581]
![image](https://user-images.githubusercontent.com/63279022/133597171-0ea3181f-cabe-4578-b8b7-5531581f5072.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.

**Comment by Draze22** [comment]
This is reproducible and easily abusable.

**Comment by SanctusAnimus** [comment]
hmm @fcalife i think it's because of how valid teams are determined? after round 1, since for round 1 creeps spawn on all arenas. that might need a rework, or tweak at least

**Comment by fcalife** [comment]
ahhh godsdamnit, I knew this would come back to bite me in the ass someday

**Comment by Draze22** [comment]
This is still a big issue.
