### ISSUE TITLE
Burning Barrage + Multicast might cause the server to crash

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1583]
This is the second time this has been reported but when I tested it the server didn't crash.

![image](https://user-images.githubusercontent.com/63279022/133728732-abda7a30-ed20-4c45-822b-d71d26c047c9.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.

**Comment by lovro-m** [comment]
Idk about crashing the server, but the multicasted burning barrage always shoots in the same direction towards the map origin.

**Comment by SanctusAnimus** [comment]
might as well just disable multicast on it then

**Comment by lovro-m** [comment]
sure
