### ISSUE TITLE
Ice Shard's with Multicast can leave invisible obstacles

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1586]
When testing this I was unable to confirm it and I tested with and without Aghs Shard. However 2 separate players have reported this happening.

![image](https://user-images.githubusercontent.com/63279022/133730778-a9a5057d-81ad-4ad1-8ac8-72ed5a83b012.png)

**Comment by lovro-m** [comment]
Duplicate of https://github.com/arcadia-redux/custom_hero_clash_issues/issues/1602
