### ISSUE TITLE
discuss implementing actor reporting

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1587]
we should figure out whether or not we want it, and why

Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/888333012020895835)

**Comment by Snoresville** [comment]
depends on the context

**Comment by Osamabinfrank** [comment]
It will make the mode much more toxic, ppl will report for no reasons while insulting each other in the voice chat.

**Comment by SanctusAnimus** [comment]
Also parties will just report people they don't like, especially if reporting will have any kind of actual power (aside from plain counter somewhere in UI)

**Comment by Draze22** [comment]
Imo if we do implement reports it should purely be so other players can see how often the player they're betting on gets reported so they can be aware they might throw the duel.

**Comment by fcalife** [comment]
![image](https://user-images.githubusercontent.com/7921728/163316787-fe4c5adc-63ee-4496-a6c3-76e668f8aa7c.png)

**Comment by Draze22** [comment]
Closing this until we have an idea we know will have a positive effect.
