### ISSUE TITLE
Check if Bounty Hunter's Jinada Talent works

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1588]
Afaik Jinada hasn't been changed in any way so the talent should work.

![image](https://user-images.githubusercontent.com/63279022/133778225-e8462ea4-1a3b-43e6-9840-340d8f211d74.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.

**Comment by lovro-m** [comment]
Works perfectly fine. He probably forgot to toggle it on.
