### ISSUE TITLE
Make Spawn Spiderlings self castable 

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1590]
When self cast it should deal no damage and spawn Spiderlings instantly.

**Comment by lovro-m** [comment]
The ability will have to be rewritten. What do you want to do with multicasting? Also no self damage?

**Comment by lovro-m** [comment]
Also since I am rewritting this I suggest bringing back the 50% damage talent for spiders against buildings but without the building part.
