### ISSUE TITLE
Make Forge Spirit's Melting Strike work on creeps

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1592]

**Comment by Snoresville** [comment]
depends on whether he tested on creeps or heroes

**Comment by Draze22** [comment]
> depends on whether he tested on creeps or heroes

I tested it on creeps only.

**Comment by Snoresville** [comment]
wiki says it only deals its debuff on enemy heroes, if you want it to affect creeps too, we'll figure a solution
