### ISSUE TITLE
Wild Axes (Aghs) can be spammed if you have at least 1 Loser Curse

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1593]
By spammed I mean the restriction of having to wait for the axes to return before casting it again gets removed when you have a Curse.

**Comment by ZLOY5** [comment]
Should be fixed in https://github.com/arcadia-redux/custom_hero_clash/commit/b5a57a36217739c07a0c8fbffb575287448e8dc4
