### ISSUE TITLE
Timothy the Brave is inconsistent

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1604]
![image](https://user-images.githubusercontent.com/63279022/134184617-55158adc-929d-469f-a1bf-d589246cf6d8.png)
![image](https://user-images.githubusercontent.com/63279022/134184817-6c15d095-6a25-4913-9865-d47c3019bbfa.png)

**Comment by SanctusAnimus** [comment]
That's the wrong repo i think? Should be in pathfinders

**Comment by Draze22** [comment]
> That's the wrong repo i think? Should be in pathfinders

This is live.

**Comment by SanctusAnimus** [comment]
Yeah but this belongs to Pathfinders? You opened issue in Custom Hero Clash issues repo, either close and open new in right place or transfer this one.

**Comment by Draze22** [comment]
oops
