### ISSUE TITLE
Consider reworking Ascension

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1610]
We should change Ascension to give temporary levels based on how many bosses the player has killed instead of permanent levels based on how many bosses the player kills while they have Ascension. 

This change will have 2 main benefits:
1. Retraining Ascension will no longer let the player keep the bonus levels. (This stretegy was very prevalent in the last tournament)
2. Players will be able to pick Ascension at any point in the game and get full value from it.

**Comment by fcalife** [comment]
I don't know of any straightforward way to 'delevel' heroes though.

What happens to their skill points? In what order are they lost? Which skills are deleveled?

**Comment by Draze22** [comment]
> What happens to their skill points? In what order are they lost? Which skills are deleveled?

Don't remove skill points.

**Comment by fcalife** [comment]
so they just lose stats?

**Comment by Draze22** [comment]
Yes.

**Comment by fcalife** [comment]
to be accurate, this would have to consider all stat bonuses based on level, such as the hero's own stat growth, late bloomer, all 3 flesh heaps, etc.

**Comment by Draze22** [comment]
If it's too hard that's fine.
