### ISSUE TITLE
Consider making rank reset previews more detailed

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1613]
Specifically add values to the reward previews:

![image](https://user-images.githubusercontent.com/63279022/134795646-42f3e09c-fd36-4336-8300-1fabda498c72.png)

![image](https://user-images.githubusercontent.com/63279022/134795655-0383bcf9-2f6d-410a-a5bd-3cdd12d2d855.png)

![image](https://user-images.githubusercontent.com/63279022/134795665-14f3d903-f835-43d5-b873-cf52fbfdd7a1.png)

**Comment by ZLOY5** [comment]
Anyone can give actual values for that?

**Comment by Draze22** [comment]
> Anyone can give actual values for that?

https://docs.google.com/spreadsheets/d/1wt1nFtWQcliKtCE1padIB-CNJcclOL8TFQCQ28IdSRY/edit#gid=1191227592

Season Reset tab, not sure if it's fully up to date though.
