### ISSUE TITLE
beastmaster axes + aghs + curses = no cooldown

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1614]
Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/891595324706136064)

**Comment by ArcadiaReduxAutomation** [comment]
can be used to use it again before the axes return

Comment from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/891595400795025450)

**Comment by Draze22** [comment]
Duplicate
