### ISSUE TITLE
Reincarnation doesn't work properly (Enfos)

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1616]
![image](https://user-images.githubusercontent.com/63279022/134803065-4f42da34-7793-447e-b8bc-14e94980eb7a.png)

**Comment by Draze22** [comment]
It works properly in 1v1 duels interestingly.

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/134804322-0214e0c3-2971-4414-9aa3-fddb4ca1eab9.png)
i wonder why lol
i've commented that out for single duels in the past, guess forgot to do the same for team duels
