### ISSUE TITLE
Fix Late Bloomer and Ascension in Enfos

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1618]

**Comment by SanctusAnimus** [comment]
There are boss rounds though? Every 10th round. Also removing mastery completely is kinda bad, for players that have small amounts of them unlocked and leveled. I'd much rather tweaked them for enfos

**Comment by Draze22** [comment]
> There are boss rounds though? Every 10th round. Also removing mastery completely is kinda bad, for players that have small amounts of them unlocked and leveled. I'd much rather tweaked them for enfos

Oh right nvm, they just need to be fixed in Enfos since they don't work.

**Comment by fcalife** [comment]
Fixed in https://github.com/arcadia-redux/custom_hero_clash/commit/163cf684ea98918e3fd48c5edf37019aac128c03

**Comment by fcalife** [comment]
@SanctusAnimus feel free to claim this since I didn't notice it was assigned to you

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/135250356-e2b92258-a9f6-4022-a9a7-f2eaaf2f113d.png)

**Comment by Draze22** [comment]
No reports of Ascension not working.

**Comment by SanctusAnimus** [comment]
Why you reopened if fix wasn't uploaded??? @Draze22

**Comment by Draze22** [comment]
Because someone reported it not working after the update.

**Comment by SanctusAnimus** [comment]
after which? fix was pushed 5 hours ago, last update in chc was nearly 20 hours ago

**Comment by Draze22** [comment]
My bad, thought we Uploaded for some reason.
