### ISSUE TITLE
MMR rounding errors (Enfos)

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1621]
![image](https://user-images.githubusercontent.com/63279022/134803955-91bcb320-156a-4a0c-bb8e-b7a0a94eae17.png)

**Comment by SanctusAnimus** [comment]
It always worked like that, eh? It's not like it's flat +-30 for win/loss

**Comment by Draze22** [comment]
> It always worked like that, eh? It's not like it's flat +-30 for win/loss

Yes but it makes no sense for one team to lose 30 and the other to gain 29.

**Comment by SanctusAnimus** [comment]
Well your team has more mmr on average, what do you expect

**Comment by SanctusAnimus** [comment]
To be clear - current formula is `base_change + round( (average rating - player current rating) * 0.02 )`, with round result being clamped between -20 and 20. Average rating is either all others player average, or enemy team average, whichever present in aftermatch request sent by custom game. It works like that for every map, only base change varies (being +30 / -30 for enfos)

**Comment by SanctusAnimus** [comment]
now that your party is more then 100 mmr above default value, you gain even less, so it works as intended
![image](https://user-images.githubusercontent.com/43399078/134806806-c418655d-9983-4b51-a86e-fee5da9cc278.png)

**Comment by Draze22** [comment]
> now that every member party is more then 100 mmr above default value, you gain even less, so it works as intended. 5th dude has 1443 so he gained more for that win

mmr is based on the lobby average so if we gain 29 they should lose 29.

**Comment by SanctusAnimus** [comment]
no? mmr is based on lobby average AND your own mmr. i've even sent formula, that also present on all sheets with mmr calculations
say avg is 1515, you have 1600, for victory you gain +30 + round(|1515 - 1600 * 0.02| = -1.7) = +30 - 2 = 28
loser has 1500, for losing he will get -30 + round(1515 - 1500 * 0.02 = 0.3) = -30 + 0 = -30

mmr gains and loses won't be even when noones personal mmr is even

**Comment by SanctusAnimus** [comment]
And as i said, it always worked like that, how's that a news for you, when you even participated in making those formulas

**Comment by SanctusAnimus** [comment]
you can even see how winner mmr gain declines over the course of matches, cause he's above lobby's average
![image](https://user-images.githubusercontent.com/43399078/134812289-a5195a3b-d294-49a8-8166-4b363572c150.png)

but it doesn't mean that loser loses less, if he's close to average, or even above it. It might make loses lose less when he's winner mmr is so much above average it outweights everyone else (i.e. dudes with 10k mmr in ffa), but that's an edge case, and impact from avg mmr difference is limited to [-20 : 20]

**Comment by Draze22** [comment]
Everyone on the same team has the same mmr here, either the formula isn't symmetrical for positive and negative gain or there's a rounding error. Either way it should be fixed.

**Comment by SanctusAnimus** [comment]
What? Average is calculated on mmr of all players, from both teams, except player himself, it's working correctly. Ask aimc, idk how else i can explain it so you can understand, i even written calculations to you. You gained less cause you have more mmr then LOBBY average, they gained default cause they are close enough to that same LOBBY average. Your party gets same mmr increase, cause indeed you have same mmr.

**Comment by SanctusAnimus** [comment]
i can't replicate it rounding wrong value with numbers as above, math was right from the beginning, so i blame whatever else.
this stays closed
