### ISSUE TITLE
Rework Bash of the Deep to have a 1.5s cooldown in Duels

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1623]
Means it's not perma bash even against players with no status resistance. To be clear the 1.5s cooldown would be for proccing the bash not for gaining charges.

**Comment by Osamabinfrank** [comment]
Its already pretty easy to counter, is this nerf rly necessary? There is helbard, silver edge, guardian helm, shadow realm, shadow dance, ghost, eblade, viper w, doom, demonic purge, chrono and plenty of more items and abilities to counter right clicker perma bash builds

**Comment by Snoresville** [comment]
yeah this is really unnecessary

**Comment by Draze22** [comment]
People hate being perma bashed, it's not about it being op.

**Comment by Snoresville** [comment]
i dont like it when i get nuked by a blitz strike dagon, but i can counter it

**Comment by Draze22** [comment]
The fact that Bash of the Deep can still mini stun you twice per second, resetting your queued actions even when you have 75% status resistance is still very frustrating even though you've "countered" the perma bash.

**Comment by SanctusAnimus** [comment]
@Draze22  Does it still "needs discussion" or i can implement that?

**Comment by fcalife** [comment]
LGTM as long as it remains the same in pve
