### ISSUE TITLE
Damage Breakdown doesn't work properly

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1630]
It's very inconsistent, sometimes it works fully, sometimes it only shows some hero's damage (I experienced 3 from each team), other times (mostly during duels) it doesn't show anything.

**Comment by SanctusAnimus** [comment]
> sometimes it only shows some hero's damage
it only shows damage of heroes that actually dealt damage, if hero stayed afk for the whole round, then he won't be shown.
Rest i'll fix soon

**Comment by SanctusAnimus** [comment]
Also it is disabled during duels, on all maps, i don't think it should pop up on duels even in enfos
