### ISSUE TITLE
add some vision on the enfos map with fog enabled

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1631]
Add permanent vision on the following spots on your team's side of the map:
- [ ] Creep spawns (both), 900 radius
- [ ] Treasury (both), 1800 radius
- [ ] Shrines (all of them), 900 radius
- [ ] Creep objective (center portal), 1800 radius
- [ ] Side portals (all four), 900 radius

Plus:
- [ ] Add permanent vision, for both teams, of both pvp arenas in their entirety.
- [ ] Add permanent fogvision of the enemy heroes (disabled if they are invisible)

We will handle adding more vision on the enemy side of the map by tweaking wizard spells accordingly with this change.

**Comment by ZLOY5** [comment]
Maybe just fully reveal team's island for team?

**Comment by fcalife** [comment]
that's fine too
