### ISSUE TITLE
Multicast sometimes doesn't work

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1635]
Seems to have started recently where some/all abilities don't multicast.

![image](https://user-images.githubusercontent.com/63279022/134893466-652d6170-90b9-40da-9026-85db3c5cefdc.png)

![image](https://user-images.githubusercontent.com/63279022/134893673-484c9d62-9644-400e-bf31-7a1cf6752cb0.png)

![image](https://user-images.githubusercontent.com/63279022/134894729-f6d183c1-ccfa-491c-a237-ab70a0e011ea.png)

**Comment by SanctusAnimus** [comment]
it's already fixed, not uploaded
