### ISSUE TITLE
Enfos parity issues megathread

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1639]
issues which arrise when innates/masteries/etc are ported into enfos

Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/870345695331221574/892255593606291456)

**Comment by ArcadiaReduxAutomation** [comment]
level 2 of revenge causes players to be invulnerable forever

Comment from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/870345695331221574/892255648325177424)

**Comment by Draze22** [comment]
> level 2 of revenge causes players to be invulnerable forever
> 
> Comment from Discord by **Australia Is My City#9760**
> Follow the conversation [here](https://discord.com/channels/501306949434867713/870345695331221574/892255648325177424)

Fixed.
