### ISSUE TITLE
Devour can't kill creeps after round 6

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1641]
Devour should be able to kill/target all creeps except for captains and bosses.

![image](https://user-images.githubusercontent.com/63279022/135028215-904478c1-4133-4b23-8e5b-c69814becf08.png)

**Comment by lovro-m** [comment]
So what is to be done? Devour rewrite or creep nerf?

**Comment by SanctusAnimus** [comment]
why rewrite lol, devour has `creep_level` ability special

**Comment by lovro-m** [comment]
well how was I supposed to know that. which values are supposed to be then?

**Comment by SanctusAnimus** [comment]
you can check dota kvs [here](https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/game/dota/scripts/npc/npc_abilities.txt)
single "9999" should be enough, no point in level differences
