### ISSUE TITLE
Most Masteries are locked since last update

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1642]
![image](https://user-images.githubusercontent.com/63279022/135051199-dad4a696-fa45-402c-81fd-17e00b87a22a.png)

![image](https://user-images.githubusercontent.com/63279022/135050965-820cd354-3c99-47b4-8acc-b72eead90a23.png)

![image](https://user-images.githubusercontent.com/63279022/135051153-42fd9d82-2194-4906-92d4-93947c5af3df.png)

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/135051940-6b02f972-9198-4a4a-9838-6ba9b14f288d.png)
why i can then
![image](https://user-images.githubusercontent.com/43399078/135052487-eae4df35-6527-416e-8333-b483941d7a69.png)

**Comment by SanctusAnimus** [comment]
ok if you have revenge unlocked it breaks kek

**Comment by SanctusAnimus** [comment]
fixed by @ZLOY5
