### ISSUE TITLE
Several players aren't getting rating for winning games

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1644]
![image](https://user-images.githubusercontent.com/63279022/135068252-8b662321-4c6a-4c8f-9bad-db6a7e4e7f6c.png)

![image](https://user-images.githubusercontent.com/63279022/135068162-232b5d79-a98e-449f-a264-0ba89cfd7e49.png)

![image](https://user-images.githubusercontent.com/63279022/135068175-d6a0efcf-0fe9-4666-8d1a-d40d48c5929f.png)

![image](https://user-images.githubusercontent.com/63279022/135068206-4694db95-4058-4eda-bfb4-59a7e3bb025e.png)

**Comment by SanctusAnimus** [comment]
i'll need their steam ids
