### ISSUE TITLE
Rework Crescendo for Enfos

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1653]
It doesn't fit in Enfos very well since 1v1 duels often happen mid round allowing players to start duels with Crescendo stacks. Also there's a much less clear transition from round to round which makes Crescendo reset while fighting creeps, when in FFA and Duos it resets while not fighting creeps.

**Comment by fcalife** [comment]
These skills can be reworked to "make sense" in enfos. I'd rather do that than remove them entirely.

For example, crescendo could (specifically in enfos) reset on duel start, never reset otherwise, and have a cap.

**Comment by SanctusAnimus** [comment]
Is there an exact number for cap? @fcalife

**Comment by fcalife** [comment]
300 stacks is probably more than enough

**Comment by SanctusAnimus** [comment]
Should i put note about it somewhere? i don't see much space in mastery UI, repeating it 3 times is kinda strange
![image](https://user-images.githubusercontent.com/43399078/136669134-ee0549f1-267d-4af2-9d20-ccedae97c6a1.png)
