### ISSUE TITLE
Give Book of Shadows a round based charge limit of 3 to prevent abuse

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1655]
Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/892775430069821460)

**Comment by SanctusAnimus** [comment]
A bit unrelated, but why does it have "bug" label? it's an enhancement, it hadn't charges, nothing broken in current behaviour
