### ISSUE TITLE
Player managed to offer to trade an ability for an item with an enemy player

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1656]
![image](https://user-images.githubusercontent.com/63279022/135390012-95cfc8f7-5775-48b5-b8b6-025618f5cc28.png)

![image](https://user-images.githubusercontent.com/63279022/135390057-1248327a-e435-49d9-95e8-6432a3330c15.png)

**Comment by ZLOY5** [comment]
This looks like fake events

**Comment by SanctusAnimus** [comment]
This specific case should be fixed in master
