### ISSUE TITLE
There's only 15-20 seconds between rounds

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1659]
![image](https://user-images.githubusercontent.com/63279022/135399323-6e079dcc-80a7-4681-91ad-b9e37a13337b.png)

**Comment by fcalife** [comment]
it was 5 seconds, already fixed

**Comment by Draze22** [comment]
Can we upload? Enfos is currently mega mard mode.

**Comment by fcalife** [comment]
already did
