### ISSUE TITLE
Абуз рейтинга. Накручиванике рейтинга. в ЕNFOS.  Rating abuse. Improving the rating. in ENFOS.

### ISSUE THREAD

**Issue by diesel-rock** [arcadia-redux/custom_hero_clash_issues#1663]
Для победы нужно 5 человек в команде, и 1 ноутбук, Создаешь лобби, подключаешься к лобби на ноутбуке вторым аккаунтом и мешаешь играть, подбираешь все вещи у соперников, или просто выходишь из игры. Два раза попадался на это, покидали игру сразу 2 человека. Пожалуйста придумайте решение проблемы.

To win, you need 5 people in the team, and 1 laptop, You create a lobby, connect to the lobby on a laptop with a second account and interfere with the game, pick up all the things from your opponents, or just leave the game. Twice I got caught in this, 2 people left the game at once. Please come up with a solution to the problem.

**Comment by jakmarles** [comment]
![image](https://user-images.githubusercontent.com/13220259/135668453-e37a07a7-87e1-48cc-863b-2402f4d3443a.png)
Кому нужен ноутбук Когда можно запустить 10 аккаунтов на 1 компе ?

Who needs a laptop When you can run 10 accounts on 1 computer?

**Comment by jakmarles** [comment]
Кому нужен ноутбук Когда можно запустить 10 аккаунтов на 1 компе ?

Who needs a laptop When you can run 10 accounts on 1 computer?

**Comment by Draze22** [comment]
We'll be changing the Treasury soon to help prevent things like this.
