### ISSUE TITLE
Bots shouldn't toggle bulwark on unless they have aghs

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1668]
Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/802155090608783371/894145013720686623)

**Comment by Osamabinfrank** [comment]
And Chakram&Second Chakram. It works like bulwark. The bot throws it away and cant attack sometimes resulting in just standing still just like the bulwark. Basically a death sentenced to a dced person
