### ISSUE TITLE
Global skills can proc things like aeon disk globally.

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#167]
Thundergod's wrath doesn't deal damage to other players in other arenas, but for some reason the game still counts that damage as dealt to you for things like raindrop and aeon disk and can proc them.

Other global skills such as wrath of nature and nimbus might also do the same thing.

┆Issue is synchronized with this [Trello card](https://trello.com/c/B6QMGC4g) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
I'm not sure if this can be avoided without a rewrite of Aeon Disk/raindrops. @SanctusAnimus @Sheodar do you see a way?

**Comment by Draze22** [comment]
A temporary solution would be to remove global abilities since they are pretty bad anyway.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/85087985-4e450600-b222-11ea-883a-fc08bd3a16b4.png)

Another reason to remove global spells either permanently or until they can be properly coded to not cause bugs like this.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/87867393-ae6cca80-c9cf-11ea-8980-b3a4f15ebf73.png)

**Comment by fcalife** [comment]
Fixed in Aeon Disk's case

**Comment by Draze22** [comment]
Either this fix stopped working or it didnt account for powershot's aghs shard.

https://discordapp.com/channels/694060511209324585/694440472273354762/866030605514965022.
