### ISSUE TITLE
Naga Siren's evasion talent broken (unconfirmed)

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1675]
naga's 40% evasion talent is not working (unconfirmed)

Opened from Discord by **Willowisp#3862**
Follow the conversation [here](https://discord.com/channels/501306949434867713/802155090608783371/894970073884803072)

**Comment by SanctusAnimus** [comment]
visual only, happens to most talents, thanks valve:tm:
