### ISSUE TITLE
unknown unverified reroll bug

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1676]
one report of someone rerolling their skills and getting no replacement

Opened from Discord by **Willowisp#3862**
Follow the conversation [here](https://discord.com/channels/501306949434867713/802155090608783371/895183144880316436)

**Comment by Draze22** [comment]
We get quite a few reports of this happening but never why it happened. It also often fixes when the player reconnects to the game.

**Comment by SanctusAnimus** [comment]
This and a few other ability bugs are tied to server lags, when it just discards pending client events. Closing for now as not much can be done here
