### ISSUE TITLE
Speed of Thought lvl 3 doesn't allow casting spells without turning around

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1685]
At this point since Speed of Thought is a very strong mastery i'm happy to just remove this aspect of it.

**Comment by SanctusAnimus** [comment]
it does though? kinda. hero still turns around, but after the cast, not sure we can fix that properly. 

https://user-images.githubusercontent.com/43399078/136668173-9b8ccb9b-6141-4356-bed4-e2eeb1f42f39.mp4


So what do we do, remove that thing entirely?

**Comment by SanctusAnimus** [comment]
ok
