### ISSUE TITLE
rework librarian

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#1687]
due to selecting innate after selecting 2 abilities, librarian is kinda trash, so instead of giving it an excessive number of ability selections, we should give the player 2 unsellable, un-transferable (unable to give to allies) tomes of retraining

Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/896393959931269210)

**Comment by fcalife** [comment]
amended:

- grants one single-use book that resets all your abilities - essentially nukes your build (does not reset innate or masteries), and lets you start again, with grand librarian's benefit
- book sells for 200 gold, and cannot be acquired by any other means
