### ISSUE TITLE
Armor/damage reduction buffs stack until complete damage immunity

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1689]
![image](https://user-images.githubusercontent.com/63279022/136677699-c91c2726-e84e-46b9-9a9f-b73a0ec65d69.png)

![image](https://user-images.githubusercontent.com/63279022/136677700-dbeb4a86-51e8-44a0-bba9-4e34e414ecbd.png)

**Comment by Draze22** [comment]
In short these buffs should be multiplicative instead of additive.

**Comment by fcalife** [comment]
obsolete due to aura being reworked into personal buff
