### ISSUE TITLE
allow to pre-pick masteries (still activate only at the proper round)

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1701]
prob Enfos-exlusive problem atm,
to pick masteries (at what feels like – a «random point in time»), sometimes during duel,
players are forced to cover the entire screen with the ui-dialog,
which is prone to unintended consequences, like dying

**Comment by Sheodar** [comment]
Implemented (need wait some time for this update ingame)
