### ISSUE TITLE
Using Book of Divinity prevents using Book of Paragon

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1704]
I'm not exactly sure how this is supposed to work, but my understanding was that Book of Divinity allows having 7 abilities total.

**Comment by dym-sh** [comment]
i have used several Divinity books in one game on the same hero (there is `9` on its cover, so i guess it allows up to 9 abilities)

but yes, using Divinity before Paragon will make paragon book unusable (since it checks if you have _6_ spells prob?), but still purchasable
