### ISSUE TITLE
Death Sentance doesn't work at all now

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1721]
![image](https://user-images.githubusercontent.com/63279022/137568574-877a1405-add3-45e6-b59b-61daeef660d4.png)

**Comment by ZLOY5** [comment]
This sholid be fixed in https://github.com/arcadia-redux/custom_hero_clash/commit/7e77f3f003e2b43cdd485845ca2130d2e60770ed
