### ISSUE TITLE
Gale Force affects players in other arenas

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1724]
A temporary fix would be reducing the cast range to 1800 (although because the radius is so big it might have to be 1200).

![image](https://user-images.githubusercontent.com/63279022/137609263-8ae51705-fed9-4d7d-aa39-e7a3c26f46cf.png)

**Comment by Osamabinfrank** [comment]
God damn it somebody finally leaked it
