### ISSUE TITLE
Switcheroo often breaks

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1732]
Would be nice if someone redesigned the innate since we've had to fix it several times and it still breaks a lot when switching from melee to ranged with things like meta, berserkers rage and shapeshift.

![image](https://user-images.githubusercontent.com/63279022/137895930-39aae882-c9b4-4dee-b70f-e4b9d7253dab.png)

![image](https://user-images.githubusercontent.com/63279022/137895970-8bd4a7b1-6113-433a-91db-93a72f686ca2.png)

**Comment by SanctusAnimus** [comment]
I vaguely remember switcheroo been changed not so long ago? Is this still relevant?

**Comment by Draze22** [comment]
No it's not now that we changed it.
