### ISSUE TITLE
Brainstorm some summon related masteries

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1743]
Several players including Baumi have asked for some Summon masteries, I'm thinking we should come up with 2-3 of them for now. Keep in mind Masteries are meant to be simple and primarily improve existing playstyles, not create new ones.

**Comment by Osamabinfrank** [comment]
You forgot to mention that you suggested it and its not a random one. Summoners are already kinda op. Soul link lifesteal is op as f adding even more masteries will completely make all of them op. There already plenty of masteries which works amazing on a summoner

**Comment by Draze22** [comment]
> You forgot to mention that you suggested it and its not a random one. Summoners are already kinda op. Soul link lifesteal is op as f adding even more masteries will completely make all of them op. There already plenty of masteries which works amazing on a summoner

We can always nerf Crown if summons get op, we're trying to make summons more interesting and strategic.

**Comment by dym-sh** [comment]
> you suggested it

not exactly, no:
https://discord.com/channels/694060511209324585/694440509883547668/903628606566195231
i only relayed the message to the bot with extended wording

**Comment by Osamabinfrank** [comment]
> > You forgot to mention that you suggested it and its not a random one. Summoners are already kinda op. Soul link lifesteal is op as f adding even more masteries will completely make all of them op. There already plenty of masteries which works amazing on a summoner
> 
> We can always nerf Crown if summons get op, we're trying to make summons more interesting and strategic.

Yes but it will also hurt the community, if you add paid content and in result nerf crown, newbies and f2p might stop building summners, its already not the best but a viable build strategy  for newbies and f2ps who can't do math

**Comment by dym-sh** [comment]
more interesting and strategic would imply bigger variety of viable impactful spells (esp early) and utility items, instead of just piling crowns and spamming Eidolons/Spiders via Magus

**Comment by Draze22** [comment]
Closing this since there's no more activity, if people have ideas they can re-open the issue or add them to #658.
