### ISSUE TITLE
Ex Machina is the best Neutral Item despite using vanilla values

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1746]
The next best Tier 4 Neutral Item is Giant's Ring which on average is 2 rounds worse in FFA and 3.5 rounds worse in Duos.

We have 3 main solutions:

1. Do nothing, accept it's the best and hope people don't care too much.
2. Nerf the item to make it worse than in vanilla Dota.
3. Move the item to tier 5.

**Comment by chariot-afv** [comment]
Refreshing BKB, hex, silences, ghost scepter etc is invaluable in duels. 3rd option, item is strong and deserves tier 5 status.

**Comment by Draze22** [comment]
Solved since it's now a tier 5 neutral item.
