### ISSUE TITLE
Big Game Hunter sometimes chooses the wrong target in Duos duels

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1749]
Might just be due to only 1 enemy being in range at the start of the duel, if so we can simply increase the range of the ability to 1800.

This video shows Big Game Hunter on the Drow who has lower max hp than Bristleback: https://www.youtube.com/watch?v=CQAX2Xr5Bls

![image](https://user-images.githubusercontent.com/63279022/138797774-6f5fd624-7b54-496b-8328-c65bc232e50e.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.
