### ISSUE TITLE
You can use a book of retraining after someone proposes an ability swap

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1751]
![image](https://user-images.githubusercontent.com/63279022/138847424-fafe1803-0117-47ca-a804-6ec57463b1c6.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.
