### ISSUE TITLE
Treasury items spawning should come from the same seed for both teams

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1753]
otherwise boost for 4k/12k exp creates an "instant" win condition by pure chance,
with basically no way to recover after a single 5v5.
everything becomes one-directional and pointless, just wait for the other side to quit.
(potentially remove exp-boosters all-together)

![exp boost](https://user-images.githubusercontent.com/59403389/139289966-f9af7a65-718c-4813-95f5-29cc23573c77.jpg)

**Comment by dym-sh** [comment]
sure, not every time it's so extreme, but also not too out of ordinary to have 10+ levels discrepancy before second 5v5:
![8-22](https://user-images.githubusercontent.com/59403389/139632539-c9579aee-ae58-4bad-80c8-2e77ed1c80c8.jpg)

**Comment by dym-sh** [comment]
maybe add passive tick of like 5 exp per sec so games won't end before lvl 6 b/c of raw creep pressure

**Comment by dym-sh** [comment]
im not sure why this was closed? this feature is not in any way balanced, nor counterable, nor even predictable

![20220317055032_1_20220317045033](https://user-images.githubusercontent.com/59403389/158771433-79413bdb-23d3-4075-8e3d-c32bbdd57992.jpg)

**Comment by jakmarles** [comment]
Its an rng based game.
