### ISSUE TITLE
Spamming Spiderlings and Eidolons (via Magus) causes huge lag and fps drop

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1754]
50+ Spiderlings and Eidolons created by spam spawing (through Magus inate) are the biggest lag/fps bottleneck atm

proposing same treatment as for Shaman's Wards and multicast

![spawners lag and fps drop](https://user-images.githubusercontent.com/59403389/139291623-5ac9646d-c66b-46ce-99ab-066921d3e00c.jpg)

**Comment by Draze22** [comment]
Firstly we can try giving them the Omnislash treatment and always give them the duel cooldown.

**Comment by dym-sh** [comment]
it still can come to the same number of spawns when several heroes on the map have those spells,
so compacting them into lesser amount of more powerful units is generally a good practice anyway
