### ISSUE TITLE
Abilities swap getting stuck in intermidiete state

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1755]
pictured: two previous swaps persist and cant be interacted with

(might something to do with moving positions of abilities, or duels, or both players proposing swap at the same time? no idea)

![abilities swap stuck](https://user-images.githubusercontent.com/59403389/139294110-047aa6b6-4d32-453c-82cb-393306bd2924.jpg)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.
