### ISSUE TITLE
Switcheroo makes Marci deal no damage

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1760]
![image](https://user-images.githubusercontent.com/63279022/139392218-326b35d6-89a5-411a-8626-1ee23af0870d.png)

**Comment by lovro-m** [comment]
how did you replicate this? I went into enfos, picked marci, chose switcheroo and she's throwing rocks normally and hitting for exactly the right damage.

**Comment by SanctusAnimus** [comment]
certainly not because it's already fixed lol
![image](https://user-images.githubusercontent.com/43399078/139485539-8d79827d-e1ff-46ae-93b8-153de359f5bb.png)

**Comment by lovro-m** [comment]
...
