### ISSUE TITLE
Apply the Tinkerer fixes from 12v12

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1761]

**Comment by lovro-m** [comment]
I'm looking at the code for the fix and it takes some percentage of current mana of the target for witchbane. Shouldn't it be from max mana of the target?

**Comment by Draze22** [comment]
> I'm looking at the code for the fix and it takes some percentage of current mana of the target for witchbane. Shouldn't it be from max mana of the target?

Yeah, looks like Sheodar just fixed it for 12v12 and Overthrow.
