### ISSUE TITLE
Natural Order doesn't affect elites

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1762]
![image](https://user-images.githubusercontent.com/63279022/139566097-23134b41-eacb-48e0-8d38-c8f4e38506db.png)

**Comment by lovro-m** [comment]
I would like to point out that I tested in vanilla and et aura does not affect ancients there also. I also see that there is a bug with magic resist lowering if you're not et. I can do a complete rewrite if we want that.

**Comment by Draze22** [comment]
I think it's fine for now.
