### ISSUE TITLE
Games sometimes use the regular Dota map

### ISSUE THREAD

**Issue by Ninjacexe** [arcadia-redux/custom_hero_clash_issues#1768]
Screens:https://steamcommunity.com/sharedfiles/filedetails/?id=2645371129
https://steamcommunity.com/sharedfiles/filedetails/?id=2645371095
https://steamcommunity.com/sharedfiles/filedetails/?id=2645371054

**Comment by whoapple** [comment]
same problem

**Comment by whoapple** [comment]
I got banned for an hour

**Comment by CaramBit23** [comment]
I have same problem
![2020111221144356_1](https://user-images.githubusercontent.com/93740932/140424635-62345572-1ebb-4187-be6c-fa7163b8cc29.png)
![20201122144356_1](https://user-images.githubusercontent.com/93740932/140424647-277e2a01-0241-4b72-8aaf-5beff6b198ce.png)
![202111221144356_1](https://user-images.githubusercontent.com/93740932/140424655-a4437ac3-082e-4b69-bbe1-9101091fe564.png)

**Comment by Draze22** [comment]
This can only be avoided by either:
1. Creating your own lobby.
2. Use the lobby list to join a lobby that's either FFA, Duos or Enfos and not dota or dota_683.
