### ISSUE TITLE
Add an option to keep playing after your team wins

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1771]
![image](https://user-images.githubusercontent.com/63279022/140594664-58d8c5a0-91db-426c-bc67-f8b119c2485a.png)

**Comment by ZLOY5** [comment]
@Draze22 any thoughts how it should looks like?
Like  voting for game ending or opposite to it - voting to keep playing. Or they just keep play before lose without any votings?

**Comment by Draze22** [comment]
> @Draze22 any thoughts how it should looks like? Like voting for game ending or opposite to it - voting to keep playing. Or they just keep play before lose without any votings?

It should work basically the same way it does in FFA and Duos. A screen appears displaying that your team won, how much mmr you gained and gives you two options "keep playing" or "finish game" as shown below.

![image](https://user-images.githubusercontent.com/63279022/151294541-6909ef1d-dfcf-4929-9f7c-0fa8e07b8e2d.png)

**Comment by ZLOY5** [comment]
I.'m just not sure how Finish Game button should work, because we have 5 players in team and any of them can click it

**Comment by Draze22** [comment]
> I.'m just not sure how Finish Game button should work, because we have 5 players in team and any of them can click it

For now we can copy the way Duos does it, if any player clicks Finish Game, the game ends, otherwise they can keep playing.
