### ISSUE TITLE
Lobby bug

### ISSUE THREAD

**Issue by fortuna21101998** [arcadia-redux/custom_hero_clash_issues#1775]
Something wrong with lobby. When there are already 10/10 it become 4/1 and the game starts. But it's a buggy dota with an old dota 2 map. And everyone who got in this trap is banned because of leaving(it consider you abandoned the game since the game has started). Fix it please

**Comment by dym-sh** [comment]
/related https://www.reddit.com/r/DotA2/comments/qnr52v/banned_from_queuing_for_1_hour_because_a_4_stack/

**Comment by dym-sh** [comment]
#1768
