### ISSUE TITLE
Wrong mode selection with punishment for leaving from game

### ISSUE THREAD

**Issue by Alezzeyka** [arcadia-redux/custom_hero_clash_issues#1779]
Sometimes when searching the game it can took you for mode with standard map and active punishment for leaving this game, in any case you would have  temporary block in game neither custom or standard modes. I have this 3 times for the last 2-3 days. It's very dissapointing. IDK why it's reproducing exacly, need to be tested.

**Comment by fcalife** [comment]
Post on reddit. This is a dota 2 arcade issue.

**Comment by Alezzeyka** [comment]
Ok
