### ISSUE TITLE
Make Heroes deal bonus damage to Tombstone

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1783]
Double the amount that heroes deal to MSW since it has roughly double the hp.

**Comment by Draze22** [comment]
Wait nvm, heroes already deal 4x damage to Tombstone which is probably enough.

**Comment by Osamabinfrank** [comment]
> Wait nvm, heroes already deal 4x damage to Tombstone which is probably enough.

Judging by my own gameplay i wasn't able to destroy a tombstone even once after round 40. Even with 2087 (0.08) attack speed
