### ISSUE TITLE
Expose debuffs aren't removed when Spirit Bear dies

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1794]
![image](https://user-images.githubusercontent.com/63279022/142130056-c1773d4d-d09d-48fe-baba-24f75800f1f5.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.
