### ISSUE TITLE
[FFA] WARNING OUTSIDER CREATE CRASH LOBBY 

### ISSUE THREAD

**Issue by MoonLad** [arcadia-redux/custom_hero_clash_issues#1799]
Outsider create crash lobby with autobot ib the role host player. 
As a result, an endless game. If exit = ban 1 hour or more.
![image](https://user-images.githubusercontent.com/41289274/142519082-ca9b3cc1-631e-4834-8777-f68735ed5657.png)
PLEASE FIX

**Comment by Osamabinfrank** [comment]
Fix how?
