### ISSUE TITLE
Tempest Double doesn't get Wukong's Command

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1809]
![image](https://user-images.githubusercontent.com/63279022/144345956-2169ee36-e928-4da6-afad-d0ec9ac988a2.png)

![image](https://user-images.githubusercontent.com/63279022/144345978-cf4bd9ca-d625-41ae-bbed-e22cf92eb710.png)

**Comment by SanctusAnimus** [comment]
Intentionally, to avoid immense lags and bugs. Maybe someone should add a note to wukong command about it
