### ISSUE TITLE
Magus with spells that can be unit target but don't have to be

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1810]
There's a bunch of abilities like Acorn Shot, Spectral Dagger, etc that could work with Magus but don't because they're not fully classified as a unit target ability. Would it be possible for us to allow them to work with Magus?

**Comment by ZLOY5** [comment]
Acorn Shot and Spectral Dagger definitely works, if you want check more abilities use [magus_spells](https://github.com/arcadia-redux/custom_hero_clash/tree/magus_spells) branch and then merge it when you done
