### ISSUE TITLE
Casting Fiend's Grip on an enemy affected by Lotus Orb while untargetable crashes the game

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1811]
![image](https://user-images.githubusercontent.com/63279022/144347536-56eae269-9d9e-4043-b77d-34903db2bfa3.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.
