### ISSUE TITLE
How to nerf Rearm + Ghost Scepter

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1819]
Rearm + Ghost Scepter was extremely prominent in the most recent CHC tournament and imo needs to be severely nerfed.

The main issue with this combo is with 1 ability any player can be invulnerable to creeps until they get 8 curses (or go significantly into overtime). 

Potential solutions:

1. Increase the channel time of Rearm from 3.5/2/1.25 --> 4.5/3.5/2.5. This will reduce the number of curses required to make this combo not give invulnerability to 3-4 curses, makes rearm weaker in duels and makes rearm builds slower to finish waves (they get less gold each round).
2. Give Rearm 1/2/3 or 3/3/3 charges per round. This limits Rearm + Ghost Scepter to 16 seconds of invulnerability against creeps and significantly nerfs rearm overall.
3. Prevent Ghost Ethereal effects (Ghost Scepter/Eblade/Decrepify/Ghost Shroud) from being rearmed. This completely removes the ability of Rearm + Ethereal to make players invulnerbale to creeps without nerfing Rearm's other strengths.
4. Do something weird like making Ethereal effects have reduced duration each time they're used on a player who is already affected by Ethereal. This would do the same thing as option 3 for most players but still allow good players to time it well and only take a few hits between each use of Ethereal (more complicated but less severe version of option 3).
5. Add rounds that deal significant amounts of magic damage through Ethereal or more rounds that can Dispel the player (add more rounds that counter Ethereal).
6. Give Rearm a cooldown of 5 seconds.

**Comment by Draze22** [comment]
My vote is on 5 long term and 1 or 2 short term.

**Comment by Osamabinfrank** [comment]
Cant you lower the duration of the ghost scepter with every curse they get

**Comment by Draze22** [comment]
> Cant you lower the duration of the ghost scepter with every curse they get

Yes, but it doesn't make sense for only Ghost Scepter to be affected like that, instead the option would to make all buffs have a shorter duration with each curse. Also I don't like that option much since without curses it's still just as strong.

**Comment by jakmarles** [comment]
> > Cant you lower the duration of the ghost scepter with every curse they get
> 
> Yes, but it doesn't make sense for only Ghost Scepter to be affected like that, instead the option would to make all buffs have a shorter duration with each curse. Also I don't like that option much since without curses it's still just as strong.

then maybe its time to add dispel to creeps? or add new dispel creeps. there are only 1 creep wave that can dispel iirc

**Comment by Draze22** [comment]
> then maybe its time to add dispel to creeps? or add new dispel creeps. there are only 1 creep wave that can dispel iirc

See option 5.

**Comment by jakmarles** [comment]
> > then maybe its time to add dispel to creeps? or add new dispel creeps. there are only 1 creep wave that can dispel iirc
> 
> See option 5.

missed it, opinion 5 seems like a good idea especially after round 40

**Comment by jakmarles** [comment]
any updates regarding this? its super annoying to play against rearm ghost mages. they easily survive 8 curses while if you do a mistake on a non mage build you are most likely dead. kinda op.
