### ISSUE TITLE
[Suggestion] nerf / remove money related Innates / masteries 

### ISSUE THREAD

**Issue by Osamabinfrank** [arcadia-redux/custom_hero_clash_issues#1822]
Please nerf / remove money related Innates / masteries . They completely ruin the game for others and way too overpowered..
Thru all the tournaments you could see ton of goldfingers, capitalists and gamblers.
Those are just broken..
The inflate the game economy way too hard. And completely ruin great aspects of the game.
Betting without those is completely ruined when you risk 2k gold just to get 300 gold while the gambler bet 1700 and gets 900 gold (just an example) the more money you get the more you can bet and the less everyone else gets. Capitalist was picked 6 times in the finals..
Removing those would be the best outcome imo although i use those every game i play since they are so overpowered

**Comment by Draze22** [comment]
Done.
