### ISSUE TITLE
Aether Remnant doesn't disappear after it finishes pulling its targets

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1823]
This allows it to affect new enemy units that walk into its radius.

![image](https://user-images.githubusercontent.com/63279022/145746232-8e7b5aad-460c-4a97-b9bd-4383db4770e5.png)

**Comment by SanctusAnimus** [comment]
It's intentional, we discussed that when it was developed

**Comment by Draze22** [comment]
> It's intentional, we discussed that when it was developed

I thought what we discussed was letting units that walked into Aether Remnant whiloe it was active would also get pulled (like Black Hole). 

What happens currently is after it finishes pulling in units any new ones will instantly take damage and not get pulled at all.

**Comment by SanctusAnimus** [comment]
Idk in my memory we agreed on leaving itt pulling anything for it's duration. And it should do exactly that. I'm not sure about
> instantly take damage and not get pulled at all.  

I'll check later

**Comment by Draze22** [comment]
Nevermind this does currently work as you described.
