### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by Dybrovskiy** [arcadia-redux/custom_hero_clash_issues#1831]
![изображение_2021-12-15_234821](https://user-images.githubusercontent.com/25589224/146262718-f4494e17-cdb3-4a00-b46f-1e2bb416fbe1.png)

**Comment by Dybrovskiy** [comment]
He said it had something to do with the fact that he didn't take a neutral item and bought a lot of books for an additional ability

**Comment by fcalife** [comment]
closed via https://github.com/arcadia-redux/custom_hero_clash/commit/cd788efc0e0449e973ad9ad51798509d73661edb
