### ISSUE TITLE
Cheats in game

### ISSUE THREAD

**Issue by YaRiY1** [arcadia-redux/custom_hero_clash_issues#1832]
1 man have 1 million money...
![image](https://user-images.githubusercontent.com/87314914/146267777-8bc14737-6ba7-49bc-aaf3-5c69a1e92ccd.png)

**Comment by janbohotdog** [comment]
![image](https://user-images.githubusercontent.com/96212474/146283189-10728f35-8786-489f-a6f3-f543039bd447.png)

**Comment by Draze22** [comment]
Fixed.
