### ISSUE TITLE
Lotus Orb + Mirror Shield removes the cooldown of Mirror Shield

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1836]
Мирор шилд + лотус орб бесконечная линка, 5 сифонов отражаются в секунду. 

Mirror shield + lotus orb infinite link, 5 siphons are reflected per second.

**Comment by ZLOY5** [comment]
Idk if we can fix this, both Lotus and Mirror Shield dota items, in dota demo happens same?

**Comment by jakmarles** [comment]
> Idk if we can fix this, both Lotus and Mirror Shield dota items, in dota demo happens same?

yes
that's how it work in regular dota since magic mirror was released. been using it for atleast year and a half now. so i don't really understand why its labeled here on github as a bug

**Comment by Draze22** [comment]
Yeah, closing this since it's a vanilla interaction.
