### ISSUE TITLE
Rework Speed Demon

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1837]
1. Make it unlock the max movespeed.
2. Make it give 5 movespeed per stack.
3. Don't remove or change any existing aspects of the innate

**Comment by Draze22** [comment]
Speed Demon doesn't unlock the max movespeed limit.

**Comment by ZLOY5** [comment]
![image](https://user-images.githubusercontent.com/10956575/154037314-841bb595-f9f5-4682-820f-99446a0c89ed.png)

**Comment by Draze22** [comment]
Nvm, it was a bug with changing innates in Demo Mode.
