### ISSUE TITLE
Undying's Tombstone on death talent spawns the Tombstone in other player's arenas

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1838]
![image](https://user-images.githubusercontent.com/63279022/147531361-c0dd3865-e85f-4713-bcb0-290f59748cc5.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.
