### ISSUE TITLE
Big Game Hunter stops working after Reincarnation

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1839]
![image](https://user-images.githubusercontent.com/63279022/147534920-03f1ede2-1338-457b-97d6-5cb21fdfcfb7.png)

**Comment by Draze22** [comment]
Pretty sure this is when your opponent has Reincarnation.

**Comment by jakmarles** [comment]
Its a decent way to counter that is it really a bug?
