### ISSUE TITLE
Treasury vote button disappears sometimes

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1840]
![image](https://user-images.githubusercontent.com/63279022/147622668-b4d09a52-97ed-412d-bbf9-93f9065dea82.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/148947105-ebeadc77-4e86-441c-b113-b058cef4c14f.png)

![image](https://user-images.githubusercontent.com/63279022/148947148-4823b451-f46b-443f-8964-18d0d4322aa8.png)
