### ISSUE TITLE
Player picked 2 Innates 

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1843]
Pudge has Healer as well as Momentum.

![image](https://user-images.githubusercontent.com/63279022/147849616-dfe1678c-49dc-40f0-99dc-e5360beb414e.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/147850422-ddb57653-3d1f-450d-86fb-fcd20bd7b843.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.
