### ISSUE TITLE
Warlus punch aganim's kick doesnt have cooldown if it got multicasted

### ISSUE THREAD

**Issue by jakmarles** [arcadia-redux/custom_hero_clash_issues#1845]
Warlus punch aganim's kick doesn't have cooldown if it got multicasted at least twice. basically you can keep kicking the enemy ,extremely op on range heroes against melee  
-Chupa Chups aka Beast
 giff fortune: 76561198338555053

**Comment by Draze22** [comment]
The reason this happens is if Warlus Kick is used but doesn't kick an enemy it doesn't go on cooldown, this means that if it's multicast it has to kick a unit from every cast or it won't go on cooldown.

**Comment by Osamabinfrank** [comment]
> The reason this happens is if Warlus Kick is used but doesn't kick an enemy it doesn't go on cooldown, this means that if it's multicast it has to kick a unit with every cast or it won't go on cooldown.

With multicast at level 3 you get at least x2 almost every cast.

**Comment by ZLOY5** [comment]
Can we just disable multicast for Walrus Kick?  Idk if there easy way to fix this since cooldown somehow tied into OnSpellStart

**Comment by Draze22** [comment]
Yeah that seems like the simplest solution.

**Comment by Draze22** [comment]
https://github.com/arcadia-redux/custom_hero_clash/commit/075d3a6c6464ee4bd8fa70981eed57206e98562c
