### ISSUE TITLE
Bots shouldn't be able to choose masteries for disconnected players

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1846]
![image](https://user-images.githubusercontent.com/63279022/148675397-69f02cae-e01d-40bc-b8ca-9e5ab7265c61.png)

Not sure about the double pick of blur and how that happened.

**Comment by ZLOY5** [comment]
@Draze22 they able only after player considered abandoned ( 3 minutes after disconnected for now )

**Comment by Draze22** [comment]
Maybe we need to increase the disconnect timer to 5 mins then.
