### ISSUE TITLE
Bug which hugely affects the gameplay 

### ISSUE THREAD

**Issue by Osamabinfrank** [arcadia-redux/custom_hero_clash_issues#1849]
I noticed a bug a year ago and today i decided to report it.
If you move/swap an item from stash to your main inventory during a duel the item will goes on 6 sec cd but if the item has a passive ability it will work immediately.netural Items like mirror shield, str tier 4 ring, etc will be active immediately. So does aeon disk, basher, infused raindrop, Guardian helm(status resist thing) 
This is highly abuse able and gives an unfair advantage to people who knows about it 

Giff fortune 76561198338555053

**Comment by jakmarles** [comment]
![image](https://user-images.githubusercontent.com/13220259/149954126-d29de84e-0c10-47cf-aad4-c358fc4de3a5.png)
here an image. notice the ring in cd but still gives the effect + stats
