### ISSUE TITLE
The Stash becomes unusable after a duel until the next duel

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1853]
Caused by accessing the stash directly before the duel starts.

**Comment by ZLOY5** [comment]
Sure it not fixed after last update?

**Comment by Draze22** [comment]
Reports were from after the update.

**Comment by dym-sh** [comment]
an hour ago:
![20220123093310_1](https://user-images.githubusercontent.com/59403389/150673577-8394a251-69d4-4861-8fbe-1f621b4ac390.jpg)
