### ISSUE TITLE
[enfos] casting arcane eye from PvE area into duel area will self-cast it onto your own hero instead

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1857]
![20220127211929_1](https://user-images.githubusercontent.com/59403389/151437700-0ffc7561-8975-49f8-838c-482bff794ac2.jpg)

**Comment by ZLOY5** [comment]
Seems you just missclicked

**Comment by dym-sh** [comment]
lmao have you tried it? it happens b/c of the same area issues with summons

**Comment by ZLOY5** [comment]
Yes I tried to reproduce it, and got nothing, this is also just ability so idk what can be broken there

**Comment by dym-sh** [comment]
it might have to do with specific zoom level, or hero position on the map, or the lag, idk

but it happened every time i tried it since forever ago, and i saw others self-casting it too

i'll record a video next time server is online, now no one plays it lol
