### ISSUE TITLE
Make items affected by Torture Pipe

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1860]
Approved items:

- [x] Witch Blade. 
- [x] Orb of Venom/Corrosion.
- [x] Meteor Hammer.
- [x] Dragon Scale.
- [x] Fae Grenade.
- [x] Cloak of Flames. 
- [x] Stormcrafter/Turbulent Sturmaz. 
- [x] Fallen Sky's Over Time Damage.
- [x] Teleports Behind You's Over Time Damage.

Items that need discussion:

- [ ] Giant's Ring/Colossus Ring. - Probably too strong
- [ ] Luminance. - Probably too strong
- [ ] Urn/Spirit Vessel/Torture Pipe. - To me it makes sense for these to be affected but have their base damage values toned down to compensate

**Comment by Draze22** [comment]
Need to do tooltips for this:

- [ ] Change Torture Pipes' descriptions to say increases the damage of most damage-over-time abilities and items by x/2x%.
- [ ] Add a tooltip to the affected items saying they're affected by torture pipe.

**Comment by ZLOY5** [comment]
https://github.com/arcadia-redux/custom_hero_clash/blob/master/game/resource/addon_english.txt#L5820-L5831
