### ISSUE TITLE
Burning Spears if set to autocast when retrained is still apllied on attack

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1861]
![image](https://user-images.githubusercontent.com/63279022/151695328-33539e47-ba90-4d2c-94a8-aa3ad1c5446f.png)

**Comment by ZLOY5** [comment]
After retraining only burning projectile remains, but not burning effect on target

**Comment by Draze22** [comment]
Cool, that's a very low priority to fix.

**Comment by Osamabinfrank** [comment]
![Screenshot_20220130-172040](https://user-images.githubusercontent.com/80932191/151705820-46afb908-460c-4054-aca2-0724dbacb3e4.png)
Maybe leave it be as a feature? Its been reported multiple times by now

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.
