### ISSUE TITLE
BAT reduction causes Giant Strikes to change attack speed wildly

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1868]
![image](https://user-images.githubusercontent.com/63279022/153416796-af522963-6b9a-43c5-83a2-92960ff3b122.png)

![image](https://user-images.githubusercontent.com/63279022/153416831-c9ad559e-c96d-4b4e-b5b5-f7c616f09890.png)

**Comment by ZLOY5** [comment]
First screenshot actually shows nothing wrong if we consider tooltip always show attack speed assuming hero have 1.7s BAT, so if hero have BAT lower that that value tooltip show wrong attack speed value(or not corrected according to actual BAT). 
Second should be fixed in commit
