### ISSUE TITLE
Undying's talent "Tombstone on death" gets triggered durin Reincarnation

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#1872]

**Comment by Osamabinfrank** [comment]
Yeah
It's not a bug?
It works the same way in r
Regular dota

**Comment by SanctusAnimus** [comment]
it is triggered on any death, including reincarnation as a spell, aegis or talent, and was always intended to.

**Comment by dym-sh** [comment]
it's called overpowered and auto-win combo gl countering it

**Comment by Osamabinfrank** [comment]
> it's called overpowered and auto-win combo gl countering it

Just because you are a noob doesn't mean every decent combo is overpowered.. How to counter it? Use bkb. After recent updates to tomb its extremely easy to counter..
