### ISSUE TITLE
Hunter in the Night's shard can't be used on Ancient Creeps during the night

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1875]

**Comment by ZLOY5** [comment]
Ability have note that say `Cannot be used on Ancient Creeps`, so i dont really understand what the issue

**Comment by Draze22** [comment]
In vanilla Dota it can be used on Ancient Creeps, I'd like change our version to do the same.

**Comment by Draze22** [comment]
Oh yeah, I forgot we don't differentiate between ancients and bosses, nvm then.
