### ISSUE TITLE
Tempest Double creates extra hero auras

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1880]
![image](https://user-images.githubusercontent.com/63279022/154624491-f137ce24-4d63-49ca-9583-4ecf6b7e0745.png)

**Comment by ZLOY5** [comment]
Not sure i understand this. Tempest Double should not be auras source?

**Comment by Draze22** [comment]
> Not sure i understand this. Tempest Double should not be auras source?

The Main hero has 1 copy of the aura and Tempest Double has 3-5 coppies in slightly different positions from what I've seen.
