### ISSUE TITLE
Rerolling Sticky Napalm then dealing damage with it crashes the game

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1884]
https://youtu.be/41QsKjKCMbQ

![image](https://user-images.githubusercontent.com/63279022/154803324-2be884b0-9cd9-47c1-92e5-5cf4c6fcb54f.png)

**Comment by ZLOY5** [comment]
Can't find any ways except rewrite, since Valve don't use modifier reference count in ability
Ability simple enough, so should be easy
