### ISSUE TITLE
Windrun sometimes has the wrong max charges

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1887]
3 max charges:

![image](https://user-images.githubusercontent.com/63279022/154876738-32d78790-e67a-415a-9663-53474b1693fa.png)

1 max charge:

![image](https://user-images.githubusercontent.com/63279022/154876815-c5ddfb99-de25-4f0e-b23c-71a5f93325da.png)

**Comment by Draze22** [comment]
Might be related:

![image](https://user-images.githubusercontent.com/63279022/154876938-d31ffee6-6869-4d83-ad4d-82e110c1d05f.png)

**Comment by ZLOY5** [comment]
Charges UI fixed
