### ISSUE TITLE
Make Wraith Pact's Totem affected by Summon Power

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1897]
Both damage per second and hits to kill should be affected by Summon Power.

**Comment by chariot-afv** [comment]
Should not cause any significant balance changes, it only does 25 dmg/sec base, not a lot by the time you can afford Wraith Pact, and by the time you will afford Summoner's Crown even boosted damage will be minor. Can be implemented imo.

**Comment by Draze22** [comment]
Ready for implementation.
