### ISSUE TITLE
Io's Shard 

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1900]
The bonus spell lifesteal is currently granted to Io (when it buys Shard, we should change it to be granted by Tether (with Shard) instead.

**Comment by ZLOY5** [comment]
It's already granted to all heroes with Tether

**Comment by Draze22** [comment]
Ok, after testing this, the only issue left is Overcharge with Shard should grant the player 10% spell lifesteal passively but it currently doesn't.

**Comment by ZLOY5** [comment]
Overcharge shard giving +10% spell amp when active

**Comment by Draze22** [comment]
All the time

**Comment by ZLOY5** [comment]
@Draze22 why this still opened, all heroes have +10% spell lifesteal when get Tether with shard

**Comment by Draze22** [comment]
Ah, we gave the spell lifesteal to Tether instead of Overcharge, that works.
