### ISSUE TITLE
Custom abilities that need updating

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1908]
- [x] Make Unstable Concoction give 5/10/15/20% movespeed while charging.
- [x] Update Counter Helix's Shard to match 7.31 changes.
- [x] Make Sticky Napalm's Shard work even if the player doesn't have Flaming Lasso.
- [x] Update Arcane Aura to give bonus mana on cast (the Arcane Aura talent will need to be rewritten too)
- [x] Make Devour grant 1/3/5/7 armor while digesting a creep. Also needs gold reduced to 50/100/150/200.
- [x] Update Demonic Conversion's Eidolon's to 7.31 values for turn rate, attack point and attack range.
- [x] Update Io's Spirit's Scepter to also grant 15% slow for 0.3s when impacting an enemy hero.
- [x] Update Fiery Soul to gain a stack whenever the hero damages an enemy with any spell. Also update the talent to +15/1%.
- [x] Update Flesh Heap Strength to have its new active ability (damage block). Also update the lvl 25 Flesh Heap talent.
- [ ] Update Tree Grab/Throw to match the 7.31 changes. Including the lvl 15 talent change and the change to Grow (tree bonus damage multiplier).
- [ ] Update Visage's lvl 25 Gravekeeper's Cloak talent to match 7.31 (now gives +10 armor instead of +5 stacks).

**Comment by ZLOY5** [comment]
Sticky Napalm shard works without Flaming Lasso

**Comment by ZLOY5** [comment]
Should Arcane Aura have same ability exceptions as have Skywrath Mage shard?

**Comment by Draze22** [comment]
> Should Arcane Aura have same ability exceptions as have Skywrath Mage shard?

Probably.
