### ISSUE TITLE
Sunder -34s cooldown talent doesn't visually update the tooltip

### ISSUE THREAD

**Issue by mmdts** [arcadia-redux/custom_hero_clash_issues#191]
Said this on discord a few days back, not sure if fixed yet. Putting it here to have a higher chance of being noticed.

**Comment by Draze22** [comment]
https://github.com/darklordabc/chc2issues/issues/176#issue-614626521

**Comment by Draze22** [comment]
This talent now works but doesn't show the reduced cooldown on the ability.

**Comment by Draze22** [comment]
The tooltip still shows that it has a 40s cooldown even though it has a 6s cooldown. If it's too difficult to fix I can make an ability note for Sunder explaining this.

**Comment by ZLOY5** [comment]
Ability should be rewritten from datadriven to lua to show cooldown properly
