### ISSUE TITLE
No gold, no levels, no skills 

### ISSUE THREAD

**Issue by KaiserAdel** [arcadia-redux/custom_hero_clash_issues#1910]
![20220225043447_1](https://user-images.githubusercontent.com/100382116/155603286-ebe762a4-8dda-4184-9f26-648865a889fc.jpg)
![20220225043515_1](https://user-images.githubusercontent.com/100382116/155603424-6d426c59-9177-4983-a239-2941d9dde72b.jpg)

**Comment by KaiserAdel** [comment]
Creeps/enemies don't attack me too.

**Comment by Draze22** [comment]
Fixed next update.
