### ISSUE TITLE
Charges given by talents or Aghs Shard/Scepter don't work

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1922]
Looks like all of our custom charges aren't working (only give 1 charge) but I've only tested waveform, sleight of fist and demonic purge.

![image](https://user-images.githubusercontent.com/63279022/156095659-2af93881-ca55-4e3a-b849-8c03d4566de9.png)

**Comment by jakmarles** [comment]
I was fight against a guy with the suck ability of death prophet (forgot the name) and the guy against me had multiple charges

**Comment by Draze22** [comment]
Yep, can confirm charges only work if the abilities has charges by default, any ability that gains charges from a talents or aghs shard/scepter doesn't gain the extra charge/s.

**Comment by Draze22** [comment]
Waveform charges talent still doesn't work.

![image](https://user-images.githubusercontent.com/63279022/166863700-c579880b-3792-4883-a676-96004c4123f9.png)

**Comment by ZLOY5** [comment]
Valve every patch moves part of abilities to new AbilityValues system, so possible in future we will have more talents broken
