### ISSUE TITLE
Add Lina's new Aghanim's Shard

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1923]
- [ ] Make this upgrade affected by spell amp.
- [ ] Make this upgrade affect all spells.
- [ ] Make it deal 70 damage whenever the player damages an enemy with a spell, with a 1s cooldown per ability (same as Static Field).

![image](https://user-images.githubusercontent.com/63279022/156098005-b17fbad9-fce6-44dc-8552-b48677b0d7a7.png)

**Comment by ZLOY5** [comment]
> * Make this upgrade affect all spells and make dure it increases their total damage, rather than dealing 70 damage each time the spell damages an enemy.
Can be impossible to do this, since there no handler that allows increase ability damage directly, but maybe we can convert it to some percent based damage bonus

**Comment by ZLOY5** [comment]
or maybe spell amp bonus

**Comment by Draze22** [comment]
We could make it like Static Field except it does raw damage instead of % damage.
