### ISSUE TITLE
Rip Tide only works on Naga Siren

### ISSUE THREAD

**Issue by Bruni10** [arcadia-redux/custom_hero_clash_issues#1929]
Rip Tide counts up to 5 hits on heroes other than Naga, procs on the 6th hit but doesn't do anything.

**Comment by Draze22** [comment]
This is probably due to Rip Tide proccing around Naga Siren and all of her illusions. I also wouldn't be surprised if this is a bug in ability draft.

**Comment by ZLOY5** [comment]
Idk, this shit completely bugged, when ability proc by illusion attack units around main hero not damaged, maybe we should wait for dota fix, otherwise we need rewrite it

**Comment by Draze22** [comment]
Ok.
