### ISSUE TITLE
Wraith Pact's totem affects creeps

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1936]
Might be a little too strong for it to affect creeps since it reduces their damage output by 25%.

**Comment by chariot-afv** [comment]
Just make it so it doesnt affect ancient creeps, and add it as a note in item's description

**Comment by Draze22** [comment]
Actually since this reduces outgoing damage it doesn't stack with other damage reduction abilities and can be allowed to affect creeps. If everyone starts buying it or we find out it combos too well with something we can nerf it then.
