### ISSUE TITLE
Static Field doesn't work properly

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1937]
- [x] Some abilities like Shackles and Life Drain can proc it on every damage tick. Should only be able to proc it once per second per enemy.
- [ ] Some abilities like Rot and Pulse Nova don't proc it at all.

**Comment by ZLOY5** [comment]
> * Some abilities like Rot and Pulse Nova don't proc it at all.

Seems this done on purpose, but idk why

**Comment by Draze22** [comment]
Maybe it was a lazy way to stop those abilities from proccing it more than once per second.
