### ISSUE TITLE
Боевая веха: Гонец

### ISSUE THREAD

**Issue by Slapmap21** [arcadia-redux/custom_hero_clash_issues#1945]
**Боевая веха**: Гонец; Не увеличивает урон героя на 2% за каждые 125 единиц скорости передвижения, возможно не работало с brawler. Прошу выяснить в чем проблема;)

**Comment by jakmarles** [comment]
![image](https://user-images.githubusercontent.com/13220259/156944603-d46a6710-25cf-46b5-8f10-029f518c048a.png)
![image](https://user-images.githubusercontent.com/13220259/156944610-b37bcab7-ec5a-4508-9215-1b5ba8098e9c.png)
увеличивает урон
