### ISSUE TITLE
Reduce Spin Web's max Simultaneous Webs to 2

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1955]
This is to stop people stacking all of them on top of each other, making it hard to see stuff.

![image](https://user-images.githubusercontent.com/63279022/157366271-d7903a74-088c-4a3c-a3fa-6fbc2f97f7ef.png)

**Comment by ZLOY5** [comment]
@Draze22 we need replace Broodmother talent that gives +3 webs

**Comment by Draze22** [comment]
Thanks, I'll do that now.
