### ISSUE TITLE
Rewrite Good Juju so it doesn't affect certain abilities

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1959]
If this isn't possible, close this issue.

Current list of abilities it shouldn't affect:

- Shadow Realm
- Borrowed Time
- Shadow Dance
- Depth Shroud
- Reincarnation
- Shallow Grave
- False Promise
- Chronosphere
- Rearm

**Comment by jakmarles** [comment]
Maybe add rearm to the list? so the cd on it wont be useless

**Comment by Draze22** [comment]
Good idea
