### ISSUE TITLE
Duel Aghs still doesn't work properly

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1962]
- [ ] Can be dropped and picked up to get the charges back.
- [ ] Doesn't always give the second charge immediately.

![image](https://user-images.githubusercontent.com/63279022/157815793-8ea855f0-fbcc-4510-aa14-fa085754d3f5.png)

**Comment by ZLOY5** [comment]
@Draze22 check it one more time after update for any issues
