### ISSUE TITLE
Bug on Weaver's Ultimate: Time Lapse

### ISSUE THREAD

**Issue by eduponto21** [arcadia-redux/custom_hero_clash_issues#1977]
The bug is related to Weaver's Ultimate, time lapse. I was playing normally and used the ult on the first seconds of a wave, then I was teleported back to 'fountain', being unable to get back to my 'square'. This crashed the game, being disconnected and unable to reconnect to it. Probably my hero was locked on the 'fountain' and the wave couldn't finish, since I was taking no damage and not killing creeps.  My Steam ID64 (Dec): 76561198089533292. Thanks and hope you guys can find any fix for it.

**Comment by Draze22** [comment]
We should probably just disable using TIme Lapse during the first 5 seconds of the round in creep rounds too (we already did it for duels).

**Comment by ZLOY5** [comment]
Player still can use timelapse first 5 seconds, but position history flushed on every round start
