### ISSUE TITLE
Rework Switcheroo

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1982]
This is to prevent the various bugs that occur when players disconnect, change to melee or ranged, etc.

- [ ] No longer change the bonus provided whenever the player changes from ranged to melee or from melee to ranged.
- [ ] Instead check if they're ranged or melee when they first pick Switcheroo and give them the corresponding buffs/changes.
- [ ] Let them change from ranged to melee or melee to ranged with other abilities (EDF, Meta, Shapeshift, etc) after they pick Switcheroo (without changing the buffs given by Switcheroo).
- [ ] Add the following to the end of Switcheroo's description: Switcheroo buffs are determined when Switcheroo is chosen, using other abilities to become ranged or melee will not affect the buffs provided.

**Comment by jakmarles** [comment]
wouldnt it introduce a whole new level of abuse?
just imagine what someone who started as range, took meele ability like lycan wolf ulti and got the range to meele buff. a carry/hybrid tank with attack range,big amounts of armor and extra status resistance..
or fat tanks with a lot of att speed..

**Comment by Draze22** [comment]
That's not really abuse, but the other option is Switcheroo could override all other melee to ranged/ranged to melee abilities.
