### ISSUE TITLE
Russian quest localization is broken

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1986]
![image](https://user-images.githubusercontent.com/63279022/161189863-14ac4744-7ee1-44bd-a1a6-f7c84c65165b.png)

**Comment by PonyashaWright** [comment]
It is bugged not only for Russian localization, no?
![image](https://user-images.githubusercontent.com/77478706/161200091-0b5f3602-f25e-47e3-aed4-9735d79f6ef6.png)
