### ISSUE TITLE
Come up with a way to prevent players from stalling

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1988]
The most common thing players do is leave one creep alive at low hp and leave it alive for as long as possible.

Potential solutions:

1. Let players vote to kick players who stall. Would require restricting who could be kicked to only players who have gone into overtime multiple times in the early game (first 20 rounds).
2. Come up with a detection system to automatically warn, then kick (if they ignore the warning) players who do this.
3. Make a manual list of players who are restricted from playing CHC, when they play a game they simply can't control their hero. This would obviously require players to report each other to us for stalling.
4. Make all money gaining/permanent buff abilities round based (so there's no legitimate reason to stall) and automatically start a kick vote when a player doesn't deal damage often enough.

None of these solutions completely fixes the problem and all of them have their own downsides.

**Comment by jakmarles** [comment]
My ideas 

How about you make the gold gained per round on the last place decrease based on time.

 Give creeps a custom ability that works like berserker but different . If the creeps didn't take any damage for x amount of times, increase their att speed, give them true sight, and increase their att range and each att DECREASES the targets hp regen.

**Comment by Draze22** [comment]
I like your first idea, it's simple to implement and as long as players know it exists it will do an excellent job at deterring them from stalling.

**Comment by Draze22** [comment]
Moved to #1989.
