### ISSUE TITLE
Reaper's Scythe doesn't deal damage if another Reaper's Scythe gets cast before it deals damage

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1995]
Only really affect Reaper's Scythe + Magus which is a very strong combo even with this bug.

**Comment by jakmarles** [comment]
After the nerf this combo is one of the worst ones so idk why u r saying its very strong

**Comment by Draze22** [comment]
The combo was strong before Reaper's Scythe gave permanent hp and mana regen, it's just back to mostly being strong against creeps again.
