### ISSUE TITLE
Astral Step charge restore time resets whenever Astral Step is cast

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1996]
1. Cast your first Astral Step charge.
2. Wait for it to almost be restored.
3. Cast your second Astral Step charge.
4. The charge restore time will be fully reset (to 20s with no cdr).

Probably applies to some other abilities with charges.

**Comment by ZLOY5** [comment]
Actually this happens with all abilities that using our custom charges.

**Comment by ZLOY5** [comment]
Should be fixed and hope I not broke nothing else

**Comment by Draze22** [comment]
@ZLOY5 looks like you broke something else. 

![image](https://user-images.githubusercontent.com/63279022/162960349-9c616642-3552-432a-9599-b5d34552f76f.png)

**Comment by Draze22** [comment]
I've only been able to do this in the fountain but when I cast Astral Step while the second charge is about to be restored I sometimes end up with 2 charges instead of 1 and once I ended up with 0 charges (and after that 2 charges restored at once).

**Comment by ZLOY5** [comment]
> @ZLOY5 looks like you broke something else.
> 
> ![image](https://user-images.githubusercontent.com/63279022/162960349-9c616642-3552-432a-9599-b5d34552f76f.png)

This happens when hero gains ability when death, and sure this was before, but somehow was not known before
