### ISSUE TITLE
Big Game Hunter sometimes affects units it shouldn't

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#1997]
![image](https://user-images.githubusercontent.com/63279022/162671526-1d4a4fd9-f939-4f37-8fa8-b43245d3e5ba.png)

**Comment by Draze22** [comment]
It also sometimes affects less units than it should.

![image](https://user-images.githubusercontent.com/63279022/163111109-cce2dd24-82e8-4bed-8b60-2c019c486d7f.png)

**Comment by lovro-m** [comment]
I spawned the waves in the pictures and it seems to work fine in tools. Is this a duos issue or maybe both players have big game hunter at the same time?

**Comment by SanctusAnimus** [comment]
There is a slight delay before modifier is applied, and it it applied only on wave start (so respawned skeletons won't get it), which might cause the issue
It is done in that way because we can't apply modifiers to invulnerable units (it just doesn't apply them silently), and creeps are invulnerable for a few frames after round starts

**Comment by Draze22** [comment]
It does look like it only happens in duos. I'll ask if both players had Big Game Hunter but I doubt it.

**Comment by lovro-m** [comment]
And what is the theory on why it jumped to low hp creeps? Tried it a couple of times and couldn't reproduce the bug.

**Comment by Draze22** [comment]
No idea yet.

**Comment by SanctusAnimus** [comment]
it checks hp of every creep in spawner against max hp (determined by spawner as well), so the only option obvious enough for me is that max health within spawner might be decided poorly (not accounting for something), but idk
i used same max health variable as it used before

**Comment by Draze22** [comment]
Hasn't been reported in a long time.
