### ISSUE TITLE
Selling reward for randoming hero gives double the gold

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#2001]
Item given for randoming hero gives 600 gold when activated, but 1200 when sold in the first 30 seconds. Make it so it always sells for 600

Opened from Discord by **Chariot#5818**

**Comment by chariot-afv** [comment]
![image](https://user-images.githubusercontent.com/44137926/163270329-2e97c572-5fd8-4688-a427-f100ff944823.png)

**Comment by jakmarles** [comment]
Since you found out the reason i frequently random. You can also sell the fairys for full price at the start of the game as well
