### ISSUE TITLE
Rebalance summons counts and stats

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#2004]
Significantly reduce count of summons spawned by every summon skill (including secondary/child summons) and increase their stats to match old combined values

Opened from Discord by **Sanctus Animus#3413**

**Comment by ArcadiaReduxAutomation** [comment]
i'll break it down in several issues, one for eidolons and second for spiderlings

Comment from Discord by **Chariot#5818**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/964537498049085500)

**Comment by chariot-afv** [comment]
- [ ] #2005
- [ ] #2006
