### ISSUE TITLE
"Teleports Behind You" does not grant the active agility from swift blink

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#2007]
Opened from Discord by **✶Twilight Sparkle✶#5795**

**Comment by PonyashaWright** [comment]
![image](https://user-images.githubusercontent.com/77478706/163889432-9ec99c5d-4aa1-48cf-a279-f7a950728ef8.png)

**Comment by ArcadiaReduxAutomation** [comment]
Closed from Discord using Issue Controls button by **✶Twilight Sparkle✶#5795**
