### ISSUE TITLE
"Teleports Behind You" does not grant the active agility from swift blink

### ISSUE THREAD

**Issue by PonyashaWright** [arcadia-redux/custom_hero_clash_issues#2008]
![image](https://user-images.githubusercontent.com/77478706/163892411-2c70facc-9ace-405c-88b5-bc2aea26f859.png)

**Comment by Draze22** [comment]
It also need's it's active attack speed and damage removed since that's what the active agility replaced in Swift Blink.

**Comment by Snoresville** [comment]
would be better if that was in a different issue
