### ISSUE TITLE
Enrage can be rearmed 

### ISSUE THREAD

**Issue by Zyrgil** [arcadia-redux/custom_hero_clash_issues#2009]
Enemy cant take damage whatsoever and purge anything. Why can other things not be rearmed but this one can? too op please fix

**Comment by jakmarles** [comment]
Ever heared of cc? Or mana burn? Its literally one of the worst combos enrage + rearm.
Skull busher/abyssal/bloodthorn/hex is more than enough to counter this kind of builds. Its not op it just requires extra items to purchase to counter it

**Comment by Draze22** [comment]
We will keep an eye on this combo but for now we aren't going to prevent Enrage from being Rearmed.
