### ISSUE TITLE
Prevent Sunder from proccing Magus

### ISSUE THREAD

**Issue by PonyashaWright** [arcadia-redux/custom_hero_clash_issues#2016]
The reason are the situations where player is facing a strong healthy creep, and they can't kill them because of constant Sunder and lifestealing, which leads to player's death in the end if they doesn't reroll Sunder.

Optionally, you can disable proccing Magus only during creep and boss rounds, but I imagine Sunder being annoying in duels for both sides as well.

**Comment by Draze22** [comment]
I'd prefer to not disable it, if players want the combo they can use, if they don't want it they can not pick it in the first place or reroll it.

**Comment by PonyashaWright** [comment]
This usually happens to newbie players, and situations like these could make them mad, so they never ever join the game again, but I see your point.

Also, some people see this as an innate's flaw, and they blame devs for that (happened last game to me).

**Comment by Draze22** [comment]
It's not a very good combo so it might be worth disabling it for those reasons.
