### ISSUE TITLE
Magical Constitution works a little strangely

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2018]
Currently:

- When you equip mana items, you get the bonus health instantly. - Doesn't need changing
- When you unequip mana items you don't lose the health until the start of the next round unless you unequip an item that gives health. - Needs changing (see below)

New options:

1. When you unequip mana items you lose the health instantly. - I vaguely remember this not being a good option but don't remember why
2. When you unequip mana items you don't lose the health until the start of the next round (at the start of the round the bonus health from Magical Constitution gets recalculated). - Is a good alternative option if the 1st option has significant downsides

**Comment by SanctusAnimus** [comment]
Currently fixed as first option - inventory changes will update innate bonuses instantly
i couldn't find any downsides after a bit of testing
