### ISSUE TITLE
Change which games are scored

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2019]
Only games that start with full players, don't have cheats enabled and don't have tournament mode enabled should be scored.

**Comment by ZLOY5** [comment]
![image](https://user-images.githubusercontent.com/10956575/165460120-0dcd9441-bca9-41d8-b572-af78156882ae.png)
Game started with 9 players

**Comment by PonyashaWright** [comment]
According to both site with matches' history and player's words, match 6542026325, which started with 8 people, had MMR scored.

**Comment by jakmarles** [comment]
> According to both site with matches' history and player's words, match 6542026325, which started with 8 people, had MMR scored. Message from the screenshot never showed.

Probably someone accidentally or not accidentally found out about the bug that allows even 2 players game to receive mmr

**Comment by jakmarles** [comment]
> According to both site with matches' history and player's words, match 6542026325, which started with 8 people, had MMR scored. Message from the screenshot never showed.

for example what does ur site say about this game i just did to test if the bug still works. match id 6543370327
![image](https://user-images.githubusercontent.com/13220259/165476225-81f08129-f3e6-4bf6-9e92-18cf26d322f5.png)

**Comment by ZLOY5** [comment]
@jakmarles shows same as endgame screen
Can you explain how you achieved this? Looks like other players disconnected before they picked hero or smth

**Comment by jakmarles** [comment]
> @jakmarles shows same as endgame screen Can you explain how you achieved this? Looks like other players disconnected before they picked hero or smth

sure but not here on public. whats ur discord?
