### ISSUE TITLE
Make Devastator have Soul Stealer passive from Desolator

### ISSUE THREAD

**Issue by PonyashaWright** [arcadia-redux/custom_hero_clash_issues#2020]
With 7.31, new passive was added to Desolator, which increases it's damage with every hero kill/assist, while the armor reduction was on the target. (2 per kill, 25 cap)

Since Devastator is built from Desolator, it's only natural for it to have the same passive, maybe even a bit stronger (let's say +4 damage per kill, 50 damage cap)

**Comment by jakmarles** [comment]
Wouldn't that give disadvantage to melee rightclickers? Since range cleave doesn't have a desolator?

**Comment by PonyashaWright** [comment]
Range carries have the benefit of being range. That is more than solid advantage

**Comment by jakmarles** [comment]
> Range carries have the benefit of being range. That is more than solid advantage

How is that solid advantage? Ranged heroes tend to be balanced around the fact that they are able to operate at range, meaning they're generally weaker than melee heros if forced into a situation where they can't use that advantage. This is particularly true for 'glass cannon' ranged heroes like Drow and Sniper, whose kit is designed almost entirely around preventing enemies from getting close.

In practice, this makes ranged heroes relatively poor when it comes to being in the centre of the fight. 

There are some other lesser benefits to melee heroes too: The fact that your attacks don't have to travel means that they can't be disjointed, and arguably makes farming easier. Some items are also coded to only have reduced effectiveness on ranged heroes (for example Vanguard, Quelling Blade, Vladmir's, echo sabre, skull busher etc)

**Comment by Draze22** [comment]
We can reduce the bonus damage from 125 to 110 and add the new soul steal passive as is, keeping it at a similar power level. 

We could also reduce the armor reduction devastator has if we want to make the soul stealer passive stronger while still keeping Devastator at a similar power level.

**Comment by lovro-m** [comment]
What about desolator 3 lmao?

**Comment by lovro-m** [comment]
Sure, when you upgrade from desolator to devastator I assume you want to keep the stacks?

**Comment by Draze22** [comment]
Yes, although we might be changing devastator soon anyway so this might not be worth doing if you haven't started.

**Comment by AustraliaIsMyCity** [comment]
absorbing this issue into https://github.com/arcadia-redux/custom_hero_clash_issues/issues/2226
