### ISSUE TITLE
Auto Fire Remnant on death can't be used

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2021]
![image](https://user-images.githubusercontent.com/63279022/165445575-49eb03a3-fe95-40ff-8d86-15b56863aece.png)

**Comment by Draze22** [comment]
The problem was due to player being able to cast Fire Remnants in the fountain.

**Comment by Draze22** [comment]
I can't figure out why Fire Remnant can be cast while in the fountain, it's in the list of fountain disabled abilities.

**Comment by ZLOY5** [comment]
A while ago I disabled this list in demo mode for test purposes.

**Comment by Draze22** [comment]
I see, maybe the issue is that Fire remnant active can't be used if you've got a fire remnant in a different arena.

**Comment by Draze22** [comment]
Ok, the issue is that the Fire Remnant left behind when you die can't be jumped to using Activate Fire Remnant.

**Comment by ZLOY5** [comment]
This was done far ago to prevent people jump to duel arena from their arenas. We can fix this only with ability rewrite
