### ISSUE TITLE
Thoroughly test and make tooltips for Good/Bad Juju

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2023]

**Comment by Draze22** [comment]
Basically finished, all other fixes/improvements should be niche interactions that won't easily be identified by my testing.

**Comment by ZLOY5** [comment]
For now charge based abilities should be affected, at least that ones that uses our custom charges

**Comment by Draze22** [comment]
Recently added tooltips explaining that several abilities (Shadow Realm, Borrowed Time, etc) can't have their cooldowns reduced by Good Juju.
