### ISSUE TITLE
If you use Poison Nova on creeps and then reroll it, this would drastically increase it's damage

### ISSUE THREAD

**Issue by PonyashaWright** [arcadia-redux/custom_hero_clash_issues#2032]

**Comment by Draze22** [comment]
Should have been fixed by: https://github.com/arcadia-redux/custom_hero_clash/commit/c621e226cf7ef12b5123471e9b1ad6fdc5448240.

**Comment by PonyashaWright** [comment]
Still works

**Comment by ZLOY5** [comment]
Is this really reproducible?

**Comment by Draze22** [comment]
Definitely doesn't work in demo mode, testing in a solo game now.

**Comment by Draze22** [comment]
Also doesn't work in a real game.
