### ISSUE TITLE
Accepting the daily fortune breaks the unlock mastery button

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2039]
Seems to also require having less than 10 fortune for it to break.

![image](https://user-images.githubusercontent.com/63279022/166202651-0dd43b6b-fc62-4f28-9d2d-ef75d328926a.png)

**Comment by Draze22** [comment]
Tested this myself on a new account:

1. Accepted the daily fortune.
2. Had 16 fortune total afterwards.
3. Unlocked 2 new masteries, leaving me with 6 fortune.
4. Tried unlocking a third but it sent me to the store instead.

**Comment by jakmarles** [comment]
> Seems to also require having less than 10 fortune for it to break.
> 
> ![image](https://user-images.githubusercontent.com/63279022/166202651-0dd43b6b-fc62-4f28-9d2d-ef75d328926a.png)

I have more than 10 100 1000 10000 combined and its doesn't work for me either

**Comment by ZLOY5** [comment]
@Draze22  would good if you test this after next update
