### ISSUE TITLE
Tree Grab, while being active, doesn't show in Duel UI

### ISSUE THREAD

**Issue by PonyashaWright** [arcadia-redux/custom_hero_clash_issues#2045]
![image](https://user-images.githubusercontent.com/77478706/166625305-aa642530-9e71-491a-b1a6-6dbad8099c48.png)

**Comment by lovro-m** [comment]
Applies to all secondary abilities 
![image](https://user-images.githubusercontent.com/63733825/166716549-09f7431e-d399-4709-b634-0284c658c9c2.png)
