### ISSUE TITLE
Insta-win with firestorm

### ISSUE THREAD

**Issue by pochi2000** [arcadia-redux/custom_hero_clash_issues#2047]
i don't know if the skill is bugged or what, but i'm playing with spectre and it's totally unfair, with firestorm i simply kill everybody, all the creeps and enemy heroes, no matter the health in literally less than 2 seconds, its doing too much damage, i dont even have any items

my skills are as follow:
firestorm, shadow dance, guardian angel, essence shift, bulwark and dispersion.

i didnt have any mastery and my innate was grand librarian

**Comment by jakmarles** [comment]
Its one of the worst % damage skills in the game, the build you described is way too easy to counter and won't be effective at the late game (past round 60)

**Comment by lovro-m** [comment]
it's a valve bug, we wait for a fix

**Comment by Draze22** [comment]
Valve have fixed it now.
