### ISSUE TITLE
Masteries chosen by bots are always max level

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2048]
The Masteries chosen by bots are max level, regardless of what level masteries the player had.

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/166911971-d376aae4-2d1a-4b67-a782-c3b2dc797a7a.png)
no they don't

**Comment by SanctusAnimus** [comment]
player might have been considered abandoned, but that's outside of bots responsibility, they use common `GameMode:HasPlayerAbandoned`, which is used everywhere

**Comment by Draze22** [comment]
They only keep playing in Duos and Enfos right?

**Comment by Draze22** [comment]
Also in that case the bug is that the masteries chosen aren't based on the mastery levels of the player.

**Comment by SanctusAnimus** [comment]
yes in ffa they stop doing anything
https://github.com/arcadia-redux/custom_hero_clash/blob/324f51ac4a244ff4bb3355ef45e53336cf281334/game/scripts/vscripts/libraries/modifiers/modifier_auto_attack.lua#L577-L584

**Comment by SanctusAnimus** [comment]
> Also in that case the only bug is that the masteries chosen aren't based on the mastery levels of the player.

it's not a bug, it's intentional

**Comment by SanctusAnimus** [comment]
moreover, i said that they do that many times when i was developing that AI, they do that to compensate for inability do make proper ability builds (since it's way too hard to implement)

**Comment by Draze22** [comment]
In that case can we unequip any masteries chosen by Bots if the player reconnects?

**Comment by SanctusAnimus** [comment]
why, if player is considered abandoned, they won't be able to return and play again

**Comment by Draze22** [comment]
Ok, makes sense.
