### ISSUE TITLE
The game crashed for an unexpected reason

### ISSUE THREAD

**Issue by nickbelous** [arcadia-redux/custom_hero_clash_issues#2049]

**Comment by Snoresville** [comment]
More information needed.

**Comment by nickbelous** [comment]
The behavior is unexpected. Today (05.05.2022) the game is crashed and reconnecting is impossible

**Comment by Snoresville** [comment]
We are looking for how the crashed happened.

**Comment by nickbelous** [comment]
again. the game is crashed 
![image](https://user-images.githubusercontent.com/30178437/166968203-cc4a7358-8a15-4426-a697-e38f33cc7e57.png)

**Comment by nickbelous** [comment]
Im cant add any logs

**Comment by Snoresville** [comment]
Appreciate the effort, but unless there is a clear understanding to the problem, we cannot figure out a fix. Sorry.
