### ISSUE TITLE
Frozen sigil can fly between arenas and affect heroes and creeps in other arenas.

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#206]
![image](https://user-images.githubusercontent.com/63279022/81787447-67cca100-9544-11ea-8a4e-c2f35b3aefad.png)

**Comment by mmdts** [comment]
Can confirm
They also give 120 gold when they hover over fountain and are killed there.

**Comment by SanctusAnimus** [comment]
We don't even have frozen sigil as a spell, reopen if i'm wrong
```
  "tusk" {
  "tusk_snowball" {"tusk_launch_snowball" "0"}
  "1"    "tusk_ice_shards"
  "2"    "tusk_snowball"
  "3"    "tusk_tag_team"
  "4"    "tusk_walrus_punch"
  }
```

**Comment by Draze22** [comment]
Frozen Sigil is granted by buying Shard while having Walrus Punch.
