### ISSUE TITLE
Centaur's double edge shard doesn't work in rounds

### ISSUE THREAD

**Issue by ArtNuevo** [arcadia-redux/custom_hero_clash_issues#2060]
Bonus hp appears only in between rounds safe time, and thus is completely useless.

**Comment by jakmarles** [comment]
I literally had a game with that a hour ago and the max hp increases immediately after the usage of the spell

**Comment by ArtNuevo** [comment]
> 
Aight, I've got this build - Sven's Hammer, CW's edge and retal;iate, Counterspell, can't remember the last skill; Brute, Initiate lvl3 and Warrior lvl 2. 
When I've cast double edge on bunch of creeps, hp hadn't been increased. Gonna try out once again, if i would have a chance.
