### ISSUE TITLE
Reconnecting to the game lets you bet on your own Duel

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2061]
1. Reconnect to the game during the preparation time for a Duel you're in.
2. You will be able to bet on the Duel.
3. If you try to bet on the Duel your game will crash.

**Comment by ZLOY5** [comment]
Even after reconnection player can't see bet panel if he participate in duel

**Comment by Draze22** [comment]
Something else might also be required to reproduce this then.

![image](https://user-images.githubusercontent.com/63279022/168053539-496ff82a-61c4-4c4c-899f-e6a8d326f4b8.png)

**Comment by ZLOY5** [comment]
Since there Beast in game i can suggest he can use some cheats to send fake events

**Comment by Draze22** [comment]
Chupa isn't Beast afaik but maybe.

**Comment by jakmarles** [comment]
> Chupa isn't Beast afaik but maybe.



> Since there Beast in game i can suggest he can use some cheats to send fake events

I can but that wasn't me.
