### ISSUE TITLE
Luminosity causes crashes

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2063]

**Comment by ZLOY5** [comment]
Any info?

**Comment by SanctusAnimus** [comment]
iirc draze reenabled talents for it recently (on dawnbreaker), so perhaps they could be the reason?

**Comment by Draze22** [comment]
https://www.youtube.com/watch?v=EyOf23J6Buo

**Comment by jakmarles** [comment]
> https://www.youtube.com/watch?v=EyOf23J6Buo

Maybe disable it like you did to my poor Phoenix?
