### ISSUE TITLE
Double Edge doesn't give bonus health if you go from 0 to 6 stacks (against creeps)

### ISSUE THREAD

**Issue by ArtNuevo** [arcadia-redux/custom_hero_clash_issues#2064]
Again, and now with screenshots.
![20220512190828_1](https://user-images.githubusercontent.com/105406820/168120642-f42d692e-5b97-4ce3-bb41-986b45ae677f.jpg)
![20220512190832_1](https://user-images.githubusercontent.com/105406820/168120685-95bf1106-79a5-43ae-94aa-f980d4e10fef.jpg)

@[jakmarles](https://github.com/jakmarles), say again, that it is working, I dare you.

**Comment by Draze22** [comment]
Bonus damage still works if you go from 0 to 6+ stacks against creeps but the health does not. Having any other modifier applied or removed from you fixes this (using ghost scepter for example).
