### ISSUE TITLE
Counter Helix doesn't proc Static Field

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2072]

**Comment by lovro-m** [comment]
Counter Helix is a passive. I see passives disabled from proccing static field. Should I implement exceptions?

**Comment by SanctusAnimus** [comment]
Yeah next thing they'll ask is dispersion to proc static field

**Comment by Draze22** [comment]
Static Field's description says "shocks any enemy that he attacks or is **hit** by his **abilities**". I would say that Counter Helix hits enemies however Arc Lightning is already a top 10 ability in both FFA and DUOS so I'm fine with it not affecting passives at all and updating Static Field's description to reflect that.
