### ISSUE TITLE
Create a player banlist so we can prevent trolls from stalling lobbies

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2076]
Players on the list should be kicked from the lobby once the game starts and kicked every time they reconnect.

**Comment by Snoresville** [comment]
stalling during lobby wait or stalling ingame?

**Comment by Draze22** [comment]
Stalling in game by not killing the creeps.

**Comment by SanctusAnimus** [comment]
Eh how is that a good decision, game should be designed to punish such behaviour instead of making manual ban list

**Comment by jakmarles** [comment]
> We already punish the behaviour by making them get less gold if they stall, but if people don't care about winning it doesn't stop them.
> 
> We'd have to do something like making a complex detection system for stalling and start removing aegis's when we detect stalling. I can't come up with a way to reliably detect it automatically and any sort of vote system could be abused.
> 
> Maybe we could create a rough detection system for stalling, add a vote kick item that can only be used on players who are detected as stalling and then if enough players vote to kick the player it kicks them.
--------------------------
**i am high on weed so here is my idea (i am typing it as i think about it).** 

how about adding to the system you made a hidden function like if a player was stalling multiple rounds in game. check if in the process of the stalling the player did or didnt do the following things (activates only if the player got the stalling debuf to determine if done on purpose)

1. Attack the creeps with physical attacks much slower than their att speed allows you to.
2. had any dmg castable abilities (not passives) (not ultis as those tend to have big cd) available and casted them on creeps or not 
3. if the user was afk or not

if those things did happen give them hidden from them point and send it to the database of the player with match id to see the time of the game and rounds.
after a player reach certain amount of points make someone review it and add the ability to manually ban them if someone reported them with proof beyond a reasonable doubt.

i would also recommend not kicking the banned players but instead killing them and muting them and allow them to send an appeal once a week-month so people can ask for forgiveness and if they will do it again make it perm.


i just made this thing up without pre thinking about it. so idk how good it is or not as i didnt rly think it thru all the aspects. just an idea for you bois to talk about

**Comment by Draze22** [comment]
That sounds like a decent detection system and yeah, making them instantly lose is better than kicking them. Not sure if the manual review is the best way to do it though.

**Comment by jakmarles** [comment]
> That sounds like a decent detection system and yeah, making them instantly lose is better than kicking them. Not sure if the manual review is the best way to do it though.

Manual review wouldn't take more than a minute. All you have to do is see the pattern. But you can make it automatically if a player reached like 3-5 total matches  where he purposely stalled the game to receive a 1 week ban with a warning that the next offense will result in a 6 week ban+ etc

**Comment by Draze22** [comment]
The issue with manual review is if no one is there to review it immediately they get to grief that game.
