### ISSUE TITLE
Heartpiercer always causes armor to be 0

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2085]
If a unit with negative armor gets hit by Heartpiercer they actually gain armor.

**Comment by PonyashaWright** [comment]
Isn't it how the ability worked in original Dota before it was reworked? I don't see a problem here.

**Comment by Draze22** [comment]
Feels like a weird spell to keep unless we rework it to not sometimes be bad.

**Comment by PonyashaWright** [comment]
I object against the statement of it being bad. It is hilariously good for rightclickers against any targets with high amounts of armor, and even better than Elder Titan's passive since it doesn't cut "green" armor which is sometimes gained in high amounts from masteries.

**Comment by Draze22** [comment]
It's definitely not bad, but when combined with other armor reduction it can be better to just not have it proc.

**Comment by PonyashaWright** [comment]
Sometimes it is okay for ability to have it's drawbacks (for example Grow's attack speed penalty). If the fix would require rewriting the ability, I don't think it's worth the effort since it isn't really that much frequent case to happen.
