### ISSUE TITLE
"Winner" Innate never working?

### ISSUE THREAD

**Issue by Wellendox** [arcadia-redux/custom_hero_clash_issues#2095]
As the title says. I've had many games with over 10 Winner stacks and we never felt an increase in damage.

And on top:
Add a Tooltip that you cannot swap the spirit bear, so people dont pick it and see it too late. Or better yet, allow people to swap the spell with their teammate. That shit is stupid.

**Comment by ZLOY5** [comment]
Sure it working, this innate increase all outgoing damage, not only damage from attacks

**Comment by Draze22** [comment]
Lvl 1 Magic Missile damage with 29 intelligence and no Winner stacks.

![image](https://user-images.githubusercontent.com/63279022/170811504-e73878ec-fd8c-422b-ab30-ee51935ce189.png)

Lvl 1 Magic Missile damage with 29 intelligence and 1 Winner stack.

![image](https://user-images.githubusercontent.com/63279022/170811546-7a303c75-018f-4a79-b3ba-1724fcddf036.png)
