### ISSUE TITLE
BOOST REITING. THIS NOT fun

### ISSUE THREAD

**Issue by Tgjumper** [arcadia-redux/custom_hero_clash_issues#2101]
![boost not fun](https://user-images.githubusercontent.com/106535575/170995737-d7b16160-08b4-457f-936b-a1c5f454960e.jpg)
this gays boost reit. bosst money this ganbler and lose duel in start. Эти люди бустят друг другу деньги проигрываю дуели. а так же есть подохрения что свой рейтинг они набили именно таким способом. они заливали с самого начала полные ставки и друга и проигрывали когда общая сумма была джекпотом .  так же с ними третий игрок котоырй подсказывает, когда какие ставки. это совсем не весело

**Comment by jakmarles** [comment]
В этом нет ничего плохого это Рабочая стратегия которая люди используют уже больше 3 лет.. это не нарушает никакие правила и вообще правил никаких нет Ты когда начинаешь играть не подписываешь соглашение на какие-либо правила кроме конечно правила Стима
