### ISSUE TITLE
Не дали ммр

### ISSUE THREAD

**Issue by T5dkr** [arcadia-redux/custom_hero_clash_issues#2102]
![kc_97KuGcP-kdLTcKHpBy420SHs29Ar0241-ivr4gYHLqp84BBzALDgR3dcCCOn9LZzIvMKoB6R8CPB2gM1B0f6W](https://user-images.githubusercontent.com/106650293/171340495-01380714-c208-45a5-8d94-04cb00f64f8a.jpg)

За 5 место не дали ммр, плюс к этому произошёл бак с дуэлью легионки, когда нажимаю на крипов крипы пропадают и дуэль не засчитывается

**Comment by jakmarles** [comment]
За пятое место и не должны были дать и Если бы у тебя был адекватный рейтинг тебе бы даже сняли

**Comment by Draze22** [comment]
You got the amount of mmr you should have.

**Comment by T5dkr** [comment]
Тогда странно, мне до этого за 5-6 место примерно по 5 ммр давали
