### ISSUE TITLE
Levelling Duel (ability) with Aghanim's Scepter lets it be used again

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2108]
1. Pick Duel, level it to level 1 and buy Aghanim's Scepter.
2. Use Duel twice.
3. Level Duel to level 2 and you'll be able to use it two more times that round.
4. Level Duel to level 3 and you'll be able to use it another two more times that round.

**Comment by jakmarles** [comment]
Same goes for bh's track
