### ISSUE TITLE
Earthshock's Enrage duration (Shard) stacks additively when cast multiple times

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2114]
This can be abused by getting Earthshock, Multicast and a bunch of cdr which can easily give players 200+ seconds of Enrage duration.

Technically not a bug, if you put on wtf in vanilla Dota you can do the same thing. However this is probably something we need to change for CHC. 

Example:

![image](https://user-images.githubusercontent.com/63279022/172388401-fcb136ed-84df-4225-9cb5-ffd9f365d686.png)

**Comment by Draze22** [comment]
Enrage's duration now also stacks. We've got 2 main options to fix this:

1. Prevent Enrage and Earthshock from being Multicast and from being cast in the fountain.
2. Make Enrage's duration refresh instead of stacking.

**Comment by Draze22** [comment]
> we've already discussed this and I stated some implementation issues with number 2 option: is mini ulti going to override enrage ulti? then it was decided to just ban the skill in the fountain, do you also want to disable multicast?

Yes please and double check that Enrage can't be cast in the fountain too.

**Comment by lovro-m** [comment]
Disabled and checked
