### ISSUE TITLE
Damage breakdown counts an extra damage instance from attacks sometimes

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#2126]
https://youtu.be/pyNKI5ovYSc

From what I can tell, it counts attacks accurately, but every 2 seconds or so, if there was an attack in that period, it counts an additional instance.

**Comment by AustraliaIsMyCity** [comment]
*this was testing with tier 1 perks for context

**Comment by ZLOY5** [comment]
This is done to reduce event count sended to clients because of perf problems i think
