### ISSUE TITLE
LAg and item issues

### ISSUE THREAD

**Issue by Aznkb** [arcadia-redux/custom_hero_clash_issues#2127]
In later rounds, my avatar lags so much that he only attacks 1 every 2 seconds, even though he has .2 attack speed.
Also, borrowed time does not auto pop on occasions causing me to lose duels I should win.

**Comment by Draze22** [comment]
1. That's the server lagging, it's something we've been working on improving but isn't easily fixed.
2. Borrowed Time doesn't activate if you go from above 400 hp to dead in one instance of damage, this isn't a bug.
