### ISSUE TITLE
Fix these Aghanim's Shard/Scepter abilities

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2131]
- [ ] Skywrath Shard (should only be granted by Arcane Bolt instead of both it and Mystic Flare)
- [ ] Oracle Scepter (should be granted by Purifying flames instead of False Promise)
- [ ] Hoodwink's Scepter (Sharpshooter doesn't have an ability draft note about it's Scepter)
- [ ] Hoodwink's Shard (should be granted by Bushwack instead of Sharpshooter)

**Comment by PonyashaWright** [comment]
Hoodwink's shard also.

**Comment by Draze22** [comment]
This is ready to be fixed.
