### ISSUE TITLE
make round charge abilities gain charges mid round if max charges are increased

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#2137]
also, if its possible to reduce max charges like in the case of aghs scepter for duel, if you remove the aghs scepter at 0 charges, you dont get to use the ability the next round either.

Opened from Discord by **Luminance#9760**

**Comment by ZLOY5** [comment]
Charges already works like that

**Comment by AustraliaIsMyCity** [comment]
still seeing reports of this occurring with track being upgrades, @Draze22 can you check it out
https://discord.com/channels/694060511209324585/694440472273354762/992701323290091520
https://discord.com/channels/694060511209324585/694440472273354762/991676130325184532
https://discord.com/channels/694060511209324585/694440472273354762/989420793098285106
https://discord.com/channels/694060511209324585/987119522752385064/987119525407363083
https://discord.com/channels/694060511209324585/694440472273354762/985173186075324506
https://discord.com/channels/694060511209324585/694440472273354762/985047596051611678

**Comment by ZLOY5** [comment]
This is fixed literally yesterday
