### ISSUE TITLE
Rephrase Enigma's 25 lvl Demonic Conversion talent

### ISSUE THREAD

**Issue by PonyashaWright** [arcadia-redux/custom_hero_clash_issues#2139]
Talent works fine and amplifies Eidolon's power, but still is pretty confusing due to native's "+5 eidolons" phrasing. Needs to be done for all languages.

![image](https://user-images.githubusercontent.com/77478706/174219594-40850e49-33d9-4c2d-95bb-74fdce256fa5.png)

**Comment by Draze22** [comment]
I'd make it say +167% stronger Eidolons.
