### ISSUE TITLE
Dismember Shard bugs

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2146]
найс игра, меня сожрал хускар способностью Dismember, сидя в хускаре, поменял способность и выбрал Gravekeeper's Cloak (пассивка Visage), и после того как я её выбрал, окно выбора способностей закрылось, а способность в панель не добавилась, при попытке юзнуть книгу переобучения, вылетает красная строка, что активен выбор той самой способности, которую я уже выбрал, пришлось доигрывать игру на 5 спеллах, без возможности перевыбрать оставшиеся 5 способностей.

I got eaten by Huskar's Dismember. While I was inside of Huskar, I rerolled a skill and chose Gravekeeper's Cloak. After that I didn't get the ability and Ability Choosing UI was closed. Upon using Book of Retraining, it says that you can't reroll abilities during rerolling. Had to play until the end with 5 spells without the ability to reroll skills

![image](https://user-images.githubusercontent.com/63279022/174550075-5d32867e-9598-4c3b-a40a-1aec0d63b23d.png)

P.S. когда сидишь в дисмемебере, ты спавнишься в челе, но при этом ROT и Pulse Nova работают в точке спавна героя, а не фактическом месте нахождения в другом герое.

P.S. When you're inside of someone, you spawn in them, but Rot and Pulse Nova work in "hero's spawn point" (whatever it is) instead of Dismember's owner"

**Comment by Draze22** [comment]
If someone wants to try and figure out exactly what's going wrong and fix it be my guest.

**Comment by Draze22** [comment]
From my testing the first part is wrong and is probably just the standard bug where retraining breaks and requires reconnecting to fix. When I tried retraining abilities while Dismembered I was able to do so with no trouble.

I can however confirm that the second part is correct and abilities like Rot and Pulse Nova don't follow the hero with Dismember after they teleport.

**Comment by PonyashaWright** [comment]
I think we should add a loading tip which recommends to reconnect upon this retraining break.

**Comment by jakmarles** [comment]
> I think we should add a loading tip which recommends to reconnect upon this retraining break.

That wouldn't be useful maybe instead add it to the message saying you can't use book while already rerolling

**Comment by ZLOY5** [comment]
Dismember behave like that after teleportation in dota too.

Retraining bug looks like some UI error, so would be good if someone send console logs when faced this issue next time

**Comment by Draze22** [comment]
> Dismember behave like that after teleportation in dota too.

Can we specifically not teleport heroes that are Swallowed by Dismember, Infested in an ally, etc?

**Comment by ZLOY5** [comment]
Iirc this caused by teleportation of carrier, but i will test it later

**Comment by Draze22** [comment]
> Iirc this caused by teleportation of carrier, but i will test it later

Using -teleport as the carrier in vanilla Dota doesn't cause the bug, only happens if the swallowed hero uses -teleport.

**Comment by ZLOY5** [comment]
@Draze22 yeah, you are right, but i think better to unswallow hero after round is ended to prevent any possible weird bugs

**Comment by Draze22** [comment]
> @Draze22 yeah, you are right, but i think better to unswallow hero after round is ended to prevent any possible weird bugs

Sure, that works.
