### ISSUE TITLE
Add an obvious way to tell that a hero is being controlled by a bot

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2147]
Something like a special aura or icon above the hero.

**Comment by SanctusAnimus** [comment]
There;s already an aura though? cog underneath the hero

**Comment by ZLOY5** [comment]
![image](https://user-images.githubusercontent.com/10956575/177279810-0e220b5f-a7df-4927-b52f-a53f16f5a807.png)
