### ISSUE TITLE
Magician, Brute and Nimble sometimes don't change the displayed primary attribute

### ISSUE THREAD

**Issue by Kamarelka** [arcadia-redux/custom_hero_clash_issues#2160]
Добрый день, уважаемые разработчики, сегодня играя в ваш продукт, обнаружил что основной перк Magican работает некорректно.
Проверьте пожалуйста на наличие бага в Custom Hero clash (NO P2W) данный баг.
Изображение прикрепляю ниже:
![photo_2022-06-26_13-46-01](https://user-images.githubusercontent.com/108215624/175806671-76c8b5d4-f136-49f6-9b61-3133c918d340.jpg)
 Please look at this photo, ang do somth with that!

**Comment by Draze22** [comment]
The damage adds up correctly, this is merely a visual bug (would still be nice to fix it if possible).

**Comment by ZLOY5** [comment]
Gaben refuse to fix that and I'm too
