### ISSUE TITLE
The losing team somehow also got the round record

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2162]
![image](https://user-images.githubusercontent.com/63279022/175808862-29105145-83bf-4b2a-b696-e3c9c6b44f9a.png)

![image](https://user-images.githubusercontent.com/63279022/175808850-861af7bd-a19c-4f69-9fe1-63e15c31fca1.png)

![image](https://user-images.githubusercontent.com/63279022/175808856-dec6a3fb-e073-4169-a55e-27307a26935c.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/175808881-18d96052-ac37-4283-89c9-735edeae8ec4.png)

**Comment by Draze22** [comment]
From what I can tell this is the only time this has happened.

**Comment by ZLOY5** [comment]
Seems thats how is done on backend side. Originally game was ended after one of teams defeated, so now @SanctusAnimus need tweak backend i think

**Comment by SanctusAnimus** [comment]
Huh what have changed?

**Comment by SanctusAnimus** [comment]
Also check said match on website, it might give some insights as to why they were counted, maybe lua passed both teams as winners or something
