### ISSUE TITLE
Numb (mastery) + Blademail's active reflecting spell damage makes the damage breakdown record you dealing pure attack damage to yourself

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2167]
Only happens with Blademail, not Luminance.

![image](https://user-images.githubusercontent.com/63279022/176434066-2880e406-6fbf-4396-997c-5c598b0fc59b.png)

**Comment by AustraliaIsMyCity** [comment]
@Draze22 can you please test this with the rewritten blademail in chc_endless

**Comment by AustraliaIsMyCity** [comment]
edit: i am a dumb, numb has been changed lol
