### ISSUE TITLE
End Fatal Bonds if there are no other targets alive

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#2169]
Since it won't do anything anyway

Opened from Discord by **Sanctus Animus#3413**

**Comment by ArcadiaReduxAutomation** [comment]
and since it's already doing damage in ticks, just check for targets count in it

Comment from Discord by **Sanctus Animus#3413**
Follow the conversation [here](https://discord.com/channels/501306949434867713/682631693172998165/991682266218647612)

**Comment by Draze22** [comment]
Only do this in creep rounds, there is at least one reason to keep Fatal Bonds on a single target in a duel.
