### ISSUE TITLE
Legion Commander's Duel charges can be refreshed during in-game duels

### ISSUE THREAD

**Issue by PonyashaWright** [arcadia-redux/custom_hero_clash_issues#2174]
Normally you can use Duel twice (with Aghanim) in a round and refresher doesn't refresh them. For some reason, duel charges can be refreshed during in-game duels between players, so you can have 4 charges instead of 2, which is kinda weird.

**Comment by ZLOY5** [comment]
https://github.com/arcadia-redux/custom_hero_clash_issues/issues/1368

**Comment by PonyashaWright** [comment]
Huh, @Draze22 said it was a bug when I asked him to make sure lmao

**Comment by Draze22** [comment]
We probably just need to write/improve tooltips to explain the inconsistency.
