### ISSUE TITLE
Venomous Gale Shard's Wards and Multicast have some weird interactions

### ISSUE THREAD

**Issue by PonyashaWright** [arcadia-redux/custom_hero_clash_issues#2177]
Venomous Gale makes it possible to have x5-x12 multicasted wards, which isn't possible with regular wards or any summons

![image](https://user-images.githubusercontent.com/77478706/176801523-694fd8a6-a329-4ee1-9345-d814ba031cc2.png)

**Comment by Draze22** [comment]
This is intentional, when Venemous Gale is cast it creates a stronger Plague Ward for every enemy hit by it, including for every enemy hit by it when it's Multicast.
