### ISSUE TITLE
Spellcraft mastery doesn't seem to be working at all

### ISSUE THREAD

**Issue by PonyashaWright** [arcadia-redux/custom_hero_clash_issues#2178]
Not sure if this is a demo mode issue, or ingame as well, but the one who reported it claims that ingame it doesn't work as well.

![image](https://user-images.githubusercontent.com/77478706/176802907-33aa39d9-0d6b-4478-9e92-4e424d108147.png)
![image](https://user-images.githubusercontent.com/77478706/176802928-929f9b59-915d-4385-b6ab-232c96a5303b.png)

**Comment by lovro-m** [comment]
After testing I've concluded that dummies do not trigger damage filters for the spell amp. Otherwise spellcraft works fine on everything else (heroes and creeps) so this can be closed.
