### ISSUE TITLE
Vengeful Spirit's 25 lvl Magic Missile talent and Magus

### ISSUE THREAD

**Issue by PonyashaWright** [arcadia-redux/custom_hero_clash_issues#2191]
If Vengeful Spirit takes 25 lvl talent "Magic Missile Pierces Magic Immunity", Magus innate still won't cast Magic Missile into magic immune enemies

**Comment by ZLOY5** [comment]
It can be easily fixed specifically for Magic Missile, but Magus have tons of issues like that with other abilities, we sure we want bother with this?

**Comment by Draze22** [comment]
Do we fix abilities not being procced by Magus by just adding them to a list?

**Comment by ZLOY5** [comment]
If we just add Magic Missile to list it will proc Magus event if hero has no shard

**Comment by ZLOY5** [comment]
Talent i mean, not shard

**Comment by Draze22** [comment]
I say it's worth fixing all the individual Magus bugs
