### ISSUE TITLE
Skills sometimes get stuck while swapping

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2193]
Not sure how to reproduce this yet, the following thread has some information that might help in narrowing down the cause: (Skill swapping bug in #bug-reports) https://discord.com/channels/694060511209324585/994235274404036708/994491963124498472.

**Comment by jakmarles** [comment]
Test this,
I think what cause it maybe be when 2 people from the same team send each other a trade for the same trade

**Comment by Draze22** [comment]
Still not sure exactly how to reproduce this, we traded abilities a lot until eventually we couldn't trade chemical rage anymore.

![Uploading image.png…]()
