### ISSUE TITLE
Illusions can proc Static Field

### ISSUE THREAD

**Issue by PonyashaWright** [arcadia-redux/custom_hero_clash_issues#2194]
Illusion's Static Field is amplified by magic amp (while it shouldn't), so it can deal insane amounts of damage

https://user-images.githubusercontent.com/77478706/177894164-ceb5c25a-dc07-4d72-9e00-accab4035fbd.mp4

**Comment by Draze22** [comment]
Illusions should be able to proc Static Field at all.

**Comment by PonyashaWright** [comment]
> Illusions should be able to proc Static Field at all.

Shouldn't
