### ISSUE TITLE
Prevent the Evasion mastery from evading Numb's delayed damage

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2196]
Not entirely sure, but this seems to be the reason that this combo is so strong.

**Comment by Draze22** [comment]
After testing it some more it seems like Evasion could never reduce Numb's self damage so this fix might not actually change anything.

**Comment by ZLOY5** [comment]
You still can see number if damage evaded with Evade mastery, but damage really not dealt

**Comment by Draze22** [comment]
I was basing it on how long it took me to die with just evasion compared to with both evasion and numb.

**Comment by jakmarles** [comment]
A simple shivas/skadi + pipe and a good damage output destroies this combo,
The core thing that makes this combo good is the ability to regenerate health fast enough to neglect the damage return and evasion increases the ability to regenerate said amounts of hp,
A simple ice blast can completely ruin this combo same goes for spells with big amounts of damage over time like jakiro/bane ultis or even high attack summoners with good attack speed
