### ISSUE TITLE
Players can somehow get 4 stacks of Revenge (mastery's buff)

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2199]
![image](https://user-images.githubusercontent.com/63279022/178134130-8e103e85-f94a-4db7-a756-a0de57f3792e.png)

![image](https://user-images.githubusercontent.com/63279022/178134136-5317c6cb-a152-4b02-b492-6f337d3bb5e8.png)

![image](https://user-images.githubusercontent.com/63279022/178134112-791295b4-3a93-49cc-a512-3072cce14a6b.png)

**Comment by PonyashaWright** [comment]
It happens if you lose all aegises except one and die on a creep wave. For some reason it makes you gain 2 stacks of Revenge instead of one.
