### ISSUE TITLE
no interface

### ISSUE THREAD

**Issue by wCotito** [arcadia-redux/custom_hero_clash_issues#2211]
![20220717001437_1](https://user-images.githubusercontent.com/101218004/179372110-a9a5276e-36f6-47b0-888c-897b54268014.jpg)
![20220717000227_1](https://user-images.githubusercontent.com/101218004/179372120-fb6d72ee-b03c-4d46-95f0-305d1d2891b0.jpg)

**Comment by ZLOY5** [comment]
Is it your game or you spectating?
How often this happens for you?
You tried reconnect to the game?

**Comment by wCotito** [comment]
These are my games. I tried reconnecting. Since the last update, this has always happened.
Checking DotA files for integrity helped.

**Comment by ZLOY5** [comment]
https://discord.com/channels/694060511209324585/694060511209324588/999385905200627794
One more guy complaining same issue
