### ISSUE TITLE
Losing the Revenge (Mastery) aegis in a duel doesn't give a stack of Revenge

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2222]
A stack of Revenge being the +5% damage reduction/outgoing damage buff.

https://www.youtube.com/watch?v=93KNYkIqPt0

**Comment by ZLOY5** [comment]
Seems i broke it after https://github.com/arcadia-redux/custom_hero_clash_issues/issues/2199
