### ISSUE TITLE
If both allies in a Duos duel are reincarnating (WK ult) at the same time they lose the duel

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2230]
https://www.youtube.com/watch?v=YeX5771-GGc

**Comment by jakmarles** [comment]
Wait that's a bug? It been like this for years now

**Comment by ZLOY5** [comment]
I can't reproduce it

**Comment by Draze22** [comment]
Nevermind, that video doesn't show what I thought it did and this bug doesn't exist.
