### ISSUE TITLE
Charges can somehow go negative

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2231]
![image](https://user-images.githubusercontent.com/63279022/182016256-043d71b0-5acd-41f2-a1b3-92f14b2de7df.png)

**Comment by Draze22** [comment]
Apparently this happened after the Grand Librarian retraining book was used.

**Comment by AustraliaIsMyCity** [comment]
fixed: https://github.com/arcadia-redux/custom_hero_clash/commit/98b2dd9ad075c01d5a15839939c228f66e96b386
