### ISSUE TITLE
Shackles isn't affected by status resistance

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2232]
Related to #2217.

**Comment by ZLOY5** [comment]
Technically target's status resistance should reduce ability channel time?

**Comment by Draze22** [comment]
Yes it should and currently it doesn't in CHC.

**Comment by AustraliaIsMyCity** [comment]
fixed https://github.com/arcadia-redux/custom_hero_clash/commit/53d1ebf43395c6c48bad543d24220ed41a376bf5
