### ISSUE TITLE
оплата доната

### ISSUE THREAD

**Issue by borodec** [arcadia-redux/custom_hero_clash_issues#2234]
зачисления так и не прошли id236757922, проверьте пожалуйста

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/182042382-14e8678a-ed8d-4881-b113-8a41fa9e8464.png)
![image](https://user-images.githubusercontent.com/43399078/182042386-d367912a-f42a-45f8-9f57-f6f04fae74ac.png)
В новой игре должно всё работать.
