### ISSUE TITLE
UI too Crowded

### ISSUE THREAD

**Issue by rafael-24** [arcadia-redux/custom_hero_clash_issues#2238]
Can we have a setting where we can disable some of the UI? specially the text when finishing/winning duel it's too annoying.

I just wish the UI could be fixed to make it more spacious and understandable at the sametime.

Overall it's a better mod thanks for your hardwork!

**Comment by Draze22** [comment]
If you're talking about the barrage text (the text that floats across the screen) it can be turned off in settings (next to your innate) by reducing the barrage opacity to 0%.

**Comment by rafael-24** [comment]
Yeah I've noticed that. I guess you guys can close this. Thanks!
