### ISSUE TITLE
Purification Frosthaven only works on allied heroes and creep heroes

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2241]
It should work on all allied units.

**Comment by lovro-m** [comment]
well this is written in kvs:
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_FRIENDLY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"SpellImmunityType"				"SPELL_IMMUNITY_ALLIES_YES"
		"AbilityTextureName"			"frostivus2018_omniknight_purification"
So I guess the only way is to rewrite?

**Comment by SanctusAnimus** [comment]
why do we even have frosthaven version, i thought we got rid of all of these kinds of spells

**Comment by lovro-m** [comment]
it's just AoE purification so that it's better than regular one

**Comment by Draze22** [comment]
If it has to be written, we can just reword the tooltip instead to reflect what it actually does.
