### ISSUE TITLE
prevent players from issuing orders outside of the bounds of their current arena

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#2245]
this will prevent any abuse relating to blinking to other arenas and instantly placing static storm or whatever before you are pulled back. add an 800 hundred unit leeway to prevent messing with players trying to path to the edge of their arena

**Comment by jakmarles** [comment]
Will to also affect cosmetics like the banner?

**Comment by AustraliaIsMyCity** [comment]
yes

**Comment by jakmarles** [comment]
Don't do it, you don't have my permission to do so

**Comment by ZLOY5** [comment]
@jakmarles with exception for cosmetic abilities

**Comment by AustraliaIsMyCity** [comment]
Why not just make cosmetics have global cast range?

**Comment by ZLOY5** [comment]
They have

**Comment by jakmarles** [comment]
Make sprays global please
