### ISSUE TITLE
Primal Beast's voicelines don't work

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2249]
Difficult to confirm since you have to spawn in as Primal Beats to use his voicelines (switch to him in Demo mode doesn't work).

**Comment by Snoresville** [comment]
What about chatwheel?

**Comment by Draze22** [comment]
I couldn't find a way to use the chatwheel for voicelines of other heroes, then again I've spent very little time using the CHC chatwheel.

**Comment by ZLOY5** [comment]
I will check it, 
And voice lines for other heroes disabled due to random sounds bug
