### ISSUE TITLE
Figure out the best way to prevent flying ranged creeps from getting knocked out of the arena

### ISSUE THREAD

**Issue by Copin11** [arcadia-redux/custom_hero_clash_issues#2252]
В игре на 73 волне крип вылетел за предел карты в следствии чего его было нельзя бить  номер матча 6717432767

**Comment by Draze22** [comment]
Flying creeps being able to be knocked outside the creep arena is an issue.

**Comment by jakmarles** [comment]
> Flying creeps being able to be knocked outside the creep arena is an issue.

you can use ghost / smoke / just move to the opposite side to make those creeps come back

**Comment by ZLOY5** [comment]
We have bounds enforcer, so creeps already should stay in arena, trees is only problem that i can imagine

**Comment by Draze22** [comment]
That's true and most melee heroes will have a Devastator which can destroy trees.
