### ISSUE TITLE
Duos Totem debuffs are dispellable

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2257]
They're reapplied immediately after being dispelled however they aren't applied or reapplied through bkb, and Demonic Cleanse (Shadow Demon Shard) lets players be unnaffected by the debuff for 7 seconds.

**Comment by Draze22** [comment]
This wasn't fixed, Totem debuffs are still dispellable.

**Comment by ZLOY5** [comment]
I misreaded issue and done completely weird thing, lol
