### ISSUE TITLE
Magus doesn't have an increased cooldown when it procs on player controlled units

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2259]
This is most important for abilities like Winters Curse and  Omnislash since they can also effect the enemy hero but when they're procced on the hero's summon they have a much lower cooldown.

**Comment by ZLOY5** [comment]
For me Magus have 5 sec cooldown when procs Omnislash on Bear or another summon

**Comment by Draze22** [comment]
> For me Magus have 5 sec cooldown when procs Omnislash on Bear or another summon

I forgot that Omnislash always uses the hero cooldown.
