### ISSUE TITLE
Tree grab not working properly

### ISSUE THREAD

**Issue by lexchi** [arcadia-redux/custom_hero_clash_issues#2262]
There is no way to pick up a tree via Tiny Tree Grab. Nothing happens when you click on the object. The same issue appears for iron branch planted trees. 

However, sometimes it's possible to grab a tree after several "skill icon swappings". Still, even that works with a random success rate.
Reproduced on tiny himself and both melee and ranged heroes.

**Comment by Draze22** [comment]
Duplicate issue that will be fixed next update.
