### ISSUE TITLE
Add Flame Cloak as a Scepter ability granted by Laguna Blade

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2267]

**Comment by lovro-m** [comment]
Adding flame cloak on non lina heroes does not grant flying movement. We can add the vanilla ability for now, but it will need a fix later.

**Comment by lovro-m** [comment]
This PR is a temporary fix.

**Comment by ZLOY5** [comment]
Actually all heroes have flying movement, just not visually
