### ISSUE TITLE
Prevent Voodoo Restoration from being affected by spell amp

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2268]
If possible only prevent Witch Doctor's +1.5% max health Voodoo Restoration heal/damage talent from being affected by spell amp.

**Comment by lovro-m** [comment]
I don't know if it's possible to disable only the talent portion of the damage, but I can disable spell amp for the entire damage with or without the talent. Is that okay?

**Comment by Draze22** [comment]
> I don't know if it's possible to disable only the talent portion of the damage, but I can disable spell amp for the entire damage with or without the talent. Is that okay?

Disabling spell amp with and with the talent is fine.
