### ISSUE TITLE
liquid frost bug

### ISSUE THREAD

**Issue by Ebash1** [arcadia-redux/custom_hero_clash_issues#2273]
liquid frost не наносит урон и не замораживает цель если включены стрелы медузы split shot

**Comment by Ebash1** [comment]
Без таланта на 25 уровне.

**Comment by lovro-m** [comment]
Also applies to liquid fire. After the attack one of the split shot arrows takes the modifier (fire or ice) and the spell goes on cooldown. This means other arrows cannot take the modifier. @Draze22 I think this works as intended, what do you think?

**Comment by Draze22** [comment]
Moved to https://github.com/arcadia-redux/custom_hero_clash_issues/issues/2314
