### ISSUE TITLE
false promise

### ISSUE THREAD

**Issue by genkagenka** [arcadia-redux/custom_hero_clash_issues#2275]
when use false promise on yourself - spend yourself HP

**Comment by lovro-m** [comment]
Do you maybe have more information? I cannot replicate the bug and the spell is original from valve. Maybe your innates, masteries or other spells.

**Comment by genkagenka** [comment]
записал, только через файлообменник могу скинуть:(

**Comment by Draze22** [comment]
This is caused by the Colossus mastery and from memory last time we discussed this interaction we decided not to bother fixing it (or maybe couldn't fix it).

**Comment by Draze22** [comment]
Link to the original discussion: https://github.com/arcadia-redux/custom_hero_clash_issues/issues/1867.
