### ISSUE TITLE
Essence Shift procs on illusions

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2289]

**Comment by Draze22** [comment]
@AustraliaIsMyCity Think we should let it proc on illusions but make it treat them as creeps? Btw it currently treats them as heroes.

**Comment by AustraliaIsMyCity** [comment]
no its good enough already, will just make it not work at all

**Comment by AustraliaIsMyCity** [comment]
fixed https://github.com/arcadia-redux/custom_hero_clash/commit/15c314dd4a95f98297b80421a5f854b575c246fb
