### ISSUE TITLE
Rework Lucky Shot to only get procced by attack and damage instances from Pangolier's abilities

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2291]
It can quite easily keep creeps perma disarmed when combined with something like Blood Mist.

**Comment by AustraliaIsMyCity** [comment]
yup, removed for now until we can decide on and implement a rework, perhaps just revert it to only proc on attack?

**Comment by Draze22** [comment]
> yup, removed for now until we can decide on and implement a rework, perhaps just revert it to only proc on attack?

Probably just make it so only Pango abilities can proc it.
