### ISSUE TITLE
Dark Willow's Bedlam pierces magic immunity talent doesn't work on Bedlam Frosthaven

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2292]

**Comment by ZLOY5** [comment]
If we strictly need frosthaven version only rewrite can help

**Comment by Draze22** [comment]
@AustraliaIsMyCity should we switch to vanilla Bedlam or rewrite?

**Comment by jakmarles** [comment]
vanilla Bedlam will be useless

**Comment by AustraliaIsMyCity** [comment]
Why dont we just remove the talent tho

**Comment by Draze22** [comment]
> Why dont we just remove the talent tho

Sure, that is a third option.

**Comment by lovro-m** [comment]
Well after looking at it for a while. Bedlam cannot be rewritten without rewritting terrorize because it gets deactivated when jex is a projectile. If you really want I can rewrite both, but it will take some time. I am open to suggestions for the third option of removing the talent.

**Comment by AustraliaIsMyCity** [comment]
Remove the talent

**Comment by lovro-m** [comment]
And replace it with what?

**Comment by Draze22** [comment]
> And replace it with what? +322 damage

30 int will do.
