### ISSUE TITLE
Ghost Scepter doesn't work when used immediately upon reviving with an Aegis

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2300]
From memory this was too hard/impossible to fix, close this if that's still the case.

**Comment by ZLOY5** [comment]
![image](https://user-images.githubusercontent.com/10956575/188279292-c576b930-7d98-4045-837a-e7e39f1d4e3b.png)
And aegis give spell immunity first 1.25 sec after respawn

**Comment by ZLOY5** [comment]
@Draze22 got idea make Ghost Scepter not usable while hero is magic immune, so you can't just waste it

**Comment by Draze22** [comment]
> @Draze22 got idea make Ghost Scepter not usable while hero is magic immune, so you can't just waste it

Why does aegis respawn give magic immunity?

**Comment by ZLOY5** [comment]
Idk, maybe to prevent hero immediately killed/rooted/stunned after respawn or so

**Comment by Draze22** [comment]
How about we change it from magic immunity to untargetability. @AustraliaIsMyCity thoughts?

**Comment by AustraliaIsMyCity** [comment]
Just give invulnerability and a strong dispel on spawn

**Comment by Draze22** [comment]
> Just give invulnerability and a strong dispel on spawn

Sure, this should work too.
