### ISSUE TITLE
Magus can't proc Open Wounds

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2303]

**Comment by ZLOY5** [comment]
![image](https://user-images.githubusercontent.com/10956575/188304703-12f2cd20-ecbd-473b-ba52-e5c583ed3bc4.png)

**Comment by PonyashaWright** [comment]
I can confirm that it doesn't proc tho. Was playing with Finger of Death and Open Wounds recently. Open Wounds weren't proccing at all, while Finger was proccing all the time.

**Comment by Draze22** [comment]
> ![image](https://user-images.githubusercontent.com/10956575/188304703-12f2cd20-ecbd-473b-ba52-e5c583ed3bc4.png)

I have no idea how you got it to work, playing demo mode on the current version of the game with the same setup it doesn't work for me ever.
