### ISSUE TITLE
Exsorcism

### ISSUE THREAD

**Issue by ehtanaise** [arcadia-redux/custom_hero_clash_issues#2304]
Заюзал 04.09.2022 экзорцизм на хускаре - пролаг жетский, в будущем кикнуло когда заюзал перед боем

**Comment by ZLOY5** [comment]
Maybe we can try increase damage and reduce spirits count?

**Comment by Draze22** [comment]
Exorcism only really causes lag when you have Aghanim's Scepter combined with a lot of attack per second.
