### ISSUE TITLE
Vanilla Split Shot bugs

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2314]
@AustraliaIsMyCity should we fix these bugs since we have a custom Split Shot?

- [ ] Auto-cast abilities (Poison Attack) use extra mana for each target hit by split shot attacks despite the split shot attacks not using the auto-cast
- [ ] Auto-cast abilities with cooldowns (Liquid Fire) are put on cooldown and not activated if a split shot attack hits a target before the primary attack does
- [ ] Modifiers with charges that are used on attack (Overpower) are consumed by each split shot attack

**Comment by jakmarles** [comment]
i'd say you should those are pretty annoying

**Comment by SanctusAnimus** [comment]
none of these are related to split shot itself and none of them can be fixed with split shot itself

**Comment by AustraliaIsMyCity** [comment]
Wont be fixed, also until today we didnt even have custom split shot
