### ISSUE TITLE
Our custom Battery Assault is dispellable 

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2317]
@AustraliaIsMyCity we could also just revert back to using vanilla Battery Assault since Clockwerk's new Scepter gives it the same modification we did (except reliant on Overclocking's cd and duration).

**Comment by AustraliaIsMyCity** [comment]
ya we can revert

**Comment by AustraliaIsMyCity** [comment]
can reproduce in chc, testing in vanilla demo now

**Comment by AustraliaIsMyCity** [comment]
ITS NOT DISPELLABLE IN VANILLA WHJAT

**Comment by AustraliaIsMyCity** [comment]
?????????????????????????????????????????????

**Comment by AustraliaIsMyCity** [comment]
what kind of black magic is this

**Comment by AustraliaIsMyCity** [comment]
we use a modifier filter to use custom version, will simply remove that
