### ISSUE TITLE
Nosedive not appear even with Viper corrosive skin with aghs

### ISSUE THREAD

**Issue by muhasyafiq** [arcadia-redux/custom_hero_clash_issues#2319]
Pretty sure it's written in the patch that nosedive is linked to Corrosive skin, i'm a Viper with Corrosive skin and aghs, still no nosedive
![Image 2022-09-10-(14-12-59)](https://user-images.githubusercontent.com/111621066/189473462-1a562975-544c-49ba-b500-ed3c21f6da8e.png)

**Comment by Draze22** [comment]
Fixed next update.
