### ISSUE TITLE
Buying Aghnaim's Shard as Shadow Demon with Demonic Purge crashes the server

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#2322]
![EC832FB1-5D12-4D4F-8725-AFDD425D0A75](https://user-images.githubusercontent.com/50186248/189785668-b9eeb774-282a-49d8-8558-e5cd8d46fc90.jpeg)

**Comment by Draze22** [comment]
Reproduced this, only crashes the server if you're Shadow Demon.
