### ISSUE TITLE
Right side of the end scoreboard is cut off in narrow aspect ratios

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#2324]
16:9
![image](https://user-images.githubusercontent.com/50186248/190293798-1c263d80-7ae5-4d7d-adfa-8985f35c25c2.png)
16:10
![image](https://user-images.githubusercontent.com/50186248/190293706-45c864c5-43d8-4c1e-b0be-853b7958080a.png)
16:12
![image](https://user-images.githubusercontent.com/50186248/190293883-4b93867b-f1f4-4d60-b51a-fe1b6cb4d88b.png)

**Comment by ZLOY5** [comment]
![image](https://user-images.githubusercontent.com/10956575/190425362-b5fa5877-b7db-49ea-a7ad-0a51b90bfbe5.png)
Сan't think of anything better w/o full redesign
