### ISSUE TITLE
Scepter effects and talents that give 2 charges cause the ability to have no cooldown

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2336]
![image](https://user-images.githubusercontent.com/63279022/192339757-e55798f3-f6c8-43ba-9e6d-567f9fd75ba4.png)

**Comment by ZLOY5** [comment]
wtf

**Comment by ZLOY5** [comment]
Now i checked every charged ability and all should be fine
