### ISSUE TITLE
Refresher Orb has it's cooldown reset when taken from the stash

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2338]
1. Use Refresher Orb during a duel.
2. After the duel put Refresher Orb in your stash/backpack.
3. When you take the Refresher Orb out of your stash/backpack its cooldown will be set to what it would be if it had never been refreshed after the duel ended. In other words it will be reset to 180s - the time since it was last used (excluding time it wasn't in your inventory).

**Comment by Draze22** [comment]
Technically happens in vanilla Dota too but there's no way to refresh Refresher Orb in vanilla Dota so Valve may never notice/fix this bug.

**Comment by ZLOY5** [comment]
Decided to not refresh Refresher after duels nad Aegis & fixed bugs with cooldown speed in fountain
