### ISSUE TITLE
Highlight mastery expiration dates which are in the past on the player profile page

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/custom_hero_clash_issues#2352]
preferably like a readable shade of red.
also add a column which says when they expire in relative time in days, hours, minutes (e.g. `4 days 6 hours 23 minutes` (white text), `0 days 12 hours 32 minutes ago` (red text)

Opened from Discord by **Luminance#9760**

**Comment by AustraliaIsMyCity** [comment]
@SanctusAnimus pretty sure you can close and claim this now

**Comment by SanctusAnimus** [comment]
oh yeah, implemented
