### ISSUE TITLE
Make Voodoo Restoration affected by Torture Pipe

### ISSUE THREAD

**Issue by PonyashaWright** [arcadia-redux/custom_hero_clash_issues#2353]
Obviously, this shouldn't affect Witch Doctor's +1.5% VR damage/heal talent.

**Comment by Draze22** [comment]
Doesn't seem like it's possible to only amp the base damage: https://github.com/arcadia-redux/custom_hero_clash_issues/issues/2268.

**Comment by lovro-m** [comment]
Unless we rewrite the ability and separate it into 2 damage instances
