### ISSUE TITLE
Improve duel frequency

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2367]
Currently duel frequency is an integer which leads to games with different numbers of players having significantly different numbers of duels. For example in FFA games with 3 players left and 6 players left have equally frequent duels.

I'm proposing we vary the number of rounds between duels to ensure that players on average participate in the same number of duels per x number of rounds regardless of how many teams are left. This will often require not having a consistent number of rounds between duels, for example with 7 players left duels might happen on rounds 1, 2, 4, 5, 7, 8 and 10 instead of rounds 1, 2, 3, 4, 5, 6, 7, 8, 9 and 10.

The check for how many rounds have passed since the last duel will also need to be changed to exclude boss rounds and greevil rounds as rounds that occured since the last duel.

**Comment by Draze22** [comment]
The goal here is to:

1. Have players participate in roughly the same number of duels over the course of each game (assuming they die on the same round).
2. Make innates like Winner and Momentum equally good in FFA, Duos and Enfos, and more consistent in general. Unfortunately it doesn't solve the problem of Sunk Cost being worse the fewer players are left.

**Comment by AustraliaIsMyCity** [comment]
im like 80% sure this already works in the chc_endless branch lol

**Comment by AustraliaIsMyCity** [comment]
Well, it wasn’t, but its a one line fix, so done https://github.com/arcadia-redux/custom_hero_clash/commit/e759041e5db61cc078e1c7c65ff3362b09f8f366

**Comment by Draze22** [comment]
> Well, it wasn’t, but its a one line fix, so done [arcadia-redux/custom_hero_clash@e759041](https://github.com/arcadia-redux/custom_hero_clash/commit/e759041e5db61cc078e1c7c65ff3362b09f8f366)

That only fixes duel frequency ignoring non-duel rounds, did you already make the other change?

**Comment by AustraliaIsMyCity** [comment]
that commit allows for float intervals, a previous rewrite of the function already removed counting invalid pvp rounds towards the rounds since last pvp counter
