### ISSUE TITLE
Не улучшаются вехи

### ISSUE THREAD

**Issue by ArisHard** [arcadia-redux/custom_hero_clash_issues#2370]
2 раза улучшил вехи , ни одна не апнулась

**Comment by Draze22** [comment]
> 2 раза улучшил вехи , ни одна не апнулась

We need more information to know what went wrong.

**Comment by ArisHard** [comment]
Извините , улучшил до 2 уровня и дождался 30 дней 2 вехи. На дальность атаки и на дополнительный урон. Ни одна не улучшилась. В улучшение стояла веха на весь урон заклинаний , щас зайду посмотрю , но думаю что и она не улучшилась

**Comment by ArisHard** [comment]
https://steamcommunity.com/profiles/76561198865582156/

Если вдруг нужна , то вот моя ссылка)

**Comment by ArisHard** [comment]
> > 2 раза улучшил вехи , ни одна не апнулась
> 
> We need more information to know what went wrong.

up
