### ISSUE TITLE
Players can tie in duels

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#253]
Seems to be because of the slight delay between a player winning a duel and them getting full healed and teleported to fountain. Alternatively if I'm mistaken and their is no delay it's probably caused by both players dying in the same game tick which might not be able to be fixed.

This seems like a very similar problem to #203 . 

On a side note it seems kinda cool to be able to tie duels so I personally wouldn't be against leaving it in the game.

![image](https://user-images.githubusercontent.com/63279022/83622782-c7fab400-a5d3-11ea-9e3e-ea09ce91bd1a.png)
![image](https://user-images.githubusercontent.com/63279022/83622807-d2b54900-a5d3-11ea-9c39-a4159ae78a89.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/2i2HPPp2) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/83717322-caade580-a675-11ea-981d-582de3c5165e.png)

**Comment by Draze22** [comment]
In addition to causing both players to win duel dividends and all players who bet to receive their winnings players can win jackpots and both players who participated in the duel will gain an extra level (likely due to levels being granted to duel participants when the duel is won and both players winning means that triggers twice).

**Comment by Draze22** [comment]
It seems like if the two players would have tied but one of them has reincarnation then the bug below occurs.

![image](https://user-images.githubusercontent.com/63279022/93970160-df42f480-fdb0-11ea-9f48-05cec8603502.png)

**Comment by AustraliaIsMyCity** [comment]
In the 10 to 20 times I've seen this happen its always been caused by blademail, I suspect that means that the pvp module is checking on a timer rather than listening for a death. This is definitely fixable.

**Comment by fcalife** [comment]
nuke it to the ground and build it again
