### ISSUE TITLE
Could add a message at the start of a game as to whether or not the game will be scored

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#273]
![image](https://user-images.githubusercontent.com/63279022/85194386-de617900-b310-11ea-9423-5ff092857a74.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/2zTxREjj) by [Unito](https://www.unito.io/learn-more)

**Comment by AustraliaIsMyCity** [comment]
this has been implemented
