### ISSUE TITLE
Passive buff aura abilities (luna blessing, precision aura) sometimes stop working after losing a duel

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#289]
![image](https://user-images.githubusercontent.com/63279022/85937401-80ebae80-b946-11ea-8bf0-66d1fb1b065b.png)
![image](https://user-images.githubusercontent.com/63279022/85937406-8a751680-b946-11ea-87b0-f12e4043a5fc.png)

**Comment by fcalife** [comment]
This might just be the old precision aura bug that got fixed when it was reworked. I'll wait for confirmation.

**Comment by Draze22** [comment]
Looks like this bug also applies to marksmanship.

![image](https://user-images.githubusercontent.com/63279022/90224708-6ff1f080-de53-11ea-8855-9b82b6dd2fd6.png)

**Comment by AustraliaIsMyCity** [comment]
This was never confirmed and has not been seen for months, especially since precision aura's bugginess was fixed. If there's another report I'll reopen but I doubt it

**Comment by fcalife** [comment]
![image](https://user-images.githubusercontent.com/7921728/102961409-f635d780-44c2-11eb-99db-ab92e252bc8b.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/120270243-9868af80-c2ec-11eb-8f8b-c9c8f85b9e04.png)

**Comment by Draze22** [comment]
This could explain this bug but i don't have an easy way to test it.
![image](https://user-images.githubusercontent.com/63279022/121810261-7fc0a800-cca3-11eb-905f-9271e489a38e.png)

**Comment by Draze22** [comment]
I'm not 100% sure but it seems to be that whenever you lose a duel and gain a curse, all of you passive auras stop working for a few rounds. 
![image](https://user-images.githubusercontent.com/63279022/122641275-9ce3f380-d147-11eb-9441-c801bf08c747.png)

**Comment by Draze22** [comment]
This may not have been fully fixed.

![image](https://user-images.githubusercontent.com/63279022/129657828-a9bef450-da25-4381-abd2-50a56b7a5603.png)
