### ISSUE TITLE
Gambler sometimes doesn't work.

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#313]
Currently gambler seems to not work the first time the player tries to use it but does work every subsequent time.

![image](https://user-images.githubusercontent.com/63279022/87224116-f08d7f00-c3c5-11ea-9ccf-7b42ee986c05.png)

**Comment by Draze22** [comment]
Gambler was fixed from a point where it never worked but there still seems to be cases where it doesn't work. It's unclear what causes it to not work. It being a problem in FFA only and only when the player randoms their hero were found to not be the cause.

**Comment by Draze22** [comment]
Currently gambler seems to not work the first time the player tries to use it but does work every subsequent time.

**Comment by Draze22** [comment]
![Uploading image.png…]()

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/99921291-93df9f00-2d7d-11eb-9f0d-39c21fe863e8.png)

**Comment by Snoresville** [comment]
fixed in the update
https://github.com/dota2unofficial/custom_hero_clash_issues/issues/313

**Comment by Draze22** [comment]
This is happening again.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/106424232-f360d600-64b5-11eb-900f-e4b621f973eb.png)

**Comment by Snoresville** [comment]
WHAT THE FUUUUUUUUUUUCK

**Comment by AustraliaIsMyCity** [comment]
still seeing reports of this today

**Comment by ZLOY5** [comment]
Pushed 1 more commit with fix yesterday, so waiting for update and confirmation

**Comment by AustraliaIsMyCity** [comment]
we did it!
