### ISSUE TITLE
If a player first connects to the game during a duel they are teleported to their creep arena and fully healed.

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#335]
![image](https://user-images.githubusercontent.com/63279022/87843335-126f9000-c8f7-11ea-90e6-aadf90c2c719.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/Kuu3SgDC) by [Unito](https://www.unito.io/learn-more)

**Comment by AustraliaIsMyCity** [comment]
Made the title a much better description of the bug
