### ISSUE TITLE
Duel wins occur multiple times when multiple players die in the same game tick

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#354]
![image](https://user-images.githubusercontent.com/63279022/88396709-41f62f00-ce06-11ea-8934-86155ed9962f.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/DSoh8MNj) by [Unito](https://www.unito.io/learn-more)

**Comment by AustraliaIsMyCity** [comment]
This happens when multiple players die on the same damage tick (Things like caustic finale in duos/squads and blademail in ffa are common causes)

**Comment by Draze22** [comment]
![Uploading image.png…]()
