### ISSUE TITLE
Make it easier to manually change the bet amount

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#358]
Currently only a very small portion of the box that contains the bet amount can be clicked on to change the bet amount manually.

┆Issue is synchronized with this [Trello card](https://trello.com/c/yxR0QW6K) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
This is still relevant, the hitbox for editing bets could be bigger

**Comment by Sheodar** [comment]
Added
