### ISSUE TITLE
Overtime ending doesn't kill the player and end the round

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#362]
![image](https://user-images.githubusercontent.com/63279022/88757487-8b999d80-d1a9-11ea-8659-65d7d0cc6603.png)
![image](https://user-images.githubusercontent.com/63279022/88757493-8dfbf780-d1a9-11ea-9f69-dcb8ee8856e1.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/U06NJ8LX) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
After testing this semi-extensively, I have witnessed it happening in tools, but couldn't figure out why.

My current theory is that sometimes, something goes wrong in this block of code:

https://github.com/dota2unofficial/custom_hero_clash/blob/0d9e72f5df8303d871f76b4d971856674247e85b/game/scripts/vscripts/game/round.lua#L805-L816

That causes the actual 'killing' part (this block: https://github.com/dota2unofficial/custom_hero_clash/blob/0d9e72f5df8303d871f76b4d971856674247e85b/game/scripts/vscripts/game/round.lua#L824-L834) to never execute.

The player's hero abilities don't seem to matter. A fresh pair of eyes would probably figure this issue out better than me continuing to bash my head against it. Good luck!

**Comment by 56kyle** [comment]
was already fixed in a duplicate issue https://github.com/dota2unofficial/custom_hero_clash_issues/issues/425e

**Comment by Draze22** [comment]
This is actually a different issue where overtime ending doesn't do anything sometimes and is an ongoing issue.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/107223988-f4bc7080-6a6a-11eb-8e31-e4f31c3dabcd.png)
![image](https://user-images.githubusercontent.com/63279022/107224043-09006d80-6a6b-11eb-92c5-9c6de5901d9d.png)
