### ISSUE TITLE
Maybe we should add DPS meter per-wave and total counter

### ISSUE THREAD

**Issue by SanctusAnimus** [arcadia-redux/custom_hero_clash_issues#372]
So you can actually see weight of every yours decision, obviously shared to team so you can compete on this and actually tell who's da boss in that game

Design: https://docs.google.com/document/d/1sZr6WxI1TibMFEc8UI2NLuVDUp7Y6m_pVHaBmEBym0w

**Comment by AustraliaIsMyCity** [comment]
should also include a death report when you lose duels
