### ISSUE TITLE
Victory Panel

### ISSUE THREAD

**Issue by natoshi** [arcadia-redux/custom_hero_clash_issues#375]
![image](https://user-images.githubusercontent.com/3074666/80220513-9eea1980-864c-11ea-9254-6cd945997218.png)

* [x] Layout
* [x] Data binding
* [x] Particle Effects
* [x] Sound Effects

┆Issue is synchronized with this [Trello card](https://trello.com/c/xa8MtTnO) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
this has been finished a long time ago, can we credit it to sheodar?

**Comment by Sheodar** [comment]
Added sounds/fixes styles
