### ISSUE TITLE
In duos you can give a book of paragon to your team mate allowing them to get 2 extra abilities

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#38]
![image](https://user-images.githubusercontent.com/50186248/78635529-ca010900-78e9-11ea-8d15-3c686fc27ac0.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/113085297-4b545880-922b-11eb-94f1-2e11e7b8ee04.png)
![image](https://user-images.githubusercontent.com/63279022/113085369-66bf6380-922b-11eb-8b9a-c896d26b3c04.png)

**Comment by AustraliaIsMyCity** [comment]
THIRTY EIGHT LMFAO

**Comment by fcalife** [comment]
I can give a teammate the book, but its muted and they can't use it. Could this be due to something else?

**Comment by Draze22** [comment]
Closing this for now since it can't be confirmed and there have been no more reports.
