### ISSUE TITLE
Change the scoreboard to show each player's networth in the scoreboard in duos and squads

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#428]
You used to be able to see this information with the old UI but with the new UI you can only see the team's total networth even in the most detailed version of the scoreboard.

┆Issue is synchronized with this [Trello card](https://trello.com/c/6zNNtyfA) by [Unito](https://www.unito.io/learn-more)

**Comment by Sheodar** [comment]
U can see personal NW in full view:
![image](https://user-images.githubusercontent.com/23509297/114598779-f688f700-9c9a-11eb-8699-b2937352cf7c.png)
And team's NW in short or middle view:
![image](https://user-images.githubusercontent.com/23509297/114598824-043e7c80-9c9b-11eb-99d5-e70770e6ec00.png)
![image](https://user-images.githubusercontent.com/23509297/114598842-099bc700-9c9b-11eb-9c7c-3b3485925b11.png)
