### ISSUE TITLE
Pick innate later button disappears if you click it while the skill selection is overlayed on top of it

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#451]
![image](https://user-images.githubusercontent.com/63279022/91503929-18518b80-e90f-11ea-84af-86c9b2452188.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/q303rgI1) by [Unito](https://www.unito.io/learn-more)

**Comment by cenalulu** [comment]
This happen to me once. After choosing 'select later' for innate, and when the skill selection overlays on top of the 'select innate' tab, the 'select innate' tab is actually clickable. If we click that, innate selection window won't pop up and the button then disappear permanently. Reconnect also doesn't solve the issue

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/99469921-e729aa00-2997-11eb-950d-4c29465d0381.png)

**Comment by SanctusAnimus** [comment]
Should be fixed now
