### ISSUE TITLE
Improve Russian Translation

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#475]
Much of the texts are not localized in Russian yet, for example, the innates are mostly not localized.

┆Issue is synchronized with this [Trello card](https://trello.com/c/jNlEiAz3) by [Unito](https://www.unito.io/learn-more)

**Comment by darklordabc** [comment]
This is still a problem, need a Russian translator.

**Comment by Draze22** [comment]
The ability tooltips have been translated recently.

**Comment by Draze22** [comment]
Russian Translation is now an ongoing process.
