### ISSUE TITLE
Players can get stuck in the side wall of the ffa duel arena

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#479]
Probably just need to bring the arena boundary in a bit.

![image](https://user-images.githubusercontent.com/63279022/98794624-5fa2df00-245d-11eb-80ad-dc12aefbe1dd.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/1aBGUXwW) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
Perfect example of this bug:
![image](https://user-images.githubusercontent.com/63279022/118790790-6feab980-b8d9-11eb-8b50-055f57f78300.png)
![image](https://user-images.githubusercontent.com/63279022/118790952-94df2c80-b8d9-11eb-85c5-0d672e917969.png)

**Comment by ZLOY5** [comment]
I'm not sure how it even possible, because that area fully unpathable
![image](https://user-images.githubusercontent.com/10956575/118852058-13889980-b8db-11eb-8a4a-9f05ff1b6f12.png)

**Comment by Draze22** [comment]
> I'm not sure how it even possible, because that area fully unpathable

You can get pushed into that area by certain abilities although I don't know why only sometimes players get stuck there while other times they don't.

**Comment by Osamabinfrank** [comment]
Well since it already reported.. You can get there by using jetpack and if you time it right you can get stuck there. Nice feature but not that useful especially if you are melee hero

**Comment by Draze22** [comment]
I'm not sure we're ever going to bother trying to fix this. I'll let @fcalife and @darklordabc close this if they want to.
