### ISSUE TITLE
The bets on the current duel should uncollapse when the players view is teleported to the duel arena.

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#487]
If a player collapses it manually, this auto uncollapsing feature should disable itself if the player manually collapses the betting view after it automatically uncollapsed.

┆Issue is synchronized with this [Trello card](https://trello.com/c/b3Is5Nty) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
Pretty sure this is in the game, feel free to re-open if this issue is still relevant.
