### ISSUE TITLE
Replace the horrible winner end game screen

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#489]
This sucks
![image](https://user-images.githubusercontent.com/16277198/99245682-1802c580-2858-11eb-8847-f2a05f910224.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/t2ZPK820) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
Reopened since this is not a duplicate and is not done

**Comment by Sheodar** [comment]
Implemented
