### ISSUE TITLE
Players are not distributed properly in DUOS if the game starts with less than 12 players.

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#495]
The player distribution is worse than necessary when players start with fewer players. E.g. if you start with 12 people, there should be one team missing two players, but the shuffling is so dumb that it will sometimes make a two teams with one player in them each.

┆Issue is synchronized with this [Trello card](https://trello.com/c/VPDH4za1) by [Unito](https://www.unito.io/learn-more)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.
