### ISSUE TITLE
Allow Reordering Abilities on Tempest Double, Bear, any other clones. 

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#498]
![image](https://user-images.githubusercontent.com/16277198/99652328-cc485a00-2aab-11eb-9f8b-547d6cd7bc33.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/8F5a1QIM) by [Unito](https://www.unito.io/learn-more)

**Comment by SanctusAnimus** [comment]
Do we need reordering here or should i just fix order of abilities being different from owner?

**Comment by darklordabc** [comment]
No they should be able to reorder
