### ISSUE TITLE
If you win two duels in a row, remove Loser Curse

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#501]
Or remove loser curse when you are the only player remaining. Not sure, up for discussion.

┆Issue is synchronized with this [Trello card](https://trello.com/c/Y9FW6v5D) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
> Or remove loser curse when you are the only player remaining

fyi, this already happens

**Comment by AustraliaIsMyCity** [comment]
polled in discord to gauge opinion

**Comment by fcalife** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [If you win two duels in a row, remove Loser Curse #501](https://trello.com/c/gVuFxoF3/183-if-you-win-two-duels-in-a-row-remove-loser-curse-501)

**Comment by fcalife** [comment]
@AustraliaIsMyCity how's the verdict on this one? yes or no?

**Comment by fcalife** [comment]
bump

**Comment by AustraliaIsMyCity** [comment]
un bump it

**Comment by AustraliaIsMyCity** [comment]
go with 3 in a row removes 1 curse
