### ISSUE TITLE
Players that die after killing the creep wave don't get revived but can get put in duels

### ISSUE THREAD

**Issue by mmdts** [arcadia-redux/custom_hero_clash_issues#51]
Match ID: 5340487286
After minute 30, QoP dies to a dragon wave and simultaneously kills it. She is rolled in a duel after the wave, and she appears in the next duel dead. After duel ends, she revives in fountain

Apparently doesn't participate in any more rounds, so this isn't as big of an issue as I thought it was.

![image](https://user-images.githubusercontent.com/14915907/78695607-9c728a80-78fe-11ea-890b-bcdfce29d556.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/p2krHdSq) by [Unito](https://www.unito.io/learn-more)

**Comment by AustraliaIsMyCity** [comment]
only 1 instance of this ever occurring is known

**Comment by mmdts** [comment]
Second instance:
![image](https://user-images.githubusercontent.com/14915907/80243911-5d676780-8668-11ea-97e0-0b108f1dd5e4.png)

They can buy retraining books after selling their items and drop them to other people (he dropped a few reroll books and a paragon for gyro)... which is frankly broken as hell!

![image](https://user-images.githubusercontent.com/14915907/80244749-cac7c800-8669-11ea-9e00-7a09404a5663.png)

![image](https://user-images.githubusercontent.com/14915907/80245254-acae9780-866a-11ea-8b39-9b44de5c04d9.png)

**Comment by Draze22** [comment]
Died in round. stayed dead in fountain. stayed dead in upcoming duel. LOL (Elusive346)
![image](https://user-images.githubusercontent.com/63279022/81405238-9a5c4f80-917a-11ea-86d0-3cdea1825143.png)

From what I can tell the bug occurs when you kill the round and then die during the very short interval between the round ending and you getting teleported back to fountain. 

This is actually quite a problem since if these two events happen the other way round (you die in a creep round and shortly after all the creeps die to something like macropyre) you continue you get revived and continue playing.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/82029426-561d0200-96da-11ea-956e-7c563bb6166f.png)
![image](https://user-images.githubusercontent.com/63279022/82029460-61702d80-96da-11ea-9656-4a202cd7812f.png)

**Comment by Draze22** [comment]
The example below seems to indicate that using -suicide cause this bug to occur.

![image](https://user-images.githubusercontent.com/63279022/82030124-5bc71780-96db-11ea-85d0-207b55df39c3.png)
![image](https://user-images.githubusercontent.com/63279022/82030193-700b1480-96db-11ea-8d7f-c5012972baaf.png)

**Comment by mmdts** [comment]
But isn't the single cause ^
I and Merraven each witnessed this bug firsthand independently of each other without using -suicide

**Comment by SanctusAnimus** [comment]
Should be fixed, reopen if still occures

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/103252456-17218f80-49d1-11eb-9700-3b3794c8c4e1.png)
![image](https://user-images.githubusercontent.com/63279022/103252459-1a1c8000-49d1-11eb-9292-44287a13dead.png)

**Comment by mmdts** [comment]
Part of the conversation related to this issue (2021-03-04):
![image](https://user-images.githubusercontent.com/14915907/109912441-bfdfba00-7cb4-11eb-8e8e-f675069598e8.png)
![image](https://cdn.discordapp.com/attachments/694440472273354762/816876856959041546/unknown.png)
