### ISSUE TITLE
Make Spear of Mars work on creeps

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#510]
Add the knockback + pin to wall effect when the spear hits creeps.

Part of #93

┆Issue is synchronized with this [Trello card](https://trello.com/c/UbH29bvQ) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
Reopened since this is not done and not a duplicate

**Comment by SanctusAnimus** [comment]
Spear of Marks already works on creeps in a way, replicating it's heroes behaviour requires rewriting it, which is overkill i believe
