### ISSUE TITLE
Make Reflection work on creeps

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#511]
Creates uncontrollable copies of the creeps (not true illusions) which deal 40/60/80/100% of their attack damage.

Part of #93

┆Issue is synchronized with this [Trello card](https://trello.com/c/Etpb61pV) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
Reopened since this is not done and not a duplicate

**Comment by AustraliaIsMyCity** [comment]
No controlling creeps.

**Comment by Snoresville** [comment]
Main post literally says "uncontrollable"
