### ISSUE TITLE
Make Soulbind work on creeps

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#513]
Currently it does not link to a nearby creep at all.

Part of #93

┆Issue is synchronized with this [Trello card](https://trello.com/c/DhwLnOd0) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
Reopened since this is not done and not a duplicate

**Comment by AustraliaIsMyCity** [comment]
adding to the ability rewrite megathread https://github.com/arcadia-redux/custom_hero_clash_issues/issues/2332
