### ISSUE TITLE
Ability UI broke during retraining

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#517]
![image](https://user-images.githubusercontent.com/63279022/99921397-3e57c200-2d7e-11eb-8df5-8806bd0c4852.png)
![image](https://user-images.githubusercontent.com/63279022/99921401-46176680-2d7e-11eb-84a3-75ddcedd9abb.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/lw86W27A) by [Unito](https://www.unito.io/learn-more)

**Comment by SanctusAnimus** [comment]
No reports after that
