### ISSUE TITLE
Show Cooldown of Abilities in Duel GUIS

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#521]
Like how chaos does.

┆Issue is synchronized with this [Trello card](https://trello.com/c/DOeA8QXz) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
Reopened since this is not a duplicate

**Comment by ZLOY5** [comment]
You want to show all abilities or items like in preround duel info?
Because its pretty massive panel, and takes a lot of screen space even if in round time bet bar is hidden.
![image](https://user-images.githubusercontent.com/10956575/106468934-9feb8980-64af-11eb-9b0e-c55a4bab195c.png)

**Comment by fcalife** [comment]
@darklordabc

**Comment by fcalife** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make ability cooldowns visible on the pre-duel/duel UI](https://trello.com/c/kR6BucZF/242-make-ability-cooldowns-visible-on-the-pre-duel-duel-ui)

**Comment by darklordabc** [comment]
> You want to show all abilities and items like in preround duel info?
> Because its pretty massive panel, and takes a lot of screen space even if in round time bet bar is hidden.
> ![image](https://user-images.githubusercontent.com/10956575/106468934-9feb8980-64af-11eb-9b0e-c55a4bab195c.png)

How is adding cool downs going to increase the size of the panel? I don't understand what your objection is

**Comment by darklordabc** [comment]
Yes do this.
