### ISSUE TITLE
Some kind of overheal bug that leaves heros with no health

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#522]
![image](https://user-images.githubusercontent.com/16277198/100022576-871f8180-2e37-11eb-9f60-d2510800cd9f.png)
![image](https://user-images.githubusercontent.com/16277198/100022629-a1f1f600-2e37-11eb-8e31-feaafc5b495c.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/ZuHsyUl4) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
This is caused by an integer overflow and afaik has no fix.

**Comment by AustraliaIsMyCity** [comment]
This isn't realistically fixable

**Comment by darklordabc** [comment]
I think there may be ways to fix this, has anyone attempted yet?

**Comment by Draze22** [comment]
An interesting interaction with this bug.
![image](https://user-images.githubusercontent.com/63279022/103162246-65ecef00-4842-11eb-998d-bc69a15ead87.png)

**Comment by AustraliaIsMyCity** [comment]
> I think there may be ways to fix this, has anyone attempted yet?

several people have with no success
