### ISSUE TITLE
Make anything that is purchaseable, also be giftable

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#527]
E.g. buying glory, or buying a cosmetic, or buying fortune etc.

Gift codes works, server side, the problem is GUI wise, ideally, any purchase a player makes should be able to be gifted to 1) At least some other player in the game.

* You can buy codes, and they go to your list of codes
* You can manually give these codes to players, via messaging or whatever means of giving codes
* There is a redeem code button that players can use to enter the codes they were given
* In addition (this requiers GUI imagination), players can gift directly to other players in their current game. Maybe its somebody they enjoyed playing with, more likely its somebody in their party. Importantly, there should be notifications in game to let all players know that player x has gifted player y, gift b. Prehaps we can add a button to the scoreboard. Or a button next to each individual code, this is a job for Bukka. But we want to encourage people to give gifts, so the GUI should be fairly prominent and easy.

┆Issue is synchronized with this [Trello card](https://trello.com/c/48JLqsMm) by [Unito](https://www.unito.io/learn-more)

**Comment by SanctusAnimus** [comment]
In which way? As a drop-down, or as a key giveaway? I need more details.

**Comment by darklordabc** [comment]
![image](https://user-images.githubusercontent.com/16277198/100397300-09f54600-309d-11eb-8a91-7a95d44a12d8.png)
![image](https://user-images.githubusercontent.com/16277198/100397454-e088ea00-309d-11eb-869e-54601fc73117.png)

**Comment by SanctusAnimus** [comment]
Wouldn't it be easier and more obvious to just add something like checkbox "As a giftcode" to payment method selection?

**Comment by SanctusAnimus** [comment]
Are we doing anything with this one? I left the card on trello regarding Gift Codes feature a while ago, asking here too

**Comment by darklordabc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Figure out how to handle gift codes in GUI](https://trello.com/c/AapDTb7d/287-figure-out-how-to-handle-gift-codes-in-gui)

**Comment by Sheodar** [comment]
Added
