### ISSUE TITLE
Disconnected player didn't get teleported to rounds or removed from the game

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#539]
![image](https://user-images.githubusercontent.com/63279022/100515942-41b2d980-31d4-11eb-992b-24d326e752e4.png)
![image](https://user-images.githubusercontent.com/63279022/100515944-48415100-31d4-11eb-9bc4-5095d524de6b.png)
![image](https://user-images.githubusercontent.com/63279022/100515947-4d060500-31d4-11eb-92ca-6964a9526d3d.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/64dkFZYY) by [Unito](https://www.unito.io/learn-more)

**Comment by AustraliaIsMyCity** [comment]
This bug is very niche and also harmless, what basically happens is occasionally certain scenarios can cause a player to die in the game but their hero lives, it doesnt actually do anything as the player is eliminated and their hero stuck in fountain although yes it is a bit jarring
