### ISSUE TITLE
Omnislash and other similar abilities can target dead units

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#546]
I've seen omnislash bounce to dead arc warden clones as well as bounce to the position the other player started in during a duel.

┆Issue is synchronized with this [Trello card](https://trello.com/c/CG4NhW6e) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
Is this specifically with arc warden clones, or with other units as well?

**Comment by Draze22** [comment]
> Is this specifically with arc warden clones, or with other units as well?

It's unclear and difficult to reproduce.

**Comment by SanctusAnimus** [comment]
For omnislash it happens in vanilla dota too, and TD should be dying completely when expired / killed, so pretty much irrelevant
