### ISSUE TITLE
Make party indication colours consistent with team colours where possible

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#548]
![image](https://user-images.githubusercontent.com/63279022/100702701-48b93200-33f6-11eb-95b8-579435629dfa.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/jx5mSlfu) by [Unito](https://www.unito.io/learn-more)

**Comment by Sheodar** [comment]
If all party memebers in same team - color will be synchronize.
