### ISSUE TITLE
Shorten the length of overtime

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#554]
Shorten the length of overtime. In my opinion it should be around 50 seconds.

┆Issue is synchronized with this [Trello card](https://trello.com/c/zGCxQ7yw) by [Unito](https://www.unito.io/learn-more)

**Comment by AustraliaIsMyCity** [comment]
how exactly is this "reproducible"?

**Comment by fcalife** [comment]
Should this still be done?

**Comment by Draze22** [comment]
No longer necessary.
