### ISSUE TITLE
Add a display for players showing highest round achieved

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#555]
Add a display next to MMR showing highest round achieved (pic related)
![image](https://user-images.githubusercontent.com/50186248/85349013-a0e33280-b540-11ea-98f6-f73d673fe6fb.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/NvtTiFMy) by [Unito](https://www.unito.io/learn-more)

**Comment by Sheodar** [comment]
Added
