### ISSUE TITLE
Spectator UI doesn't work, but hey at least the mastery notification is there

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#571]
![image](https://user-images.githubusercontent.com/50186248/101474972-e042f580-399f-11eb-8007-5708a53cf94d.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/QJ3L5iPw) by [Unito](https://www.unito.io/learn-more)

**Comment by AustraliaIsMyCity** [comment]
Additionally, you cannot see upcoming duels once you have been eliminated from the game.

**Comment by fcalife** [comment]
that last part should be fixed now. the rest should be tracked in https://github.com/arcadia-redux/custom_hero_clash_issues/issues/356
