### ISSUE TITLE
Make parties visible in loading screen

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#576]
![image](https://user-images.githubusercontent.com/50186248/101709981-b6471b80-3ae4-11eb-9fcf-a9f2e5578067.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/aKbiQYXy) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
I really don't think we want people leaving games before they start because they're against a party and causing everyone to have to find another game.

**Comment by AustraliaIsMyCity** [comment]
duplicate of https://github.com/arcadia-redux/custom_hero_clash_issues/issues/576 which is more up to date
