### ISSUE TITLE
Permanent black hole (disable black hole from being swapped or retrained while being channeled)

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#583]
![image](https://user-images.githubusercontent.com/63279022/101847196-c4f60700-3ba6-11eb-90b3-3e0588025e01.png)
![image](https://user-images.githubusercontent.com/63279022/101847219-d6d7aa00-3ba6-11eb-99cc-c417a32dc328.png)
Can't be due to multicast since black hole is disabled from being multicast.
![image](https://user-images.githubusercontent.com/63279022/101847290-01296780-3ba7-11eb-92ff-b793855d32cd.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/g8KqYQsw) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
Guessing this is similar to #580

**Comment by AustraliaIsMyCity** [comment]
my guess is its related to retraining the ability while its channelling if someone wants to try that

**Comment by fcalife** [comment]
indeed
![DmfMDRDJXG](https://user-images.githubusercontent.com/7921728/102962319-59286e00-44c5-11eb-9540-674213ca6b18.gif)

**Comment by fcalife** [comment]
To fix, issue a stop channeling command before cleaning up the ability, if it is being channeled at that time

**Comment by SanctusAnimus** [comment]
Should no longer be an issue
