### ISSUE TITLE
Player died from using life drain

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#588]
![image](https://user-images.githubusercontent.com/63279022/102007052-cf1c2f00-3d79-11eb-8766-c71d25d45408.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/qNTSuTvf) by [Unito](https://www.unito.io/learn-more)

**Comment by SanctusAnimus** [comment]
No more reports of this one
