### ISSUE TITLE
Swapping in duos while ice blast is mid cast bugs out the swap UI

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#592]
![image](https://user-images.githubusercontent.com/63279022/102129652-d4759880-3ea3-11eb-831d-a25fdedc8b24.png)
![image](https://user-images.githubusercontent.com/63279022/102129678-dfc8c400-3ea3-11eb-9e12-63dd6896e982.png)
![image](https://user-images.githubusercontent.com/63279022/102129734-f5d68480-3ea3-11eb-97aa-f443d268932e.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/xnF6XpYw) by [Unito](https://www.unito.io/learn-more)

**Comment by SanctusAnimus** [comment]
Should no longer be an issue
