### ISSUE TITLE
[7.28] test Aghanim's Shard upgrades (C-G)

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#612]
Test each hero's aghanim's shard upgrade, making sure it works properly. If any bugs arise, open a related issue.

If the upgrade requires another ability in order to work (e.g. Eclipse vs. Lucent Beam), make a note telling the players so, and open a issue requesting the ability to be reworked so that its shard upgrade works with no need of extra abilities.

* [ ] Crystal Maiden (Frostbite)
* [ ] Dark Willow (Cursed Crown)
* [ ] Dazzle (Bad Juju)
* [ ] Death Prophet (Spirit Siphon)
* [ ] Disruptor (Thunder Strike)
* [ ] Doom (Infernal Blade)
* [ ] Drow Ranger (Frost Arrows)
* [ ] Earth Spirit (Stone Remnant)
* [ ] Earthshaker (Fissure)
* [ ] Elder Titan (Echo Stomp)
* [ ] Ember Spirit (Fire Remnant)
* [ ] Enchantress (Nature's Attendants)
* [ ] Enigma (Black Hole)
* [ ] Faceless Void (Time Walk)
* [ ] Gyrocopter (Rocket Barrage)

┆Issue is synchronized with this [Trello card](https://trello.com/c/AD5szdE3) by [Unito](https://www.unito.io/learn-more)

**Comment by lovro-m** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[7.28] test Aghanim's Shard upgrades (C-G)](https://trello.com/c/AD5szdE3/84-728-test-aghanims-shard-upgrades-c-g)

**Comment by lovro-m** [comment]
Crystal Maiden (Frostbite): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Dark Willow (Cursed Crown): WORKS
Extra spells required: Bramble Maze
Should be rewritten to cast without the extra spell.

**Comment by lovro-m** [comment]
Dazzle (Bad Juju): WORKS
Extra spells required: -
Works with any cast spell. Might be imba with extremely low cd abilities such as quill spray.

**Comment by lovro-m** [comment]
Death Prophet (Spirit Siphon): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Disruptor (Thunder Strike): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Doom (Infernal Blade): WORKS BUT USELESS
Extra spells required: -
Useless against creeps because they are mostly lvl 1. Otherwise ok.

**Comment by lovro-m** [comment]
Drow Ranger (Frost Arrows): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Earth Spirit (Stone Remnant): DOES NOT WORK
Extra spells required: Gets provided with other es spells
The shard should provide remnant AoE vision and 4 extra charges. The vision part is partially useless and the extra charges does not work.

**Comment by lovro-m** [comment]
Earthshaker (Fissure): DOES NOT WORK
Extra spells required: Aftershock, Enchant Totem, Echo Slam
Should be rewritten to not require aftershock and can be applied with any ability, not just es abilities.

**Comment by lovro-m** [comment]
Elder Titan (Echo Stomp): DOES NOT WORK
Extra spells required: -
Cannot test because echo stomp is not in the game.

**Comment by lovro-m** [comment]
Ember Spirit (Fire Remnant): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Enchantress (Nature's Attendants): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Enigma (Black Hole): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Faceless Void (Time Walk): DOES NOT WORK
Extra spells required: -
Reverse time walk does not appear when the spell is cast.

**Comment by lovro-m** [comment]
Gyrocopter (Rocket Barrage): WORKS
Extra spells required: -
No extra remarks.
