### ISSUE TITLE
[7.28] test Aghanim's Shard upgrades (H-M)

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#613]
Test each hero's aghanim's shard upgrade, making sure it works properly. If any bugs arise, open a related issue.

If the upgrade requires another ability in order to work (e.g. Eclipse vs. Lucent Beam), make a note telling the players so, and open a issue requesting the ability to be reworked so that its shard upgrade works with no need of extra abilities.

* [ ] Huskar (Inner Fire)
* [ ] Invoker (Ice Wall)
* [ ] Io (Tether)
* [ ] Juggernaut (Blade Fury)
* [ ] Keeper of the Light (Illuminate)
* [ ] Legion Commander (Duel)
* [ ] Leshrac (Split Earth)
* [ ] Lina (Laguna Blade)
* [ ] Lion (Mana Drain)
* [ ] Lone Druid (Savage Roar)
* [ ] Luna (Lucent Beam)
* [ ] Lycan (Summon Wolves) <- needs a rework in order to do anything
* [ ] Mars (Spear of Mars)
* [ ] Meepo (Ransack)
* [ ] Mirana (Leap)

┆Issue is synchronized with this [Trello card](https://trello.com/c/jIwKpslD) by [Unito](https://www.unito.io/learn-more)

**Comment by lovro-m** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[7.28] test Aghanim's Shard upgrades (H-M)](https://trello.com/c/jIwKpslD/83-728-test-aghanims-shard-upgrades-h-m)

**Comment by lovro-m** [comment]
Huskar (Inner Fire): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Invoker (Ice Wall): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Io (Tether): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Juggernaut (Blade Fury): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Keeper of the Light (Illuminate): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Legion Commander (Duel): WORKS
Extra spells required: Overwhelming odds
Needs to be rewritten to not require overwhelming odds.

**Comment by lovro-m** [comment]
Leshrac (Split Earth): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Lina (Laguna Blade): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Lion (Mana Drain): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Lone Druid (Savage Roar): DOES NOT WORK
Extra spells required: -
Cannot test because Savage Roar is not in the game.

**Comment by lovro-m** [comment]
Luna (Lucent Beam): WORKS
Extra spells required: -
Does not target creeps.

**Comment by lovro-m** [comment]
Lycan (Summon Wolves): DOES NOT WORK
Extra spells required: -
Requires complete rework.

**Comment by lovro-m** [comment]
Mars (Spear of Mars): WORKS
Extra spells required: -
Does not target creeps - for better or for worse.

**Comment by lovro-m** [comment]
Meepo (Ransack): DOES NOT WORK
Extra spells required: (Geostrike maybe)
In vanilla probably uses hidden geostrike. Anyway, needs to be rewritten.

**Comment by lovro-m** [comment]
Mirana (Leap): WORKS
Extra spells required: -
No extra remarks.
