### ISSUE TITLE
[7.28] test Aghanim's Shard upgrades (M-R)

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#614]
Test each hero's aghanim's shard upgrade, making sure it works properly. If any bugs arise, open a related issue.

If the upgrade requires another ability in order to work (e.g. Eclipse vs. Lucent Beam), make a note telling the players so, and open a issue requesting the ability to be reworked so that its shard upgrade works with no need of extra abilities.

* [ ] Monkey King (Tree Dance)
* [ ] Morphling (Adaptive Strike)
* [ ] Naga Siren (Riptide)
* [ ] Nature's Prophet (Sprout)
* [ ] Night Stalker (Hunter in the Night)
* [ ] Nyx Assassin (Vendetta)
* [ ] Oracle (False Promise)
* [ ] Outback Defenestrator (Essence Flux)
* [ ] Phantom Lancer (Spirit Lance)
* [ ] Phoenix (Fire Spirits)
* [ ] Puck (Waning Rift)
* [ ] Pudge (Dismember)
* [ ] Pugna (Life Drain)
* [ ] Queen of Pain (Blink)
* [ ] Razor (Storm Surge)

┆Issue is synchronized with this [Trello card](https://trello.com/c/pE0gA2gs) by [Unito](https://www.unito.io/learn-more)

**Comment by lovro-m** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[7.28] test Aghanim's Shard upgrades (M-R)](https://trello.com/c/pE0gA2gs/82-728-test-aghanims-shard-upgrades-m-r)

**Comment by lovro-m** [comment]
Monkey King (Tree Dance): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Morphling (Adaptive Strike): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Naga Siren (Riptide): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Nature's Prophet (Sprout): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Night Stalker (Hunter in the Night): WORKS
Extra spells required: -
May need to check all the creeps to see if any strong ones can be consumed unintentionally.

**Comment by lovro-m** [comment]
Nyx Assassin (Vendetta): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Oracle (False Promise): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Outhouse Decorator (Essence Flux): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Phantom Lancer (Spirit Lance): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Phoenix (Fire Spirits): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Puck (Waning Rift): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Pudge (Dismember): DOES NOT WORK
Extra spells required: EJECT
The eating an ally part works, but the eject spell is missing so the ally can stay inside you forever.

**Comment by lovro-m** [comment]
Pugna (Life Drain): WORKS
Extra spells required: -
Life drain only works on other heroes, not on creeps.

**Comment by lovro-m** [comment]
Queen of Pain (Blink): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Razor (Storm Surge): WORKS
Extra spells required: -
No extra remarks.
