### ISSUE TITLE
[7.28] test Aghanim's Shard upgrades (R-T)

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#615]
Test each hero's aghanim's shard upgrade, making sure it works properly. If any bugs arise, open a related issue.

If the upgrade requires another ability in order to work (e.g. Eclipse vs. Lucent Beam), make a note telling the players so, and open a issue requesting the ability to be reworked so that its shard upgrade works with no need of extra abilities.

* [ ] Rubick (Telekinesis)
* [ ] Sand King (Epicenter)
* [ ] Shadow Demon (Demonic Purge)
* [ ] Shadow Fiend (Necromastery)
* [ ] Shadow Shaman (Shackles)
* [ ] Silencer (Glaives of Wisdom)
* [ ] Skywrath Mage (Ancient Seal)
* [ ] Slardar (Corrosive Haze)
* [ ] Snapfire (Scatterblast)
* [ ] Spectre (Dispersion)
* [ ] Spirit Breaker (Nether Strike)
* [ ] Sven (Storm Hammer)
* [ ] Techies (Blast Off!)
* [ ] Templar Assassin (Psionic Trap)
* [ ] Tidehunter (Anchor Smash)

┆Issue is synchronized with this [Trello card](https://trello.com/c/GJsaWKzs) by [Unito](https://www.unito.io/learn-more)

**Comment by lovro-m** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[7.28] test Aghanim's Shard upgrades (R-T)](https://trello.com/c/GJsaWKzs/81-728-test-aghanims-shard-upgrades-r-t)

**Comment by lovro-m** [comment]
Rubick (Telekinesis): DOES NOT WORK
Extra spells required: Telekinesis Land
Ally and enemy targeting and tossing works. Only self targeting works. Self toss must be fixed.

**Comment by lovro-m** [comment]
Sand King (Epicenter): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Shadow Demon (Demonic Purge): DOES NOT WORK
Extra spells required: -
The spell is already rewritten. Shard must be added to lua.

**Comment by lovro-m** [comment]
Shadow Fiend (Necromastery): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Shadow Fiend (Necromastery): WORKS
Extra spells required: Mass Serpent Ward
No extra remarks.

**Comment by lovro-m** [comment]
Silencer (Glaives of Wisdom): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Skywrath Mage (Ancient Seal): WORKS
Extra spells required: -
Not extensively tested. May not work on all spells.

**Comment by lovro-m** [comment]
Slardar (Corrosive Haze): WORKS
Extra spells required: Slithereen Crush
No extra remarks. Useless without crush.

**Comment by lovro-m** [comment]
Snapfire (Scatterblast): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Spectre (Dispersion): DOES NOT WORK
Extra spells required: Haunt
Only targets heroes and cannot test because haunt is not in the game. Needs to be rewritten completely.

**Comment by lovro-m** [comment]
Spirit Breaker (Nether Strike): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Sven (Storm Hammer): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Techies (Blast Off!): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Templar Assassin (Psionic Trap): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Tidehunter (Anchor Smash): WORKS
Extra spells required: -
No extra remarks.
