### ISSUE TITLE
[7.28] test Aghanim's Shard upgrades (T-Z)

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#616]
Test each hero's aghanim's shard upgrade, making sure it works properly. If any bugs arise, open a related issue.

If the upgrade requires another ability in order to work (e.g. Eclipse vs. Lucent Beam), make a note telling the players so, and open a issue requesting the ability to be reworked so that its shard upgrade works with no need of extra abilities.

* [ ] Treant (Nature's Guise)
* [ ] Troll Warlord (Battle Trance)
* [ ] Underlord (Firestorm)
* [ ] Undying (Decay)
* [ ] Ursa (Fury Swipes)
* [ ] Vengeful Spirit (Wave of Terror)
* [ ] Venomancer (Venomous Gale)
* [ ] Viper (Poison Attack)
* [ ] Visage (Gravekeeper's Cloak)
* [ ] Void Spirit (Dissimilate)
* [ ] Warlock (Shadow Word)
* [ ] Weaver (The Swarm)
* [ ] Windranger (Powershot)
* [ ] Winter Wyvern (Cold Embrace)
* [ ] Wraith King (Reincarnation)
* [ ] Zeus (Static Field)

┆Issue is synchronized with this [Trello card](https://trello.com/c/NbapVlbe) by [Unito](https://www.unito.io/learn-more)

**Comment by lovro-m** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[7.28] test Aghanim's Shard upgrades (T-Z)](https://trello.com/c/NbapVlbe/80-728-test-aghanims-shard-upgrades-t-z)

**Comment by lovro-m** [comment]
Treant (Nature's Guise): DOES NOT WORK
Extra spells required: -
Nature's Guise not in the game. Cannot test.

**Comment by lovro-m** [comment]
Troll Warlord (Battle Trance): WORKS
Extra spells required: -
Useless in solo mode.

**Comment by lovro-m** [comment]
Underlord (Firestorm): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Undying (Decay): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Ursa (Fury Swipes): WORKS
Extra spells required: Enrage
Has to be rewritten without enrage required.

**Comment by lovro-m** [comment]
Vengeful Spirit (Wave of Terror): WORKS
Extra spells required: -
Can only be used on heroes. Useless against creeps.

**Comment by lovro-m** [comment]
Venomancer (Venomous Gale): WORKS
Extra spells required: Plague Wards
Has to be adjusted to summon without plague wards.

**Comment by lovro-m** [comment]
Viper (Poison Attack): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Visage (Gravekeeper's Cloak): DOES NOT WORK
Extra spells required: -
Gravekeeper's Cloak not in the game.

**Comment by lovro-m** [comment]
Void Spirit (Dissimilate): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Warlock (Shadow Word): WORKS
Extra spells required: -
No extra remarks.

**Comment by lovro-m** [comment]
Weaver (The Swarm): WORKS
Extra spells required: Geminate Attack
Has to be rewritten to not have to require Geminate Attack. Otherwise works.

**Comment by lovro-m** [comment]
Windranger (Powershot): WORKS
Extra spells required: -
Global range not exactly useful.

**Comment by lovro-m** [comment]
Winter Wyvern (Cold Embrace): WORKS
Extra spells required: Splinter Blast
Has to be rewritten to not have to require Splinter Blast. Otherwise works.

**Comment by lovro-m** [comment]
Wraith King (Reincarnation): WORKS
Extra spells required: Vampiric Spirit
Has to be rewritten to not have to require Vampiric Spirit. Otherwise works. Skeletons only spawn near enemy heroes, not creeps.

**Comment by lovro-m** [comment]
Zeus (Static Field): WORKS
Extra spells required: -
No extra remarks.

**Comment by mmdts** [comment]
Can confirm lovro's findings on Viper, Ursa, Troll Warlord, and Underlord
