### ISSUE TITLE
[7.28] Other 7.28 issues masterlist

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#630]
List of other odds and ends which don't fit elsewhere. If anything does not work as expected and requires more work/discussion, feel free to open a related issue.

* [x] Test fixed accuracy aura (on dinosaur round) and check if it makes the round too strong. nerf accordingly if appropriate.
* [x] Test if Alchemist's scepter buff is working properly (granting stats and gold), and if net worth is updated accordingly.
* [x] Make sure Chen teleport (both self and creep targeted) respect arena movement/teleportation rules.
* [x] Update trigger for Clinkz skeleton walk skeletons, if necessary.
* [x] Check if Invoker's new talents work properly with his AD spells.
* [x] Remove Omnislash/Swiftslash ancient targeting override.
* [x] Figure out how the fuck KOTL's spirit form works now.
* [x] Make sure Spirit Bear health scales appropriately with LD's new lv25 talent.
* [x] Check if Sacred Arrow's new scepter effect requires Starfall, open an ability rework issue if necessary.
* [x] Test whatever is going on with Phoenix's shard-upgraded Fire Spirits, make sure it works or fucking yeet it.
* [x] Test if Shadow Step requires Spectral Dagger to work properly.
* [x] Test if 'Vampiric Spirits' skeletons are less stubborn about their health than the old mortal strike ones.

┆Issue is synchronized with this [Trello card](https://trello.com/c/Hobq2hZ2) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
This one could still use being done

**Comment by Draze22** [comment]
> Check if Invoker's new talents work properly with his AD spells.

- Cold Snap's talent works fully.
- Deafening Blast's talent works fully.
- Tornados's talent works fully.

- Alacrity's talent says it gives +35/35, it's tooltip gets updated to show this but when alacrity is used the talent gives it +50/50.
- Ice Wall's talent appears to work correctly except that it doesn't update Ice Wall's tooltip.
- Chaos Meteor's talent appears to work correctly except that it doesn't update Chaos Meteor's tooltip.

- Forged Spirit's talent doesn't work at all and neither does Forged Spirit's armor reduction on attack.

**Comment by Draze22** [comment]
> Update trigger for Clinkz skeleton walk skeletons, if necessary.

Already done.

**Comment by Draze22** [comment]
> Test if Alchemist's scepter buff is working properly (granting stats and gold), and if net worth is updated accordingly.

Seems to work fully but not update networth accordingly.

![image](https://user-images.githubusercontent.com/63279022/121484401-871d5280-ca12-11eb-8fe0-65672e73b194.png)

**Comment by Draze22** [comment]
> Figure out how the fuck KOTL's spirit form works now.

The following only work while Spirit Form is active:

- Grants some stats (cast range and movespeed).
- Makes Illuminate heal (for a certain amount that scales) during the day.
- Makes Illuminate not require active channeling: is channeled by a "separate spirit" (can be cast early as normal by pressing the hotkey again).
- Gives the Blinding Light ability.

**Comment by Draze22** [comment]
> Make sure Chen teleport (both self and creep targeted) respect arena movement/teleportation rules.

This has been disabled since it makes no sense in CHC (it teleports units specifically into the fountain which would break arena movement/teleportation rules).

**Comment by Draze22** [comment]
> Make sure Spirit Bear health scales appropriately with LD's new lv25 talent.

It currently does not work. When you take the talent, Spirit Bears current hp gets reduced but max hp stays the same.

**Comment by lovro-m** [comment]
> Test if Shadow Step requires Spectral Dagger to work properly.
 You don't need haunt to cast it and neither do you "need" spectral dagger (it just doesn't apply the dagger upon cast). Balance team has decided it is not suitable for the game because it does not affect creeps and would have to be rewritten to affect them.

**Comment by lovro-m** [comment]
> Test if 'Vampiric Spirits' skeletons are less stubborn about their health than the old mortal strike ones.

I can manually change their hp in the KV file, but they seem unaffected by the summon buff.
![image](https://user-images.githubusercontent.com/63733825/128334555-d77dde6f-5bf1-4243-bfc0-e1b61e83faa9.png)
