### ISSUE TITLE
Mortal strike crit doesn't work sometimes

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#642]
![image](https://user-images.githubusercontent.com/63279022/103123183-92382c80-46d7-11eb-97f2-b333f3b60034.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/sYeEuuXj) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/103272009-df860800-4a0f-11eb-9f0a-8316e1b7c7bb.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/104161142-70180b80-5446-11eb-9571-4a0e4c124f7d.png)

**Comment by fcalife** [comment]
no longer disabled on fountain, works perfectly.
