### ISSUE TITLE
Essence flux can be procced by toggled abilities

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#644]
![image](https://user-images.githubusercontent.com/63279022/103123355-2efaca00-46d8-11eb-8ed7-45ba29d42d50.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/1QwAqcTe) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
This ability doesn't even exist anymore
