### ISSUE TITLE
Ice wall can't be levelled if you already have aghanim's shard when you choose ice wall

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#648]
![image](https://user-images.githubusercontent.com/63279022/103123622-12ab5d00-46d9-11eb-8e85-5b76ba844955.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/oRZsVBvG) by [Unito](https://www.unito.io/learn-more)

**Comment by HappyFeedFriends** [comment]
this? 
![image](https://user-images.githubusercontent.com/31066449/103168501-85414780-4855-11eb-8e9f-984d40d08880.png)

**Comment by Draze22** [comment]
@HappyFeedFriends the screenshot doesn't show any abilities.

**Comment by HappyFeedFriends** [comment]
this ice wall and aghanim

**Comment by Draze22** [comment]
@HappyFeedFriends you have to buy aghanim's shard before you get ice wall to make this happen.

**Comment by fcalife** [comment]
confirmed that this doesn't happen *only* from rerolls, but from picking the ability in general while having a shard
