### ISSUE TITLE
Abilities that can't be cast in the fountain

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#664]
Abilities that can be cast but are instantly dispelled:

* [x] Ion Shell with aghanim's scepter upgrade.
* [x] Ethereal blade. (Can be cast on enemies as well which it shouldn't be able to).

Abilities that can't be cast on allied units in fountain:

* [ ] Tether.
* [ ] Inner Vitality.

┆Issue is synchronized with this [Trello card](https://trello.com/c/LZomPwXT) by [Unito](https://www.unito.io/learn-more)

**Comment by HappyFeedFriends** [comment]
Either it's already been fixed, or it wasn't a bug. ![image](https://user-images.githubusercontent.com/31066449/103164712-8dd35700-4830-11eb-9da7-431c135ff13e.png)

**Comment by Draze22** [comment]
@HappyFeedFriends heroes can remain tethered from the previous round while in the fountain since they get teleported to the fountain at the same to so the tether doesn't break. The issue is if the tether does break for whatever reason it can't be cast again while in the fountain.

**Comment by fcalife** [comment]
- Ion Shell now works on fountain
- Inner Vitality causes a crash if cast on invulnerable units (so it stays disabled on them)
- Tether has custom targeting that ignores invulnerable units unless remade
- Ethereal Blade can no longer be used on the fountain
