### ISSUE TITLE
Venge aghs-illusion should gain the same abilities Tempest Double does

### ISSUE THREAD

**Issue by dym-sh** [arcadia-redux/custom_hero_clash_issues#672]
Currently after an aghs Vengeance Aura illusion spawns, it only has Venge's base spells which greatly reduces its viability in duos' duels.

┆Issue is synchronized with this [Trello card](https://trello.com/c/6jbIuD7N) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
It gets all abilities from your hero in ability draft so it makes sense for it to in CHC.
