### ISSUE TITLE
Pinging abilities and items in the duel UI doesn't use localisation

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#676]
![image](https://user-images.githubusercontent.com/50186248/103185368-42907580-4910-11eb-86c7-ae334b1af114.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/QEBey1Qz) by [Unito](https://www.unito.io/learn-more)

**Comment by Sheodar** [comment]
Fixed and updated icons in pings from duel UI / retrain UI.
