### ISSUE TITLE
Player was only able to pick their first 2 skills

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#692]
They also had the bug where player's can't pick their innate (issue #451).
![image](https://user-images.githubusercontent.com/63279022/103434239-8a860400-4c52-11eb-94e5-8c660b2c20ca.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/SkgtcU4y) by [Unito](https://www.unito.io/learn-more)

**Comment by SanctusAnimus** [comment]
No more reports of this one
