### ISSUE TITLE
Arctic burn and pulse nova sometimes turn off automatically right after being turned on

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#697]
https://cdn.discordapp.com/attachments/694440472273354762/794965349073813524/Dota_2_2564-01-02_23-06-18.mp4

┆Issue is synchronized with this [Trello card](https://trello.com/c/YJ1GmLjQ) by [Unito](https://www.unito.io/learn-more)

**Comment by SanctusAnimus** [comment]
Haven't heard of it for quite some time, reopen with more details if still happening
