### ISSUE TITLE
Players are occasionally losing an aegis after winning a duel

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#698]
![image](https://user-images.githubusercontent.com/63279022/103469286-01d4a880-4db7-11eb-9aca-3e6ab78ad716.png)
![image](https://user-images.githubusercontent.com/63279022/103469292-0bf6a700-4db7-11eb-8369-d9adf9f9eed9.png)
![image](https://user-images.githubusercontent.com/63279022/103469298-19139600-4db7-11eb-894f-dc979cc01fc8.png)
![image](https://user-images.githubusercontent.com/63279022/103469300-1c0e8680-4db7-11eb-8499-594f9b3eb86b.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/TVZEB2I1) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
Possible explanation for this issue.
![image](https://user-images.githubusercontent.com/63279022/103493014-fc449480-4e82-11eb-8797-6d8ee21431e5.png)

**Comment by AustraliaIsMyCity** [comment]
pretty sure this is only visual btw
