### ISSUE TITLE
Several people have experienced the "win a game" quest not working

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#702]
![image](https://user-images.githubusercontent.com/63279022/103492898-49743680-4e82-11eb-9b4b-203d040ecc1a.png)
![image](https://user-images.githubusercontent.com/63279022/103492899-4e38ea80-4e82-11eb-9137-247bbd565d69.png)
![image](https://user-images.githubusercontent.com/63279022/103492900-53963500-4e82-11eb-8a74-410dc1509328.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/ujxr8lby) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/107841785-15414d80-6e12-11eb-93c6-c464618bbfe0.png)

**Comment by Draze22** [comment]
This is still happening.

![image](https://user-images.githubusercontent.com/63279022/116661030-2ba18300-a9d7-11eb-8c6d-14626d3d9a3c.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/119801400-0560fb80-bf21-11eb-975a-a61385493e8f.png)

**Comment by ZLOY5** [comment]
This may be due to the fact Valve stop server immediately after game ends (DOTA_GAMERULES_STATE_POST_GAME)

**Comment by Draze22** [comment]
> This may be due to the fact Valve stop server immediately after game ends (DOTA_GAMERULES_STATE_POST_GAME)

Surely if that's the case we can detect which player wins the game and communicate it with the server when the second last player is eliminated. There's always a period of time after that where the winning player chooses if they want to continue in PVE.

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **23** days with label "unknown cause".  
It will be **closed** automatically after **7** days if this issue stays inactive.
