### ISSUE TITLE
Player had no hero model

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#704]
![image](https://user-images.githubusercontent.com/63279022/103495960-9f4fdb00-4e90-11eb-8b81-4019dbcddffc.png)
![image](https://user-images.githubusercontent.com/63279022/103496007-c0b0c700-4e90-11eb-98bc-4d3f4806f206.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/njQLmOY1) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
When I tried to replicate this nothing happened.

**Comment by AustraliaIsMyCity** [comment]
:omegalul:

**Comment by SanctusAnimus** [comment]
No more reports, guess it was some weird precache issue
