### ISSUE TITLE
Issue with individual scoreboard showing up early and causing the player to crash

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#732]
![image](https://user-images.githubusercontent.com/63279022/104519804-2ac62a80-564e-11eb-9b86-9180d895d091.png)
![image](https://user-images.githubusercontent.com/63279022/104519790-24d04980-564e-11eb-9794-81c69070afbf.png)
![image](https://user-images.githubusercontent.com/63279022/104519843-37e31980-564e-11eb-87ea-4b0c3841b8a0.png)
![image](https://user-images.githubusercontent.com/63279022/104519819-2ef24800-564e-11eb-889c-1bdf20f5bc0e.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/554dlk6q) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/104519967-71b42000-564e-11eb-8c0e-31278d50eacd.png)
![image](https://user-images.githubusercontent.com/63279022/104519967-71b42000-564e-11eb-8c0e-31278d50eacd.png)
![image](https://user-images.githubusercontent.com/63279022/104519995-7bd61e80-564e-11eb-88b7-7d1360d56f3a.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/104714016-c0f66f80-5778-11eb-87cd-18370444f803.png)
![image](https://user-images.githubusercontent.com/63279022/104714043-cbb10480-5778-11eb-8856-212efd3b625e.png)
![image](https://user-images.githubusercontent.com/63279022/104714030-c653ba00-5778-11eb-9ed7-3562f900fd81.png)
![image](https://user-images.githubusercontent.com/63279022/104714074-db304d80-5778-11eb-9a3f-972e09c2c47d.png)
![image](https://user-images.githubusercontent.com/63279022/104714085-dff50180-5778-11eb-9648-16da535c56f6.png)
![image](https://user-images.githubusercontent.com/63279022/104714107-e6837900-5778-11eb-9fa9-f219b0eaf438.png)
![image](https://user-images.githubusercontent.com/63279022/104714115-e97e6980-5778-11eb-8b73-71baebf2b281.png)

**Comment by fcalife** [comment]
Might be related to https://github.com/dota2unofficial/custom_hero_clash_issues/issues/756

**Comment by fcalife** [comment]
This and #756 should be gone by now?
