### ISSUE TITLE
Tempest Double doesn't get all talents

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#733]
![image](https://user-images.githubusercontent.com/63279022/104536671-915a4100-566c-11eb-9fe1-b3305fb74b6d.png)
![image](https://user-images.githubusercontent.com/63279022/104536677-93bc9b00-566c-11eb-923a-80565c99ae97.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/FfsPF6hH) by [Unito](https://www.unito.io/learn-more)

**Comment by SanctusAnimus** [comment]
PR merged, i assume this is fixed
