### ISSUE TITLE
Display masteries in the duel UI and the left player UI (in the most expanded view)

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#736]
Only display which masteries they have (not what level they are).

Maybe also add a way to see an individual hero's mastery when clicking on them as suggested below.

![image](https://user-images.githubusercontent.com/63279022/104661997-ea35e200-571d-11eb-9c30-3a1b4af0b834.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/etDYM2MA) by [Unito](https://www.unito.io/learn-more)

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/106319684-78f84200-627a-11eb-9a71-df31fdff79a1.png)

**Comment by fcalife** [comment]
I understand this *should* be in the game from a gameplay standpoint but it would increase cries of p2w and would make it easier for people to harass paying players in the game. We want to avoid that.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/109096913-8964e500-7772-11eb-839d-9e6feb9145eb.png)

**Comment by fcalife** [comment]
@darklordabc gonna need you to confirm or veto this

**Comment by Draze22** [comment]
Would this be better if we only displayed which masteries players have (not what level they are).

**Comment by SanctusAnimus** [comment]
I think this one is done? at least for duel ui
close if yes

**Comment by fcalife** [comment]
its done
