### ISSUE TITLE
Arcane blink overrides the cast point reduction mastery

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#757]
![image](https://user-images.githubusercontent.com/63279022/105561427-c94b3d80-5d6a-11eb-90ba-6de440f1329c.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/Tcfso91s) by [Unito](https://www.unito.io/learn-more)

**Comment by Nibuja05** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Arcane blink overrides the cast point reduction mastery](https://trello.com/c/RNdNEEvM/218-arcane-blink-overrides-the-cast-point-reduction-mastery)
