### ISSUE TITLE
A player abandoning and dying during the first creep wave in duos while their team mate clears it will cause the round to never end

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#759]
![image](https://user-images.githubusercontent.com/63279022/105572823-9a09f000-5dad-11eb-8c81-62cd771acb06.png)
![image](https://user-images.githubusercontent.com/63279022/105572829-a130fe00-5dad-11eb-80e1-cbb3f18ec6cf.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/svUsj2yI) by [Unito](https://www.unito.io/learn-more)

**Comment by Snoresville** [comment]
could this problem be related to his partner disconnecting?

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/105574797-12c37900-5dbb-11eb-8330-466ec624b6f7.png)

**Comment by Draze22** [comment]
Looks like it.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/107456846-128df080-6ba5-11eb-84d0-30375660f820.png)
![image](https://user-images.githubusercontent.com/63279022/107456852-16217780-6ba5-11eb-9bad-f4d2446c5ae9.png)
