### ISSUE TITLE
Player that is shown to be dead in the left UI isn't dead

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#761]
![image](https://user-images.githubusercontent.com/63279022/105617578-2ad6df00-5e33-11eb-8383-faafc38a3999.png)
![image](https://user-images.githubusercontent.com/63279022/105617587-48a44400-5e33-11eb-9ab1-496cadb447ee.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/Sy2nCQrs) by [Unito](https://www.unito.io/learn-more)

**Comment by SanctusAnimus** [comment]
No more reports = closing
