### ISSUE TITLE
Add a status resistance-granting item to help counter permabash

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#774]
Here's a suggestion. Open to other ideas.

**Guardian Helmet**
_Let's see them try and bash your head in now._

Guardian Greaves + Soul Booster + Fluffy Hat (8,700 gold)

+700 health
+700 mana
+5 armor
+50 movement speed

**Active: Mend**

Applies a strong purge to the owner, heals all nearby allies for 20% of their maximum health, and recovers 20% of their maximum mana. Grants 80% status resistance for 3 seconds to affected allies. Cannot be affected by Mend again for a duration equal to its cooldown.

If you are reduced below 35% health and Mend is off-cooldown, it is triggered automatically.

**Passive: Guardian Aura**

Grants +5 health regeneration, 5 armor, and 10% status resistance to nearby allies. If they are below 35% health, those bonuses are increased to 20 health regeneration, +20 armor, and +40% status resistance.

┆Issue is synchronized with this [Trello card](https://trello.com/c/3os8zJZI) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
Looks like a good way to counter perma bash to me.

**Comment by darklordabc** [comment]
Maybe the active should be castable even when stunned?

**Comment by fcalife** [comment]
@Draze22 @AustraliaIsMyCity ur opinions welcome

**Comment by Draze22** [comment]
I prefer Firetoad's version but both would work.

**Comment by fcalife** [comment]
![image](https://user-images.githubusercontent.com/7921728/106333485-8821c480-6267-11eb-9c4c-27cbd90057c8.png)

**Comment by Shushishtok** [comment]
I almost forgot that Assault Cuirass upgrade is not allowed, so instead I suggest this:

**Helmet of Insusceptibility**:
Platemail (1400) + Soul Booster (3200) + Crimson Guard (3850 gold) - 8450 gold total.

+18 Armor
+700 Health
+425 Mana
+12 Health Regeneration
+30% Status Resistance

**Passive: Damage Block of Insusceptibility**:
Grants a 50% chance to block 80 damage from incoming attacks on melee heroes, and 40 damage on ranged. When proccing the damage block, increases the status resistance bonus by 5% for 2 seconds. Stacks with itself indefinitely. Each stack has its own timer.

**Active: Hardened Guard:**
Grants all nearby allies 100% chance to block 80 damage from incoming attacks, and grants them 5% bonus status resistance for each attack blocked for 2 seconds, which stacks with itself indefinitely. Each stack has its own timer. The status resistance modifier does not apply for the caster, which has its own passive modifier. Lasts 12 seconds, 36 seconds cooldown.
The active effect cannot be applied on the same unit for 35 seconds.

**Comment by darklordabc** [comment]
Yours seems a bit too complicated @Shushishtok, also the name is a issue (although that is easily fixable) but ultimately I think firetoads is much more easy to understand and I like that it auto triggers.

Also "When proccing the damage block, increases the status resistance bonus by 5% for 2 seconds. Stacks with itself indefinitely. Each stack has its own timer." Wouldn't that mean at late game, players would quickly get 100% status resistance very quickly?

**Comment by Shushishtok** [comment]
Name is fixable as you said.

Mine is basically just Crimson Guard's passive/active components, where each time it procs, it gives you a stack that grants 5% status resistance. Nothing big.

> Wouldn't that mean at late game, players would quickly get 100% status resistance very quickly?
They would need to hit you ~40 times when used passively (due to 50% chance to trigger) or 20 times when used actively (due to 100% chance to trigger) in a 2 seconds window.

**Comment by darklordabc** [comment]
Okay, but I'm still going to go with Firetoads suggestion on this one.

**Comment by Shushishtok** [comment]
Very well. Need to assign someone to make it. Also need an awesome icon!

**Comment by Snoresville** [comment]
I'm making this.

**Comment by Snoresville** [comment]
What is the cooldown for Guardian Helmet? For reference, Guardian Greaves is 40 seconds.
