### ISSUE TITLE
Improve 'daily login bonus'

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#776]
Currently we give players a maximum of 1 mastery per day, whenever they first finish a game in the top half of players. This is not shown anywhere, and only described on the mastery on-hover tooltip.

* [ ] Increase this daily reward based on the player's current 'streak': as long as they don't miss a day, the reward keeps growing, day after day.
* [ ] Define numbers for the above: what rewards are given on each day, and how long a streak can be.
* [ ] Show the rewards properly on the individual match results screen of each player (this one): 
![dota2!UNITO-UNDERSCORE!r87SS3gC9x](https://user-images.githubusercontent.com/7921728/105988577-9cef3400-607e-11eb-9d4e-82492afb86cc.png)
* [ ] Rewards (beyond fortune) should be chest-based, with x (few, please) tiers of chests that the player gains and can open at any time.

┆Issue is synchronized with this [Trello card](https://trello.com/c/57AsdBiy) by [Unito](https://www.unito.io/learn-more)
┆Attachments: <a href="https://github.com/dota2unofficial/custom_hero_clash_issues/issues/776">custom_hero_clash_issues #776 Improve &#39;daily login bonus&#39;</a>

**Comment by SanctusAnimus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve 'daily login bonus'](https://trello.com/c/57AsdBiy/14-improve-daily-login-bonus)

**Comment by darklordabc** [comment]
test

**Comment by darklordabc** [comment]
test

**Comment by fcalife** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve CHC 'daily login' bonus: define numbers](https://trello.com/c/77PoV3gW/222-improve-chc-daily-login-bonus-define-numbers)

**Comment by darklordabc** [comment]
Well for one we should be showing the fortune earned on this screen, not sure why they was never implemented. And we need to add a open daily streak treasure button (maybe a better name for it than that).

1. Show Fortune gained if it was the game were they earned their one fortune.
2. Show button or way to open their streak chest. Need to design how to show this and how to name it, players need to know its something that gets refreshed daily and gets better the longer play streak they have (a play streak is the amount of days in a row where they met the condition to earn 1 fortune per day).

**Comment by SanctusAnimus** [comment]
Also i would kindly ask to not add a chest as a separate item each time player can open it, and open a chest UI directly (since in design sheet we already have it as "open chest")

**Comment by fcalife** [comment]
@SanctusAnimus do you mind tracking the chest's state for the day in the server then? That way if the player for some reason doesn't open the chest before quitting, they can do it the next game.

Should track: 'chest already earned today?' and 'chest already opened today?', both bools.

**Comment by SanctusAnimus** [comment]
That doesn't sound like incremental streak though, how would you know which reward to give from just those bools? I expected something like numeric streak field and last redeemed date to track that, with bool for chest opening that resets every day. And yeah, settings field of player is not a suitable place for this, it should not contain everything we'll ever need

**Comment by SanctusAnimus** [comment]
So I'll need more details about exact implementations of streaks and daily login

**Comment by fcalife** [comment]
Yeah I was not talking about the streak, just the additional info needed to have this reward not be a 'normal' chest. This is good though.

I'll whip up some numbers for the streaks later today before talking about server variables so as to make sure I don't double-cross myself later

**Comment by SanctusAnimus** [comment]
Are we going to implement that at all?

**Comment by SanctusAnimus** [comment]
Currently settled with fortunius being enough
