### ISSUE TITLE
Player has 3 extra skill points

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#792]
![image](https://user-images.githubusercontent.com/63279022/106091696-0e171000-6181-11eb-98c1-f0521bb9277d.png)
![image](https://user-images.githubusercontent.com/63279022/106091710-11aa9700-6181-11eb-9d56-371f00c0b4e1.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/RlorUhd2) by [Unito](https://www.unito.io/learn-more)

**Comment by SanctusAnimus** [comment]
No more reports of it
