### ISSUE TITLE
Very strange bug

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#796]
![image](https://user-images.githubusercontent.com/63279022/106234468-01f88480-624d-11eb-82be-1a1e0b1f75ed.png)
![image](https://user-images.githubusercontent.com/63279022/106234503-12106400-624d-11eb-87dc-016f06208ed0.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/lTNstk7A) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
I believe this has the same root cause as #800 . If we don't get any reports of this after uploading the fix to that issue, then this can probably be closed.
