### ISSUE TITLE
Skills disappeared after a while leading to the game crashing

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#801]
![image](https://user-images.githubusercontent.com/63279022/106327739-c3a5a880-62d2-11eb-985b-0e0138e0ffe3.png)
![image](https://user-images.githubusercontent.com/63279022/106327843-e637c180-62d2-11eb-9404-5872660fd872.png)

**Comment by dym-sh** [comment]
same happens if you go to the main menu (to adjust volume setting for example) – after returning to the game all custom things are blanked out, and game crashes after a minute or so
