### ISSUE TITLE
Implement seasonal mmr/leaderboards reset for CHC

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#807]
Reset mechanics and rewards are described in the design spreadsheet, linked on discord (don't link here since it's open for edits).

In-game side of implementation includes mostly UI work, but also adding a lot of cosmetics. For more details, see https://github.com/dota2unofficial/custom_hero_clash/issues/669

**Comment by SanctusAnimus** [comment]
Implemented
