### ISSUE TITLE
Improve multicast/summons interaction

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#810]
Current multicast with summons is nice and interesting but creates a ton of summons and lags the game. Biggest culprits are serpent and plague wards.

This rework's aim is to make it so when a summoning ability is multicast, instead of spawning extra units, the first cast's units become stronger instead.

- when multicasting x2, x3, x4 etc. the units' health and damage should be increased accordingly (e.g. from 1,000 HP to 2,000, then 3,000, then 4,000, etc.)
- should not affect attack speed
- summon power should work normally
- should show the units' size increasing every time the 'multicast' text pops up, ideally with a 'power up' particle effect as well
- unit count should be kept at what is the base value for the ability (1 for plague wards, 2 for summon wolves, 8 for mass serpent wards, etc.)

bonus: extend this logic to things like rearm and refresher orb. But that needs further discussion of mechanics.

**Comment by ZLOY5** [comment]
Please check it
And can you please explain how it must work with abiltities like Tombstone

**Comment by fcalife** [comment]
We didn't think about tombstone when brainstorming this, but just increasing the tombstone health should be fine.

I'm almost sure tombstone is also disabled from the game due to lag, so either way not handling it shouldn't be an issue.

**Comment by ZLOY5** [comment]
Eidolons that spawned after 7 attacks mus be default or upgraded bt multicast too?
Seems in both cases I need recreate their behavior in custom ability to handle it properly

**Comment by ZLOY5** [comment]
- [x] Demonic Conversion
- [x] Plague Ward & Venomous Gale (gale spawn wards only for last multicast cast lol)
- [x] Rain of Chaos
- [x] Mass Serpent Ward 
- [ ] Shackles (waiting rework for aghanims by @lovro-m)
- [ ] Death Ward & Voodoo Switheroo - need rework or i can just disable multicast for this? 

@fcalife 
This https://github.com/arcadia-redux/custom_hero_clash_issues/issues/591 still relevant?
Other summons can stay with my previous version of multicast for summons?

**Comment by SanctusAnimus** [comment]
> Death Ward & Voodoo Switheroo - need rework or i can just disable multicast for this?

I think multicast for both of them is already disabled though?

**Comment by ZLOY5** [comment]
Been enabled in my branch, and work pretty well if we not count switcheroo ability

**Comment by fcalife** [comment]
@ZLOY5 for death ward, give it the summon multicast behavior (i.e. higher stats on multicast)

for switcheroo, just disable multicasting.

forge spirits remake would be good, they're useless for a long time due to being bugged.

> Other summons can stay with my previous version of multicast for summons?
yep
