### ISSUE TITLE
Add automatic random banning of abilities in each match

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#811]
Ban a few of the strongest abilities each match, in order to keep things fresher.

The exact amount of abilities to ban is up in the air, but the basic mechanics for this are as follows:

- Fetch from the server a list of the 100 or so best performing abilities in the current map
- This should only include abilities picked over 100 times, at least (to avoid outliers and statistical garbage)
- Randomly select 15 out of those 100 abilities and ban them, making them impossible to learn during this match
- The banned abilities need to be **clearly** indicated somewhere on the UI

In order to preemptively reduce the server load this would incur, maybe it'd be best to perform the randoming logic once per day on the server, and receive a list of banned abilities from it instead. That way there's less data being sent, and the bans stay consistent throughout a day, which might be a good thing (lets people have at least some time to adapt to a possible temporary meta).

**Comment by Draze22** [comment]
Issue #468 needs to be implemented before this an even be considered for implementation.

**Comment by Draze22** [comment]
Imo these bans will need to be displayed somewhere in-game, the disabled abilities being displayed in the picking phase only works long term since they are rarely changed. With these new bans being changed daily player will need to check which abilities are banned during the game.

**Comment by SanctusAnimus** [comment]
Denied by @darklordabc, stays as a mechanic for disabling problematic abilities
