### ISSUE TITLE
Make Track and Duel usable once per round

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#813]
Revert them to vanilla values, halved effect on creeps if necessary for balance.

Make them charge-based so that they can only be used once per round. They're recharged when the player enters the fountain area or the round ends.

Refresher Orb can be used to add one charge mid-round. Charges don't stack beyond the maximum of 1.

**Comment by Shushishtok** [comment]
So combining @Firetoad's initial suggestion of making this ability used only once per round, how about it could have an AoE application? 

For Track - you put the track modifier on all enemies in a small AoE, say 300.

For Duel - you go into a Duel with all enemies in a small AoE, say 300, and you're taunted in order of application, starting with the target you used it on. The application is starting from closest units to furthest.

Both abilities are only usable once per round, after which the ability deactivates until the round ends. 
Refresher's Orb can re-activate them for an additional single use this round if used after the ability has been deactivated.

In a Duel, both those abilities still use single target as per usual.

**Comment by Shushishtok** [comment]
Pending @darklordabc  decision. Put on Trello card for him to take a look at.

**Comment by Shushishtok** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Decide what to do about Track and Duel to solve round stalling.](https://trello.com/c/my01FfGy/227-decide-what-to-do-about-track-and-duel-to-solve-round-stalling)

**Comment by darklordabc** [comment]
I prefer @fcalife solution of just having it charged based, and having the charge replenish after each round, or used by refresher orb. I think having AOE could make these abilities much too powerful.

**Comment by Shushishtok** [comment]
@ZLOY5 said that @fcalife 's solution has the issue that it's basically a one-time bonus damage/bonus gold per round, which makes the abilities super boring, which is why I added the AoE. 

The AoE could be smaller than 300, e.g. 200 will only cast them on a bunch of clamped up units (hull radius of most units is usually 64 or 96).
Some rounds have units that spawn later, or single units that doesn't spawn more units, so the ability wouldn't be as strong there.

**Comment by Shushishtok** [comment]
@darklordabc Is your decision final?

**Comment by SanctusAnimus** [comment]
Implemented
