### ISSUE TITLE
Add more trees to arenas for abilities like nature's call

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#816]
![image](https://user-images.githubusercontent.com/63279022/106375521-ddcdac80-63e0-11eb-9806-708cca44325b.png)

**Comment by AustraliaIsMyCity** [comment]
a better idea: rework it to not require trees

**Comment by Draze22** [comment]
There are multiple abilities that benefit from having more trees, most of Timbersaw's abilities for example.

**Comment by Draze22** [comment]
Closing this since trees respawn at the end/start of each round.
