### ISSUE TITLE
Summons killing creeps doesn't count towards daily quests

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#818]
![image](https://user-images.githubusercontent.com/63279022/106375664-1c179b80-63e2-11eb-999b-7f84b6d290f5.png)

**Comment by Draze22** [comment]
Summons killing either creeps or ancient creeps doesn't count towards daily quests.

**Comment by AustraliaIsMyCity** [comment]
should be as simple as changing hero detection to player detection

**Comment by Draze22** [comment]
Seems like this is still an issue (maybe just with ancient creeps).

![image](https://user-images.githubusercontent.com/63279022/123506507-e1bbdd00-d6a7-11eb-92c5-292797e49569.png)

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for 10 days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.

**Comment by SanctusAnimus** [comment]
Nope, not true, summon kills count
