### ISSUE TITLE
Multicast rework

### ISSUE THREAD

**Issue by Shushishtok** [arcadia-redux/custom_hero_clash_issues#822]
Currently, Multicast spawns a ton (to be exact, 8) of dummies for every player that procs Multicast.
Multicast is custom and uses a system where dummies are set to be a clone of the hero in terms of stats, abilities, items and modifiers. Multicast abilities are cast from the caster's position to make it work as if the hero has Multicasted those abilities.

This has a ton of logic which can be simplified a lot, and most likely solve Multicast related issues and lags.
The process should be having flow:
- Passive modifier has ON_ABILITY_FULLY_CAST
- Listens to self casts
- Selects other targets/positions, if possible
- Triggers SetCursorPosition/Target, then OnSpellStart of that ability.

This should work for most abilities apart from channeling abilities (and probably Vector targeted).

Solutions:
- Keep using dummies, but rework them to only trigger when you cast channeling abilities.
- Determine that channeling abilities are no longer Multicast-able, which means just removing the entire dummy concept. (preferable, but depends on how much you mind people crying manly tears). Also technically a nerf to certain combos.

P.S. if the dummy system is kept, then the SetBaseStrength, SetBaseAgility and SetBaseIntellect need to get the base forms of the caster's stats, not the current caster's stats, as they include items that he has, which causes the dummy benefits twice from the item bonuses.

**Comment by darklordabc** [comment]
Is this a problem that has been reported? As far as I am aware we don't have issues with multicast, even assuming I agree that it's inefficient, is it a problem that needs fixing?

**Comment by Shushishtok** [comment]
There was a problem that was fixed today:
https://github.com/dota2unofficial/custom_hero_clash/pull/700

I've also found an issue where abilities could deal more damage, which is what I've stated in the P.S of this issue in the initial message.

The only reason those issues could occur was because of that dummy concept. Who knows what other issues we haven't seen yet.

**Comment by darklordabc** [comment]
This solution sounds fine to me
"Keep using dummies, but rework them to only trigger when you cast channeling abilities."
I dont want to disable multicast for channeling abilities, that seems a loss of a feature.

**Comment by Shushishtok** [comment]
Probably low priority regardless.

**Comment by darklordabc** [comment]
Okay I agree to remake it, as long as it keeps the same functionality and does not lose the ability to multicast anything it can currently multicast (like channeling abilities). I agree, it's pretty low priority.

**Comment by SanctusAnimus** [comment]
I don't think this one is relevant?

**Comment by Draze22** [comment]
@ZLOY5 fixed this in: https://github.com/arcadia-redux/custom_hero_clash/commit/9175b41682d90dcc7013c5813e4a938d95a00546.
