### ISSUE TITLE
Time Lapse doesn't work

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#824]
![image](https://user-images.githubusercontent.com/63279022/106416081-bd672600-64a4-11eb-83e9-dfd2963c03c1.png)

**Comment by Draze22** [comment]
Neither the base version or the aghs version does anything when cast except cost mana and go on cooldown.

**Comment by Draze22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Time Lapse doesn't work #824](https://trello.com/c/5XZ5nRjr/250-time-lapse-doesnt-work-824)

**Comment by lovro-m** [comment]
@Draze22 Can you please tell me which hero or specific situation you tried to reproduce the bug? I tried it now with and without aghs and it seems to work just fine.

**Comment by Draze22** [comment]
Pretty sure I tried it on a hero that isn't Weaver.

**Comment by 56kyle** [comment]
tested it on a couple different heroes with and without aghs. All worked normally during creep rounds, but doesn't work at all during duels. This includes later in the duel / etc, not just the start. Still haven't tested if it works for weaver in duels

**Comment by 56kyle** [comment]
Alright it seems to stop working altogether after dueling

**Comment by SanctusAnimus** [comment]
Is it still an issue?

**Comment by Draze22** [comment]
I believe so.
