### ISSUE TITLE
Fire Spirits still can't be relearned while you have aghanim's shard

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#825]
![image](https://user-images.githubusercontent.com/63279022/106416405-6f9eed80-64a5-11eb-9ccf-17430252131d.png)

**Comment by Eschada** [comment]
The spells usage and damage works properly.
The spell can be unlearned without shard if you don't have any active charges.
With the shard the spell cannot be unlearned and you get the error that the spell is currently beeing used.
This is identical on phoenix and other heroes.

**Comment by Snoresville** [comment]
"identical"?

**Comment by Eschada** [comment]
It shows the same behaviour on these tested heroes:
Phoenix
Enigma
Pl
Mars

**Comment by Draze22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fire Spirits still can't be relearned while you have aghanim's shard #825](https://trello.com/c/O1ifhN3E/249-fire-spirits-still-cant-be-relearned-while-you-have-aghanims-shard-825)

**Comment by AustraliaIsMyCity** [comment]
instead of closing and making a new issue, can we please just reopen the old issue. this is the 4th issue for this same bug specifically

**Comment by SanctusAnimus** [comment]
Yet another fire spirits issue
