### ISSUE TITLE
Fissure aghs shard only allows walking on fissure

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#830]
![image](https://user-images.githubusercontent.com/63279022/106553742-1484fd80-656e-11eb-87f5-a443016d18f1.png)

**Comment by lovro-m** [comment]
Aftershock on the fissure path triggers only with the other es abilities (enchant totem and echo slam). It had been decided here https://github.com/arcadia-redux/custom_hero_clash_issues/issues/920 to not rework this ability. This works as intended.
