### ISSUE TITLE
Mirrored UI setting causes text to be mirrored so a 2 looks like an S

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#831]
![image](https://user-images.githubusercontent.com/63279022/106553838-52822180-656e-11eb-9e4e-b1aeaecb2468.png)

**Comment by AustraliaIsMyCity** [comment]
lmfao

**Comment by SanctusAnimus** [comment]
It is the same in original dota rn, reopen if you have screenshots of our UI being broken that way
