### ISSUE TITLE
Re add Hoodwink to the game

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#837]
She can now buy Aghanim's Blessing and Aghanim's Shard so there's no reason not to add her anymore.

![image](https://user-images.githubusercontent.com/63279022/106846511-18955480-6701-11eb-9df6-7a45b8e7f384.png)

**Comment by Draze22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Re add Hoodwink to the game #837](https://trello.com/c/Hz5QGczw/253-re-add-hoodwink-to-the-game-837)

**Comment by darklordabc** [comment]
The portrait is broken @Sheodar 
![image](https://user-images.githubusercontent.com/16277198/107135695-e843f500-6950-11eb-999e-c2e9c7ac5ea8.png)

**Comment by darklordabc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Hood-Winks Portrait](https://trello.com/c/JxGwI1ik/266-fix-hood-winks-portrait)

**Comment by Sheodar** [comment]
Fixed

**Comment by AustraliaIsMyCity** [comment]
this is still very bugged #858 #861

**Comment by Shushishtok** [comment]
Fully reproduced in dota, that guy in the screenshot is talking bullshit.

**Comment by SanctusAnimus** [comment]
Hero is added, why is that reopened
