### ISSUE TITLE
If player has disconnected for more than 7 minutes total, kill them 

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#838]

**Comment by fcalife** [comment]
There's disconnect detection in the game already, please don't create a second one

**Comment by AustraliaIsMyCity** [comment]
please change this to 4 minutes consecutively or if they enter overtime while disconnected in FFA, same for duos only if both players are disconnected at the same time for a combined 8 minutes consecutively

**Comment by fcalife** [comment]
changed to 3min
