### ISSUE TITLE
Rework Lil Shredder

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#841]
Instead of lasting 6 attacks it should last 6 seconds

**Comment by AustraliaIsMyCity** [comment]
This implementation has several issues:
- The tooltip must show the new mechanic written in green text (see Arcane Aura or Flesh Heap if you're confused)
- Currently if used on snapfire with her talent it causes an infinite attack loop, please prevent the splits from procing marksmanship as well as the marksmanship splits from procing lil shredders talent
- Please ask for approval from myself, @Draze22, @fcalife, as well as letting @darklordabc give his input when pushing something relating to balance

**Comment by Draze22** [comment]
It should also be nerfed to 3 seconds instead of 6. 6 seconds is 50% up time with no cdr.
