### ISSUE TITLE
The Hunter in the night visual stays permanently after relearning

### ISSUE THREAD

**Issue by Eschada** [arcadia-redux/custom_hero_clash_issues#843]
When picking hunter in the night and unlearning it after being transformed into the form you keep the Nightstalker "skin". It  should not give any bonuses according to the buff description. This does also not disapear once it becomes daytime again.

This can be reproduced easily by picking the spell in demo mode and unlearning it once nighttime sets in.

![405706d39565e577fd828b9f998113f3](https://user-images.githubusercontent.com/77821399/107078628-da765e80-67ee-11eb-8583-21a676dc79bc.jpg)

**Comment by lovro-m** [comment]
This does not seem to be an issue any more, I have tried it with multiple heroes and with dark ascension.
![hunterinthenight2](https://user-images.githubusercontent.com/63733825/121817026-3a8a7f00-cc7f-11eb-96b9-27332c41411b.gif)

**Comment by Draze22** [comment]
I can confirm this has been fixed.
