### ISSUE TITLE
Sort CHC supporters by patreon

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#850]
https://github.com/dota2unofficial/12v12/issues/182 this but chc
@SanctusAnimus is gae

**Comment by SanctusAnimus** [comment]
@AustraliaIsMyCity no, u

**Comment by SanctusAnimus** [comment]
Implemented
also you will burn in hell for opening this in public issues repo, it took me a while to find it

**Comment by AustraliaIsMyCity** [comment]
![image](https://user-images.githubusercontent.com/50186248/111059967-9a8d5000-84ed-11eb-9470-f322b7936a99.png)

**Comment by SanctusAnimus** [comment]
Implemented
