### ISSUE TITLE
Some abilities are showing they are on cd for 120 seconds when their cooldown should be much lower

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#855]
Might be related to issue #853. Could also just be an issue with our custom terror wave.
![image](https://user-images.githubusercontent.com/63279022/107178557-7ccd5680-6a28-11eb-856e-c3d51abbfe90.png)
![image](https://user-images.githubusercontent.com/63279022/107178674-c3bb4c00-6a28-11eb-8c23-efa91e5eb8b4.png)

**Comment by Snoresville** [comment]
Terror wave isn't custom, but it is connected to a custom ability

**Comment by AustraliaIsMyCity** [comment]
my best guess is its related to the new cooldowns lib

**Comment by Draze22** [comment]
No more reports of this.
