### ISSUE TITLE
Neutral items have 2 sell buttons

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#856]
![image](https://user-images.githubusercontent.com/63279022/107178781-08df7e00-6a29-11eb-83ec-c4c4d976415a.png)
![image](https://user-images.githubusercontent.com/63279022/107178804-18f75d80-6a29-11eb-80a5-49f9b48b52ff.png)

**Comment by Draze22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Neutral items have 2 sell buttons #856](https://trello.com/c/pR2F3Unc/277-neutral-items-have-2-sell-buttons-856)

**Comment by Ninggodlike** [comment]
How about making neutral items not sellable?

**Comment by Draze22** [comment]
That sounds far worse.

**Comment by Ninggodlike** [comment]
[Fixed](https://github.com/dota2unofficial/custom_hero_clash/blob/Nordguy/game/scripts/npc/npc_abilities_override.txt)
