### ISSUE TITLE
Resonant pulse with aghs doesn't cooldown properly (needs to be rewritten)

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#866]
![image](https://user-images.githubusercontent.com/63279022/107224591-becbbc00-6a6b-11eb-9687-192e9de24d09.png)

**Comment by Draze22** [comment]
Resonant pulse needs our custom ability charges to cooldown properly.

**Comment by SanctusAnimus** [comment]
Aghs charges cannot be overriden, this will require rewriting ability

**Comment by Draze22** [comment]
It's been several months since anyone has complained about this so It's probably not worth fixing.
