### ISSUE TITLE
Remove Third Eye from Shop

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#868]
1. It's setting a precedent I don't like. It's adding neutral items to shop. What's next?
2. It's a lazy way to dick over invis builds
3. Custom items need a big justification. This is not a custom game where players expect weird new abilities and items, it's not Dota imba
The current custom items have been added for wise and strong reasons

**Comment by darklordabc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove Third Eye](https://trello.com/c/m1qm566y/286-remove-third-eye)

**Comment by AustraliaIsMyCity** [comment]
Third eye was added to the shop as a way to stop people from complaining about invisibility in later duels, with the idea being it is entirely useless and should never be bought

**Comment by darklordabc** [comment]
Why would we add an item to the shop that is entirely useless and should never be bought?

**Comment by Ninggodlike** [comment]
I removed the third_eye from shops. Check Nordguy brunch.

**Comment by AustraliaIsMyCity** [comment]
> I removed the third_eye from shops. Check Nordguy brunch.

hey can we not do things in the middle of a discussion please, theres a ton of people who can easily remove it, the important thing here is if and why we want to or not remove it

**Comment by Roshrach** [comment]
or the devs could make it consumable, but not permanent. it will stay if you die, but it only lasts for like, 5 or 7 minutes

**Comment by darklordabc** [comment]
This has been decided, remove it from the shop pls.

**Comment by Ninggodlike** [comment]
> 
> 
> This has been decided, remove it from the shop pls.

So it's not purchasable but still droppable right?

**Comment by Draze22** [comment]
It was never droppable.
