### ISSUE TITLE
Game was very laggy (includes error report)

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#869]
![image](https://user-images.githubusercontent.com/63279022/107322028-c46ee380-6af7-11eb-8291-4be8a25a6e22.png)
![image](https://user-images.githubusercontent.com/63279022/107322097-ebc5b080-6af7-11eb-94fc-802a3385211c.png)
![image](https://user-images.githubusercontent.com/63279022/107322083-dea8c180-6af7-11eb-9469-c364ab5a297c.png)

**Comment by AustraliaIsMyCity** [comment]
hacker + memory leak = out of memory error

**Comment by Draze22** [comment]
Seems to be a duplicate of issue #845.
