### ISSUE TITLE
Jingu Mastery doesn't work on tempest double

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#871]
![image](https://user-images.githubusercontent.com/63279022/107345230-78339b80-6b17-11eb-846e-a1efa9122946.png)
![image](https://user-images.githubusercontent.com/63279022/107345325-8da8c580-6b17-11eb-9b3b-aa4ea1e17fac.png)

**Comment by Snoresville** [comment]
![image](https://user-images.githubusercontent.com/19840964/107345790-dbbbca00-6b13-11eb-878b-a942ae3bbdcf.png)
that's because it SHOULDN'T work on illusions

**Comment by Draze22** [comment]
Tempest double isn't an illusion technically though.

**Comment by Snoresville** [comment]
no? just because it can cast abilities doesn't mean it's not a hero clone

**Comment by Draze22** [comment]
https://dota2.gamepedia.com/Heroes/Mechanics#Spawning

**Comment by Snoresville** [comment]
interesting

**Comment by lovro-m** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jingu mastery doesn't work on tempest double #871](https://trello.com/c/b6nXF3Yo/288-jingu-mastery-doesnt-work-on-tempest-double-871)

**Comment by lovro-m** [comment]
Legion commander moment of courage also doesn't work on tempest double. Will keep searching for more and upload when I fix everything.

**Comment by Draze22** [comment]
This might be relevant.

![image](https://user-images.githubusercontent.com/63279022/107485686-328ad780-6bd8-11eb-8b7e-02c8bf0b3e28.png)

**Comment by lovro-m** [comment]
Death ward works both with and without aghanim's. Need more specification.
