### ISSUE TITLE
Check that feral impulse works

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#873]
Probably just players noticing it doesn't affect them while in the fountain and not checking during creep rounds/duels where it actually does work.

**Comment by Ninggodlike** [comment]
Checked, it does work in creep rounds and duels. But has no effect in fountain.

**Comment by Draze22** [comment]
Works fine for me.

![image](https://user-images.githubusercontent.com/63279022/112707584-a66f0e00-8f00-11eb-865b-e41830c9177e.png)
