### ISSUE TITLE
Multicast + channeling ability bug

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#875]
![image](https://user-images.githubusercontent.com/63279022/107466345-eb8cea00-6bb7-11eb-8c5e-13fa7ab926a0.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/107467420-17a96a80-6bba-11eb-947c-49ca39c79569.png)

**Comment by Draze22** [comment]
![Uploading image.png…]()

**Comment by Draze22** [comment]
This player showed me this bug happening. The steps to reproduce should be:
1. Use an ability that does an effect around you for a duration (blade fury, rolling thunder, sunray, etc).
2. Multicast a channeled ability such as powershot.
3. A permanent version of the first ability you used will continue to occur (sometimes in that stop, sometimes in the top right).

**Comment by SanctusAnimus** [comment]
i thought we fixed it a long time ago huh

**Comment by SanctusAnimus** [comment]
couldn't replicate this with multicast, blade fury, sun ray and channeled as life drain and shackles

**Comment by SanctusAnimus** [comment]
effects do appear near my hero, but they don't last forever, they have duration of the original casted ability
