### ISSUE TITLE
Check if Dragon's Blood works

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#876]

**Comment by Ninggodlike** [comment]
It works, both in creep rounds and fountain.

**Comment by AustraliaIsMyCity** [comment]
i can confirm ive seen it not working

**Comment by Draze22** [comment]
Works fine for me, my guess is it's the classic Gaben visual armor bug.

![image](https://user-images.githubusercontent.com/63279022/112707606-be469200-8f00-11eb-835b-71566280ab58.png)

**Comment by fcalife** [comment]
![5PO0ljjw8x](https://user-images.githubusercontent.com/7921728/113394914-734cd480-936f-11eb-83ba-4309720833c9.gif)
![yvyoDgS5wv](https://user-images.githubusercontent.com/7921728/113394920-75af2e80-936f-11eb-8a6b-f5382f66c2ca.gif)

![image](https://user-images.githubusercontent.com/7921728/113395013-9bd4ce80-936f-11eb-8a24-62a3a9e7ff84.png)
