### ISSUE TITLE
Tree Grab (along with a bunch of other abilities) can't be seen in the duel UI

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#877]
From my experience it's fairly consistent which abilities can't be seen in the duel UI and is almost always multi-part abilities or abilities that change when you use them (burrow, tree grab, etc).

![image](https://user-images.githubusercontent.com/63279022/107476444-ef296c80-6bc9-11eb-8855-927b9a220b78.png)

**Comment by Snoresville** [comment]
as of may 24th, the duel ui will now only show base abilities.

**Comment by Draze22** [comment]
Seems to have been fixed by @Sheodar in this commit: https://github.com/arcadia-redux/custom_hero_clash/compare/964bc3e5b497...a54e9ae08559.
