### ISSUE TITLE
Tempest Double plus Arcane Aura provides 2 instances of the aura to all allies

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#878]
This is probably due to Tempest Double never technically dying.

![image](https://user-images.githubusercontent.com/63279022/107489105-58b27680-6bdc-11eb-8d49-917903e84438.png)
![image](https://user-images.githubusercontent.com/63279022/107488922-26087e00-6bdc-11eb-9aa8-1d945e02aec7.png)

**Comment by lovro-m** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tempest double arcane aura bug #878](https://trello.com/c/GmtQ7V5R/295-tempest-double-arcane-aura-bug-878)

**Comment by lovro-m** [comment]
Just give me all the tempest double bugs :D. I'll make checks for the modifiers.

**Comment by lovro-m** [comment]
I don't think there are other global passives in the game so it should be a unique case.
