### ISSUE TITLE
Having a Ballista and Headshot makes you do no knockback on Headshot procs

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#882]
![image](https://user-images.githubusercontent.com/63279022/107604220-86062f80-6c83-11eb-88f7-28df3843aea0.png)

**Comment by lovro-m** [comment]
As we can see the balance team has decided that ballista does not knockback at all. 
Needs approval by @fcalife.
![image](https://user-images.githubusercontent.com/63733825/108105660-2fd32b00-708d-11eb-88ae-7125378e373f.png)

**Comment by fcalife** [comment]
I don't understand this issue, both abilities trigger entirely separately, could you elaborate?

**Comment by Shushishtok** [comment]
@fcalife I'm going to assume "modifier_knockback" is being overridden or something which causes this behavior. I wonder if this happens with Headshot + Greater Bash, for instance.

**Comment by Snoresville** [comment]
![image](https://user-images.githubusercontent.com/19840964/116842581-1f5a3780-ac1c-11eb-8bcf-b3af616b57de.png)
hmm... looks like there isn't any more knockback on ballista
