### ISSUE TITLE
New particles for innates update

### ISSUE THREAD

**Issue by Snoresville** [arcadia-redux/custom_hero_clash_issues#886]
We require:
- Particles on Unstable Arcana to indicate that an ability that hero has recently casted has been refreshed (currently uses refresher particles; want to change this to avoid confusion)
- Trickster's hard dispel whenever they get stunned while Trickster is not on cooldown (currently looks like aeon disk + windrun)
- Berserker's berserk mechanic: a particle should be played when the hero first reaches the berserk threshold, and another should be played when entering berserk mode

~~Needs discussion before we can add it to the list~~ Ok'd by Firetoad:
- Blank Soul's debuff being shown on the units affected by it
- Speed Demon's fiery particles to flex on other players for being first (probably a particle that is attached on the hero, has no set duration, but should be removed if the modifier the particle is attached to is removed)
- Arcane Acceleration (renamed to Swift Arcana) shown to take effect (like a refresher particle, but maybe different in colour to show everyone else that the cause of their abilities being refreshed was not because of a refresher)
- Toppler of Mountains' proc
- Blitz Strike's proc
- Magus' proc
- Rend/Cascading Arcana growing stronger on affected units as their armor/magic resistance debuff gets stronger

part of: https://github.com/dota2unofficial/custom_hero_clash_issues/issues/808

**Comment by Snoresville** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New particles for innates update #886](https://trello.com/c/wBGYFLbE/301-new-particles-for-innates-update-886)

**Comment by fcalife** [comment]
Those all sound like good ideas for particles, though most can be simple.

Blank Soul debuff should show (since it's a proper aura now). Swift Arcana can just use a recolored refresher orb/ex machina/overclock particle, whatever fits best.

**Comment by Snoresville** [comment]
Further requesting an activation particle for the new t5 item (details about it can be shared on discord)

**Comment by Snoresville** [comment]
i would like to rescind that recent request because the new t5 item is no longer going to be used

**Comment by Snoresville** [comment]
awesome work by nibuja
