### ISSUE TITLE
Frosthaven Searing Arrows of Clinkz are missing their particle

### ISSUE THREAD

**Issue by SanctusAnimus** [arcadia-redux/custom_hero_clash_issues#887]

**Comment by SanctusAnimus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Frosthaven Searing Arrows of Clinkz are missing their particle](https://trello.com/c/B1FQKLRL/302-frosthaven-searing-arrows-of-clinkz-are-missing-their-particle)

**Comment by Ninggodlike** [comment]
Anyone experienced that? I tested in the demo mode but didn't the particle missing.

**Comment by SanctusAnimus** [comment]
There's 2 particle effects - arrow itself (which is present), and a psi blades effect (since those are frosthaven arrows, read their description carefully). The psi-blades effect was missing (at least for me), just a bunch of red error particles
