### ISSUE TITLE
Time Lock doesn't get affected by status resistance

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#888]
This seems to have been introduced by our time lock rework.

**Comment by Snoresville** [comment]
The issue originates from the GetStatusResistance function not returning anything other than 0 when called on creeps. This function  works as intended on heroes.

**Comment by fcalife** [comment]
could make a custom function that uses GetModifierStatusResistanceStacking, since that's the only status resistance modifier we use on creeps.

**Comment by Snoresville** [comment]
I'll see what I can do about creating the custom function, but I'll wait for the refactor to be fully pushed since I'll most likely throw that function into the util.lua file.

**Comment by fcalife** [comment]
agree
