### ISSUE TITLE
Arcane Acceleration doesn't work properly on items

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#892]
![image](https://user-images.githubusercontent.com/63279022/107876739-e1524f00-6f1b-11eb-840a-97873dd73862.png)
![image](https://user-images.githubusercontent.com/63279022/107876748-f202c500-6f1b-11eb-9c86-6560df982524.png)

**Comment by Snoresville** [comment]
dont attempt to fix it until the innate rework has been pushed

**Comment by AustraliaIsMyCity** [comment]
![image](https://user-images.githubusercontent.com/50186248/107998543-8151ca80-7039-11eb-8039-6fbe13326035.png)
this is somewhat related

**Comment by Draze22** [comment]
No longer relevant.
