### ISSUE TITLE
Pit of malice with high amounts of increased disable duration is bugged

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#895]
My guess is once the pit of malice root duration becomes longer than the root interval it starts bugging out.

![image](https://user-images.githubusercontent.com/63279022/108009153-2d091380-7056-11eb-8163-c70d7dc2c0d1.png)
![image](https://user-images.githubusercontent.com/63279022/108009163-33978b00-7056-11eb-8088-33548d0e0768.png)

**Comment by fcalife** [comment]
can confirm this happens due to the way it's implemented (in order to prevent the necessity of a rework)

**Comment by SanctusAnimus** [comment]
Haven't seen anyone complaining about this one and rewriting this spell for such a niche stack combo is an overkill, closing for now
