### ISSUE TITLE
Apply a strong dispel to duelling players at the start of a duel

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#896]
This would prevent pre-casting certain things like shadow blade/silver edge before a duel and swapping it out just before the duel starts to gain the advantage of having 6 items plus invis/break.

The major down down side would be that it would also dispel every buff we'd want players to keep (empower, bloodlust, etc) however in most cases they could simply recast them or wait until the duel starts to cast them. However if we could specifically remove the problematic buffs (shadow blade and silver edge) this could be a decent addition to the game.

**Comment by dym-sh** [comment]
case: `false promise` are already cant be applied in between rounds

**Comment by AustraliaIsMyCity** [comment]
absolutely not
