### ISSUE TITLE
Find out why this ability bar background is breaking and fix it

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#900]
First we need to find out how to proc it, may be related to screen sizes. 
![image](https://user-images.githubusercontent.com/16277198/108205306-fed02480-7178-11eb-9963-cc4232207b53.png)

**Comment by Snoresville** [comment]
![image](https://user-images.githubusercontent.com/19840964/108207483-b95f2780-7177-11eb-89d0-f64e9e64d4a3.png)
my dota seems to consistently do like this, didn't feel like a problem for me, but it's nice if it didn't happen
My resolution is 1366x768

**Comment by fcalife** [comment]
This **feature** was introduced by valve on the 7.28 patch

![image](https://user-images.githubusercontent.com/7921728/108242443-ae7ea580-712b-11eb-9e4c-501ccc258b5c.png)

**Comment by dym-sh** [comment]
it's native dota hud problem, 
https://www.reddit.com/r/DotA2/comments/lo8282/still_not_fixed_1440p_on_every_hero_that_has_more/

prob can expect fix after next "spring cleaning" event

**Comment by SanctusAnimus** [comment]
Fixed
