### ISSUE TITLE
Shop in Demo mode is missing items

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#905]
![image](https://user-images.githubusercontent.com/16277198/108256296-76ba4100-71b1-11eb-8038-8dc0249c0595.png)

**Comment by Draze22** [comment]
Isn't this just the custom shop that FIretoad made?

**Comment by fcalife** [comment]
![chrome_2u7UvOPGTJ](https://user-images.githubusercontent.com/7921728/113395175-d5a5d500-936f-11eb-8cba-f08fa73f481e.png)

its only missing items which are unnecessary in demo mode
