### ISSUE TITLE
Specific tests to perform after refactor is done

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#906]
This is by no means an exhaustive list, but rather a set of reminders so that I don't forget to test some specific things that were done.

 - [x] Have a player disconnect during the setup phase's countdown and reconnect before pregame is done, check that they can pick a hero and play normally.
 - [x] Have a player disconnect during the setup phase's countdown and reconnect after pregame but before the first round starts, check that they receive a random hero and can play normally.
 - [x] Have a player disconnect during the setup phase's countdown and reconnect after the first round starts, check that they are eliminated from the game.

**Comment by fcalife** [comment]
Other stuff that still needs testing:
 - dev/debug commands
 - party modes
 - demo map
 - enfos (probably largely broken)
 - game end (on tools and live)
 - overtime forcekilling

**Comment by 56kyle** [comment]
there may be an issue with the skeleton round; in the ffa match with bots that I am in 2 of the bots were left in their arena after killing all skeletons while some others returned normally

**Comment by fcalife** [comment]
@56kyle fixed
