### ISSUE TITLE
After reconnecting to the game in DUOS you can bet on yourself

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#908]
![image](https://user-images.githubusercontent.com/63279022/108570284-9bedb180-7361-11eb-8b7d-ceed5c2dde15.png)
![image](https://user-images.githubusercontent.com/63279022/108570305-a445ec80-7361-11eb-9336-525fa16a7346.png)

**Comment by AustraliaIsMyCity** [comment]
![image](https://user-images.githubusercontent.com/50186248/110399789-8f3fbc00-80ca-11eb-9841-ec61097b83fd.png)
