### ISSUE TITLE
Consider re-enabling Rearm + Guardian Angel

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#910]
Since creeps are able to deal damage through guardian angel during overtime and after wave 40 this combo is no longer a problem in creep waves. It's also not a problem in duels since it can be countered by silence, any offensive dispel or simply dealing magical or pure damage.

**Comment by AustraliaIsMyCity** [comment]
seeing as nullifier dispels constantly now im happy with this
