### ISSUE TITLE
Make Fury Swipes aghs shard reset the 1s Enrage duration instead of adding to it

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#917]
At the moment with high enough attack speed or an ability like Marksmanship that causes extra attacks you can build up enough time on Enrage to make it permanent. We should change it so proccing it resets the Enrage duration to 1 second instead of increasing the duration by 1 second.

**Comment by SanctusAnimus** [comment]
no longer relevant
