### ISSUE TITLE
Hunter in the night doesn't work properly

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#918]
![image](https://user-images.githubusercontent.com/63279022/109360186-dd8ad900-78da-11eb-990e-085860d0f864.png)

**Comment by Ninggodlike** [comment]
I don't have this issue in demo mode.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/112078453-91c60980-8bd2-11eb-9950-cae920cf1ad5.png)

**Comment by Draze22** [comment]
Buff doesn't show correct values

![image](https://user-images.githubusercontent.com/63279022/112707329-a0782d80-8efe-11eb-8cfe-c8c47b374056.png)

**Comment by Draze22** [comment]
Seems to provide bonus movespeed without actually showing it in the UI.

![image](https://user-images.githubusercontent.com/63279022/112707346-c43b7380-8efe-11eb-9c55-e58d48c30733.png)

**Comment by Draze22** [comment]
When I first skilled hunter in the night I didn't have the buff, but at 1:30 (still daytime) I got the buff. My movespeed and attackspeed were definitely buffed but it didn't show it in my hero UI.

![image](https://user-images.githubusercontent.com/63279022/112707792-0c0fca00-8f02-11eb-8ef7-4ac1a69a8b58.png)
