### ISSUE TITLE
Swapping death ward while it's being channeled makes it last forever

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#925]
![image](https://user-images.githubusercontent.com/63279022/110277987-7da6d780-802a-11eb-834d-b29c0d8f1ae7.png)

**Comment by AustraliaIsMyCity** [comment]
this applies to all channels (black hole, dismember etc)
can be fixed by disallowing swapping those while channeling

**Comment by SanctusAnimus** [comment]
Should no longer be the case, reopen if reoccurs
