### ISSUE TITLE
Metamorphosis causes players to not deal damage

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#928]
![image](https://user-images.githubusercontent.com/63279022/110398311-b8128200-80c7-11eb-93f6-bbfd67ccee18.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/112250699-f73af880-8cad-11eb-998b-9d075b9daa76.png)

**Comment by Draze22** [comment]
Steps to reproduce:
1. Pick Gyrocopter (might not be necessary).
2. Pick Metamorphosis.
3. Use Metamorphosis.
4. Use Metamorphosis a second time after the first one ended.
5. Your attack will travel away from the target you're attacking.

![image](https://user-images.githubusercontent.com/63279022/112707454-b6d2b900-8eff-11eb-839d-62fe4dc7ffa0.png)

**Comment by fcalife** [comment]
this is amazing, wtf
