### ISSUE TITLE
Disable Sprout in fountain

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#929]
It can be spammed with aghs shard to spawn a bunch of greater treants.
![image](https://user-images.githubusercontent.com/63279022/110723516-4c1b4f80-8268-11eb-8df8-3c95fd8ccae3.png)

**Comment by AustraliaIsMyCity** [comment]
this doesnt even make sense the treants should get killed when the new ones spawn

**Comment by Draze22** [comment]
Maybe they can't die since the fountain makes them invulnerable.
