### ISSUE TITLE
Make curses and or overtime increase mana costs

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#931]
This is mostly to deal with rearm builds since they can often survive 10+ curse stacks when combined with ghost scepter and percent damage.

**Comment by AustraliaIsMyCity** [comment]
what if we instead made it increase the channel time of rearm?

**Comment by fcalife** [comment]
Overtime now increases mana costs by 20% per second https://github.com/arcadia-redux/custom_hero_clash/commit/b0f79926bc127935d4ce6690aee9466e8baa5487

**Comment by fcalife** [comment]
Rearm channel time now increases by 17% (exponentially) with each curse stack https://github.com/arcadia-redux/custom_hero_clash/pull/755/
