### ISSUE TITLE
Fix headstart party mode not working

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#932]
caused by
```lua
	local MAXPLAYERS = 14 and GetMapName() == "duos" or 10
	
        local heroes = FindUnitsInRadius(hHero:GetTeamNumber(), hHero:GetAbsOrigin(), nil, FIND_UNITS_EVERYWHERE, DOTA_UNIT_TARGET_TEAM_BOTH, DOTA_UNIT_TARGET_HERO, DOTA_UNIT_TARGET_FLAG_NONE, FIND_ANY_ORDER, false)
	
	if #heroes ~= MAXPLAYERS then
		Timers:CreateTimer({
		endTime = 1,
		callback = function()
			PartyMode:HeadStart(hHero)
		end})
		return
        end
```

**Comment by Snoresville** [comment]
why does it not work?

**Comment by AustraliaIsMyCity** [comment]
> why does it not work?

basically that loop there is to ensure that it doesnt activate before all players have selected a hero, but for whatever reason it just never activates (idk why its not like its the most jank code ive ever written xd), anyways we should be able to use the constants in the rework to tell whether every player has a hero and go from there

**Comment by Snoresville** [comment]
the heroes are invulnerable in the fountain, so the FindUnitsInRadius wont catch them

**Comment by Snoresville** [comment]
anyway, i'm working on this

**Comment by AustraliaIsMyCity** [comment]
no please dont just make a shitty bandaid fix, properly fix it

**Comment by Snoresville** [comment]
i fixed it though

**Comment by Snoresville** [comment]
i don't see how it's a band-aid fix

**Comment by Snoresville** [comment]
if you mean for me to put it in the refactor branch, i'll do that

**Comment by Snoresville** [comment]
alright, i made changes to the head start party mode in https://github.com/arcadia-redux/custom_hero_clash/commit/12d549431ffe27092b5e83ec2a61ea52e3133004
