### ISSUE TITLE
CHC Refactor Bugs MegaThread

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#940]
- [x] Aeon disk has no cooldown
- [x] sudden death never triggers
- [x] winning pvp while resurrecting causes you to respawn in fountain without invulnerability
- [x] aegis count sometimes doesnt update from 2 to 1
- [x] some heroes get 1 extra level sometimes
- [x] disconnecting during hero selection then reconnecting to the game in duos causes you to stay as hero soul
- [ ] commands now send in chat
![image](https://user-images.githubusercontent.com/50186248/112702544-fa212d80-8ee7-11eb-8da1-f8c5bb0da832.png)
- [x] using -suicide causes the game to never end in PvE

**Comment by fcalife** [comment]
this is a duplicate of the horribly named https://github.com/arcadia-redux/custom_hero_clash_issues/issues/906

**Comment by AustraliaIsMyCity** [comment]
eh not really the same thing

**Comment by AustraliaIsMyCity** [comment]
- [ ] Aeon disk has no cooldown

**Comment by fcalife** [comment]
all should be fixed

**Comment by fcalife** [comment]
Ur mum gay
