### ISSUE TITLE
Add item from shop that can be used to gift 100 glory and 1 fortune

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/custom_hero_clash_issues#942]
A free item in the shop that players can only purchase once per week. They can use it on any other player, it will grant the player 100 bonus glory and 1 fortune in the form of a gift code in their gift code stash. This feature is intended to be a reminder of the gift code mechanic and to encourage people to use them (outside of this item).

There should be notifications when the player uses this, like how tipping notifies who is the giver and receiver, in regular dota.2

**Comment by AustraliaIsMyCity** [comment]
need i remind you that steam accounts are free to create, someone's bound to bot this...

**Comment by Sheodar** [comment]
Just idea for prevent abuse. Minimum mmr for buying. Like 2500. Btw, we could add several items.
1) 100 glory + 1 fortune. Min MMR 2500
2) 200 glory + 1 fortune. Min MMR 3500
So it will be bonus for MMR

**Comment by Sheodar** [comment]
And we can just remove this items in dedicated server each week from players. All other will be implemented in game side (2 new `Special` items)

**Comment by Draze22** [comment]
2500 is quite high. If we're going to make it a challenge the reward should be better than 100 glory and 1 fortune.

**Comment by Draze22** [comment]
Make the minimum required mmr to use this 2000 and this should be a nice(ish) improvement to the game.

**Comment by Draze22** [comment]
On second thought people will make several smurf accounts to take advantage of this, closing for now.
