### ISSUE TITLE
Ice blast can affect duels of other players (only the healing reduction)

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#945]
![image](https://user-images.githubusercontent.com/63279022/111563510-3370e380-87ec-11eb-9d01-ff9397f14c0f.png)

**Comment by fcalife** [comment]
no
![2RIckppzN6](https://user-images.githubusercontent.com/7921728/113396020-2ff36580-9371-11eb-800c-4455bde5d712.gif)
