### ISSUE TITLE
Spirit bear can equip neutral items in regular slots

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#946]
![image](https://user-images.githubusercontent.com/63279022/111563846-d9bce900-87ec-11eb-86eb-251944ef7f46.png)

**Comment by Ninggodlike** [comment]
It seems like this is a Dota2 bug, not only in CHC.

**Comment by Snoresville** [comment]
i thought we had this discussion a while ago where we talked about spirit bear being able to equip neutral items. normally the spirit bear can; if it's a bug, why wont valve balance it patches ago?

**Comment by Ninggodlike** [comment]
> 
> 
> i thought we had this discussion a while ago where we talked about spirit bear being able to equip neutral items. normally the spirit bear can; if it's a bug, why wont valve balance it patches ago?

Maybe Valve didn't notice it. See this https://www.youtube.com/watch?v=X6qqbd3ila8

**Comment by Ninggodlike** [comment]
Also this https://www.youtube.com/watch?v=gORNttc0VT0

**Comment by fcalife** [comment]
This was recently fixed by Valve. please verify if that's also the case for us

**Comment by Draze22** [comment]
Fixed.
