### ISSUE TITLE
Retraining geminate attack can give you infinite damage

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#948]
Seems like if you retrain geminate attack such that you don't get a new ability (which is another bug) you get infinite damage from geminate proccing repeatedly.

https://drive.google.com/file/d/1oCd0hn6TZECejv1pABIjXUNYENpCQGcn/view

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/111746517-41a12b80-88e2-11eb-8594-0ee99b1b04a9.png)

**Comment by AustraliaIsMyCity** [comment]
thats fucking hilarious can we get an instant replay on that

**Comment by SanctusAnimus** [comment]
Should no longer be an issue
