### ISSUE TITLE
Snowball hotkey bug

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#951]
![image](https://user-images.githubusercontent.com/63279022/111995014-90fa8c80-8b6c-11eb-9433-8821e0838c4e.png)

**Comment by SanctusAnimus** [comment]
This sounds like a very dota 2 own bug, that has nothing to do with us, and it haven't been reported ever again (it's kinda rare interaction too tbh), so i'm closing it for now
