### ISSUE TITLE
Game crashes for many players at hero selection and game start

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#952]
![image](https://user-images.githubusercontent.com/63279022/112406727-d08dc800-8d68-11eb-8b36-ee53ba47a376.png)
![image](https://user-images.githubusercontent.com/63279022/112406758-dc798a00-8d68-11eb-89e2-d101e396c997.png)
![image](https://user-images.githubusercontent.com/63279022/112406768-e26f6b00-8d68-11eb-92b2-7b92819f9732.png)
![image](https://user-images.githubusercontent.com/63279022/112406781-e8654c00-8d68-11eb-955b-b2c359159398.png)

**Comment by Draze22** [comment]
Is happening in both FFA and DUOS.

**Comment by SanctusAnimus** [comment]
Should be fixed
