### ISSUE TITLE
Tempest double doesn't work

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#953]
![image](https://user-images.githubusercontent.com/63279022/112454527-e3c28700-8dac-11eb-9468-0fa38eb95675.png)
![image](https://user-images.githubusercontent.com/63279022/112454542-e7eea480-8dac-11eb-8dbe-5af0cd21cd72.png)

**Comment by SanctusAnimus** [comment]
Fixed
