### ISSUE TITLE
Voodoo switcheroo can be multicast

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#954]
Just needs to be disabled, I would do it myself but I can't find the ability in our files, doesn't seem to be in npc_abilities or npc_custom.

![image](https://user-images.githubusercontent.com/63279022/112455210-9db9f300-8dad-11eb-8381-b9a0d0e4f161.png)

**Comment by SanctusAnimus** [comment]
Because it's not custom. For everything missing refer [here](https://raw.githubusercontent.com/SteamDatabase/GameTracking-Dota2/master/game/dota/scripts/npc/npc_abilities.txt)

**Comment by SanctusAnimus** [comment]
Done
