### ISSUE TITLE
Killing heroes gives experience

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#955]
![image](https://user-images.githubusercontent.com/63279022/112455332-b924fe00-8dad-11eb-9eb7-52fc30dbcf9f.png)

**Comment by fcalife** [comment]
Unable to reproduce in either ffa or duos, at multiple exp levels and with multiple level differences. Gonna close this one and call it user error.

**Comment by Osamabinfrank** [comment]
I think they might talk about draw, when a draw occurs and both enemies kill each other they both gain an extra level

**Comment by fcalife** [comment]
draws no longer happen
