### ISSUE TITLE
Rounds sometimes don't end

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#956]
Seems to be caused by disconnected players and there are a lot of reports of this happening.

![image](https://user-images.githubusercontent.com/63279022/112455437-d4900900-8dad-11eb-9e58-6d03e73879c8.png)
![image](https://user-images.githubusercontent.com/63279022/112455498-e2458e80-8dad-11eb-8ba9-c17e19443c7d.png)
![image](https://user-images.githubusercontent.com/63279022/112455697-1325c380-8dae-11eb-88a4-10b213867106.png)
![image](https://user-images.githubusercontent.com/63279022/112455767-22a50c80-8dae-11eb-8b20-7e1b3a57bec9.png)

**Comment by fcalife** [comment]
Fixed in https://github.com/arcadia-redux/custom_hero_clash/commit/08608c58c77f35f768bdac493d5cc1fb8a734717
