### ISSUE TITLE
aeon disk can cause players to never die

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#957]
![image](https://user-images.githubusercontent.com/63279022/112456103-84fe0d00-8dae-11eb-9449-b29a5f910010.png)
![image](https://user-images.githubusercontent.com/63279022/112456254-b1198e00-8dae-11eb-9df4-6539a2f5d324.png)

**Comment by SanctusAnimus** [comment]
Couldn't replicate it with just aeon disk, might need something else

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/112562127-bd433100-8e2a-11eb-9722-bc7c59cd36bc.png)
![image](https://user-images.githubusercontent.com/63279022/112562143-c2a07b80-8e2a-11eb-9bf3-d8c7b603e16d.png)

**Comment by fcalife** [comment]
Attempted a fix in https://github.com/arcadia-redux/custom_hero_clash/commit/a97cfbf700ad333333162015b5f90a90e9aa0726, reopen if necessary

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/112705490-2ee6b200-8ef3-11eb-9683-b230c0ed5b40.png)
![image](https://user-images.githubusercontent.com/63279022/112705494-31e1a280-8ef3-11eb-9fd2-bb959a595e90.png)

**Comment by fcalife** [comment]
Another attempt https://github.com/arcadia-redux/custom_hero_clash/commit/b5367164004319dd54bc1134131558daae5fd90c

**Comment by fcalife** [comment]
Stopped receiving reports of this; closing again.
