### ISSUE TITLE
Duels during sudden death are causing players to lose 2 aegises and gain 2 curse stacks

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#961]
![image](https://user-images.githubusercontent.com/63279022/112561415-48232c00-8e29-11eb-8c63-3d9037169da6.png)
![image](https://user-images.githubusercontent.com/63279022/112561425-4eb1a380-8e29-11eb-9fe2-73b80df2576b.png)

**Comment by fcalife** [comment]
Fixed in https://github.com/arcadia-redux/custom_hero_clash/commit/7ec78d2c3c08d73887844263c63a50f16cc92f2b
