### ISSUE TITLE
Curses aren't removed when you win the game

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#962]
![image](https://user-images.githubusercontent.com/63279022/112563694-f3ce7b00-8e2d-11eb-85d9-a130624dbfc7.png)

**Comment by fcalife** [comment]
I couldn't verify this one in tools

**Comment by fcalife** [comment]
nvm, found it

**Comment by fcalife** [comment]
Fixed in https://github.com/arcadia-redux/custom_hero_clash/commit/bceec39fa72bdb0b27f64c690e6a70295ea8ba35
