### ISSUE TITLE
Rerolling Requim of Souls doesn't grant skill points back from skill points put in Necromastery

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#963]
![image](https://user-images.githubusercontent.com/63279022/112573926-5bda8c80-8e41-11eb-84b3-25a6af639610.png)

**Comment by Snoresville** [comment]
this one got destroyed by the refactor lol

**Comment by Snoresville** [comment]
as in: it took out the patch up for this
