### ISSUE TITLE
camera dummy in duel arena can be affected by abilities like hookshot

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/custom_hero_clash_issues#965]
title

**Comment by SanctusAnimus** [comment]
Howwwwww gaben it has `MODIFIER_STATE_INVULNERABLE`, what purpose does that state even serves then

**Comment by fcalife** [comment]
some skills affect invulnerable units, for whatever reason (i.e. pudge hook)

I think OUT_OF_WORLD should do the trick

**Comment by SanctusAnimus** [comment]
should be fixed

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/113238260-237cf780-92f4-11eb-9fd3-2ea5878802a4.png)

**Comment by SanctusAnimus** [comment]
So camera is already out of world, invulnerable and magic immune, any other suggestions? From what I've seen in bug reporr, hookshot also hooks to mars bulwark soldiers lol

**Comment by SanctusAnimus** [comment]
Made another attempt, reopen if reoccurs
