### ISSUE TITLE
ability selection ignores opened innate selection

### ISSUE THREAD

**Issue by SanctusAnimus** [arcadia-redux/custom_hero_clash_issues#967]
and overrides it, causing a lost state.

**Comment by SanctusAnimus** [comment]
there are some reports of it, but i can't really replicate it? needs replication steps

**Comment by Draze22** [comment]
Duplicate of issue #451 (Which has replication steps).

**Comment by Draze22** [comment]
Replication steps:
1. Have the innate selection screen open.
2. Wait for round 3, 6 or 9 to start.
3. Innate selection screen will be overridden.

**Comment by SanctusAnimus** [comment]
This doesn't happen to me at all though?
![https://youtu.be/BPVt8IyM3dY](https://youtu.be/BPVt8IyM3dY)

**Comment by Snoresville** [comment]
![image](https://user-images.githubusercontent.com/19840964/112715554-bacaff00-8f30-11eb-8376-8800bbb0b8df.png)

**Comment by SanctusAnimus** [comment]
edited to plain link

**Comment by Draze22** [comment]
Maybe you have to have picked all the previous abilities.

**Comment by SanctusAnimus** [comment]
using both relearn and paragon books while innate selection is active does nothing, just tested

**Comment by SanctusAnimus** [comment]
Should be fixed, either way haven't heard of it anymore, or i'll need way more detailed repro steps
