### ISSUE TITLE
Fiend's Grip aghs shard "illusions" aren't disappearing when Fiend's Grip ends

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#968]
From what I've seen the illusions can't be killed and don't do anything.

![image](https://user-images.githubusercontent.com/63279022/112707924-ffd83c80-8f02-11eb-853e-5402dc774956.png)
![image](https://user-images.githubusercontent.com/63279022/112707939-14b4d000-8f03-11eb-97d1-2ebad16d420c.png)

**Comment by lovro-m** [comment]
already mentioned here: https://github.com/arcadia-redux/custom_hero_clash_issues/issues/920
if this gets fixed please fill the checkbox

**Comment by Draze22** [comment]
No longer relevant since this got moved to Fiend's Grip Aghs Scepter.
