### ISSUE TITLE
Our custom aeon disk isn't affected by nullifier

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#971]
Vanilla aeon disk is affected by nullifier. Ours is not and should be. The way they should interact is aeon disk doesn't dispel nullifier and nullifier does dispel aeon disk.

**Comment by fcalife** [comment]
Fixed in https://github.com/arcadia-redux/custom_hero_clash/commit/e994281d84651649daf88e1fbf8cf24aa8b5d860
