### ISSUE TITLE
DUOS players who disconnect while picking remain a hero soul forever

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#972]
Last update once their partner finished a round they would receive a hero and continue to play, now they just get to be a shitty hero soul for the entire game.

![image](https://user-images.githubusercontent.com/63279022/112718530-b3fbb680-8f47-11eb-9b7a-332fde20255e.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/117529408-c8d56a80-b01a-11eb-9419-338139b07a4c.png)
![image](https://user-images.githubusercontent.com/63279022/117529412-cd9a1e80-b01a-11eb-91d2-b430fc60f33b.png)

**Comment by ZLOY5** [comment]
Seems it returned after innate pick moved to second round

**Comment by Draze22** [comment]
This has been fixed again.
