### ISSUE TITLE
Jetpack + tempest double can escape arenas

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/custom_hero_clash_issues#974]

**Comment by fcalife** [comment]
Fixed in https://github.com/arcadia-redux/custom_hero_clash/commit/9897691548405b4434c160fd1b12c74c9ee8c9d0

**Comment by Draze22** [comment]
@AustraliaIsMyCity is this how the Disruptor escaped to kill Sniper?

**Comment by AustraliaIsMyCity** [comment]
yes
