### ISSUE TITLE
Aeon disk is sometimes freezing people's health much lower than 70%

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#976]
![image](https://user-images.githubusercontent.com/63279022/112740284-6888ed00-8fc7-11eb-8962-ffea73e40199.png)
https://www.youtube.com/watch?v=rpgI_xZWDx0

**Comment by AustraliaIsMyCity** [comment]
this doesnt need confirmation we literally have a video of it lmao

**Comment by AustraliaIsMyCity** [comment]
basically all that needs to happen is on the tick its activated the heroes health should be increased up to the activation health %

**Comment by fcalife** [comment]
Dates are close, but it looks like this video was recorded before the latest aeon disk fix, and might no longer be relevant.

Correct me if I'm wrong or new evidence appears. Leaving this on limbo for now.

**Comment by Snoresville** [comment]
if problem persists, we can try using the avoid damage modifier

**Comment by Draze22** [comment]
Pretty sure this is no longer an issue.
