### ISSUE TITLE
Camera doesn't move to the player's hero after a duel

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#981]
![image](https://user-images.githubusercontent.com/63279022/112740633-2b722a00-8fca-11eb-9e62-b54083e7a909.png)

**Comment by AustraliaIsMyCity** [comment]
it never does

**Comment by SanctusAnimus** [comment]
after player's own duel or after spectating someone's else duel?

**Comment by Draze22** [comment]
Pretty sure it's after your own duel.

**Comment by SanctusAnimus** [comment]
works for me with bots, is there any extra details?

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/113495281-de470880-9533-11eb-8cdf-5829e9d4288f.png)

**Comment by SanctusAnimus** [comment]
Presumably, should be fixed, reopen if reoccurs
