### ISSUE TITLE
Hero soul can level and use abilities which may crash the server

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#987]
![image](https://user-images.githubusercontent.com/63279022/112796717-1672c500-90b6-11eb-8be8-7da856791380.png)
![image](https://user-images.githubusercontent.com/63279022/112796729-1a9ee280-90b6-11eb-8cf8-bced569772e5.png)

**Comment by ZLOY5** [comment]
Why it have any abilities even?
