### ISSUE TITLE
Hovering over hero stats in pick phase doesn't work

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#988]
![image](https://user-images.githubusercontent.com/63279022/112826049-387d3f00-90d8-11eb-9a10-d595ddcf925e.png)
![image](https://user-images.githubusercontent.com/63279022/112826122-4d59d280-90d8-11eb-8bcd-9094a41c07f3.png)

**Comment by ZLOY5** [comment]
Ye, @darklordabc need to hover all custom tooltips in tools to compile, and also endgame UI

**Comment by SanctusAnimus** [comment]
Issue of compilation on darklord's side, doubt he will look here when uploading next time, thus closing

**Comment by darklordabc** [comment]
If this is still an issue this shouldn't be closed.

**Comment by ZLOY5** [comment]
I`m played few days ago and that tooltip been ok
