### ISSUE TITLE
Advertise the CHC FFA tournament in-game

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#991]
Sign-up link: https://forms.gle/NX4SAjpcdHYeEXaZ6.
![image](https://user-images.githubusercontent.com/63279022/112965948-78eec280-9195-11eb-947e-f8d6b38d0711.png)

**Comment by SanctusAnimus** [comment]
Implemented, though text should be tweaked, i'm not that confident in either wording or grammar
