### ISSUE TITLE
Game lags on round 40+/50+

### ISSUE THREAD

**Issue by Roshrach** [arcadia-redux/custom_hero_clash_issues#993]
The game lags when there are a lot of enemies on a single round. This is due to the sheer amount of abilities/items used during these rounds(even on low graphics settings). Needs optimizing, I guess.

Specs(if needed)
Intel i5 10300H, Nvidia RTX 2060, 8gb RAM. Basically an Acer Nitro 5 Laptop

**Comment by SanctusAnimus** [comment]
> Needs optimizing, I guess.

You're telling it like we are Valve and are able to do anything with dota being poorly optimized itself. Most optimizations we can do will result in significant game pace slowing

**Comment by Roshrach** [comment]
oh. so you're saying optimizing chc is not possible? well that's unfortunate

**Comment by SanctusAnimus** [comment]
Our level of control over things and debugging tools are nowhere near enough to make significant changes that could optimize the game without changing game flow and meta (i.e. without lowering max attack speed from 2000 to 700)
