### ISSUE TITLE
Ice Spire isn't invulnerable in the fountain

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#994]
![image](https://user-images.githubusercontent.com/63279022/113238484-9d14e580-92f4-11eb-8820-cba9e8b59a1c.png)

**Comment by fcalife** [comment]
should disable casting it in fountain, like it works for other summoning abilities

**Comment by fcalife** [comment]
Fixed in https://github.com/arcadia-redux/custom_hero_clash/commit/805a648328f3c18147cf490fa90bb57b9517a936
