### ISSUE TITLE
Walrus Kick with speed of thought level 3 is bugged

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#996]
Exactly how it's bugged needs to be investigated.

![image](https://user-images.githubusercontent.com/63279022/113309448-e2680000-9352-11eb-864f-9ae6612ec81f.png)

**Comment by fcalife** [comment]
![RbDHLFYoTA](https://user-images.githubusercontent.com/7921728/113384121-c452cd80-935b-11eb-97ad-e56364939c7f.gif)
no bug found on basic inspection, confirm or close.

**Comment by Ninggodlike** [comment]
didn't find any issues with the kick

**Comment by Draze22** [comment]
Closing this for now since it can't be reproduced and hasn't been reported again.
