### ISSUE TITLE
Arc warden spark wraiths aren't cleared at the end of a duel

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#997]
![image](https://user-images.githubusercontent.com/63279022/113310778-51922400-9354-11eb-814e-b5dbfd8415a0.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/116352673-de87aa80-a838-11eb-91b1-dfa3f4309a9a.png)

**Comment by SanctusAnimus** [comment]
They aren't real entities afaik, so we can't really clean them up? best thing we can do is probably just reduce max duration of them down to like 5-10 seconds so they would expire before next duel
