### ISSUE TITLE
Jetpack can be used to escape arenas

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#998]
![image](https://user-images.githubusercontent.com/63279022/113311674-48558700-9355-11eb-8126-5a1c389523bf.png)

**Comment by fcalife** [comment]
need confirmation. shouldn't be possible currently.

**Comment by Ninggodlike** [comment]
I just had a test. Jetpack can't make you escape arenas.

**Comment by Draze22** [comment]
Can't be reproduced and hasn't been reported again.
